snowflakedb/snowpark-python

.github/labeler.yml, .github/workflows/label_snowpark_pandas.yml, .github/workflows/labeler.yml
=> Add PR Labeler to label Snowpark pandas PRs.

CHANGELOG.md
based upon discussion with @sfc-gh-yixie , this is considered as an improvement, as users code didn't work with unsupported options and unclear error information is raised already
=> prepare 1.18.0 release changelog update

.github/workflows/precommit.yml, tox.ini
instruction:
https://docs.codecov.com/docs/adding-the-codecov-token
need to set up the codecov token in the gh repo setting -- variable
test report could be generated now: https://app.codecov.io/gh/snowflakedb/snowpark-python/tree/fix-codedev-issue
=> fix codecov rate limit issue and enable coverage for local testing

src/snowflake/snowpark/modin/pandas/series_utils.py, src/snowflake/snowpark/modin/plugin/docstrings/__init__.py, src/snowflake/snowpark/modin/plugin/docstrings/series_utils.py
Fixes SNOW-1445381
This PR moves the docstrings of `StringMethods` and `DatetimeProperties` to use docstring overrides.
=> SNOW-1445381: Override docstrings for Series.str/Series.dt

docs/source/_templates/autosummary/base.rst, docs/source/index.rst, docs/source/modin/index.rst
Fixes SNOW-1453518
Updating the documentation:
- increase the number of levels in the toctree/left navigation bar
- Move "All Supported APIs" to the top of the modin index.rst 
- Fix general and IO related API links on index page so you can now access the methods directly. Previously, it only displayed text (no link) and it was impossible to access the methods.
=> SNOW-1453518 Fix documentation in v1.17.0

tox.ini
SNOW-1453027 Remove modin oss code from code coverage. Those modin OSS code will be eventually removed so we don't need to monitor the code coverage here.
=> SNOW-1453027 Remove modin oss code from code coverage

docs/source/_templates/autosummary/base.rst, docs/source/modin/index.rst
Fixes SNOW-1453518
- Moved the modin "All supported APIs" category to the top on its index page.
- Removed base.rst code that prevented displaying links for general and IO APIs.
=> SNOW-1453518 Fix v1.18.0 docs

src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, src/snowflake/snowpark/modin/plugin/extensions/pd_overrides.py, tox.ini
SNOW-1456322 CI: make sure all modin doctests are covered
=> SNOW-1456322 CI: make sure all modin doctests are covered

docs/source/index.rst, docs/source/snowpark/index.rst
Fixes SNOW-1453518
Refer to thread: https://snowflake.slack.com/archives/C049VF99031/p1717087196127959?thread_ts=1716580744.074129&cid=C049VF99031
- increased the toctree maxdepth from 2 to 3 - this should make the sidebar navigation work as expected (drop downs)
- removed duplicate session documentation link for the index.rst for Snowpark APIs, it should still exist in the landing page.
=> SNOW-1453518 Fix documentation for v1.17.0 - increase toctree maxdepth to 3

README.md
This is a PR to merge Doris' changes for the README.md - https://github.com/snowflakedb/snowpark-python/pull/1656/files
=> [README Fix] Move Doris' changes to a new branch

docs/source/index.rst, docs/source/snowpark/index.rst
Fixes SNOW-1453518
Refer to thread: https://snowflake.slack.com/archives/C049VF99031/p1717087196127959?thread_ts=1716580744.074129&cid=C049VF99031
- increased the toctree maxdepth from 2 to 3 - this should make the sidebar navigation work as expected (drop downs)
- removed duplicate session documentation link for the index.rst for Snowpark APIs, it should still exist in the landing page.
=> SNOW-1453518 Fix documentation in v1.18.0

CHANGELOG.md
=> Remove merge artifact in CHANGELOG.md

.github/labeler.yml
=> Add auto PR labeler for local testing label

tests/integ/modin/frame/test_apply.py, tests/integ/modin/series/test_apply.py
SNOW-1428607 Reenable quarantined tests after 8.20
=> SNOW-1428607 Reenable quarantined tests after 8.20

tests/integ/modin/conftest.py, tests/integ/modin/sql_counter.py
Fixes [SNOW-1435354](https://snowflakecomputing.atlassian.net/browse/SNOW-1435354)
We skip sql count check in some scenarios (e.g., cte tests, stored proc regression tests) by adding a pytest argument
[SNOW-1435354]: https://snowflakecomputing.atlassian.net/browse/SNOW-1435354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Skip SQL count check in test

src/snowflake/snowpark/mock/_analyzer.py, src/snowflake/snowpark/mock/_connection.py, src/snowflake/snowpark/mock/_select_statement.py, tests/integ/test_function.py, tests/mock/test_not_implemented_error.py
=> SNOW-1356862: local testing remove unused code

src/snowflake/snowpark/mock/_plan.py, src/snowflake/snowpark/mock/_stored_procedure.py, src/snowflake/snowpark/mock/_udf.py, src/snowflake/snowpark/mock/_util.py, tests/mock/test_udf.py, tests/mock/test_util.py
Refactors in preparation for SNOW-1460922
This change is part of a refactor to how we call mocked functions. While looking at the udf handler code to determine if I needed to make changes there I saw some opportunity for some simplification to improve readability. No functionality should have changed due to this commit.
=> SNOW-1460922: [Local Testing] Refactor udf/sproc calls

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/analyzer.py, src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py, src/snowflake/snowpark/_internal/analyzer/expression.py, src/snowflake/snowpark/dataframe_na_functions.py, src/snowflake/snowpark/mock/_analyzer.py, src/snowflake/snowpark/mock/_plan.py, tests/integ/test_dataframe.py
Fixes SNOW-1373556
Previous implementation will fail due to maximum recursion exceeded when there are a large number of columns
=> SNOW-1373556: Implement dropna using a new expression

CHANGELOG.md, README.md, src/snowflake/snowpark/dataframe.py, src/snowflake/snowpark/modin/plugin/__init__.py, src/snowflake/snowpark/udaf.py
Fixes SNOW-1439789
This PR replaces LIMITEDACCESS doc links with the corresponding public links.
=> SNOW-1439789: Replace LIMITEDACCESS doc links with public links

docs/source/modin/dataframe.rst, docs/source/modin/series.rst
Followup for #1712, where I forgot to include pct_change in the doc hierarchy.
=> Add DataFrame/Series.pct_change to docs

src/snowflake/snowpark/modin/plugin/_internal/index.py, tests/integ/modin/index/__init__.py, tests/integ/modin/index/test_transpose.py
Fixes SNOW-1458140
Implemented `Index.T` which by definition just returns `self`. Added one simple test.
=> Add Index.T

src/snowflake/snowpark/modin/plugin/_internal/index.py
Fixes SNOW-1464295 suppress index to_pandas_warning
This should be suppressed until the lazy index implementation is in.
=> SNOW-1464295 suppress index to_pandas_warning

tests/integ/modin/series/test_apply.py
=> SNOW-1478794 xfail test_3rd_party_package_with_session while investigating

tests/integ/modin/strings/test_get_dummies.py
=> Fix Jenkins CI failure for lazy index query count

tests/ast/data/col_literal.test, tests/ast/data/col_star.test, tests/ast/data/col_string.test
Corresponding PR for the Unparser changes: https://github.com/snowflakedb/snowflake/pull/187374
=> Update tests based on unparser changes

CHANGELOG.md, tests/integ/scala/test_window_spec_suite.py, tests/integ/test_column.py
Fixes SNOW-1348700
~This PR fixes 2 issues we uncovered from https://github.com/snowflakedb/snowpark-python/issues/1440:~ After rebasing onto the coercion PR, this PR becomes a test only change. It adds the tests for following cases:
- CaseWhen fails when incoming column is empty
- Window function fails when incoming data is empty (0 rows)
=> SNOW-1348700 Fix CaseWhen and Window bugs when input data is empty

.pre-commit-config.yaml, setup.py
=> CI:fix-lint numpy < 2.0.0

.github/workflows/daily_modin_precommit.yml
A successful run here https://github.com/snowflakedb/snowpark-python/actions/runs/9569472848/job/26382175196
=> Fix CTE optimization test in daily precommit 

tests/mock/test_stage_registry.py, tests/unit/test_generated_udf_lock.py
=> Fix local testing flaky test_stage_put_file

tests/ast/update-unparser.sh
Convenience script `update-unparser.sh` uses sbt build currently. With introduction of the bazel scala targets dependencies (i.e., IR changes) switch to using them to create an updates unparser.sh as IR/protobuf updates will be reflected.
=> [SERVER-SIDE CI] In update-unparser.sh script use bazel targets now instead of sbt

src/snowflake/snowpark/session.py, tests/integ/test_session.py
=> Read server side CTE parameter when initializing the session 

src/snowflake/snowpark/modin/plugin/_internal/index.py, tests/integ/modin/conftest.py
Fixes SNOW-1493834
Make the index represented as a dataframe with an index column and empty data columns. It currently saves the index values in both index and data columns.
=> Remove duplicate data for Index Constructor

CHANGELOG.md, src/snowflake/snowpark/_internal/open_telemetry.py, src/snowflake/snowpark/stored_procedure.py, src/snowflake/snowpark/udaf.py, src/snowflake/snowpark/udf.py, src/snowflake/snowpark/udtf.py, tests/integ/test_open_telemetry.py, tests/unit/test_open_telemetry.py
=> SNOW-1341738: Emit spans for stored procedure registrations

docs/source/modin/dataframe.rst, docs/source/modin/series.rst
FixesSNOW-1445733
Fix typo in dataframe.rst and series.rst
=> SNOW-1445733: Fix typo causing doc build failures

CHANGELOG.md, recipe/meta.yaml, src/snowflake/snowpark/version.py
=> Prepare release v1.19.0

tests/unit/test_open_telemetry.py
=> Skip open telemetry test in CTE mode

.github/workflows/daily_modin_precommit.yml
Fixes SNOW-1489910
The modin daily job is using v1 or v3 action for upload and download. Update the version from v3-> v4 to stay consistent with other daily job
=> [SNOW-1489910] Update upload and download action from v3 -> v4 for modin daily precommit

tests/unit/test_open_telemetry.py
=> Fix flaky test in opentelemetry tests

src/snowflake/snowpark/_internal/analyzer/cte_utils.py, tests/integ/modin/frame/test_transpose.py, tests/integ/test_cte.py
Fixes SNOW-1413967
#1834 fixes the issue and we can remove the workaround now.
=> SNOW-1413967: Remove workaround for dynamic pivot when CTE optimization is enabled 

tests/utils.py
Structured type tests have been failing due to unexpected results.
https://ci-dev-142.int.snowflakecomputing.com/job/SnowparkPythonSnowflakePythonClientRegressRunner/658/
It now passes with the account added to the list of supported accounts.
https://ci-dev-142.int.snowflakecomputing.com/job/SnowparkPythonSnowflakePythonClientRegressRunner/660/console
=> Add Jenkins account to structured type support list

tests/integ/test_udtf.py
Disable this test due to its failure in AWS, and will enable it once the external access issue is fixed.
=> Disable test_udtf_external_access_integration

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py, tests/integ/scala/test_function_suite.py
Fixes SNOW-1520035
Fixed a minor bug in sql generation for `lag(x, 0)`
=> SNOW-1520035: Fix lag(x, 0)

tests/integ/modin/io/test_to_csv.py
=> SNOW-1447365: Fix to_csv tests running on windows

CHANGELOG.md, src/snowflake/snowpark/mock/_connection.py, src/snowflake/snowpark/mock/_plan.py, tests/integ/scala/test_dataframe_writer_suite.py, tests/integ/test_dataframe.py
modification of PR https://github.com/snowflakedb/snowpark-python/pull/1854
=> SNOW-1507519: Add support for column_order='name' in append mode write.save_as_table

src/snowflake/snowpark/dataframe.py
Fixes #1897 
It's already out of preview.
=> SNOW-1529332: Remove private_preview decorator for create_or_replace_dynamic_table

src/snowflake/snowpark/functions.py
=> SNOW-1540745: Fix snowpark ntile doctest failing

tests/conftest.py, tests/integ/test_open_telemetry.py, tests/unit/test_open_telemetry.py
=> Fix open telemetry test flakiness in non-localtesting env

CHANGELOG.md, recipe/meta.yaml, src/snowflake/snowpark/version.py
1) cherry-pick release note v1.20.0 https://github.com/snowflakedb/snowpark-python/pull/1922 back to main
2) resolve merge conflict for new feature added
=> [CHERRY-PICK] Cherry-pick release note back to main

tests/integ/test_telemetry.py
=> Fix telemetry test when sql simplifier is disabled

tests/integ/modin/conftest.py
Fix CI error where rename test is failing because no session is provided-  this is because an Index is being created in the old way. Now, pd.Index and native_pd.Index produce different outputs.
=> [CI-fix] Fix rename test

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/__init__.py
Fixes SNOW-1542753
We're removing the warning message that appears on importing Snowpark pandas.
See [slack discussion](https://snowflake.slack.com/archives/C04HF38JFAQ/p1721162764902609) for details.
=> SNOW-1542753: Remove Snowpark pandas PuPr import warning

src/snowflake/snowpark/_internal/analyzer/analyzer.py, src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py, src/snowflake/snowpark/mock/_analyzer.py, src/snowflake/snowpark/mock/_plan.py, src/snowflake/snowpark/table.py
Fixes SNOW-1531493
The original name is from Spark, and it doesn't make sense semantically now. It is a pure renaming PR.
=> SNOW-1531493: Rename `UnresolvedRelation` to `SnowflakeTable`

CHANGELOG.md
Some of the changelog Index entries were removed/placed in the wrong location. This PR corrects that.
=> Fix CHANGELOG Index entries

setup.py, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/_internal/compiler/__init__.py, src/snowflake/snowpark/_internal/compiler/plan_compiler.py
Fixes SNOW-1541091
This is a refactor where we introduce a new component compiler which will to run all optimizations on the final plan to arrive at execution queries. Snowflake plan calls into this component to get its execution queries.
=> SNOW-1541091: Add plan compiler component

src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
After removing the create_temp_table function, build_from_multiple_queries is not used anymore. Remove the unused function.
=> Remove unused function build_from_multiple_queries

CHANGELOG.md, src/snowflake/snowpark/_internal/server_connection.py, tests/integ/scala/test_async_job_suite.py, tests/integ/test_dataframe.py
=> SNOW-1515947:Unexpected pandas casting exception during to_pandas_batches iteration

tests/integ/modin/series/test_drop_duplicates.py
Fixes SNOW-154917
pandas sort is unstable by default resulting in flaky test. Use kind='stable' to fix flakiness in test.
=> SNOW-154917: Fix test test_drop_duplicates_post_sort_values

tests/integ/test_dataframe.py
=> Skip test_dataframe::test_dataframe_to_local_iterator_with_to_pandas_isolation when there is no pandas

src/snowflake/snowpark/_internal/analyzer/select_statement.py, tests/integ/test_deepcopy.py, tests/unit/test_deepcopy.py
SNOW-1552736
1) Add unit test for deepcopy for all selectable class
2) Add integ test for deepcopy of complicated plan
3) Extend SelectTableFunction init function to take an already resolved function
=> [SNOW-1552736] Add unit test for deepcopy for selectable and integ test for complicated plan

tests/integ/test_cte.py
This test will be re-enabled once the new cte implementation is done
=> Disable test_cte.test_sql when sql simplifier is disabled

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/extensions/index.py
Fixes SNOW-1555437
Fix a bug in the decorator `is_lazy_check` which ignored the docstrings.
=> SNOW-1555437 Fix Index docstrings

src/snowflake/snowpark/_internal/type_utils.py, tests/unit/test_types.py
Fixes SNOW-1331032
This PR breaks down #1509.
Follow-up PR is #1957 
This PR adds function `python_value_str_to_object` which takes in a string and datatype from a python file and converts the string into a python object.
=> SNOW-1331032 Add function python_value_str_to_object

src/snowflake/snowpark/dataframe.py, src/snowflake/snowpark/dataframe_na_functions.py, src/snowflake/snowpark/session.py, src/snowflake/snowpark/table.py, tests/ast/data/DataFrame.create_or_replace.test, tests/ast/data/DataFrame.join.inner.column_list_predicate.test, tests/ast/data/DataFrame.join.inner.predicate.test, tests/ast/data/DataFrame.join.inner.predicate_rsuffix.test, tests/ast/data/DataFrame.join.right_outer.predicate.test, tests/ast/data/Dataframe.filter.test, tests/ast/data/Dataframe.with_col_fns.test, tests/ast/data/case_when.test, tests/ast/data/col_binops.test, tests/ast/data/col_literal.test, tests/ast/data/col_rbinops.test, tests/ast/data/df_sort.test, tests/ast/data/functions.test
[SNOW-1562752](https://snowflakecomputing.atlassian.net/browse/SNOW-1562752)
- `DataFrame.union` required further push-down of the AST for proper downstream use of the output `DataFrame`
- Add `stmt` parameter to `with_src_position` helper calls everywhere possible
- Update tests according to Unparser changes in the server PR: https://github.com/snowflakedb/snowflake/pull/198803
[SNOW-1562752]: https://snowflakecomputing.atlassian.net/browse/SNOW-1562752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-1562752 Pass stmt params to with_src_position, df.union fn AST pushdown

CHANGELOG.md, src/snowflake/snowpark/mock/_functions.py, src/snowflake/snowpark/mock/_plan.py, tests/integ/scala/test_update_delete_merge_suite.py
fixing issue SNOW-1511601
https://github.com/snowflakedb/snowpark-python/issues/1856
this PR fixes a bug that the column values doesn't get populated into the column when performing inserting column during the merge operation.
with the new implementation, values show up in the result dataframe
=> SNOW-1511601: fix bug that merge insert does not populate values into the columns

CHANGELOG.md, src/snowflake/snowpark/modin/pandas/indexing.py, src/snowflake/snowpark/modin/plugin/extensions/index.py, tests/integ/modin/frame/test_iloc.py, tests/integ/modin/frame/test_set_index.py, tests/integ/modin/index/test_indexing.py, tests/integ/modin/series/test_iloc.py
SNOW-1461224 Implement indexing for Index
Use series.iloc to implement indexing for index.
=> SNOW-1461224 Implement indexing for Index

src/snowflake/snowpark/dataframe.py, tests/ast/data/DataFrame.agg.test, tests/ast/data/col_literal.test
Support DataFrame.agg in Snowpark IR
=> [SNOW-1491295] Support DataFrame.agg in Snowpark IR

src/snowflake/snowpark/modin/plugin/extensions/index.py
SNOW-1440313
This PR uses the `TelemetryMeta` metaclass to add telemetry for all Index APIs
=> SNOW-1440313: Add telemetry for Index APIs

CHANGELOG.md, docs/source/snowpark/index.rst, docs/source/snowpark/testing.rst, src/snowflake/snowpark/testing.py, tests/integ/test_testing.py
Fixes #1320
Added a util function to check the equality of two Snowpark DataFrames
=> SNOW-1247349: Add `snowflake.snowpark.testing.assert_dataframe_equal`

src/snowflake/snowpark/modin/plugin/_internal/frame.py, src/snowflake/snowpark/modin/plugin/_internal/transpose_utils.py, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, src/snowflake/snowpark/modin/plugin/extensions/index.py, tests/integ/modin/index/test_sort_values.py, tests/integ/modin/utils.py, tests/unit/modin/test_internal_frame.py
SNOW-1514879
Support Index in eval_snowpark_pandas_result, a good tool for testing
=> SNOW-1514879 Support Index in eval_snowpark_pandas_result

docs/source/snowpark/session.rst
…
Fixes SNOW-1565224
The doc strings for these two methods exist and provide examples, but were not linked to in the official documentation.
=> SNOW-1565224: Add Session.append_query_tag and Session.update_query_tag to docs

tests/mock/test_pandas_util.py
This test should be skipped when pandas is not installed
=> Fix no pandas test

src/snowflake/snowpark/session.py
1. Please describe how your code solves the related issue.
The server side parameter for new compilation stage is PYTHON_SNOWPARK_COMPILATION_STAGE_ENABLED to be conistent with other parameter added
=> Update there server parameter PYTHON_SNOWPARK_ENABLE_COMPILATION_STAGE to PYTHON_SNOWPARK_COMPILATION_STAGE_ENABLED

CHANGELOG.md, src/snowflake/snowpark/modin/pandas/__init__.py, src/snowflake/snowpark/modin/plugin/extensions/datetime_index.py, src/snowflake/snowpark/modin/plugin/extensions/index.py, src/snowflake/snowpark/modin/plugin/extensions/pd_overrides.py, tests/integ/modin/frame/test_loc.py, tests/integ/modin/index/conftest.py, tests/integ/modin/index/test_astype.py, tests/integ/modin/index/test_datetime_index_methods.py, tests/integ/modin/index/test_equals.py, tests/integ/modin/index/test_index_methods.py, tests/integ/modin/series/test_loc.py, tests/integ/modin/tools/test_to_datetime.py, tests/unit/modin/test_class.py
- Add DatetimeIndex class (which is a subclass of pd.Index)
- Use self.__constructor__ in index.py to return correct Snowpark pandas index type.
TODO (changedoc)
=> SNOW-1558877: Add Snowpark pandas DatetimeIndex class

tests/integ/modin/frame/test_apply.py, tests/integ/modin/frame/test_head_tail.py, tests/integ/modin/groupby/test_groupby_basic_agg.py, tests/integ/modin/pivot/test_pivot_table_single.py, tests/integ/modin/test_merge.py, tests/unit/modin/test_internal_frame.py, tox.ini
Fixes SNOW-1471198
Test only change. Note `modin_sp_short_regress` is not used any more so move to `modin_sp_precommit`
Testing passed: https://ci-dev-142.int.snowflakecomputing.com/job/SnowparkPandasStoredProcPrecommitTest/77/
=> SNOW-1471198 move modin_sp_short_regress to modin_sp_precommit

tests/integ/modin/io/test_read_csv.py, tests/integ/modin/io/test_read_snowflake.py, tests/integ/modin/test_dtype_mapping.py
Fixes SNOW-1471198 Snowpark pandas sproc precommit: fix and add more tests
Test passed: https://ci-dev-142.int.snowflakecomputing.com/job/SnowparkPandasStoredProcPrecommitTest/79/
=> SNOW-1471198 Snowpark pandas sproc precommit: fix and add more tests

src/snowflake/snowpark/session.py
Fixes SNOW-1418507
This is a minor refactor to update usage of `session._custom_package_usage_config` to be more friendly for thread-safe updates. To do so, we make a copy of the dictionary and then use this dictionary for running functions. When making the thread-safe update, we will make the copy step atomic thus making the overall conversion easier.
=> SNOW-1418507: Refactor _custom_package_usage_config

src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py, src/snowflake/snowpark/_internal/compiler/utils.py, tests/unit/compiler/test_replace_child_and_update_node.py, tests/unit/test_query_plan_analysis.py
=> SNOW-1546396: Fix update_resolvable_node to reset attributes for SelectStatement & SetStatement

src/snowflake/snowpark/dataframe.py, src/snowflake/snowpark/udtf.py
Fixes SNOW-1617110
This is updating doc string to remove `Preview Feature` tags for GA features.
=> SNOW-1617110: Remove preview feature annotation for GA features

tests/integ/modin/frame/test_apply.py
Fixes SNOW-1471203 remove unused test case in test_apply.py
=> SNOW-1471203 remove unused test case in test_apply.py

CHANGELOG.md, src/snowflake/snowpark/modin/pandas/series.py, tests/integ/modin/series/test_cache_result.py, tests/integ/modin/series/test_reset_index.py
Fixes SNOW-1442354 Fix a bug in series.reset_index where the result name may be wrong
=> SNOW-1442354 Fix a bug in series.reset_index where the result name may be wrong

CHANGELOG.md
=> SNOW-1625582: Move 2 changelog lines into pandas section.

src/snowflake/snowpark/_internal/temp_table_auto_cleaner.py
=> SNOW-1567720: Use statement parameter to track the drop table query issued by auto temp table cleaner

ci/docker/snowpark_test_fips/Dockerfile, ci/docker/snowpark_test_fips/scripts/entrypoint.sh, ci/test_fips.sh, ci/test_fips_docker.sh
Fixes SNOW-1616098
This change does 2 things:
1. apply this change https://github.com/snowflakedb/snowflake-connector-python/pull/1992 to fix mirrors.
2. build openssl 3.0.0 and enable fips mode to fix fips tests.
3. increase parallelism for fips tests.
=> SNOW-1616098: Fix FIPS test

tests/integ/modin/types/test_timedelta.py
=> SNOW-1629010: Make note of timedelta precision bug.

ci/snyk/requirements.txt
Fixes SNOW-1628439
Fixing the synk vulnerabilities due to old python connector version here: https://app.snyk.io/org/snowflakedb-sca-scanning-public-repo/project/773f470d-2a57-4aa9-b797-101b0b098f6c
=> SNOW-1628439: Update synk requirement to match with setup.py

tests/integ/modin/index/test_index_ops.py
Fixes SNOW-1624171 Fix flaky test
Fix: https://ci-dev-142.int.snowflakecomputing.com/job/SnowparkPythonSnowPandasDailyRegressRunner/720/console
=> SNOW-1624171 Fix flaky test

docs/source/modin/indexing.rst
Fixes SNOW-1578717 Fix build doc
=> SNOW-1578717 Fix build doc

.github/workflows/python-publish.yml
Fixes SNOW-1632086
Signing process is failing to validate the signature due it uses the gh action name for it. The script had a different file name and the fix is to use the correct one.
=> SNOW-1632086: update gh action name to verify signature

tests/integ/test_dataframe.py
Fixes SNOW-1632264
The test is expected to fail when the result set is large in stored procedure
=> SNOW-1632264: skip test in stored proc 

tests/integ/test_lineage.py
Fixes SNOW-1632818
we need to grant lineage view privilege in the test to view the lineage
=> SNOW-1632818: fix lineage trace test failure in daily regression test

tests/integ/modin/strings/test_strings.py
Passing Jenkins: https://ci-dev-142.int.snowflakecomputing.com/job/SnowparkPythonSnowPandasDailyRegressRunner/736/
=> Fix Jenkins test_strings.py error

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/_internal/ordered_dataframe.py, tests/integ/modin/test_chained_operations.py
Fixes SNOW-1632454 and SNOW-1518846
Fix AssertionError in tree of binary operations.
=> SNOW-1632454, SNOW-1518846: Fix AssertionError in tree of binary operations

tests/integ/scala/test_dataframe_suite.py
=> SNOW-1635810: fix precommit

tests/integ/test_lineage.py
=> SNOW-1633773 : unskip lineage test as account privilege is resolved

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/_internal/frame.py, src/snowflake/snowpark/modin/plugin/_internal/type_utils.py, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/frame/test_astype.py, tests/integ/modin/series/test_astype.py
SNOW-1620412
This PR adds support for `astype` by allowing conversion to Timedelta.
=> SNOW-1620412: Add support for `astype` conversion to Timedelta

src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/frame/test_to_snowflake.py, tests/integ/modin/frame/test_to_snowpark.py, tests/integ/modin/io/test_to_csv.py, tests/integ/modin/io/test_to_dict.py, tests/integ/modin/io/test_to_pandas.py
Fixes SNOW-1625378 Test write timedelta in I/O
Warn user the timedelta type may be lost during writing back to Snowflake.
=> SNOW-1625378 Test write timedelta in I/O

src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py, src/snowflake/snowpark/modin/plugin/_internal/cut_utils.py, src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py, src/snowflake/snowpark/modin/plugin/_internal/join_utils.py, src/snowflake/snowpark/modin/plugin/_internal/ordered_dataframe.py, src/snowflake/snowpark/modin/plugin/_internal/pivot_utils.py, src/snowflake/snowpark/modin/plugin/_internal/resample_utils.py, src/snowflake/snowpark/modin/plugin/_internal/snowpark_pandas_types.py, src/snowflake/snowpark/modin/plugin/_internal/telemetry.py, src/snowflake/snowpark/modin/plugin/_internal/timestamp_utils.py, src/snowflake/snowpark/modin/plugin/_internal/utils.py, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, src/snowflake/snowpark/modin/plugin/utils/error_message.py, tests/integ/modin/test_telemetry.py, tests/unit/modin/test_telemetry.py
SNOW-1638433 Add AssertionError message into Telemetry
Also make sure all assert errors from plugin code have error message
=> SNOW-1638433 Add AssertionError message into Telemetry

CHANGELOG.md, src/snowflake/snowpark/functions.py, src/snowflake/snowpark/mock/_functions.py, tests/integ/test_function.py
=> SNOW-1549041: Expose and create function ln

CHANGELOG.md, docs/source/snowpark/functions.rst, src/snowflake/snowpark/functions.py, tests/integ/scala/test_function_suite.py
Fixes saved changes [SNOW-1529718)
Morgan Stanley: array_remove is available in SQL but there is no corresponding API
=> Add method array_remove.

CHANGELOG.md, docs/source/snowpark/functions.rst, src/snowflake/snowpark/functions.py
=> SNOW-1549041: Add doc and fix description of function ln

src/snowflake/snowpark/modin/plugin/_internal/frame.py, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
This PR is just a small refactor to deduplicate code on snowflake query compiler.
=> SNOW-1637945: Deduplicate code in snowflake query compiler

src/snowflake/snowpark/_internal/compiler/utils.py
Fixes SNOW-1546396
Fixing a bad merge which duplicated updates in `compiler/utils.py`
=> SNOW-1546396: Fix bad merge

src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, tests/integ/compiler/test_query_generator.py, tests/integ/scala/test_snowflake_plan_suite.py, tests/integ/test_large_query_breakdown.py
Fixes SNOW-1546396
Use scoped temp table for large query breakdown.
=> SNOW-1546396: use scoped temp tables for large query breakdown

CHANGELOG.md, src/snowflake/snowpark/modin/pandas/general.py, src/snowflake/snowpark/modin/plugin/extensions/datetime_index.py, src/snowflake/snowpark/modin/plugin/extensions/index.py, src/snowflake/snowpark/modin/plugin/extensions/timedelta_index.py, tests/integ/modin/index/test_datetime_index_methods.py, tests/integ/modin/index/test_index_methods.py, tests/integ/modin/index/test_timedelta_index_methods.py
=> SNOW-1616989: Create lazy Index from another lazy Index without pulling data to client

tests/integ/test_telemetry.py
Fixes SNOW-1624163
Updating telemetry test to also extract out telemetry type.
=> SNOW-1624163 update telemetry test to return type

src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py, tests/integ/modin/types/test_timedelta_indexing.py
=> SNOW-1649753 Fix a bug while setting None to timedelta column

src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/test_concat.py
=> SNOW-1651274 Fix raising NotImplementedError for concat

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/extensions/index.py, tests/integ/modin/index/test_index_methods.py, tests/integ/modin/index/test_index_ops.py
=> SNOW-1651271 Raised  for Index bitwise operators.

tests/integ/scala/test_async_job_suite.py
to_pandas_batches require pandas
=> Skip `test_iter_cursor_wait_for_result` for no pandas

src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/groupby/test_groupby_basic_agg.py
=> Fix groupby.agg bug with Timedelta

src/snowflake/snowpark/modin/plugin/_internal/resample_utils.py
This PR refactors Snowpark pandas `resample` implementation to use `pd.date_range` for the resulting index (complete with missing bins) rather than compute the number of rows required in the output and using a generator function. `pd.date_range` uses a generator under-the-hood.
=> REFACTOR: Reuse `pd.date_range` for resample computation

CHANGELOG.md
=> Cherrypick 1.21.1 changelog to release-v1.22.0

CHANGELOG.md, recipe/meta.yaml, src/snowflake/snowpark/version.py
cherry pick https://github.com/snowflakedb/snowpark-python/pull/2268
=> [CHERRY-PICK][Release-v1.22.0] Cherry pick release change for v1.22.0

tests/mock/test_multithreading.py
Fixes SNOW-1418543
Fixing flaky test that created collision due to use of same table/view name in test.
=> SNOW-1418543: Fix Flaky test

CHANGELOG.md, recipe/meta.yaml, src/snowflake/snowpark/version.py
cherry pick pr https://github.com/snowflakedb/snowpark-python/pull/2277
=> [CHERRY-PICK][Release v1.22.1] Cherry pick changes made for release v1.22.1 

src/snowflake/snowpark/_internal/udf_utils.py
Fixes SNOW-1418523
We make a minor refactor in function `resolve_imports_and_packages` to make it more readable
=> SNOW-1418523: Minor refactor for `resolve_imports_and_packages`

tox.ini
Fixes SNOW-1671194
See a recent flaky test related to "Insufficient resource during interleaved execution.". This should help to lower the chance to hit it again.
=> SNOW-1671194 CI: configure rerun to avoid flaky tests

tests/integ/modin/frame/test_filter.py
=> SNOW-1640215: Test filtering by timedelta values.

tests/integ/modin/groupby/test_groupby_apply.py, tests/integ/modin/groupby/test_groupby_property.py
=> SNOW-1672619: Remove test code working around pandas bugs fixed in pandas 2.2.

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/_internal/frame.py, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/test_dtype_mapping.py
Fixes SNOW-1657459
make sure dtype for timestamp_ltz is correct.
=> SNOW-1657459 Improved  dtype results for TIMESTAMP_LTZ type to show correct timezone

tests/integ/test_column_names.py, tests/integ/test_cte.py, tests/integ/test_large_query_breakdown.py, tests/integ/test_query_plan_analysis.py
=> SNOW-1659276 sp precommit fixes

src/snowflake/snowpark/_internal/compiler/utils.py, tests/integ/compiler/test_query_generator.py, tests/integ/test_cte.py, tests/integ/test_dataframe.py
SNOW-1641640
1) fix field update for expr_to_alias and df_aliased_col_name_to_real_col_name during node reset for SelectStatement
2) add tests for test subqueries and alias map
=> [SNOW-1641640] Fix query generation for df alias after query transformation and add tests for df alias and subqueries

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/extensions/series_overrides.py, tests/integ/modin/series/test_apply.py
Fixes SNOW-1692775
Remove convert_dtype warning in Series.apply.
=> SNOW-1692775: Remove convert_dtype warning in Series.apply

setup.py, src/snowflake/snowpark/_internal/compiler/plan_compiler.py, src/snowflake/snowpark/_internal/compiler/utils.py, tests/integ/test_large_query_breakdown.py
=> SNOW-1642103: Add plan plotter

tests/integ/test_temp_table_cleanup.py
Fixes SNOW-1645523
Parse the query and find the query id, then wait for this drop table sql query complete before checking whether the table exists or not. However, log is not available in stored proc
=> SNOW-1645523: Fix flakiness of temp table cleaner test by waiting for query complete

tests/integ/test_large_query_breakdown.py
=> NO-SNOW: fix daily precommit

tests/integ/test_session.py
The parameter value is changed.
=> Fix test_cte_optimization_enabled_on_session

tests/unit/test_query_history.py
=> add unit test for query history repr

src/snowflake/snowpark/_internal/compiler/query_generator.py, tests/integ/compiler/test_query_generator.py
SNOW-1706295
The snowflake plan query generation is not used in actual generation, but only used by the testing. This pr does the following:
1) remove the SnowflakePlan overwrite in the code and test the query generator in a different way
2) add sql counter check for the test
=> [SNOW-1706295] Remove unused overwrite for SnowflakePlan node resolve in query generator

tests/integ/scala/test_dataframe_suite.py
=> SNOW-1710280: mark flaky test xfail

src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
ADHOC: Fix a misspelling
Just notice a misspelling of "ambiguous" , fixing it
=> ADHOC: fix a misspelling - ambiguou

tests/integ/modin/io/test_read_snowflake_query_cte.py
SNOW-1723157 Add test in precommit.
Tested https://ci-dev-142.int.snowflakecomputing.com/job/RT-Snowfort-Test-Custom/148/console
=> SNOW-1723157 Add test in precommit

tests/integ/scala/test_snowflake_plan_suite.py
=> fix test failure caused by fixture in stored proc

src/snowflake/snowpark/modin/plugin/_internal/telemetry.py, tests/integ/modin/test_telemetry.py
=> SNOW-1730923: Add interchange protocol __dataframe__ to telemetry.

CHANGELOG.md, recipe/meta.yaml, src/snowflake/snowpark/version.py, tests/integ/scala/test_snowflake_plan_suite.py
=> [CHERRY-PICK] Release v1.23.0

src/snowflake/snowpark/dataframe_writer.py
=> SNOW-1652350: Update save_as_table docstring

src/snowflake/snowpark/_internal/open_telemetry.py, tests/integ/scala/test_update_delete_merge_suite.py, tests/integ/test_udf.py
- record log sometimes contain open telemetry warning
- pandas import error in no pandas installed tox env
=> SNOW-1734196: fix flaky test

.github/workflows/daily_modin_precommit.yml, .github/workflows/daily_precommit.yml, .github/workflows/precommit.yml, tests/conftest.py, tests/unit/test_open_telemetry.py
Fixes SNOW-1732002
Because parameters for cte is enabled by default on the test account now, we can flip the test
=> SNOW-1732002: Add disable cte tests

tests/integ/test_query_history.py
=> Fix flaky test in query history

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/frame/test_tz_convert.py, tests/integ/modin/frame/test_tz_localize.py, tests/integ/modin/index/test_datetime_index_methods.py, tests/integ/modin/series/test_dt_accessor.py, tests/integ/modin/series/test_tz_convert.py, tests/integ/modin/series/test_tz_localize.py
Fixes SNOW-1707419
Improve error message for unknown timezone in tz_convert and tz_localize.
=> SNOW-1707419: Improve error message for unknown timezone in tz_convert and tz_localize

src/snowflake/snowpark/session.py
This doctest is currently not needed
=> Remove doctest in `auto_clean_up_temp_table_enabled`

.github/workflows/daily_modin_precommit.yml, .github/workflows/daily_precommit.yml, .github/workflows/precommit.yml, tests/conftest.py, tests/unit/test_open_telemetry.py
Reverts snowflakedb/snowpark-python#2432
=> Revert "SNOW-1732002: Add disable cte tests"

CHANGELOG.md
Fixes SNOW-1740300
Fixing the Changelog for 1.24.0.
=> SNOW-1740300: Fix changelog for 1.24.0

recipe/meta.yaml
=> SNOW-1654437: change recipe to accept env variable to control whether noarch build

CHANGELOG.md, docs/source/snowpark/functions.rst, src/snowflake/snowpark/functions.py, src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py, tests/integ/modin/test_apply_snowpark_python_functions.py, tests/integ/test_function.py
Fixes SNOW-1690713
This is the first step to support snowflake.cortex functions natively in Snowpark Python and pandas. More discussion related to this topic can be found [here](https://docs.google.com/document/d/17Kk5YfXDF6tSfUSCqjadjniYsGX8Kc4lgG-mICMP_Pk/edit#heading=h.548ijfvwcyee).
=> SNOW-1690713 Add support for applying snowflake_cortex_summarize

tests/integ/test_reduce_describe_query.py
There are some invalid test cases causing failure when sql simplifier is disabled
=> Fix invalid test cases in test_reduce_describe_query

src/snowflake/snowpark/column.py, src/snowflake/snowpark/dataframe.py, src/snowflake/snowpark/functions.py, src/snowflake/snowpark/udaf.py, src/snowflake/snowpark/window.py
=> [PR-review] Changes addressing column.py

src/snowflake/snowpark/dataframe.py
Addresses PR feedback for dataframe.py file.
=> [PR review] Feedback on dataframe.py

.github/workflows/precommit.yml, tests/ast/README.md, tests/ast/conftest.py, tests/ast/test_ast_setup.py, tox.ini
=> [IR] SNOW-1491199 add ast-encoding test in precommit (#2510)

CHANGELOG.md
Fixes SNOW-1773962
Fix changelog for 1.25.0.
=> SNOW-1773962: Fix changelog for 1.25.0

docs/source/snowpark/functions.rst
N/A
This adds the system_reference function to the functions doc.
=> Add system_reference to docs

tests/integ/test_reduce_describe_query.py
set eliminate_numeric_sql_value_cast_enabled to true for quoted identifiers comparison
=> Set eliminate_numeric_sql_value_cast_enabled to True for test_reduce_describe_query.py

tests/integ/test_multithreading.py
Fixes SNOW-1758742
Add test that ensures that large query breakdown and repeated subquery elimination work correctly with multiple threads.
=> SNOW-1758742: Add cte/large_query_breakdown test in multithreading suite

.github/workflows/precommit.yml, src/snowflake/snowpark/query_history.py, tests/ast/ast_test_utils.py, tests/ast/test_ast_driver.py, tests/conftest.py, tests/integ/conftest.py
SNOW-1779671 Add full ast validation mode to snowpark integration tests
=> SNOW-1779671 Add full ast validation mode to snowpark integration tests

setup.py
Make sure protobuf version compatible with streamlit and snowbook.
=> SNOW-1491199 update protobuf version requirement

src/snowflake/snowpark/_internal/server_connection.py, src/snowflake/snowpark/dataframe.py, src/snowflake/snowpark/mock/_nop_plan.py, src/snowflake/snowpark/query_history.py, src/snowflake/snowpark/session.py, tests/ast/ast_test_utils.py, tests/ast/data/df_first.test, tests/ast/test_ast_driver.py
SNOW-1787415 Fix ast validation issues found running integ tests
=> SNOW-1787415 Fix ast validation issues found running integ tests

tests/integ/test_multithreading.py
=> NO-SNOW: skip flaky test

src/snowflake/snowpark/dataframe.py
Fixes SNOW-1786772
We can track the lifetime of a temp table then
=> SNOW-1786772: Add temp table name to statement params of cache_result

src/snowflake/snowpark/_internal/server_connection.py, tests/ast/ast_test_utils.py, tests/ast/data/col_alias.test, tests/integ/utils/sql_counter.py
SNOW-1787415 Fix binary op expr with alias and send dataframe ast only once for multi-queries
=> SNOW-1787415 Fix binary op expr with alias and send dataframe ast only once for multi-queries

scripts/jenkins_regress_snowpandas.sh
install protoc for pandas jenknis job
=> SNOW-1491199 install protoc for pandas jenkins job

CHANGELOG.md, src/snowflake/snowpark/dataframe.py, tests/integ/test_open_telemetry.py
=> SNOW-1570704: add open telemetry for cache_result

src/snowflake/snowpark/modin/plugin/docstrings/__init__.py, src/snowflake/snowpark/modin/plugin/docstrings/index.py, src/snowflake/snowpark/modin/plugin/extensions/index.py
Fixes SNOW-1791556
Use docstrings folder for Index methods and properties. Docstrings for DatetimeIndex and TimedeltaIndex will be treated similarly in follow-up PRs.
=> SNOW-1791556: Use docstrings folder for Index methods and properties

.github/scripts/install_protoc.sh, .github/workflows/daily_precommit.yml, .github/workflows/precommit.yml, ci/test_fips.sh, scripts/jenkins_regress.sh, scripts/jenkins_regress_snowpandas.sh, setup.py
Fixes SNOW-1792741
We specify the version of `protoc` to make sure the generated python code works for all protobuf versions we claimed. Also add tests into CI.
=> SNOW-1792741 make sure protobuf backcompatible

CHANGELOG.md, src/snowflake/snowpark/_internal/open_telemetry.py, tests/integ/test_open_telemetry.py
=> SNOW-1734254:opentelemetry logs warnings which can be omited 

tests/integ/test_multithreading.py
This test was written badly and was not fully tested. The changes in this PR fix this test, by ensuring it runs correctly once we exit `ThreadPoolExecutor` context.
=> Fix flaky test_file_io

.github/workflows/precommit.yml, src/snowflake/snowpark/dataframe.py, tests/ast/data/Dataframe.join.prefix.test
SNOW-1787415 Fix dataframe join suite failures related to formatting of remapping left and right columns of join.
=> SNOW-1787415 Fix dataframe join suite failures related to formatting of remapping left and right columns of join.

.github/workflows/precommit.yml, src/snowflake/snowpark/_internal/ast_utils.py, src/snowflake/snowpark/_internal/proto/ast.proto, src/snowflake/snowpark/_internal/utils.py, src/snowflake/snowpark/dataframe_writer.py, src/snowflake/snowpark/table_function.py, src/snowflake/snowpark/window.py, tests/ast/data/windows.test, tests/integ/scala/test_dataframe_join_suite.py, tests/integ/scala/test_dataframe_range_suite.py, tests/integ/test_stored_procedure_profiler.py
Fixes remaining tests for AST enabled merge gate.
Details:
- changes window IR to use Expr instead of int to support make_interval.
- moves checks for orderby in front.
- fixes package moduletype management for sproc.
- fixes check for create_map
- fixes bug in AST serialization for dataframewriter
=> SNOW-1760495 Fix remaining merge gate failures.

.github/workflows/daily_precommit.yml
SNOW-1491199 Fix type_checking in daily precommit
=> SNOW-1491199 Fix type_checking in daily precommit

tests/integ/test_multithreading.py
=> Fix daily pre-commit tests

.github/workflows/daily_modin_precommit.yml, .github/workflows/daily_precommit.yml
Fix build docs in daily precommit
=> SNOW-1491199 Fix build docs in daily precommit

src/snowflake/snowpark/dataframe_analytics_functions.py, tests/ast/data/df_analytics_functions.test, tests/integ/test_df_to_pandas.py
SNOW-1787415 Fix dataframe analytic functions col formatter
=> SNOW-1787415 Fix dataframe analytic functions col formatter

src/snowflake/snowpark/_internal/analyzer/metadata_utils.py, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, tests/integ/test_reduce_describe_query.py
Fixes SNOW-1791084
Another optimization we can do further by caching metadata on the child of SelectStatement
=> SNOW-1791084: Cache metadata on SelectStatement.from_._snowflake_plan

src/snowflake/snowpark/_internal/utils.py, src/snowflake/snowpark/dataframe_writer.py, src/snowflake/snowpark/query_history.py, src/snowflake/snowpark/relational_grouped_dataframe.py, src/snowflake/snowpark/stored_procedure.py, tests/ast/ast_test_utils.py
Address comments for
- `dataframe_writer.py`
- `query_history.py`
- `relational_grouped_dataframe.py`
- `stored_procedure.py`
=> PR review core files

src/snowflake/snowpark/mock/_analyzer.py, src/snowflake/snowpark/mock/_connection.py, src/snowflake/snowpark/mock/_functions.py, src/snowflake/snowpark/mock/_nop_connection.py, src/snowflake/snowpark/mock/_plan.py, src/snowflake/snowpark/mock/_stored_procedure.py, src/snowflake/snowpark/mock/_udtf.py
Address PR feedback for SNOW-1491199.
=> PR feedback on local testing files

src/snowflake/snowpark/relational_grouped_dataframe.py
revert change to move docstring to constructor in GroupingSets.
=> Revert docstring

recipe/meta.yaml
Make sure build proto correctly in conda
https://ci-dev-142.int.snowflakecomputing.com/job/AnacondaPackageBuilder-x86/1574/
=> SNOW-1491199 IR: Fix conda requirements

tests/integ/modin/series/test_str_accessor.py
=> SNOW-1803169: Fix test_str_len_list_coin_base to account for sql simplifier

setup.py, tox.ini
Deliver better message if packages are not installed for protoc
=> SNOW-1491199 Improve developer experience related to protoc

.github/workflows/python-publish.yml
Fix python publish job: https://github.com/snowflakedb/snowpark-python/actions/runs/11827990870/job/32957225738
=> NO-SNOW: fix protoc dependency to fix python publish

tests/integ/test_stored_procedure_profiler.py
=> Fix stored procedure profiler test of error sp

.github/workflows/python-publish.yml
=> SNOW-1491199 Fix publish job

tox.ini
=> Fix coverage

.github/workflows/daily_modin_precommit.yml, .github/workflows/daily_precommit.yml, .github/workflows/precommit.yml
Fixes the location to find docs so they can be uploaded after the build.
=> NO-SNOW: fix build doc location

CHANGELOG.md, src/snowflake/snowpark/_internal/utils.py, src/snowflake/snowpark/modin/plugin/__init__.py, tests/integ/modin/frame/test_transpose.py, tests/integ/modin/strings/test_get_dummies_series.py, tests/integ/scala/test_dataframe_aggregate_suite.py
Fixes SNOW-1815309
[x] I acknowledge that I have ensured my changes to be thread-safe
=> SNOW-1815309: Remove dynamic pivot private preview warnings.

CHANGELOG.md, docs/source/snowpark/io.rst, src/snowflake/snowpark/dataframe_reader.py, src/snowflake/snowpark/dataframe_writer.py, tests/integ/scala/test_dataframe_reader_suite.py, tests/integ/scala/test_dataframe_writer_suite.py
Fixes SNOW-1794370
Add `.format().load()` methods to `DataFrameReader` and `.format().save()` methods to `DataFrameWriter`.
=> SNOW-1794370 dataframe reader writer improvements

tests/integ/test_session.py
=> CP fix precommit test failure (#2648)

docs/source/snowpark/session.rst, src/snowflake/snowpark/session.py
Fixes SNOW-1794382
Update rst files for new public methods `version` and `getActiveSession`.
=> SNOW-1794382: Update rst files

src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
apply/applymap doctests are failing in the daily tests of certain environments https://github.com/snowflakedb/snowpark-python/actions/runs/11909589229/job/33187474965
This is caused by SNOW-1818207, a Snowpark Python bug where package constraints for UDFs are not being correctly resolved under certain conditions. I'm skipping these failed tests until we have a resolution for the packaging bug.
=> NO-SNOW: Skip pandas apply doctests

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/extensions/indexing_overrides.py, tests/integ/modin/frame/test_loc.py
Fixes SNOW-1829928 Fix a bug related to df.loc set
The bug fix is simply make sure the input of columns to internal method should not be a scalar.
=> SNOW-1829928 Fix a bug related to df.loc set

.github/workflows/precommit.yml, src/snowflake/snowpark/_internal/utils.py
SNOW-1826001
Removes some deadcode which was removed in main. Removes uploading coverage for AST doctest.
=> SNOW-1826001 Follow up with post-merge comments, remove coverage upload for AST doctest.

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/analyzer.py, src/snowflake/snowpark/_internal/analyzer/expression.py, src/snowflake/snowpark/_internal/analyzer/select_statement.py, src/snowflake/snowpark/dataframe.py, tests/integ/test_column.py, tests/unit/test_expression_dependent_columns.py
Fixes SNOW-1794364
implement colRegex of snowpark in dataframe. here is an one pager to explain the scenario of col_regex():https://docs.google.com/document/d/14tYspmPDlRGYOnZNLnmFurHb4S_1jDRGQI8u_-styMw/edit?usp=sharing
=> SNOW-1794364: [API Coverage] DataFrame.colRegex

recipe/meta.yaml
Fixes SNOW-1829954
Make setup.py and conda recipe have same requirement of cloudpickle
=> SNOW-1829954: Make setup.py and conda recipe have same requirement of cloudpickle

.github/pull_request_template.md, CONTRIBUTING.md
=> SNOW-1673185: update contributing.md to reflect thread-safe changes

.github/workflows/daily_jupyter_nb_test.yml
Fixes SNOW-1831660
Fix daily notebook precommit test:
Passed: https://github.com/snowflakedb/snowpark-python/actions/runs/12057364658
=> SNOW-1831660 Fix daily notebook precommit test

src/snowflake/snowpark/_internal/analyzer/select_statement.py, tests/integ/test_large_query_breakdown.py, tests/integ/test_multithreading.py, tests/integ/test_nested_select_plan_analysis.py
Fixes SNOW-1830648
Update project complexity calculation by no directly updating dictionary which causes wrong updates.
=> SNOW-1830648: Fix nest query complexity adjustment

src/snowflake/snowpark/_internal/utils.py, src/snowflake/snowpark/session.py, tests/integ/test_session.py, tests/unit/test_session.py
Fixes SNOW-1830203
We need a new parameter for control snowpark version
=> SNOW-1830203: Add a new parameter for CTE optimization 

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/docstrings/io.py
Fixes SNOW-1830249
Improve docs for pd.read_excel.
=> SNOW-1830249: Improve docs for pd.read_excel

CHANGELOG.md, recipe/meta.yaml, setup.py
Fixes SNOW-1842464
Add explicit dependencies on `python-dateutil` to `setup.py` and `recipe/meta.yaml`.
=> SNOW-1842464 Fix the stored procedure build break 

tests/integ/scala/test_dataframe_copy_into.py, tox.ini
=> SNOW-1843690: fix daily precommit test failiure

tests/ast/decoder.py
=> Batur-1847106

tests/ast/decoder.py
=> Snow-1847462 Add support for decoding col_string.

tests/ast/decoder.py
=> Snow-1830499

.github/workflows/python-publish.yml, CHANGELOG.md, docs/source/snowpark/functions.rst, recipe/meta.yaml, src/snowflake/snowpark/functions.py, src/snowflake/snowpark/version.py
snowpark python 1.26.0 is released
CP changes from the release branch back to main branch
=> v1.26.0 changelog merge back

tests/ast/decoder.py
=> SNOW-1830499: Incorporate arthurs suggested improvement

tests/ast/decoder.py, tests/ast/test_ast_driver.py
=> Snow-1852882 Add support for df.collect()

tests/ast/decoder.py
=> df.count()

src/snowflake/snowpark/_internal/proto/ast.proto, src/snowflake/snowpark/dataframe.py, tests/ast/data/RelationalGroupedDataFrame.test, tests/ast/decoder.py, tests/ast/test_ast_driver.py
Fixes SNOW-1830511 and SNOW-1830542
Added decoder logic for `DataFrame.agg`, `DataFrame.group_By`, and `RelationalGroupedDataFrame.agg`. The corresponding tests are: `DataFrame.agg.test`, `RelationalGroupedDataFrame.test`, and `RelationalGroupedDataFrame.agg.test`.
=> SNOW-1830511, SNOW-1830542 Decoder logic for `DataFrame.agg`, `DataFrame.group_By`, and `RelationalGroupedDataFrame.agg`

src/snowflake/snowpark/_internal/ast/utils.py, tests/ast/decoder.py, tests/ast/test_ast_driver.py
=> Snow-1830508: Support for UDFs.

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
Fixes SNOW-1859608
Add missing docs for DataFrame.map.
=> SNOW-1859608: Add missing docs for DataFrame.map

CHANGELOG.md, README.md
add instruction for package signature verification
=> SNOW-1862674: update readme for signature verification

tests/ast/decoder.py
Fixes SNOW-1830535
Added decoder functionality for `df.drop`, `df.first`, `df.intersect`, and `df.except`.
=> SNOW-1830535 Add decoder functionality for `df.drop`, `df.first`, `df.intersect`, and `df.except`

tests/ast/decoder.py
Fixes SNOW-1830497
Added decoder logic for `asc`, `desc`, and  `case_when`.
=> SNOW-1830497: Added decoder logic for `asc`, `desc`, and  `case_when`

tests/ast/decoder.py
=> fixing typo

src/snowflake/snowpark/_internal/proto/ast.proto, src/snowflake/snowpark/dataframe.py, tests/ast/data/DataFrame.unpivot.test
Fixes SNOW-1866100
Update DataFrame.unpivot AST encoding to include `include_nulls`
=> SNOW-1866100 Update DataFrame.unpivot AST encoding to include `include_nulls`

src/snowflake/snowpark/dataframe_reader.py
Fixes SNOW-1863392
POC of python multi-process ingestion of external data source
=> SNOW-1863392:POC of python multi-process data ingestion 

tests/ast/data/RelationalGroupedDataFrame.test, tests/ast/data/df_sort.test, tests/ast/decoder.py
Fixes SNOW-1830517, SNOW-1830516
Fixed the way columns were being decoded, added decoder functionality for Dataframe cube, describe, distinct, drop_duplicates, filter, and getitem.
=> SNOW-1830517, SNOW-1830516 Add Decoder functionality for more Dataframe functions

CHANGELOG.md, src/snowflake/snowpark/dataframe.py, tests/integ/test_dataframe.py
=> SNOW-1873919: Add an option to keep the order in df.with_columns

tests/ast/data/DataFrame.pivot.test, tests/ast/data/DataFrame.unpivot.test, tests/ast/decoder.py
Fixes SNOW-1830521, SNOW-1830526
Added decoder logic for select_expr, stat, pivot, rollup, indexers.
=> SNOW-1830521, SNOW-1830526 even more decoder df

src/snowflake/snowpark/_internal/ast/utils.py, src/snowflake/snowpark/mock/_stored_procedure.py, src/snowflake/snowpark/session.py, tests/ast/data/Session.call.test, tests/ast/data/sproc.test, tests/ast/decoder.py
Fixes SNOW-1830543
Adds support for Session.call.test.
=> Snow-1830543 Session.call etc.

.github/workflows/daily_precommit.yml
The [daily_precommit](https://github.com/snowflakedb/snowpark-python/actions/workflows/daily_precommit.yml) workflow has been broken since #2852 due to a missing `run` key.
=> NO-SNOW: Fix daily_precommit.yml

src/snowflake/snowpark/functions.py, tests/ast/data/col_lit.test
Changes to allow for proper lit(lit(...)) AST behavior.
=> [AST FIX] functions.py modification for lit(lit(lit(....)))

src/snowflake/snowpark/_internal/proto/ast.proto, tests/ast/decoder.py
Fixes SNOW-1830541
Minor changes to the decoder to make functions1.test and functions2.test work.
=> SNOW-1830541 Decoder functionality for functions1.test and functions2.test

.github/workflows/daily_precommit.yml
Fixes NO-SNOW
This PR disables doctests in python 3.12 runs of the daily_precommit tests. Those tests suites will fail in udf examples until a version of this library is available on the server side.
=> NO-SNOW: Fix daily precommit doctests for python 3.12

tests/ast/data/Session.table_function.test
Fixes SNOW-1830540
Updating the Session.table_function.test expectation test so that it works logically as well. Previously, it was using functions that were not defined.
=> SNOW-1830540 Session.table_function.test

src/snowflake/snowpark/_internal/compiler/cte_utils.py, tests/integ/scala/test_datatype_suite.py, tests/integ/test_cte.py, tests/integ/test_large_query_breakdown.py
a. Fixed the tests here: https://github.com/snowflakedb/snowpark-python/actions/runs/12826845109/job/35767761873
b. Updated `is_simple_select_entity` to also detect `SnowflakeTable` when sql simplifier is disabled.
=> NO-SNOW: Fix Large Query Breakdown daily precommit

tests/ast/decoder.py
=> Minor typo using "is" instead of "=="

tests/integ/test_catalog.py
Do not fail test if the failure is due to `APIError`
=> NO-SNOW: Fix Flaky APIError in catalog tests

scripts/copy-remote-ast.sh
Fixes NOSNOW
Just an internal script change... No impact on anything in prod.
=> NOSNOW | AST/unparser: fixed the script to ensure the output directory exists before scping the JAR

src/snowflake/snowpark/_internal/type_utils.py, tests/integ/test_dataframe.py, tests/unit/test_types.py
=> SNOW-1890997: Support schema string without colon in create_dataframe

tests/integ/modin/frame/test_apply_axis_0.py, tests/integ/modin/frame/test_cache_result.py, tests/integ/modin/frame/test_iloc.py
Further reduce some slow tests suite
=> Disable couple more slow test suites on github

tests/ast/data/DataFrame.count2.test, tests/ast/data/Dataframe.to_snowpark_pandas.test, tests/ast/data/Table.merge.test, tests/ast/data/case_when.test, tests/ast/data/col_cast.test, tests/ast/data/col_cast_coll.test, tests/ast/data/col_in_.test, tests/ast/data/col_try_cast.test, tests/ast/data/session.read.test, tests/ast/data/sproc.test, tests/ast/decoder.py
Fixes SNOW-1794510
Added functionality for DataFrame reader and writer, fixed the AST used with `column.in_` in the decoder, and a couple bug fixes.
=> SNOW-1794510 Support missing functionality in the decoder

src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/_internal/compiler/plan_compiler.py, src/snowflake/snowpark/_internal/server_connection.py, src/snowflake/snowpark/_internal/temp_table_auto_cleaner.py, src/snowflake/snowpark/_internal/utils.py, src/snowflake/snowpark/mock/_connection.py, src/snowflake/snowpark/session.py, tests/unit/test_dataframe.py, tests/unit/test_session.py
Fixes SNOW-1720855
Re-add multi-thread param which was cleaned-up here: https://github.com/snowflakedb/snowpark-python/pull/2658
=> SNOW-1720855: Re-add param protection for thread-safe updates

CHANGELOG.md, src/snowflake/snowpark/column.py, src/snowflake/snowpark/functions.py, tests/integ/test_function.py
=> SNOW-1875145: change `json_element` to `_is_qualified_name`

CHANGELOG.md, docs/source/snowpark/functions.rst, src/snowflake/snowpark/_internal/analyzer/window_expression.py, src/snowflake/snowpark/functions.py, tests/ast/data/functions2.test
=> SNOW-1896935 Implement nth_value

src/snowflake/snowpark/_internal/server_connection.py
Fixes NOSNOW
Correct server-connection.py in merge-decoder
=> [NOSNOW] Correct server-connection.py in merge-decoder

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/analyzer.py, src/snowflake/snowpark/_internal/error_message.py, src/snowflake/snowpark/relational_grouped_dataframe.py, tests/integ/scala/test_dataframe_aggregate_suite.py, tests/unit/scala/test_error_message.py
=> SNOW-1883226: Allow multiple aggregations in DataFrame.pviot

src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/test_scoped_temp_objects.py, tests/unit/test_internal_utils.py
=> Fix assert MissingPandas

tests/integ/test_scoped_temp_objects.py
=> SNOW-NO: reenable test

CHANGELOG.md, src/snowflake/snowpark/column.py, src/snowflake/snowpark/functions.py, tests/integ/scala/test_column_suite.py
=> SNOW-1882644: Support Column object in `in_`

tests/integ/scala/test_dataframe_suite.py, tests/integ/test_df_aggregate.py, tests/integ/test_function.py, tests/integ/test_pandas_to_df.py
=> NO-SNOW: fix broken tests in SP

tests/ast/decoder.py, tests/ast/test_ast_driver.py
Fixes SNOW-1794510
Updated AST tests (they had a weird Spark error message appear in the expectation tests output) and clean up decoder.
=> SNOW-1794510 Update AST tests and clean up decoder

tests/ast/data/col_within_group.test
[SNOW-1911478: Expectation tests for Column.within_group AST generation](https://snowflakecomputing.atlassian.net/browse/SNOW-1911478)
=> Column.within_group expectation test

src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py
- fix conn.execute
- make 2 function internal
=> SNOW-1916596: fix conn execute, make implmentation function private

src/snowflake/snowpark/functions.py, tests/ast/data/functions1.test
[SNOW-1911483: Fix functions that rely on Column APIs to generate AST](https://snowflakecomputing.atlassian.net/browse/SNOW-1911483)
=> Use builtin function AST pattern for {equal_nan, is_null, negate, not_}

src/snowflake/snowpark/functions.py, tests/ast/data/functions2.test
[SNOW-1876948: AST for v1.27 - Support new functions in functions.py](https://snowflakecomputing.atlassian.net/browse/SNOW-1876948)
=> Add AST gen to new functions in Snowpark 1.27

src/snowflake/snowpark/_internal/utils.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py, tests/resources/test_data_source_dir/test_data_source_data.py
Fixes SNOW-1887897
- add custom type support
- add dbms detection
- wrap exception
- column name related code optimization
=> SNOW-1887897: [DataSource] add custom schema support

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py, src/snowflake/snowpark/dataframe.py, src/snowflake/snowpark/session.py
=> SNOW-1846317: Fix version number for arrow table support

CHANGELOG.md, docs/source/modin/supported/series_str_supported.rst, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/series/test_str_accessor.py
Fixes SNOW-1891887
Add support for list values in Series.str.get.
=> SNOW-1891887: Add support for list values in Series.str.get

CHANGELOG.md, src/snowflake/snowpark/_internal/utils.py, tests/unit/test_internal_utils.py
similar the connector PR change: https://github.com/snowflakedb/snowflake-connector-python/pull/2034/
there's a chance that concurrent object creation resulting in same obj name due to global seed being the same.
this PR improves random object name generation by creating a new Random() obj each time which uses a new seed
=> SNOW-1882766: improve random name generation

src/snowflake/snowpark/_internal/ast/utils.py, src/snowflake/snowpark/_internal/proto/ast.proto, src/snowflake/snowpark/dataframe_stat_functions.py, src/snowflake/snowpark/types.py, tests/ast/data/DataFrame.count2.test, tests/ast/data/DataFrame.stat.test, tests/ast/data/Dataframe.drop_duplicates_snow1874622.test, tests/ast/data/RelationalGroupedDataFrame.test, tests/ast/data/Session.create_dataframe.test, tests/ast/data/Table.merge.test, tests/ast/data/col_cast.test, tests/ast/data/col_cast_coll.test, tests/ast/data/session.read.test, tests/ast/data/sproc.test, tests/ast/data/udtf.test
[SNOW-1918334](https://snowflakecomputing.atlassian.net/browse/SNOW-1918334)
[SNOW-1918334]: https://snowflakecomputing.atlassian.net/browse/SNOW-1918334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-1918334: Fix missing ColumnIdentifier calls

src/snowflake/snowpark/_internal/proto/ast.proto, tests/ast/data/RelationalGroupedDataFrame.test, tests/ast/data/sproc.test, tests/ast/data/udtf.test
Fixes NOSNOW
Update ast.proto and fix AST tests.
=> NOSNOW - Fix Snowpark AST Tests

.github/workflows/daily_jupyter_nb_test.yml, .github/workflows/daily_modin_precommit_py311_py312.yml, .github/workflows/daily_modin_precommit_py39_py310.yml
Fixes SNOW-1936622
This PR meant to change the start time to reduce pressure on warehouse. This PR shall reduce flaky test caused by insufficient resources
The start time is decided based on the average time taken by each test
=> SNOW-1936622:change daily precommit start time to reduce pressure on warehouse

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py, src/snowflake/snowpark/mock/_snowflake_to_pandas_converter.py, src/snowflake/snowpark/mock/_stage_registry.py, tests/integ/scala/test_dataframe_reader_suite.py
Fixes SNOW-1923645
This PR adds support to the local testing csv reader for the NULL_IF/NULLVALUE option. This allows users to specify one or more values that should be considered as nulls when loading the data.
=> SNOW-1923645: [Local Testing] Add support for NULL_IF when loading csvs

src/snowflake/snowpark/functions.py
=> Fix sql_expr docstring example

tests/integ/scala/test_dataframe_writer_suite.py, tests/integ/scala/test_datatype_suite.py
Fixes NO-SNOW
This PR disables a couple of parameters that are breaking iceberg tests. These parameters will require some additional changes in order for the client to be able to support them.
=> NO-SNOW: Disable LOB parameters for iceberg tests.

tests/integ/modin/test_sql_counter.py
Fixes SNOW-1937431
Fix describe query counts in test_sql_counter.py.
=> SNOW-1937431: Fix describe query counts in test_sql_counter.py

src/snowflake/snowpark/dataframe_reader.py, src/snowflake/snowpark/exceptions.py, tests/integ/test_data_source_api.py
Fixes SNOW-1888002, SNOW-1923199
- implement session_init_statement
- improve error experience, previously error is passed back from sub process because it does not support pickle protocol
=> SNOW-1888002, SNOW-1923199: implement session_init_statement and improve error experience

CHANGELOG.md, src/snowflake/snowpark/dataframe.py, src/snowflake/snowpark/session.py, tests/integ/test_dataframe.py
Fixes SNOW-1210188
Add param protection to disable the df.distinct improvement. All tests seem to pass but adding this for anyone to revert to old behavior if they want.
=> SNOW-1210188: Add param protection for df.distinct improvement

CHANGELOG.md
=> NO-SNOW:bump release date

CHANGELOG.md, docs/source/snowpark/functions.rst, src/snowflake/snowpark/functions.py, tests/ast/data/functions2.test
=> SNOW-1936677: Support ai_filter, ai_agg and summarize_agg functions

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, tests/integ/test_multithreading.py
=> SNOW-1943700: minor thread-safe bugfix

src/snowflake/snowpark/_internal/data_source_utils.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py, tests/resources/test_data_source_dir/test_data_source_data.py
=> SNOW-1938435: implement fetch size based ingestion

setup.py, src/snowflake/snowpark/_internal/data_source_utils.py, src/snowflake/snowpark/dataframe_reader.py
=> SNOW-1933176: oracle perf improve

tests/integ/compiler/test_query_generator.py, tests/integ/test_cte.py, tests/integ/test_large_query_breakdown.py, tests/integ/test_query_history.py
=> SNOW-1946738: Update expectations for reduce describe query enabled

tests/perf/data_source/README.md, tests/perf/data_source/dev_requirements.txt, tests/perf/data_source/scripts/base_db_setup.py, tests/perf/data_source/scripts/dbtest_config.py, tests/perf/data_source/scripts/e2etest.py, tests/perf/data_source/scripts/jdbc_drivers/README.md, tests/perf/data_source/scripts/oracle_resource_setup.py, tests/perf/data_source/scripts/sql_server_resource_setup.py, tox.ini
=> SNOW-1913915: add perf test scripts

src/snowflake/snowpark/_internal/data_source_utils.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py
Fixes SNOW-1916054
- mark feature as prpr
- improve error message
- refactor retry code
=> SNOW-1916054: release preparation

setup.py, src/snowflake/snowpark/_internal/type_utils.py, src/snowflake/snowpark/dataframe_reader.py, src/snowflake/snowpark/dataframe_writer.py, tests/resources/test_data_source_dir/test_data_source_data.py
=> SNOW-1916054: release preparation update batch 2

src/snowflake/snowpark/functions.py
=> Skip `ai_filter` doctest on gcp

tests/integ/test_stored_procedure.py, tests/integ/test_udaf.py, tests/integ/test_udf.py, tests/integ/test_udtf.py
=> Skip running artifact repo related tests on python 3.8

tests/integ/scala/test_dataframe_writer_suite.py, tests/integ/scala/test_datatype_suite.py
=> Avoid `alter session` in stored proc test

src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py
=> SNOW-1956122: support dbapi options load

src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py
=> NO SNOW: merge preparation for dbapi

src/snowflake/snowpark/dataframe_reader.py
=> NO SNOW: enchance docstring

tests/conftest.py, tests/integ/conftest.py
--->
Fixes SNOW-1794509 Add dataframe-processor pkg version and location options to pytest
=> SNOW-1794509 Add dataframe-processor pkg version and location options to pytest

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py, src/snowflake/snowpark/modin/plugin/extensions/pd_extensions.py, src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
Fixes SNOW-1432556
Improve documentation for if_exists in to_snowflake.
=> SNOW-1432556: Improve documentation for if_exists in to_snowflake

tests/integ/test_data_source_api.py
=> NO-SNOW: skip time check for parallel as it's not mock test any more

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/select_statement.py, src/snowflake/snowpark/_internal/telemetry.py, src/snowflake/snowpark/session.py, tests/integ/scala/test_snowflake_plan_suite.py, tests/integ/test_simplifier_suite.py, tests/integ/test_telemetry.py
=> SNOW-1959601: fix distinct bug with .orderby().select().distinct()

tests/ast/conftest.py, tests/ast/data/smoke1.test, tests/ast/data/smoke2.test
Fixes SNOW-0000000
Add a couple of test tables, and two tests that exercise a realistic and semantically correct combination of Snowpark API calls.
=> Add a couple of AST tests with a more realistic schema

CHANGELOG.md, docs/source/snowpark/functions.rst, recipe/meta.yaml, setup.py, src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py, src/snowflake/snowpark/_internal/proto/ast.proto, src/snowflake/snowpark/_internal/type_utils.py, src/snowflake/snowpark/_internal/utils.py, src/snowflake/snowpark/file_operation.py, src/snowflake/snowpark/functions.py, src/snowflake/snowpark/session.py, src/snowflake/snowpark/types.py, src/snowflake/snowpark/udf.py, tests/ast/data/col_cast.test, tests/ast/data/col_try_cast.test, tests/ast/data/functions2.test, tests/integ/scala/test_datatype_suite.py, tests/integ/scala/test_udf_suite.py
=> SNOW-1936676: Support FILE type and its functions

src/snowflake/snowpark/_internal/data_source_utils.py, src/snowflake/snowpark/_internal/utils.py, tests/unit/test_utils.py
=> NO-SNOW: do not use packaging as it's not a dependency in stored proc

tests/integ/scala/test_dataframe_join_suite.py
=> SNOW-1964016: fix error mismatch

.github/workflows/daily_precommit.yml, tests/integ/test_cte.py
=> Fix daily precommit

.github/workflows/daily_precommit.yml, .github/workflows/precommit.yml, src/snowflake/snowpark/session.py, tests/integ/test_packaging.py, tests/resources/test_requirements.txt
=> SNOW-1933233: Enable tests for python3.12

.github/workflows/daily_precommit.yml, CHANGELOG.md, ci/snyk/requirements.txt, recipe/meta.yaml, setup.py, tests/integ/scala/test_dataframe_join_suite.py, tests/integ/test_cte.py
=> NO-SNOW: Release v1.29.0 merge back

src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
Fixes SNOW-1926348
Refactor only PR
Moves common logic of creating output Dataframe in UDTF to a shared method.
=> SNOW-1926348: [Refactor only] De duplicate code between udtf functions

src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
Fixes SNOW-1926348
During apply execution in UDTF we try to infer if the function is a transform or not. In current implementation, we are are not able to distinguish between transform or aggregate if dataframe has only 1 row. This PR fixes the issue by explicitly passing `is_transform` boolean from caller function.
Jenkins validation run: https://snowpark-python-001.jenkinsdev1.us-west-2.aws-dev.app.snowflake.com/job/SnowparkPythonSnowPandasDailyRegressRunner/197597/
=> SNOW-1926348: Fix failing tests in daily regress runner

docs/source/snowpark/io.rst, src/snowflake/snowpark/_internal/data_source_utils.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py
=> SNOW-1956591: copy doc update

src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py, tests/integ/test_stored_procedure.py
=> SNOW-1975289: fix put bug in sproc

src/snowflake/snowpark/_internal/data_source_utils.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py
=> SNOW-1975364: use file for cross process communication

CHANGELOG.md, src/snowflake/snowpark/dataframe_reader.py, src/snowflake/snowpark/dataframe_writer.py
=> NO-SNOW: revert ast change and update changelog

src/snowflake/snowpark/functions.py, tests/integ/scala/test_udf_suite.py
=> Fix file type test 

.github/workflows/cla_bot.yml, scripts/copy-ast.sh, scripts/copy-remote-ast.sh, tests/ast/README.md, tests/ast/conftest.py
=> NOSNOW Updated monorepo unparser location

CHANGELOG.md, docs/source/snowpark/files.rst, src/snowflake/snowpark/files.py, tests/unit/test_files.py
SNOW-1998295
This PR only updates documentation related to the SnowflakeFile writes feature general availability.
=> SNOW-1998295: Update docs for SnowflakeFile writes general availability

CHANGELOG.md, docs/source/snowpark/files.rst, src/snowflake/snowpark/files.py, src/snowflake/snowpark/mock/_functions.py, src/snowflake/snowpark/mock/_plan.py, tests/integ/scala/test_function_suite.py, tests/integ/test_df_aggregate.py, tests/unit/test_files.py
Fixes SNOW-1983231
This PR fixes a bug where empty aggregation groups could still generate rows. This should only ever be the case when the dataframe contains no rows. When a group by key is specified the expected result is that no rows are returned. If there is no group_by key specified then the aggregate is over the whole dataframe and a single result row is expected with a default value for the specified aggregations.
This PR better matches the expected behavior by ignoring results for empty aggregation groups when a group by is specified and adding the default value when a group …
=> SNOW-1983231: [Local Testing] Fix empty aggregations creating rows.

.github/pull_request_template.md, .github/workflows/ast-check.yml, CONTRIBUTING.md
[SNOW-1923653](https://snowflakecomputing.atlassian.net/browse/SNOW-1923653)
This PR creates an AST acknowledgement checkbox in our repository's PR template along with a GitHub action to verify its usage. This is in the same vein as the thread safety acknowledgement checkbox and GitHub Action.
[SNOW-1923653]: https://snowflakecomputing.atlassian.net/browse/SNOW-1923653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-1923653: Add AST generation acknowledgement to PR template and GitHub action to validate it

src/snowflake/snowpark/modin/plugin/_internal/utils.py
Fixes SNOW-2016764
Fix credit usage tracking for cout_rows().
=> SNOW-2016764: Fix credit usage tracking for cout_rows()

src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-2107878
Fix credit usage tracking for DataFrame/Series.to_csv.
=> SNOW-2107878: Fix credit usage tracking for DataFrame/Series.to_csv

CHANGELOG.md, docs/source/modin/dataframe.rst, docs/source/modin/series.rst, src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py, src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py, tests/integ/modin/frame/test_create_or_replace_dynamic_table.py, tests/integ/modin/series/test_create_or_replace_dynamic_table.py
Fixes SNOW-213702, SNOW-2014127
Add support for DataFrame/Series.create_or_replace_dynamic_table.
=> SNOW-213702, SNOW-2014127: Add support for DataFrame/Series.create_or_replace_dynamic_table

src/snowflake/snowpark/functions.py, tests/integ/scala/test_udf_suite.py
Fix and skip some file data type related tests
=> Fix FILE type related tests

tests/integ/modin/io/test_read_snowflake_iceberg.py
Fixes SNOW-2021998
Add tests to verify read_snowflake can read iceberg tables in the relaxed pandas mode.
=> SNOW-2021998: Add tests to verify read_snowflake can read iceberg tables

src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/_internal/proto/ast.proto
NOSNOW
Update `ast.proto` to reflect changes in server-side (introduction of truncated statement entities).
=> NOSNOW: Update ast.proto

.github/scripts/decrypt_parameters.sh, .github/workflows/parameters/parameters_dbapi.py.gpg
=> SNOW-1906584: setup ci/cd and data source

src/snowflake/snowpark/_internal/udf_utils.py, tests/integ/conftest.py, tests/integ/test_udf.py
=> NO SNOW: add client side check on aritfact

CHANGELOG.md, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py
=> SNOW-1913860: update default fetch size value

CHANGELOG.md
=> NO-SNOW: fix changelog

docs/source/snowpark/index.rst, docs/source/snowpark/stored_procedure_profiler.rst, src/snowflake/snowpark/__init__.py, src/snowflake/snowpark/session.py
=> SNOW-2033125: remove profiler prpr tag as it is going to GA

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/io/snow_io.py, tests/integ/modin/io/test_read_html.py, tests/integ/modin/io/test_read_sas.py, tests/integ/modin/io/test_read_xml.py
Fixes SNOW-2041753, SNOW-2041754, SNOW-2041755
Add support for reading files from stage for pd.read_html/read_xml/read_sas.
=> SNOW-2041753, SNOW-2041754, SNOW-2041755: Add support for reading from stage for pd.read_html/read_xml/read_sas

tests/integ/scala/test_dataframe_reader_suite.py
=> Skip XML read test in stored proc

tests/integ/scala/test_dataframe_reader_suite.py, tests/integ/scala/test_dataframe_suite.py, tests/integ/test_column.py, tests/integ/test_dataframe.py
=> NO SNOW: fix regression tests

docs/source/modin/supported/series_str_supported.rst
Fixes SNOW-2044891
Improve documentation for string functions operating on string and non-string columns.
=> SNOW-2044891: Improve documentation for string functions operating on string and non-string columns

CHANGELOG.md, docs/source/modin/dataframe.rst, docs/source/modin/series.rst, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py, src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py, tests/integ/modin/frame/test_to_iceberg.py, tests/integ/modin/series/test_to_iceberg.py
Fixes SNOW-2029020, SNOW-2029022
Add support for DataFrame/Series.to_iceberg.
=> SNOW-2029020, SNOW-2029022: Add support for DataFrame/Series.to_iceberg

tests/integ/modin/test_sql_counter.py
Fixes SNOW-2040872
Fix describe_count issue in jenkins.
=> SNOW-2040872: Fix describe_count issue in jenkins

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/metadata_utils.py, src/snowflake/snowpark/_internal/analyzer/select_statement.py, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, tests/integ/test_large_query_breakdown.py, tests/integ/test_reduce_describe_query.py
Fixes SNOW-2040349
We don't cache metadata on SelectableEntity in the past so some metadata is lost when calling session.table
=> SNOW-2040349: Cache metadata on SelectableEntity 

CHANGELOG.md
=> NO SNOW: add changelog for UDTF ingestion in dbapi

tests/integ/datasource/test_databricks.py
=> NO-SNOW: skip dbx test if missing pandas dependency

CHANGELOG.md, docs/source/modin/supported/series_str_supported.rst, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/series/test_str_accessor.py
Fixes SNOW-2053920
Add Support for dict values in Series.str.slice.
=> SNOW-2053920: Add Support for dict values in Series.str.slice

tests/perf/data_source/scripts/dbtest_config.py, tests/perf/data_source/scripts/e2etest.py, tests/perf/data_source/scripts/oracle_resource_setup.py
Fixes SNOW-2025399
- add configs for pyspark optimization
- misc improvement for test code
=> SNOW-2025399: update dbapi perf test scripts

tests/integ/modin/strings/test_strings.py
Fixes SNOW-2062234
Fix failure in test_strings.py::test_get_with_dict_label.
=> SNOW-2062234: Fix failure in test_strings.py::test_get_with_dict_label

recipe/meta.yaml
CP change: https://github.com/snowflakedb/snowpark-python/pull/3110
=> NO-SNOW: add python runtime

CHANGELOG.md
Fixes SNOW-2082322
Move misplaced changelog bug fix entry from the Snowpark pandas section to the Snowpark Python section.
=> SNOW-2082322: Move misplaced changelog entry

src/snowflake/snowpark/functions.py
=> Fix ai_classify test

tests/utils.py
=> SNOW-2083780: Temporarily disable structured type tests.

src/snowflake/snowpark/dataframe_reader.py
=> SNOW-2060159: Change warning message of XML reader

setup.py, tests/integ/datasource/test_oracledb.py, tests/integ/test_data_source_api.py, tests/resources/test_data_source_dir/test_data_source_data.py, tox.ini
Fixes SNOW-1923698
This PR meant to use real data of oracledb and remove mock data
=> SNOW-1923698:Remove mock data of oracledb

tests/utils.py
Fixes SNOW-2083780
Test accounts have been updated to support structured types pupr. These tests should be safe to re-enable.
=> SNOW-2083780: Re-enable structured type tests.

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/_internal/error_message.py, tests/integ/scala/test_dataframe_reader_suite.py
=> SNOW-2096114: Improve the error message of XML reader when row tag is not found 

tests/integ/scala/test_dataframe_reader_suite.py
=> SNOW-2044853: Fix XML reader test in stored proc

tests/integ/test_dataframe.py
=> SNOW-2099398: fix test error caused by lob issue

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/_internal/proto/ast.proto, src/snowflake/snowpark/dataframe.py, src/snowflake/snowpark/dataframe_writer.py, tests/ast/data/DataFrame.write.test, tests/integ/scala/test_dataframe_writer_suite.py
Fixes SNOW-2103154
iceberg_version is a new sql option for create table statements. This PR patches it through with the other iceberg config options.
=> SNOW-2103154: Add support for iceberg_version

CHANGELOG.md, setup.py, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/_internal/xml_reader.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/scala/test_dataframe_reader_suite.py, tests/integ/test_xml_reader_row_tag.py, tests/resources/declared_namespace.xml, tests/resources/undeclared_namespace.xml, tests/unit/scala/test_utils_suite.py, tests/unit/test_xml_reader.py, tests/utils.py
Fixes SNOW-2097941
Use lxml library to enable namespace support
=> SNOW-2097941: Support reading XML files with namespace

src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
Fixes SNOW-2096114
We should check Node first in the recursion
=> SNOW-2096114: Fix XML error message when sql simplifier is disabled

CHANGELOG.md, scripts/copy-remote-ast.sh, src/snowflake/snowpark/_internal/proto/ast.proto, src/snowflake/snowpark/dataframe.py, tests/ast/data/DataFrame.describe.test, tests/integ/test_dataframe.py
=> SNOW-2028625 adding new feature flag and accompanying test

CHANGELOG.md, src/snowflake/snowpark/mock/_plan.py, tests/mock/test_column.py
Fixes SNOW-1661619
Local testing had an issue where the result for evaluating an `InExpression` would have an incorrect index. This PR fixes the issue by copying the input from the input data.
=> SNOW-1661619: [Local Testing] Fix isin filter issue

CHANGELOG.md
=> NO SNOW: fix changelog for SNOW-2099580

src/snowflake/snowpark/functions.py
=> Fix `ai_classify` doctest

tests/integ/datasource/test_databricks.py, tests/resources/test_data_source_dir/test_databricks_data.py
databricks sql engine doesn't guarantee order
we add explicit sort by to enforce ordering
=> NO-SNOW: order databricks test data to address flakiness

tests/integ/datasource/test_databricks.py
=> NO-SNOW: improve databricks test

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/_internal/xml_reader.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_xml_reader_row_tag.py, tests/unit/test_xml_reader.py
=> SNOW-2125145: Add `attributePrefix` option for xml reader

CHANGELOG.md, src/snowflake/snowpark/session.py, tests/integ/test_dataframe.py, tests/unit/test_pandas_to_df.py
=> SNOW-664933: Raise an exception for empty pandas df without a column 

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/_internal/xml_reader.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_xml_reader_row_tag.py, tests/unit/test_xml_reader.py
=> SNOW-2126714: Add `excludeAttributes` option for xml reader

.github/workflows/daily_precommit.yml, tests/integ/datasource/test_databricks.py, tests/resources/test_data_source_dir/test_databricks_data.py
psycopg2 has issue on macos 3.9, so we skip the daily dbapi test on macos 3.9
=> NO-SNOW: fix dbpi tests

tests/integ/datasource/test_databricks.py
Fixes SNOW-2128983
temporarily skip the test while investigating
=> SNOW-2128983: skip databricks dbapi test on macos python 3.12

src/snowflake/snowpark/_internal/telemetry.py, tests/integ/test_telemetry.py
Fixes SNOW-2127246
This is required to track downstream usage after ingesting files into Snowflake as a Snowpark DataFrame.
=> SNOW-2127246: Add telemetry to save table name in `DataFrameWriter.save_as_table`

.github/workflows/daily_precommit.yml
=> No-SNOW: fix dbapi daily job on macos python 3.9

CHANGELOG.md, src/snowflake/snowpark/udaf.py
=> SNOW-2045761: Fix native_app_params retrieval by using pop instead of get

src/snowflake/snowpark/modin/conftest.py
Follow-up to #3378, which disabled multi-line queries in Snowpark pandas integration tests but missed the conftest file for doctests.
=> NO-SNOW: Disable multiline queries for Snowpark pandas doctests

src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, tests/integ/test_dataframe.py
=> NO SNOW: fix lint in SNOW-2019483 fix and skip dynamic table test in snowfort

src/snowflake/snowpark/files.py, tests/unit/test_files.py
Part of a fix of SNOW-2110572 (1/x)
Local testing io will need a callable path for file location in order to enable python io.
=> SNOW-2110572: use tempfile name for file location

tests/integ/scala/test_dataframe_reader_suite.py
=> NO-SNOW: Skip test in unsupported env

tests/integ/scala/test_datatype_suite.py
=> NO-SNOW: Skip test lob test in sproc

src/snowflake/snowpark/dataframe.py, tests/integ/compiler/test_query_generator.py, tests/integ/scala/test_snowflake_plan_suite.py, tests/integ/test_dataframe.py, tests/integ/test_simplifier_suite.py, tests/integ/test_table_function.py, tests/integ/test_telemetry.py, tests/utils.py
=> NO-SNOW: Fix sql simplifier disabled tests

src/conftest.py
=> Enable some AISQL tests in Azure and GCP

tests/integ/modin/io/test_read_csv.py
Fixes SNOW-2149016
Fix test_read_csv_s3 for windows.
=> SNOW-2149016: Fix test_read_csv_s3 for windows

tests/integ/modin/series/test_str_accessor.py
Fixes SNOW-2149024
Fix KeyError bug in test_str___getitem___dict and test_str_slice_dict.
=> SNOW-2149024: Fix KeyError bug in test_str___getitem___dict and test_str_slice_dict

CHANGELOG.md, src/snowflake/snowpark/mock/_plan.py, tests/mock/test_functions.py
Fixes SNOW-2148589
This PR addresses an indexing issue identified in https://github.com/snowflakedb/snowpark-python/issues/3459
The pandas RollingGroupBy reindexes the data when grouping rows, but does not expose the reordered index. This change materializes the new index by calling a simple function on the groupings in order to get the new index.
=> SNOW-2148589: [Local Testing] Fix window indexing issue

CHANGELOG.md, src/snowflake/snowpark/table.py, tests/ast/data/df_sample.test, tests/integ/test_query_plan_analysis.py, tests/integ/test_simplifier_suite.py
Fixes SNOW-2150430
Flatten the query generation for `session.table().sample()`. `Dataframe.sample()` can be further improved later.
=> SNOW-2150430: Flatten session.table.sample

tests/integ/scala/test_session_suite.py
=> NO-SNOW: fix temp table txn

CHANGELOG.md, setup.py, tests/integ/modin/hybrid/test_switch_operations.py
Adding these dependencies lets us show progress bars by default.
Fixes SNOW-2171720
=> SNOW-2171720: Add tqdm and ipywidget to modin dependencies.

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/extensions/pd_extensions.py, tests/integ/modin/hybrid/test_extensions.py
=> SNOW-217172: Support read_snowflake on pandas backend.

CHANGELOG.md, docs/source/snowpark/functions.rst, src/conftest.py, src/snowflake/snowpark/_internal/analyzer/analyzer.py, src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py, src/snowflake/snowpark/_internal/analyzer/expression.py, src/snowflake/snowpark/functions.py
=> SNOW-2037671: Support model function that allows users to call methods of a model

CHANGELOG.md
Fixes SNOW-2196636
Fix misalignment of changelog with published release notes for 1.33.0.
https://docs.snowflake.com/en/release-notes/clients-drivers/snowpark-python-2025#version-1-33-0-2025-06-19
=> SNOW-2196636: Fix misalignment of changelog with published release notes for 1.33.0

src/snowflake/snowpark/dataframe.py, tests/integ/test_dataframe.py
Fixes SNOW-2196225
It's not necessary to resolve the column name
=> SNOW-2196225: Do not resolve column when it's a string

CHANGELOG.md, src/snowflake/snowpark/_internal/data_source/drivers/base_driver.py, tests/integ/test_data_source_api.py
=> SNOW-2192069: Improve error experience of infer schema in dbapi

tests/unit/modin/test_io.py
Fixes SNOW-2204849
Add to_view/dynamic_table/iceberg to test_io.py unit test.
=> SNOW-2204849: Add to_view/dynamic_table/iceberg to test_io.py unit test

src/snowflake/snowpark/mock/_nop_plan.py
=> NOSNOW: Fix _nop_plan to support UnresolvedAttributes

src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
Fixes SNOW-2206502
Fix docstest for DataFrame.boxplot.
=> SNOW-2206502: Fix docstest for DataFrame.boxplot

src/snowflake/snowpark/functions.py
=> Improve the usage of `model` function

CHANGELOG.md, docs/source/snowpark/functions.rst, src/snowflake/snowpark/functions.py
Fixes SNOW-2217359
Add function try_parse_json
=> SNOW-2217359: Add function try_parse_json

src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py, tests/integ/modin/frame/test_apply.py, tests/integ/modin/frame/test_cache_result.py
Fixes SNOW-2217486
Fixes a few apply-related tests on Jenkins that get skipped in Github actions. An error message caught and re-raised during pickling is now appropriately caught earlier, and some query counts in test_cache_result.py are updated.
The remaining test failures related to numpy version uploads seem to be caused by a server-side change, and will be addressed in SNOW-2217451.
=> SNOW-2217486: Fix some apply-related Jenkins failures

CHANGELOG.md, src/snowflake/snowpark/_internal/data_source/datasource_partitioner.py, tests/integ/datasource/test_databricks.py, tests/integ/datasource/test_mysql.py, tests/integ/datasource/test_oracledb.py, tests/integ/datasource/test_postgres.py, tests/integ/test_data_source_api.py, tests/resources/test_data_source_dir/test_data_source_data.py, tests/resources/test_data_source_dir/test_databricks_data.py, tests/resources/test_data_source_dir/test_mysql_data.py, tests/resources/test_data_source_dir/test_postgres_data.py
=> SNOW-2213418:align custom_schema behavior with pyspark

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/docstrings/io.py
Fixes SNOW-2221923
Add example for reading from stage in pd.read_excel docstring.
=> SNOW-2221923: Add example for reading from stage in pd.read_excel docstring

src/snowflake/snowpark/relational_grouped_dataframe.py, tests/integ/test_df_aggregate.py
=> SNOW-2205628: Exclude grouping columns in aggregation 

src/snowflake/snowpark/functions.py
=> Skip ai_complete test

CHANGELOG.md, docs/source/snowpark/functions.rst, src/snowflake/snowpark/functions.py
=> SNOW-2236715: support `ai_sentiment`

docs/source/snowpark/async_job.rst, src/snowflake/snowpark/async_job.py
Fixes SNOW-2223110
Update rst and doctest for asyncjob::is_failed & status
=> update rst and doctest for asyncjob::is_failed & status

.github/workflows/daily_jupyter_nb_test.yml, .github/workflows/daily_modin_precommit_py39_py310.yml, src/conftest.py
fix:
https://github.com/snowflakedb/snowpark-python/actions/workflows/daily_modin_precommit_py39_py310.yml
- join alias
- disable sql simplifier
https://github.com/snowflakedb/snowpark-python/actions/workflows/daily_jupyter_nb_test.yml
- fix uv issue on windows
=> NO-SNOW: fix more daily test failures

tests/integ/test_df_aggregate.py
=> Fix `test_filter_sort_limit_snowpark_connect_compatible` when sql simplifier is disabled

.github/workflows/precommit.yml, tox.ini
=> SNOW-2235395: built-in retry in our merge gate for snowpark python api

src/snowflake/snowpark/_internal/data_source/datasource_partitioner.py, src/snowflake/snowpark/_internal/data_source/drivers/base_driver.py, src/snowflake/snowpark/_internal/data_source/utils.py, src/snowflake/snowpark/_internal/telemetry.py, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_data_source_api.py
=> SNOW-2134524:fine grained ingestion performance telemetry

src/snowflake/snowpark/functions.py
=> Fix `ai_similarity` doc

CHANGELOG.md, src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py, src/snowflake/snowpark/context.py, tests/integ/conftest.py, tests/integ/test_context.py, tests/integ/test_df_debug_trace.py, tests/integ/test_query_line_intervals.py, tests/integ/test_trace_sql_errors_to_df.py, tests/unit/test_selectable_queries.py
Fixes SNOW-2237247
Made the following changes
i. Each feature must be explicitely enabled.
ii. For the features that depend on AST, they enable AST for the session automatically instead of relies it to be done by the user.
iii. Minor formatting updates to make the debug context look better.
=> SNOW-2237247: Update interface to enable developer improvement features

docs/source/snowpark/io.rst, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_dataframe_reader_file.py
Fixes SNOW-2236730
Changelog is not updated for now. There will be a bulk update for all unstructured data engineering APIs
=> SNOW-2236730: Support `DataFrameReader.file`

CHANGELOG.md, recipe/meta.yaml, setup.py
=> SNOW-2224943: support protobu>6

src/snowflake/snowpark/_internal/telemetry.py, src/snowflake/snowpark/session.py, tests/unit/test_stored_proc_telemetry.py
Fixes SNOW-2206079
Description of how stored proc telemetry will work is described in this document, along with examples:
https://docs.google.com/document/d/1Bajsnc7kkWzdVpFGxQg_wjay4RDa8BEgB8VMfC8hrjM/edit?usp=sharing
=> Adding telemetry to stored procs

CHANGELOG.md, src/snowflake/snowpark/_internal/packaging_utils.py, tests/unit/test_packaging_utils.py
=> SNOW-2259557: Deprecate one more `pkg_reosurces`

tests/integ/test_df_to_pandas.py
=> Skip `test_to_pandas_json_format` in stored proc test

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/__init__.py
Fixes SNOW-2276169
Add '--upgrade' to 'pip install "snowflake-snowpark-python[modin]"' in the import error message.
=> SNOW-2276169: Add '--upgrade' to 'pip install "snowflake-snowpark-python[modin]"' in the import error message

docs/source/snowpark/dataframe.rst, docs/source/snowpark/grouping.rst, src/snowflake/snowpark/dataframe_ai_functions.py, src/snowflake/snowpark/relational_grouped_dataframe.py, tests/integ/test_dataframe_ai.py
Fixes [SNOW-2270322](https://snowflakecomputing.atlassian.net/browse/SNOW-2270322)
[SNOW-2270322]: https://snowflakecomputing.atlassian.net/browse/SNOW-2270322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-2270322: Support `DataFrame.ai.agg` and `DataFrame.group_by().ai_agg`

src/snowflake/snowpark/dataframe_ai_functions.py, tests/integ/test_dataframe_ai.py
=> SNOW-2270330: `DataFrame.ai.similarity`

src/snowflake/snowpark/functions.py
=> NO-SNOW: fix doc test

docs/source/snowpark/dataframe.rst, src/snowflake/snowpark/dataframe_ai_functions.py, tests/integ/test_dataframe_ai.py, tests/utils.py
=> SNOW-2301877: Support `DataFrame.ai.transcribe` and `DataFrame.ai.parse_document`

CHANGELOG.md, src/snowflake/snowpark/_internal/proto/ast.proto, src/snowflake/snowpark/dataframe_reader.py, src/snowflake/snowpark/session.py, tests/ast/data/session.read.test, tests/ast/data/session_directory.test, tests/integ/test_session.py
Fixes SNOW-641374
support https://docs.snowflake.com/en/user-guide/data-load-dirtables-query
a thin wrapper of `SELECT * FROM DIRECTORY( @<stage_name> )`
=> SNOW-641374: support directory

tox.ini
Pin pytest-rerunfailures due to https://github.com/pytest-dev/pytest-rerunfailures/issues/303
=> NO-SNOW: Pin pytest-rerunfailures due to be release

CHANGELOG.md, docs/source/snowpark/functions.rst, src/snowflake/snowpark/_functions/general_functions.py, src/snowflake/snowpark/_functions/scalar_functions.py, src/snowflake/snowpark/functions.py
Fixes [SNOW-2249728](https://snowflakecomputing.atlassian.net/browse/SNOW-2249728)
Adds support for the functions:
- all_user_names
- current_account_name
- current_client
- current_ip_address
- current_organization_name
- current_organization_user
- current_role_type
- current_secondary_roles
- current_transaction
[SNOW-2249728]: https://snowflakecomputing.atlassian.net/browse/SNOW-2249728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-2249728: Add support for scalar functions (batch 1)

src/snowflake/snowpark/dataframe_reader.py, tests/ast/data/session.read.test
`dataframe_reader.py::option` uses `build_expr_from_python_val` for AST support, but it does not support `TimestampTimeZone` type casting yet. This PR casts `TimestampTimeZone` to string before passing to `build_expr_from_python_val`.
https://github.com/snowflakedb/snowpark-python/actions/runs/17335980343/job/49222290291
=> AST on TimestampTimeZone type casting

CHANGELOG.md, src/snowflake/snowpark/dataframe_reader.py, tests/integ/datasource/test_jdbc.py
=> NO SNOW: align behavior of session_init_statement in dbapi and jdbc

tests/integ/modin/hybrid/conftest.py
whoops (missed a flag in https://github.com/snowflakedb/snowpark-python/pull/3698/files)
=> NO-SNOW: Actually skip hybrid tests on Windows

docs/source/snowpark/dataframe.rst, docs/source/snowpark/io.rst, docs/source/snowpark/session.rst, src/snowflake/snowpark/dataframe_reader.py
=> NO-SNOW: add missing doc update

CHANGELOG.md
=> Remove duplicate changelogs

CHANGELOG.md, src/snowflake/snowpark/mock/_analyzer.py, src/snowflake/snowpark/mock/_functions.py, src/snowflake/snowpark/mock/_plan.py, tests/mock/test_functions.py
Fixes SNOW-2317419
support patching NamedFunctionExpression in local testing
=> SNOW-2317419: add capability to mock ai_complete

tests/integ/test_dataframe.py
Fixes SNOW-2312892
Snowfort sproc `test_dataframe.py` failed due to 1) time travel tests' `offset` calculation and 2) calling `select current_timestamp() `always returning 1967: 
`t_python_sp_integ/test_python_sp_integ_dataframe.py::TestPythonSPInteg::test_snowpark_module_dataframe[tests/integ/test_dataframe.py-additional_params15-not
`
https://snowci-prod.ci1.us-west-2.aws-dev.app.snowflake.com/reports/plid_eukflxbi?hierarchyEnforcement=all&hierarchySearch=dataframe&jobAttemptStatus=all&jobDetailsTab=jo …
=> Snow 2312892 fix snowfort sproc tests time travel

CHANGELOG.md, src/snowflake/snowpark/dataframe_reader.py, tests/integ/test_xml_reader_row_tag.py
=> SNOW-2103211: Cache XML dataframe

.github/workflows/daily_precommit.yml
=> NO SNOW: fix daily precommit to include localtesting

tox.ini
=> NO SNOW: pin databricks-sql-connector version

CHANGELOG.md, CONTRIBUTING.md, recipe/meta.yaml, setup.py, src/snowflake/snowpark/modin/plugin/__init__.py, src/snowflake/snowpark/modin/plugin/_internal/utils.py, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/frame/test_eval_and_query/test_eval.py, tests/integ/modin/frame/test_eval_and_query/test_query.py, tests/integ/modin/test_modin_stored_procedures.py, tox.ini
=> SNOW-2363878: Update modin dependency to >=0.36.0,<0.38.0; support pre-op switching for joins

tests/integ/datasource/test_sql_server.py
=> NO-SNOW: skip dbapi sql server on non github env

tests/integ/modin/frame/test_boxplot.py, tests/integ/modin/test_plot.py
Fixes SNOW-2389746
Fix flakiness in test_boxplot.py and test_plot.py on windows.
=> SNOW-2389746: Fix flakiness in test_boxplot.py and test_plot.py on windows

tests/integ/modin/series/test_hist.py
Fixes SNOW-2395124
Fix flakiness in test_hist.py on windows.
=> SNOW-2395124: Skip flaky test_hist.py cases on windows

tox.ini
oracledb 3.4.0 breaks dbapi, temp pin dep to unblock PR merge
follow up jira: SNOW-2397605
=> NO-SNOW: fix oracledb failure caused by latest release

CHANGELOG.md, src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py, tests/integ/modin/test_faster_pandas.py
Fixes SNOW-2396665
Add support for isin in faster pandas.
=> SNOW-2396665: Add support for isin in faster pandas
