- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_copy_into.py
Fixes SNOW-586919
Updated DataFrame.copy_into_table() to be able to use the inferred schema of a parquet or avro or orc file
> SNOW-586919: Added support to use inferred schema in DataFrame.copy_into_table()

- tests/integ/scala/test_complex_dataframe_suite.py
- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_file_operation_suite.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/scala/test_result_attributes_suite.py
- tests/integ/scala/test_result_schema_suite.py
- tests/integ/scala/test_session_suite.py
- tests/integ/scala/test_sql_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_df_to_pandas.py
- tests/integ/test_query_history.py
- tests/integ/test_session.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/utils.py
In this way, we can easily fix/disable the test without committing to snowflake repo. Also, I enabled several test which is working in SP regression test now:
- test_add_import_stage_file (SNOW-539576 is done)
- test_limit_on_order_by (fixture is added, but this test will be skipped since sample data is not available)
- test_add_import_package (this doesn't not require the specific package on the server)
Please also review other disabled tests (which probably can be enabled)!
Regression test:
https://buwa.c1.us-west-2.aws-dev.app.snowflake.com/builds/precommit/ci73.int.snowflakecomputing.com/8080 (the only failed test is caused by the new commit https://github.com/snowflakedb/snowpark-python/commit/1604b6573da36445489c05dac2bbf10bf0c5b4b4)
> SNOW-606808: Move blocklist of SP regression test to snowpark 

- recipe/meta.yaml
Given Anaconda builds packages in arch specific way, we need to
change our local recipe to adapt.
We still need local recipe for snapshot testing. The one in feedstock
is used as the latest released recipe.
Fixes #NNNN
> SNOW-608059 Change local recipe to build arch specific package

- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
Fixes SNOW-607796. I don't think we need to escape anything from this object name, because it's controlled by the user and it should not violate snowflake identifier rule. Therefore, I just add the validation here to make sure we have clear error message. 
> SNOW-607796: Validate object name in `session.use_*` methods

- src/snowflake/snowpark/dataframe_stat_functions.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/udf.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_dataframe.py
> SNOW-614533: Fix `create_dataframe` that mistakenly converts 0 and False to None when the input data is only a list

- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_query_tag_suite.py
Fixes SNOW-607796. See another fix for `use <object>` in #380. 
> SNOW-607796: Escape query tag in SQL when it has special characters

- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_query_history.py
Fixes SNOW-607224 by replacing the created temp table. We should avoid using `if not exist` when creating a temp table in case the underlying table is changed, though both should be fine as our dataframe is immutable. Actually not only `create_dataframe`, this PR also fixes this issue when reading files from a stage. 
> SNOW-607224: "Create or replace" temp table for `create_dataframe` with large local data and reading files from a stage

- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/test_dataframe.py
This internal method is needed for table stored proc that executes the dataframe and get the result query ID, which will be returned back to GS and used for getting the result back with result scan. 
> SNOW-620212: Execute and get the result query id of a dataframe

- src/snowflake/snowpark/column.py
- tests/integ/test_column.py
Description
When we use the builtin sum function instead of the Snowpark defined sum function, then the library hangs and uses up a lot of memory. This PR addresses that and tests for other builtin functions that shadow Snowpark function names
Testing
Tested builtin sum function as well as other builtin functions
Fixes #NNNN
> SNOW-620677 Using Builtin sum Function Causes Hanging

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_stat_functions.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/file_operation.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/table.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_file_operation_suite.py
- tests/integ/scala/test_udtf_suite.py
- tests/integ/scala/test_update_delete_merge_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
- tests/unit/test_query_tag.py
Fixes SNOW-592212
Add statement_param keyword argument support to ACTION apis in snowpark.
two key functions that requires which serves as the fundamental to upper level apis.
```python
_session._conn.execute() # connection cursor execution
_internal_collect_with_tag() # which calls _session._conn.execute
```
add the keyword argument to all public apis that will call `_internal_collect_with_tag` or ` _session._conn.execute`
> SNOW-592212 Accept statement level params

- README.md
- docs/source/_themes/snowflake_rtd_theme/layout.html
- docs/source/index.rst
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/table_function.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
1. Fixes SNOW-608590
Not applicable
Changed old private preview "LIMITEDACCESS" URLs to use the new URLs.
Fixed some typos.
谢谢你！
> SNOW-608590: Update Python Snowpark API docs to fix typos and URLs

- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
1. Fixes SNOW-616929
Not applicable
In 0.7.0, we added a Snowpark-specific exception class for SQL errors. This replaces the previous ProgrammingError from the Python connector. This PR updates the documentation to reflect that change.
> SNOW-616929: Update API docs to remove old ProgrammingError mention

- setup.py
Some new versions of Sphinx may introduce break changes. For instance, 5.1.0 reports `Extension error (sphinx.ext.napoleon)`
> Pin sphinx==5.0.2 instead of latest version

- docs/source/index.rst
SNOW-633678
Not applicable
Some text in a callout in the api docs was out of date. 
I already fixed this in the docs that will be getting published for 0.8.0. Just updating it in the source for next time.
> SNOW-633678: Fix typo in API docs callout

- src/snowflake/snowpark/udtf.py
SNOW-636197
Fill out the following pre-review checklist:
not applicable
Please describe how your code solves the related issue.
Fixing a few small typos in the API doc strings about udtfs.
> SNOW-636197: Fix doc typo in API doc for UDTFs

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/dataframe_writer.py
- tests/integ/scala/test_dataframe_writer_suite.py
`df.write.save_as_table` needs to match column names when appending new data to an existing table.
It currently insert data by column sequence.
When appending data to a table, change the SQL from `insert into t values(val1, val2, ...)` to `insert into t(col1, col2, ...) values (val1, val2, ...)`. A new parameter is added to `save_as_table` for users to choose what they want.
> SNOW-619431: Support save_as_table with column name sequence

- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Fixes #SNOW-619461
The function `uniform` accepts `min` and `max` to generate random numbers. Based on the input of `min` and `max`, which can be either `int` or `float`, we generate a random number.
When parsing the limits for `min` and `max`, we infer the type and cast the limits into `IntegerType` or `FloatType`. These values are then forwarded to built-in function `uniform`.
> SNOW 619461 casting decimal like python numbers to float type

- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
Fixes https://github.com/snowflakedb/snowpark-python/issues/414. 
The unquoted identifier name in Snowflake is not case sensitive, so we already quote the column name from schema when building the query. However, previously we didn't quote the keys in dicts to make sure they are consistent. This PR fixes this issue. See details of Snowflake identifier [here](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html).
> SNOW-637532: Use quoted names for `create_dataframe` with dicts and a given schema 

- setup.py
- src/snowflake/snowpark/session.py
- tests/integ/test_pandas_to_df.py
Fixes #383 
Using the [write_pandas()](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.html#snowflake.snowpark.Session.write_pandas) API there is now a way to optionally overwrite contents of a Snowflake table with that of a Pandas DataFrame.
> Updates related to SNOW-616002

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
Description
Create table requires a different privilege from insert, and
appending to an existing table should be allowed for user without
create privilege. To achieve that, we skip creating table if
it already exists.
Testing
integ test
Fixes #NNNN
> SNOW-641398 Skip create table if exists in append mode

- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
The workaround of using `DESC TABLE` in `describe_only` mode risks failure because it depends on  `ENABLE_COMBINED_DESCRIBE` being `false`. Currently this param is false in prod but is true in test deployment, so we should avoid using `DESC TABLE` in `describe_only` mode.
Fixes #NNNN
> Revert changes in _table_exists

- src/snowflake/snowpark/_internal/analyzer/table_function.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/table_function.py
- tests/integ/test_dataframe.py
Fixes #SNOW-650679
Add support to alias the columns names that come from the output of table function joins. The support can be seen for functions `select`, `join_table_function`, `with_column` and `with_columns`
> SNOW-650679: Add alias support to TableFunctionCall

- src/snowflake/snowpark/session.py
- tests/integ/test_udf.py
Fixes #395 
`pkg_resources.Requirement.parse` will convert all underscores to dashes, whereas some packages in Anaconda are still using underscores. The fix is that if a package is added as a string which contains an underscore, we just pass this raw string to the server without parsing it.
> SNOW-623550: Fix the bug that packages with underscores cannot be added

- tests/integ/scala/test_file_operation_suite.py
Fixes #SNOW-654033
Fix flaky test for windows environment caused by `rmtree`
> SNOW-654033 add a randomized sleep to handle rmtree error

- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/functions.py
- tests/integ/scala/test_literal_suite.py
- tests/integ/scala/test_permanent_udf_suite.py
- tests/integ/test_dataframe.py
- tests/unit/test_datatype_mapper.py
- tests/unit/test_expressions.py
Fixes SNOW-500400
Make list, tuple and dict a valid literal value in snowpark
> SNOW-500400: Allow structured data to be literal value 

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/session.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-624867
Convert `TableFunctionRelation` to a `Selectable` so that we can leverage the sql simplifier and flatten select queries
> SNOW-624867: flatten session.table_function

- src/snowflake/snowpark/dataframe.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-621596
This PR addresses `dataframe.union_by_name` as a larger effort to simplify the sql query generated on the client side and reduce the amount of nesting.
> SNOW-621596: flatten union by name

- src/snowflake/snowpark/session.py
- tests/unit/test_session.py
Fixes [SNOW-647398](https://snowflakecomputing.atlassian.net/browse/SNOW-647398)
It implements a `__repr__` method for Snowpark.Session so `print(session)` will display some helpful information about the session.
Before: `<snowflake.snowpark.session.Session object at 0x11c681700>`
After: `<snowflake.snowpark.session.Session: role='ROLE', database='DB', schema='SCHEMA', warehouse='WH'>`
> [SNOW-647398] show details when printing a snowpark session

- tests/integ/scala/test_dataframe_suite.py
Fixes SNOW-654839
Attempting to save a new dataframe created out of a
`SELECT *` result failed in 0.8.0 but was fixed by
SNOW-619431 inadvertently.
This change adds an additional test covering a scenario
where a bulk insert is made from data collected through
a SELECT * query (no columns specified).
This is a **test-only change**. It makes no changes to
any library or API files.
Testing notes:
- Ran all of the test suites via pytest
- Newly added unit test passes on main
- Verified manually that the unit test also:
- Passes on tag 0.7.0
- Fails  on tag 0.8.0
- Passes on tag 0.9.0 …
> SNOW-654839: Additional regression test for save_as_table

- tests/integ/scala/test_dataframe_suite.py
Fixes #NNNN
Large result is not supported for localfs test in stored proc
> Skip test_bulk_insert_from_collected_result on localfs

- src/snowflake/snowpark/session.py
- tests/unit/test_session.py
Fixes SNOW-658388
`_session_parameter` could be `None` is stored proc, we should check and default to `True` if it's None.
> SNOW-658388: Check session parameter is None

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/test_simplifier_suite.py
Fixes SNOW-659103
Get the full list of attributes when `df["*"]` is used.
> SNOW-659103: Fix support for df.select(df['*'])

- src/snowflake/snowpark/_internal/analyzer/expression.py
- tests/unit/test_expression_dependent_columns.py
Fixes SNOW-656574
Added unit test code for the `Expression` class and all descendants.
> SNOW-656574: Add unit tests for Expression dependent_column_names

- src/snowflake/snowpark/dataframe.py
Description
We could return Table, which is a more accurate dataframe for cache_result.
Testing
Existing tests
Fixes SNOW-652245
cached_result returning a table is more accurate, which unlocks certain new operations that can be done on the cached temp table.
> SNOW-652245 Return Table for cache_result

- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/test_simplifier_suite.py
SNOW-665754
Previously every `df.with_column` will have a describe query sent to snowflake to get the metadata, but it's unnecessary when sql simplifier is used (column names are saved).
> SNOW-665754: Avoid describing the dataframe for `df.with_column` and several other methods when using SQL simplifier

- tests/integ/scala/test_file_operation_suite.py
Fixes #NNNN
Regression tests for stored procedure are failing due to a file-not-found test which causes XP to fail the whole test instead of returning the error message to python file.
```
call snowpark_scala_test_file_operation_suite();
! FAILURE: Remote file 'https:/xxxx/non_existing_file' was not found. There are several potential causes. The file might not exist. The required credentials may be missing or invalid. If you are running a copy command, please make sure files are not deleted when they are …
```
> SNOW-641129 skip stored-proc file not found test

- src/snowflake/snowpark/stored_procedure.py
- tests/integ/test_stored_procedure.py
Description
This is more natural given the sp function is defined as my_proc(session, a, b)
Testing
integ test
Fixes SNOW-588269
This is more natural given the sp function is defined as `my_proc(session, a, b)`
> SNOW-588269 Support session as the first argument when calling sp

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_view_suite.py
- tests/integ/test_dataframe.py
- tests/utils.py
Fixes #SNOW-560612
Use `is_sql_select_statement` regex match instead of simple `startswith("select:)` to detect sql statement.
> SNOW-560612 use is_sql_select_statement for sql check

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/window_expression.py
- src/snowflake/snowpark/functions.py
- tests/integ/scala/test_function_suite.py
- tests/integ/scala/test_window_frame_suite.py
Fixes #540 
This adds two new functions (i.e. `last_value` and `first_value`) that are subclasses of `RankRelatedFunctionExpression`. 
Since `RankRelatedFunctionExpression` was implemented with a requirement for `offset` and `default` arguments, some modifications were needed in the `analyzer` to allow for null values since `first/last_value` do not support `offset` and `default`, contrary to the already-implemented `lag` and `lead` functions.
> feat: add first_value and last_value

- tests/integ/scala/test_sql_suite.py
- tests/integ/test_query_history.py
Description
alter session is not allowed in owner's right stored procedure, so this skip message is not accurate
Testing
N/A
Fixes #NNNN
> SNOW-609875 Change skip message for tests involving alter session

- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- tests/integ/scala/test_session_suite.py
- tests/integ/test_dataframe.py
Fixes #SNOW-664210
Use `SELECT $1 AS "a b" FROM ( VALUES (1 :: INT))` instead of `SELECT  *  FROM ( VALUES (1 :: INT) AS SNOWPARK_TEMP_TABLE_EVQQHTZLRR("a b"))`. The latter has column `"""a b"""` instead of `"a b"`. The former has column `"a b"`.
> SNOW-664210: Fix create_dataframe when schema has special characters

- src/snowflake/snowpark/_internal/utils.py
- tests/unit/scala/test_utils_suite.py
Fixes #SNOW-676378
Like the experimental decorator, use `private_preview` decorator to mark APIs as "in private preview".
> SNOW-676378: Add private preview decorator

- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_async_job_suite.py
Fixes #NNNN
This PR adds support for creating an `AsyncJob` from a query ID.
- Add `Session.create_async_job` to allow creating an `AsyncJob` from a query ID.
- Add (reimplement) `AsyncJob.query` property so we can get the query text (lazily) from a query ID.
- Add `AsyncJob.to_df()` method to convert an async job to a dataframe using result scan. 
- Add an argument `result_type` in `AsyncJob.result()` to allow converting the result to the desired type.
> SNOW-667857: Add support for creating an `AsyncJob` from a query ID

- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Description
Supporting strict will allow skip invoking the python function if input contains NULL.
Testing
integ
Fixes SNOW-670988
Supporting strict will allow skip invoking the python function if input contains NULL.
> SNOW-670988 Support strict UD(T)F/SP

- tests/integ/scala/test_udf_suite.py
- tests/utils.py
Description
Use Utils.check_answer and Utils.get_sorted_rows when applicable for all tests in test_udf_suite. Note that some one-row result check theoretically does not need this but are still changed for consistency
Testing
existing tests
Fixes SNOW-679724
Returned rows by snowflake is inherently a set, so asserting on the sequence of the result is not stable. We use
existing util functions to help sort the result before actually comparing with expected result.
> SNOW-679724 Fix test flakiness in test_udf_suite

- src/snowflake/snowpark/_internal/server_connection.py
- tests/unit/conftest.py
- tests/unit/test_pandas_to_df.py
- tests/unit/test_server_connection.py
Description
This adds coverage to code paths not covered by existing tests. The remaining ones are all with `is_stored_procedure()` being True.
Testing
unit test
This makes all non-stored-proc code path covered
> SNOW-683056 Add exception tests for server_connection.py

- tests/integ/test_session.py
Description
Currently we try to create a new session directly from db_parameters, which does not work in sp because creating a new connection is not allowed in sp connector. To make sure we could test not allowing new session being created, we should reuse existing connection.
Testing
integ test
Fixes SNOW-544808
Fix to enable test_create_session_in_sp in sp test
> SNOW-544808 Use existing connector in test_create_session_in_sp

- docs/source/functions.rst
SNOW-677088 added new functions seq1, seq2, seq4, seq8 and associated docstrings but due to a change in the documentation generation it missed adding it to the index required to generate their docstrings into HTML.
This change adds the missing sequence functions into the functions index so they can be generated during docs builds.
Testing:
- Manual: Ran `make html` under the docs/ directory and compared the index and sequence function pages before and after the change.
Fixes #NNNN
Please write a short …
> SNOW-689204: Add missing sequence generator funcs to docs

- .pre-commit-config.yaml
- src/snowflake/snowpark/udf.py
- tests/integ/test_session.py
Fixes #SNOW-695533
Telemetry calls were added to udf/udtf/sprocs and a [potential error was identified](https://github.com/snowflakedb/snowpark-python/pull/520) where `get_active_session()` call could throw in case there were no sessions or more than one active sessions. To fix this, we made [changes](https://github.com/snowflakedb/snowpark-python/pull/539) to telemetry path but one of the `get_active_session()` was left out. This PR fixes the instance that got left out.
> SNOW-695533 remove redundant and error prone telemetry tracker

- recipe/meta.yaml
Fixes #NNNN
libffi 3.4.2 is not compatible with the latest cryptography library in conda channel. As a result we want to pin libffi version to unblock stored proc regression test
> Constrait libffi to <3.4.2 in conda recipe

- src/snowflake/snowpark/session.py
- tests/integ/test_pandas_to_df.py
Description
Prior to this change, schema is ignored if the input data is a pandas DF in create_dataframe(). This can be confusing as user would expect schema to take effect.
Note that this is a behavior change.
Testing
integ test
Fixes #504 
Prior to this change, schema is ignored if the input data is a pandas DF in create_dataframe(). This can be confusing as user would expect schema to take effect.
> SNOW-664934 Support schema for pandas DF in create_dataframe()

- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/exceptions.py
- tests/integ/test_udf.py
- tests/unit/test_udf_utils.py
- tox.ini
Fixes #[SNOW-707132](https://snowflakecomputing.atlassian.net/browse/SNOW-707132)
The error is caused by `cloudpickle` de-pickling a function that has reference to the module in where it's defined in the newly created UDF, i.e. pickle by reference then depickle in a different environment. This is the issue `cloudpickle` tries to tackle by introducing [pickle by value](https://github.com/cloudpipe/cloudpickle#overriding-pickles-serialization-mechanism-for-importable-constructs). For local functions, …
> SNOW-707132 Support creating UDFs that reference non-local-scoped functions

- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_datatype_suite.py
- tests/unit/test_types.py
Description
Add dtypes as a property of DataFrame, which returns datatype with names in pandas Series.
This change referenced mobilize's implementation in https://github.com/MobilizeNet/snowpark-extensions-py/blob/main/tests/test_dataframe_extensions.py with modifications.
Testing
Integration test
Fixes SNOW-703369
Add dtypes as a property of DataFrame, which returns datatype with names in pandas Series.
Note that the implementation is not exactly the same as mobilize, for example, this change does not use …
> SNOW-703369 Support DataFrame.dtypes

- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/scala/test_dataframe_join_suite.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-697912
When sql simplifier is enabled, a DataFrame's and its previous level DataFrame (the subquery) share the same `Attribute` instances. This generates a wrong SQL in a specific case. The fix is to copy those `Attribute` instances.
> SNOW-697912: Fix SQL simplifier for renaming column names

- src/snowflake/snowpark/files.py
Fixes [SNOW-700720](https://snowflakecomputing.atlassian.net/browse/SNOW-700720)
For safety reason, we want to warn the users when using stage url/uri for file access. We add an arg "require_scope_url" to SnowflakeFile.open func, so that by default when using stage url/uri, the users will be declined and received an error msg to require the arg as False, which will be implemented in XP
[SNOW-700720]: https://snowflakecomputing.atlassian.net/browse/SNOW-700720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
> SNOW-700720 Change python SnowflakeFile.open API that requires scoped URL

- .pre-commit-config.yaml
Fixes failing precommit due to new poetry version as reported in https://github.com/PyCQA/isort/issues/2077
Version bump from 5.10.1 -> 5.12.0 to allow precommit to run.
> [HOTFIX] Bump isort 5.10.1 -> 5.12.0 to fix precommit linter

- src/snowflake/snowpark/session.py
Description
Now that table_type was released on connector's write_pandas, we should stop using create_temp_table to avoid warning messages.
Testing
Existing tests
Fixes SNOW-734704
Now that table_type was released on connector's write_pandas, we should stop using create_temp_table to avoid warning messages.
> SNOW-734704 Remove usage of create_temp_table

- src/snowflake/snowpark/dataframe.py
- tests/integ/test_dataframe.py
Fixes #SNOW-743672
Fixed a bug where `df.join(..., how="cross")` fails with `snowflake.snowpark.exceptions.SnowparkJoinException: (1112): Unsupported using join type 'Cross'`
> SNOW-743672 Fix how=cross in df.join

- .github/workflows/precommit.yml
- setup.py
- tests/integ/scala/test_udtf_suite.py
- tests/integ/test_column_names.py
- tests/integ/test_dataframe.py
- tests/integ/test_simplifier_suite.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_telemetry.py
- tests/integ/test_udtf.py
- tox.ini
Description
Add python 3.9 integ test non-required merge gate. These tests
explicitly skip udf test because 3.9 is not supported for UDFs yet
Testing
n/a
Fixes SNOW-742340
Add python 3.9 integ test non-required merge gate. These tests explicitly skip udf test because 3.9 is not supported for UDFs yet
> SNOW-742340 Add python 3.9 integ test merge gate 

- src/snowflake/snowpark/files.py
Fixes SNOW-738952
Previously we had introduced `is_owner_file`. We want to replace that with `require_scoped_url` which this PR introduces. require_scoped_url can only be passed a kwarg to SnowflakeFile.open()
> SNOW-738952: Add require_scoped_url to API

- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Fixes #SNOW-706842
Adding a parameter `if_not_exists` in sp/udf/udtf registration so that users can skip creating procedure or function in the case when one is already registered.
> SNOW-706842 add a parameter if_not_exists

- recipe/meta.yaml
Description
This helps us building internal snapshot packages for regression tests, and gets us prepared for stored proc testing when server supports py39
Testing
N/A
Fixes SNOW-742344
This helps us building internal snapshot packages for regression tests, and gets us prepared for stored proc testing when server supports py39
> SNOW-742344 Allow python version >=3.8 in internal recipe

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
- tests/unit/test_analyzer_util_suite.py
- tests/unit/test_dataframe.py
Fixes #SNOW-719900
Previously, dataframe/table joins will use random aliases for the left and right subquery results at query generation, which means users cannot take advantage of query [result cache](https://community.snowflake.com/s/article/Caching-in-Snowflake-Data-Warehouse). This PR removes that and adds a unit test.
> SNOW-719900 Remove random alias for subqeury in joins

- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
Fixes #SNOW-747658
`Session.conf` lets users to lookup runtime config parameters. Previously, options passed into configs are not preserved for future lookup. E.g. users who want to make sure paramstyle is pyformat cannot easily confirm this. With this change, users can easily access these configs with `session.conf`.
Reference: https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.SparkSession.conf.html#pyspark.sql.SparkSession.conf
> SNOW-747658 Add session.conf to store runtime configuration

- src/snowflake/snowpark/session.py
Fixes #SNOW-737313
Set `chunk_size` 100,000 by default in stored procedures.
> SNOW-737313 Set default parameter chunk_size in create_dataframe/write_pandas

- src/snowflake/snowpark/session.py
https://github.com/snowflakedb/snowpark-python/issues/688
Fixes #688
My solution changes the documentation in the doc-string to match the source code of the configs() method of the SessionBuilder class.
> SNOW-748484 Fix documentation issue when creating a `Session` object from existing Python connector connection

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-756443
The code change fixes chained sort statements (e.g. `df.order_by().order_by()`) by prepending the subquery's expressions with the current query's expressions.
> SNOW-756443  Fix chained sort

- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Fixes #NNNN
Tests that are testing `if_not_exists` show flaky behavior and fail error messages like with `Unknown function TEST_SP_IF_NOT_EXISTS_ADD` on first invocation of sp/udf after being registered with `if_not_exists=True`. Updating the first isntance of registration with `replace=True` instead of `if_not_exists` to test whether it fixes the flakiness.
> mark xfail on if_not_exist tests 

- src/snowflake/snowpark/async_job.py
- tests/integ/scala/test_async_job_suite.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/scala/test_query_tag_suite.py
- tests/integ/test_session.py
Description
Add xfail to known flaky tests to make merge gate stable, the fix will be in separate PRs.
There are two tests that are treated differently:
1. Doctest snowpark.async_job.AsyncJob. I don't see a good reason for this "two async runs faster than two sync" as a useful doc.
2. Removed a stored proc skip because the reason for skip is flaky
Testing
Existing tests
Fixes SNOW-759276
Add xfail to known flaky tests to make merge gate stable, the fix will be in separate PRs.
There are two tests that are …
> SNOW-759276 Add xfail to known flaky tests

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/dataframe_stat_functions.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-760037
The SQL simplifier wrongly flatten a set operation (union, except, etc) when there is a column change after a previous set operation. The fix detects that there is a column change the set operation is not flattened.
> SNOW-760037: Fix set operations when it's after another set operator with column changes

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
Fixes #SNOW-747658
Previously in #669, we exposed `use_constant_subquery_alias` in the public API. This is ideally a temporary parameter that should be hidden from users and removed. This PR addresses the need to store temporary parameters using `Session.RuntimeConfig` and switches `use_constant_subquery_alias` to use the temp param implementation.
> [Release Blocker] Add temporary parameter config

- CHANGELOG.md
- src/snowflake/snowpark/session.py
Fixes #NNNN
Add `statement_params` for job telemetry. SProc call triggers execution but cannot be monitored via statement params. cc: @sfc-gh-pdorairaj
> Add statement_params to session.call

- .pre-commit-config.yaml
Fixes #NNNN
On DevVM, the pre-commit by default uses Python 3.6 to run some hooks but they need Python3.7 or above.
> Set pre-commit default language version to Python3.8

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
- tests/unit/test_dataframe.py
Fixes #NNNN
Use dataframe's statement params at query execution if no statement params are specified (eg in `collect`). We need this to track credit consumption from dataframes with snowml contributions. cc: @sfc-gh-pdorairaj
> Add statement params to dataframe as a property

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/session.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-759929
Flatten generated SQL when DataFrame.order_by() is followed by projection statements, don't flatten if the (subquery's) order by clause depends on columns that are changed or newly introduced in the current query (select).
> SNOW-759929  Flatten select after order_by

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/session.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-704094
The code change checks if the subquery's where clause depends on a column that is NEW in the current query, if it does not, flatten the query. Note that, WHERE is evaluated on the subquery first, so it is safe to flatten when there are columns that are CHANGED between the current query and the subquery.
> SNOW-704094  Flatten select after filter

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/session.py
- tests/integ/test_simplifier_suite.py
Fixes #NNNN
Refactors part of select_statements.py to get rid of some flag variables.
> Refactor select_statement and (stacked PR) flatten select after filter/orderby

- src/snowflake/snowpark/udf.py
- tests/integ/scala/test_udf_suite.py
- tests/integ/test_udf.py
Fixes #NNNN
The current code swaps the two expressions. Reference: [scala API](https://github.com/snowflakedb/snowpark-java-scala/blob/6bc35743456bf384a643b7ab32dac97ee011c41f/src/main/scala/com/snowflake/snowpark/UserDefinedFunction.scala#L44-L44). This PR fixes that and removes duplicate tests.
> Fix UDF value error message when number of arguments and number of parameters mismatch

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
- tests/unit/scala/test_utils_suite.py
Fixes #SNOW-763159
`is_sql_select_statement` identifies any SQL query which starts with `select` or `with` as a `SELECT` SQL statement. This is fine in most cases but it mis-identifies anonymous sprocs which have a pattern `with <proc_name> as procedure ...`.
> SNOW-763159 Fix is_sql_select_statement

- src/snowflake/snowpark/functions.py
Fixes #SNOW-796550. Using lit() is better than sql_expr() so sql simplifier can flatten SQLs when related functions(approx_percentile, to_decimal, etc) are used. Local testing doesn't work with sql_expr() but does for lit().
Change sql_expr() to lit() whenever lit() can be used.
> SNOW-796550: Use lit() instead of sql_expr() in functions

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Add function substring_index(str, delim, count) in module snowflake.snowpark.functions. This function returns the substring from string str before count occurrences of the delimiter delim. If count is positive, everything the left of the final delimiter (counting from left) is returned. If count is negative, every to the right of the final delimiter (counting from the right) is returned.
Providing the functionality with the following generated SQL
```
array_to_string(array_slice(
strtok_to_array(s, delim),
0 …
```
> [SNOW-743111] Add substring_index support under sqlfunction

- src/snowflake/snowpark/dataframe_na_functions.py
Fixes #NNNN
The current type hint only suggests a list of values whereas `replace` can also take a scalar value.
> Add LiteralType to type hint of DataFrame.replace

- src/snowflake/snowpark/session.py
- tests/unit/test_session.py
Description
Some internal accounts do not have snowflake as database. Use snowflake by default will cause problems for these accounts
Testing
internal test
Fixes SNOW-809689
Some internal accounts do not have snowflake as database. Use snowflake by default will cause problems for these accounts
> SNOW-809689 Use snowflake only when no current database exists

- .github/workflows/precommit.yml
- src/snowflake/snowpark/session.py
- tests/integ/test_udf.py
- tests/resources/test_requirements.txt
Description
Production is running on 7.13 now and we enabled python 3.9 for test account. We could start testing the full suites including udf tests.
Testing
Existing tests
Fixes SNOW-767996
Production is running on 7.13 now and we enabled python 3.9 for test account. We could start testing the full suites including udf tests.
> SNOW-767996 Run full test suites on python3.9/3.10

- CHANGELOG.md
- src/snowflake/snowpark/_internal/type_utils.py
Fixes https://github.com/snowflakedb/snowflake-connector-python/issues/1525 and #810 
Test PR for user.
> Test pr 799

- setup.py
Fixes #SNOW-823418
Adding 3.9 support for snowpark client.
> SNOW-823418 Allow Snowpark client to run on Python 3.9 runtime environment

- tests/integ/scala/test_async_job_suite.py
- tests/integ/test_df_to_pandas.py
Fixes #NNNN
Our tests are breaking due to pandas import `pandas.utils.testing`. Use `pandas.testing` instead.
See Also: https://github.com/pydata/pandas-datareader/issues/775
> use pandas.testing for assert_frame_equal

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_reader.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
Fixes SNOW-629569
- [c] I am adding a new automated test(s) to verify correctness of my new code
Implement dataframe.alias to enable (1) joining two dataframes with duplicate columns w/o specifying suffix, (2) self join (3) referring to columns with syntax `col(<df alias name>, <col name>)` after such joins.
**TODO:**
- Add `col(<df alias name>, "*")` support
- Make df.copy preserve `df._select_statement`, such that self join queries can be flattened.
> SNOW-628569 Implement DataFrame.alias

- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes #SNOW-619443
Use objects from `Column` class to choose metadata columns objects.
> SNOW-619443: Use Column objects for choosing Metadata Columns

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/stored_procedure.py
- tests/integ/test_stored_procedure.py
Added execute_as parameter to StoredProcedureRegistration.register_from_file() function
N/A
Added execute_as parameter to StoredProcedureRegistration.register_from_file() function. This allows the stored procedure to be called with either 'owner' or 'caller' rights.
> SNOW-834932: Added execute_as parameter to StoredProcedureRegistration.register_from_file() function

- recipe/meta.yaml
In the local test env, the old upper bound is giving conda solver some headache to solve to the latest snowpark version
Fixes #NNNN
> SNOW-838017 Bump libffi version to 3.4.4

- CHANGELOG.md
- docs/README.md
- docs/source/functions.rst
- docs/source/types.rst
- setup.py
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/types.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/scala/test_function_suite.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/scala/test_table_suite.py
- tests/integ/scala/test_udf_suite.py
- tests/integ/test_udf.py
- tests/unit/test_datatype_mapper.py
- tests/unit/test_types.py
- tests/utils.py
- tox.ini
Fixes #SNOW-656580
Geometry support was added to python connector in release 3.0.4. This PR update snowpark to use leverage the connector changes and add support for Geometry type.
> SNOW-656580 support geometry data type in snowpark

- src/snowflake/snowpark/udf.py
Fixes SNOW-836583.
The function needs to be marked explicitly as a vectorized UDF handler using (1) `@vectorized` decorator or (2) [function attribute](https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-batch#id2), this PR ~changes `register_from_file` such that **when the udf is a vectorized UDF based on input/return types** AND **the source file does not contain either of the specifications** , it makes a copy of the source file and appends `<handler>._sf_vectorized_input = …
> SNOW-836583 Update `register_from_file` documentation for vectorized UDFs 

- CHANGELOG.md
- setup.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/async_job.py
- tests/integ/scala/test_async_job_suite.py
- tests/integ/test_bind_variable.py
Description
Currently we use SQL stored proc for multi-query plan during async collect. This is not binding friendly, so we want to migrate to use multistatement that we already support in the connector.
Testing
integ test
Fixes #NNNN
> SNOW-791242 Use multistatement query for async multi-query plan

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- tests/integ/test_udf.py
Fixes SNOW-856555
A TypeError will be raised if we try to call get_type_hints from a numpy ufunc, e.g., `get_type_hints(np.exp)`. In this case, if it fails, we just assume there are no type hints. This bug blocks supporting series/df.apply on numpy functions in snowpandas.
> SNOW-856555: Fix get_type_hint exception on numpy ufunc

- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
Description
Enabling UDAF adds an is_aggregate field when describing a function. We need to make sure our tests work both ways before enabling the feature in the test accounts.
Testing
Tested on an account that has UDAF enabled
Fixes SNOW-747608
Enabling UDAF adds an is_aggregate field when describing a function. We need to make sure our tests work both ways before enabling the feature in the test accounts.
> SNOW-747608 Make tests compatible with UDAF behavior change

- CHANGELOG.md
- src/snowflake/snowpark/session.py
- tests/integ/test_bind_variable.py
Description
The change in Snowflake and the connector was checked in to reach full parity as far as integ/test_bind_variable.sql goes. We could remove this restriction from snowpark.
Testing
regression test with test_bind_variable.sql
Fixes SNOW-861532
The change in Snowflake and the connector was checked in to reach full parity as far as integ/test_bind_variable.sql goes. We could remove this restriction from snowpark.
> SNOW-861532 Remove sp check for params in session.sql

- src/snowflake/snowpark/session.py
Description
Add doc: only support qmark, and a link to connector's qmark bind variable doc
Testing
N/A
Fixes SNOW-856070 
Add doc: only support qmark, and a link to connector's qmark bind variable doc
> SNOW-856070 Add doc for params in session.sql

- CHANGELOG.md
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/types.py
- src/snowflake/snowpark/udtf.py
- tests/integ/scala/test_udtf_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
- tests/resources/test_udtf_dir/test_vectorized_udtf.py
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_types.py
- tests/utils.py
Fixes #NNNN
-    Implement the support for registering vectorized UDTF by (1) specifying `PandasDataFrameType` as `output_schema` or (2) specify `PandasDataFrame` as type hints or (3) specify `pd.DataFrame` as type hints **and** a `StructType(List[StructField])` as `output_schema`.
> SNOW-828211  Support registering vectorized UDTF

- tests/integ/test_pandas_to_df.py
Description
This enables testing writing pandas DF to a different schema for both client and stored proc.
Testing
integ
Fixes SNOW-853049
This enables testing writing pandas DF to a different schema for both client and stored proc.
> SNOW-853049 Add write_pandas test to a different schema

- src/snowflake/snowpark/session.py
- tests/integ/test_packaging.py
- tests/integ/test_stored_procedure.py
> SNOW-874787: Prevent future flakiness of packaging tests

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-876321
A regression was identified in the attached SNOW ticket. The root cause is that the schema_query generated when sql simplifier is enabled only took the first operand of union into consideration. This change updates the schema query generation to consider all operands.
> SNOW-876321: Fix schema_query for union with sql simplifier enabled

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_dataframe.py
Fixes SNOW-729449
`DataFrame.cache_result` now creates temp tables using fully qualified names under current database and current schema.
> SNOW-729449 Fix DataFrame.result_cache to handle schema changes

- CHANGELOG.md
- docs/source/types.rst
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/types.py
- src/snowflake/snowpark/udf.py
- tests/integ/test_udf.py
Fixes SNOW-876999
Previously we add support for timestamp variations in data types, but we also need such support for UDFs with type annotations.
> SNOW-876999: Add support for timezone-aware type annotation on UDF 

- docs/source/functions.rst
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
> SNOW-860063 Update documentation

- .github/workflows/precommit.yml
- tox.ini
Fixes #NNNN
The current `Test when pandas is not installed macos-3.8-aws` fails because pytest runs the `test_*.py` files in `tests/resource` which are used for registering UDF from files. This PR fixes this issue.
> Clear pytest errors for tests/resource dir

- docs/source/_themes/empty/layout.html
- docs/source/_themes/empty/theme.conf
- docs/source/conf.py
Fixes #DOC-845
This change adds an empty theme and specifies it as the theme to use when producing documentation. With the [Snowpark Python API reference documentation being newly integrated into Snowflake's documentation as a first-class citizen](https://docs.snowflake.com/developer-guide/snowpark/reference/python/latest/index), generating the documentation using an empty template is a requirement for embedding.
> Add empty theme

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udaf.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
> SNOW-878135 is_permanent behavior fix

- setup.py
No issue
When I ran unit tests on a brand-new repository after development environment initialization, I got the error:
pytest tests/unit
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --timeout=1200
inifile: /opt/atlassian/pipelines/agent/build/tox.ini
rootdir: /opt/atlassian/pipelines/agent/build
To fix the problem I installed **pytest-timeout** lib
> Fix development environment

- CHANGELOG.md
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
> SNOW-896744: Allow creating dataframes using tuples as schema

- src/snowflake/snowpark/dataframe.py
- tests/unit/test_dataframe.py
Overview: Adding `printSchema` method for printing a human readable version of dataFrame schema. Note that the jira asks for print_schema and printSchema(alias), but in the parent jira and pySpark we only have `printSchema`. I can make changes is we actually need the two methods mentioned in the jira ticket.
Precommit test link: https://ci-dev-142.int.snowflakecomputing.com/job/PythonStoredProcBuildPrecommitTest/545/
SNOW-859941
Please write a short description of how your code change solves the related …
> Adding dataFrame.printSchema

- tests/integ/test_dataframe.py
Fixes SNOW-903873, dynamic table needs refresh to initialize, scheduled refresh is not reliable leading to flaky test failure, here we manually refresh the table 
> SNOW-903873: fix flaky test dynamic table creation

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/udaf.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
SNOW-903916
This PR adds keyword support for volatile/immutable when registering Snowpark UDFs.
> [Snowpark] Add arg for volatile/immutable UDF

- CHANGELOG.md
- setup.py
- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
Fixes SNOW-910685
Bump the connector version of connector so we have the latest change of default config file, and support reading connection parameters from default config file for creating session, and add a test
> SNOW-910685: Support creating session from default configuration file 

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/test_session.py
- tests/unit/test_expressions.py
No issue, quick fix
`Query` constructor was being called with params passed to the wrong argument. This uses the keyword argument correctly. I also changed the `Query` constructor to require any parameters after the SQL string to be keyword arguments, to prevent this in the future.
> Fix SELECT after session.sql() with params

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_dataframe_join_suite.py
- tests/integ/test_dataframe.py
Also fixes #875 and #886
Fixes `DataFrame.copy` for simplifier path by make sure attributes are copied from the subquery so that `NamedExpression.expr_id` is regenerated. As a result, `df1.filter(col("a") > 1).a` has a different expression id than `df1.a`, which enables basic diamond shaped joins like 
```
df2 = df1.filter(col("a") > 1).sort("b")
df1.join(df2, df1.a == df2.a)
```
> SNOW-841405  Fix df copy and enable basic diamond shaped joins for simplifier

- src/snowflake/snowpark/session.py
Fixes #SNOW-903907
The test is already present in `test_packaging::test_add_requirements_unsupported_with_cache_path` which is failing on merge gates on 3.9/3.10 runtimes. The fix is to get merge-gates back
> SNOW-903907: Fix custom package uplaod bug

- CHANGELOG.md
- setup.py
Description
We should not remove this dependency because it is a required dependency for snowpark, and we cannot rely on the fact that python connector also depends on it, because python connector can one day remove the dependency.
Testing
merge gate
Fixes #NNNN
> Add typing-extension dependency back

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/test_dataframe.py
Fixes #1046, #SNOW-911327
In PR #895 we started using create-table-insert-values pattern instead of using a CTAS pattern for saving dataframes. This is causing issues for multiple users so we are using CTAS while also respecting nullable columns. The tests added before also work for the correctness of this change.
> SNOW-911327: Use CTAS for save as table

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- src/snowflake/snowpark/_internal/type_utils.py
- tests/integ/scala/test_literal_suite.py
- tests/unit/test_datatype_mapper.py
SNOW-935457
Support creating literals of VariantType, e.g. `Column(Literal(10, VariantType()))` will create a literal corresponding to `10::VARIANT`. Change datatype_mapper to use PythonObjJSONEncoder to allow more Python objects for ARRAY/OBJECT literals.
> [SNOW-935457] Support variant type for Literal

- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/snowflake_data_type.py
- src/snowflake/snowpark/mock/window_utils.py
- tests/integ/scala/test_window_frame_suite.py
- tests/integ/scala/test_window_spec_suite.py
> [Local Testing] SNOW-783554 Support selecting window expressions

- CHANGELOG.md
- src/snowflake/snowpark/session.py
- tests/integ/test_packaging.py
Fixes SNOW-872425
fix adding package when the specifier contains name with underscore and version
previously we pass the whole string to the backend, and backend will report packages can not be found because of the version string. only project name shall be passed to the backend
> SNOW-872425: fix adding package when the specifier contains name with underscore and version

- CHANGELOG.md
- src/snowflake/snowpark/_internal/server_connection.py
- tests/integ/test_df_to_pandas.py
Fixes #SNOW-940607
When using `pandas.to_numeric` to fix https://github.com/snowflakedb/snowflake-connector-python/issues/828 caused precision issues when number of digits contained in the number was high and was interpreted as object instead of int64. We use `.astype('int64')` in a try block to try to convert the pandas column into `int64` if possible. If we hit exception, we fall back to `to_numeric`. Using `.astype('int64')` preserves precision in cases when the column can be converted into an int64 (which …
> SNOW-940607: Fix precision loss during to_pandas conversion

- src/snowflake/snowpark/mock/plan.py
Fixes #NNNN
Previously something like `df.sort(col("a")*col("b"))` would not work because the expression is not an existing column in the dataframe. This PR fixes the issue by modifying the implementation of `handle_order_by_clause ` to temporarily add the column `col("a")*col("b")` during sorting.
> [Local Testing] SNOW-915624 Fix DataFrame.sort where the orderby expression is not an Attribute

- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/stored_procedure.py
- tests/integ/test_stored_procedure.py
Fixes SNOW-946900
This is useful for Pandas API to skip code uploading when the stored procedure is registered by us (not users) and we are pretty sure the function won't be very large.
> SNOW-946900: Add internal parameter in stored proc registration to allow forcing inline code

- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/connection.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_view_suite.py
- tests/integ/scala/test_window_spec_suite.py
- tests/integ/test_dataframe.py
This PR enables DataFrame.createOrReplaceView and DataFrame.createOrReplaceTempView by changing the existing `TableRegistry` class to store a separate map of string to `MockExecutionPlan` pairs, where the key is the view name (str) and the value is an `MockExeuctionPlan` instance corresponding to the underlying query of a [View](https://docs.snowflake.com/en/user-guide/views-introduction) . When users fetch from a view using `Session.table`, we execute the `MockExecutionPlan` to obtain the results. In this way, changes in dependencies (e.g. `sum(*)` from a table) will be correctly reflected.
> [Local Testing] SNOW-931294 Support DataFrame.createOrReplaceView and DataFrame.createOrReplaceTempView

- CHANGELOG.md
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/exceptions.py
- tests/unit/test_error_message.py
Fixes SNOW-947875. When there is a parent stored procedure calling a child stored procedure, the parent stored procedure needs to determine the error code in the child query to determine how to format its error message. (See SNOW-800808 for more context.) Currently, the only way to do this when the parent is a Python sproc is to parse `SnowflakeSQLException.message`. It's slightly nicer and less error prone to have this information exposed directly in the exception class.
Adds raw message and error code …
> SNOW-947875 Add sql_error_code and raw_message into SnowparkSQLException

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes #SNOW-937665
Fix a bug where `Dataframe.write.save_as_table` would throw an error for dataframe created from file api due to invalid column name `$1` error. This PR analyzes the column names to be saved and renames them in case they have name `${number}`.
> SNOW-937665 fix unsupported column name $1

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_udtf.py
[SNOW-948486](https://snowflakecomputing.atlassian.net/browse/SNOW-948486)
The PR introduces a new optional parameter `input_names` to `UDTFRegistration.register/register_file` and `functions.py/pandas_udtf`, where we now support specifying input column names for UDTF's. Note this is essentially a NOOP for regular UDTFs since the columns are mapped to function parameters, the feature is only useful for vectorized UDTF where we rely on names to access the columns in the pandas DataFrame. The parameter is set as optional for backwards compatibility, if unspecified, the default column names will be `ARG1`, `ARG2`, etc.
As a result, we now infer the column names from schema in `RelationalGroupedDataFrame.applyInPandas`.
[SNOW-948486]: …
> SNOW-948486 Support specifying input column names for vectorized UDTF

- src/snowflake/snowpark/udtf.py
The deleted line is unnecessary for the doctest to work and against the purpose of example 14.
> Delete typo in doctests 

- local-testing-docs/README.md
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/connection.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/snowflake_data_type.py
- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/scala/test_function_suite.py
- tests/integ/scala/test_session_suite.py
- tests/integ/test_column.py
- tests/integ/test_column_names.py
- tests/integ/test_dataframe.py
- tests/integ/test_function.py
- tests/mock/test_agg.py
- tests/utils.py
Support creating dataframes with columns of VariantType, MapType and ArrayType by implementing conversion functions `to_variant`/`to_array`/`to_object`.
**Todo/Questions**
- Should we keep variant type as strings to align with the existing behavior?
> [Local Testing] SNOW-848935 Support VariantType, MapType and ArrayType

- tests/integ/scala/test_async_job_suite.py
Description
We have to skip these tests before because we don't support result_scan and large result for multistmt queries. Now that these are supported, we could remove the skip
Testing
Regression test
Fixes SNOW-964034
> SNOW-964034 Enable skipped multistmt tests for stored proc

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
- tests/integ/test_dataframe.py
Fixes SNOW-950417
In this PR the regex for detecting whether a column name is quoted is enhanced to support column names with newlines in them.
> SNOW-950417 fix quoted name matching for new lines

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/exceptions.py
- tests/unit/test_error_message.py
https://snowflakecomputing.atlassian.net/browse/SNOW-956848
This is mostly addressed by https://github.com/snowflakedb/snowpark-python/pull/1111, but I think this is a better long-term solution, for the user to have access to any information in the underlying error.
> SNOW-956848 Store underlying error in SnowparkSQLException

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_simplifier_suite.py
- tests/utils.py
Fixes #1093
Added a`pivot` method in `RelationalGroupedDataFrame` which allows to access `pivot` using `df.group_by().pivot()`
> Add RelationalGroupedDataFrame.pivot()

- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/plan.py
- tests/integ/scala/test_update_delete_merge_suite.py
> [Local Testing] SNOW-929078 Support Table.update/delete/merge

- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/connection.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/snowflake_data_type.py
- src/snowflake/snowpark/types.py
- tests/integ/test_datatypes.py
- tests/mock/test_create_df_from_pandas.py
> SNOW-958008: fix local test division datatypes

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- src/snowflake/snowpark/_internal/analyzer/schema_utils.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/types.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/scala/test_udf_suite.py
- tests/integ/test_function.py
- tests/unit/test_datatype_mapper.py
- tests/unit/test_types.py
- tests/utils.py
Fixes SNOW-950842
Added support for the vector data type to snowpark. As with arrays, we temporarily serialize vector inputs as strings and wrap `parse_json` and `cast` calls to construct the right type. Let me know if there are any edge cases that this temporary bypass introduces that I need to handle.
There are many formatting changes that were automatically applied by the repository's precommit because I edited certain files.
> SNOW-950842 Add support for the vector data type

- src/snowflake/snowpark/mock/functions.py
N/A
Previously `mock_avg` always return a column of floating point values rounded to 5 digits after the floating point, where the result type is incorrectly set to the type of the incoming column. As a result, average of Integer column will have a return type of Integer. Average of Decimal columns will not have the correct precision and scale. This PR fixes these issues.
> [Local Testing] SNOW-976759 Fix implementation of mock_avg to compute the correct return type and precision

- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes SNOW-984111
executing inside SP is different than non-SP
the datetime will by default given a timestamp timezone NTZ
to align the behavior, we explicitly set the timestamp type
> SNOW-984111: Fix new test failure related to timezone when executed in stored proc

- CHANGELOG.md
We mistakenly put 11-xx for the last two release dates happened in December, this PR corrects the dates.
> Update CHANGELOG.md to reflect the correct release dates

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/test_pandas_to_df.py
- tests/integ/test_simplifier_suite.py
SNOW-980540
The sql simplifier incorrectly flattened the following query 
```
FROM ( 
SELECT "A", "B", min("B") OVER (  ) AS "C" 
FROM ( 
SELECT "A", iff(("A" = 0 :: INT), 10, 11) AS "B" 
FROM ( 
SELECT "A" FROM ( 
SELECT $1 AS "A" FROM  VALUES (0 :: INT), (1 :: INT))))) 
WHERE ("A" = 1 :: INT)
```
into
```
SELECT 
"A", "B", min("B") OVER (  ) AS "C" 
FROM ( 
SELECT "A", iff(("A" = 0 :: INT), 10, 11) AS "B" 
FROM ( 
SELECT $1 AS "A" 
FROM  VALUES (0 :: INT), (1 :: INT))) WHERE ("A" = 1 :: INT)
```
where the …
> [SNOW-980540] Fix for sql simplifier that incorrectly pushed filter down during flattern with window function

- mypy.ini
- setup.py
- src/snowflake/snowpark/_internal/code_generation.py
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/_internal/packaging_utils.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/_internal/utils.py
- tox.ini
This PR fix the type hints in 
- src/snowflake/snowpark/_internal/packaging_utils.py
- src/snowflake/snowpark/_internal/code_generation.py 
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/_internal/server_connection.py
such that
`tox -e mypy` pass with no errors.
> Fix type hints for src/snowflake/snowpark/_internal/packaging_utils.py, code_generation.py error_message.py server_connection.py

- CHANGELOG.md
- src/snowflake/snowpark/dataframe_na_functions.py
Fixes SNOW-990324
Added an example to na.fill that breaks under current logic. With that example I traced execution and found that `_is_value_type_matching_for_na_function` was incorrectly including `bool` as a valid numeric type. Python counts [bool](https://docs.python.org/3/c-api/bool.html)s as integers, but we don't want it to count as a numeric type so I've added an additional clause to the condition that checks if the datatype is numeric.
> SNOW-990324: Fix inconsistency when calling na.fill

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/session.py
- tests/unit/scala/test_utils_suite.py
Fixes SNOW-971157
This PR adds a couple extra parameters to the `Session.add_import` method. These parameters allow the user to specify a specific chunk size when adding an import. A larger chunk_size can be useful when files start to get larger. A second parameter allows the user to specify that the entire file should be hashed. In this case it will be read one chunk at a time with the hashing algorithm updated each time.
I've left the default behavior of the the `calculate_checksum` alone, but it might be …
> SNOW-971157: Add additional parameters to Session.add_import

- CHANGELOG.md
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/mock/_connection.py
- tests/integ/test_df_to_pandas.py
- tests/integ/test_udf.py
Fixes #SNOW-940607
In this PR, we update `_fix_pandas_df_integer` to use `astype('int64')` for cases where the precision value sent by GS is greater than 10. This is done to fix the loss of precision when using `pandas.to_numeric` for long numbers.
> SNOW-940607: use precision value to decide when to use astype(int64)

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/expression.py
- tests/integ/test_column_names.py
- tests/integ/test_dataframe.py
This PR adds support for Interval expressions, which the Snowpark pandas team needs to support binary operations with pandas DateOffsets (using Interval keyword).
> Add Interval expression to Snowpark API

- CHANGELOG.md
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/mock/_connection.py
- tests/integ/test_df_to_pandas.py
Fixes #SNOW-990542
Pandas doesn't recognize decimal type. When we convert snowpark dataframe to pandas dataframe, the decimal columns are not handled correctly, and thus result in issues. 
When we convert snowpark dataframe to pandas dataframe, we cast decimal columns into float64.
For more details, please see [[thread](https://snowflake.slack.com/archives/C03NGNUKF37/p1704936911017529)]
> [SNOW-990542] When converting snowpark dataframe to pandas, cast decimal columns to float type

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
Description
Add support for array_except that by default follows the semantic of Snowflake. We also introduced a flag `allow_duplicates` to control the behavior.
Testing
doc test
Fixes SNOW-967725
Add support for array_except that by default follows the semantic of Snowflake. We also introduced a flag `allow_duplicates` to control the behavior.
> SNOW-967725 Support array_except

- CHANGELOG.md
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/stored_procedure.py
- tests/integ/test_packaging.py
- tests/integ/test_stored_procedure.py
- tests/unit/test_stored_procedure.py
Fixes SNOW-949781
As part of this change I had to understand `Session._resolve_packages`. This method was overly long so as part of this commit I broke it up into smaller chunks to make it a little more understandable. I also modified the exception logic for that function so that errors are gathered for all packages rather than failing on the first erroneous package. If this sort of refactor is better pulled into a separate commit I can remove it from this one.
After understanding that method it seemed easier …
> SNOW-949781: Add Snowpark Package automatically for sprocs

- tests/integ/test_session.py
Fixes #NNNN
When setting the query tag, we run `alter session...`, which should be skipped in stored proc tests
> Skip `test_update_query_tag` in stored procedure tests

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Fixes [SCT-7891](https://snowflakecomputing.atlassian.net/browse/SCT-7891)
It adds support for the function `snowflake.snowpark.functions.create_map` which creates a new column that contains a map of key-value pairs.
[SCT-7891]: https://snowflakecomputing.atlassian.net/browse/SCT-7891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCT-7891: Add support for create_map function in snowflake.snowpark.functions

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/types.py
- tests/integ/test_dataframe.py
Description
Snowflake has an undefined behavior of nullability for columns in select statement. For example, `select 'string'` returns non-nullable, but `select True` returns nullable.
This means our approach of type mapping between user-specified schema is not working as expected. For example if a user specifies a non-nullable boolean field when invoking create_dataframe, then does a save_as_table, the table will contain a nullable boolean column, which can be surprising.
In this change, we create a temporary table using user's specified schema if there is non-nullable fields, then override the schema query by directly select from the newly created temp table. If user does not have temp table creation privilege, we will fall back to the original select statement approach for schema. …
> SNOW-990777 Use temp table for non-nullable schema when possible

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-945984
When, `to_subqueryable()` is called, it triggers the non-select to be converted into a select statement by creating a `pre_action` for main query and using a `select * from table(result_scan(...))` for the result from the `pre_action` query. In this PR, I add missing pre and post actions that are added to `from_` when running `to_subqueryable()`.
> SNOW-945984: Fix sql simplifier when non select statement is used with limit

- CHANGELOG.md
- recipe/meta.yaml
- setup.py
- src/snowflake/snowpark/version.py
> SNOW-1021998: prepare release for v1.12.0

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
SNOW-1023214
This PR adds support for the optional `date_part` argument for the Snowflake function `last_day`. See the SQL documentation here: https://docs.snowflake.com/en/sql-reference/functions/last_day
> SNOW-1023214: Support date_part argument in last_day

- CHANGELOG.md
- src/snowflake/snowpark/_internal/server_connection.py
- tests/integ/scala/test_async_job_suite.py
- tests/integ/test_dataframe.py
Fixes #945 
**Issue**: All queries issued from a Snowpark `Session` object are executed using the same SnowflakeCursor instance, this causes unexpected, wrong behavior when we fetch results from an iterator but have code that executes a different query half way, e.g.
```
df = session.create_dataframe([[1,2,3],[4,5,6]], schema=["a", "b", "c"]) 
my_iter = df.to_local_iterator()
row_counter
for row in my_iter:
len(df.schema.fields)  # this executes a schema query, which overwrites properties of the cursor object …
```
> SNOW-869536 Fix buggy behavior in DataFrame.to_local_iterator 

- src/snowflake/snowpark/functions.py
Fixes #NNNN
Removes the Optional type hint for `date_part` param in `last_day`.
> Fix type hint for `date_part` param in `last_day` Snowpark function

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
Fixes #1032642
The below error message assumes that tables are quoted which is not always the case.
> SNOW-1032642: Fix table name truncation in local testings error

- CHANGELOG.md
- src/snowflake/snowpark/_internal/server_connection.py
- tests/integ/test_df_to_pandas.py
Fixes [SNOW-1026241 ](https://github.com/snowflakedb/snowpark-python/issues/1229)
When there is a NaN value in the column, it does not try to cast it to integer but keeps it as float64
> Fix of to_pandas() when having integer column with null values

- CHANGELOG.md
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/mock/_connection.py
Fixes #SNOW-1018660
Setting `split_blocks=True` until we get a resolution for default case. This also aligs with the recommendation from pyarrow maintainers.
> SNOW-1018660: use split_blocks=True by default

- .github/workflows/changelog.yml
- .github/workflows/jira_close.yml
- .github/workflows/jira_issue.yml
- .github/workflows/precommit.yml
- .github/workflows/python-publish.yml
- .github/workflows/snyk-issue.yml
- .github/workflows/snyk-pr.yml
SNOW-1060034
Github displays a warning when using old v2 versions because of a deprecated nodejs version. Update to more recent versions for 
- checkout@v2 -> checkout@v4
- setup-python@v2 -> setup-python@v4
- download-artifact@v2 -> download-artifact@v4
- upload-artifact@v2 -> download-artifact@v4
> [SNOW-1060034] Update Github actions from v2  to newer v4.

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/scala/test_function_suite.py
- tests/utils.py
Fixes #1043119
This PR adds support for string operations upper, lower, length, and initcap to local testing. I also added additional testing examples to check a few more cases that I wanted.
> SNOW-1043119: Add upper/lower/length/initcap support to local testing

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/scala/test_function_suite.py
Fixes #1016709
This PR adds local testing support for STRIP_NULL_VALUE.
Question for reviewers:
Is STRIP_NULL_VALUE always called with a value column or should it be able to walk a json object and replace all instances of 'null'?
> SNOW-1016709: Add local testing support for STRIP_NULL_VALUE

- CHANGELOG.md
- src/snowflake/snowpark/_internal/server_connection.py
This fix enables tracking snowpark ML usage in sprocs, notebooks, and streamlit apps. This is a workaround because statement params telemetry is not received from sprocs.
* set "applications" parameter if snowpark ML is present
* fix helper method name
* Make sure "streamlit" is also set if present
> SNOW-1014048: Set `PARAM_APPLICATIONS` for snowpark ML usage tracking

- src/snowflake/snowpark/_internal/server_connection.py
Fixes SNOW-1058663
**Context:** Currently t_python_sp::table_procs_on_snowsql.ssql is failing in PythonStoredProcBuildPrecommitTest because of the changes introduced in SNOW-869536 Fix buggy behavior in DataFrame.to_local_iterator  by sfc-gh-stan · Pull Request #1226 · snowflakedb/snowpark-python . This is because the implementation of table sprocs calls `_execute_and_get_query_id`, which calls `ServerConnection._to_data_or_iter` with `to_iter` set to True, therefore is affected by the code change in Snowpark …
> SNOW-1058663  Fix `ServerConnection. _to_data_or_iter` to return the original query id

- src/snowflake/snowpark/session.py
- tests/integ/test_packaging.py
Description
Our merge gate is broken because of a new python-dateutil release.
To fix merge gate, there are two changes
- We don't check python-dateutil is in package set. The reason is that the latest version of python-dateutil is not on Snowflake yet, and as a result, we use custom package and not specify this package in session.
- We add session.custom_package_usage_config for the python-dateutil related doc test.
Testing
Merge gate passing
Fixes #NNNN
Please write a short description of how your code …
> Merge gate fix

- CHANGELOG.md
- docs/source/session.rst
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_reader.py
- src/snowflake/snowpark/mock/_plan_builder.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_permanent_udf_suite.py
- tests/integ/scala/test_session_suite.py
- tests/integ/scala/test_udf_suite.py
- tests/integ/test_session.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/unit/test_stored_procedure.py
- tests/unit/test_udaf.py
- tests/unit/test_udf.py
- tests/unit/test_udtf.py
Description
In snowpark API, we use fully qualified name for temp objects created implicitly by the API, mainly to support locating the object even if user changes schema of the session.
However, in stored procs, we have use cases like bundle where it is legit to have current_database/current_schema to return NULL. We still want to support object creation in this case.
Thus, our change is to fall back to use the object name if there is no current database/schema and the client is running inside the stored procedure
Testing
Existing tests + bundle integration test
Fixes #NNNN
2. Fill out the following pre-review …
> SNOW-1064328 Use object name if db/schema is missing in stored proc

- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/cte_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/session.py
- tests/integ/test_cte.py
- tests/unit/test_cte.py
- tests/unit/test_dataframe.py
- tests/unit/test_server_connection.py
Fixes SNOW-1060064
This PR adds an optimization to eliminate repeated subquery using CTE (see details in https://docs.google.com/document/d/1vVUYqLeD_nQRVaH3SX2c4jDNJoBGHJlg8PqiJ8qxgVM/edit), with original query generation framework. 
The basic idea is to convert repeated subqueries to a CTE, e.g., 
`
( SELECT * FROM ( SELECT  *  FROM ( SELECT "A", "B" FROM ( SELECT $1 AS "A", $2 AS "B" FROM  VALUES (1 :: INT, 2 :: INT), (3 :: INT, 4 :: INT))) WHERE ("A" = 1 :: INT))) UNION ALL ( SELECT * FROM ( SELECT  * …
> SNOW-1060064: Eliminate repeated subquery using CTE (part 1, with original query generation framework)

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_column_suite.py
Fixes #SNOW-1063758
**Issue**: Previously, if `pattern` is specified as column (e.g. `df.col1.regexp(df.col2)`), Local Testing uses the first entry in the column to match all entries in the left hand side. This is incorrect, the expected behavior is to do a row-wise match so each LHS entry is matched with the corresponding entry from `pattern`.
**Fix**: This PR implements the expected behavior.
> SNOW-1063758 Fix Local Testing's implementation of Column.regexp to handle Column of strings as `pattern`

- CHANGELOG.md
- src/snowflake/snowpark/mock/_connection.py
- tests/integ/test_dataframe.py
Fixes SNOW-1216530, i.e. #1290
**Issue**: The current implementation is not iterating over the rows correctly. E.g. A pandas DataFrame can be initialized with 3 rows, after removing the middle row, the dataframe's row index now looks like [0,2]. So `df[col][1]` does not access the second row, the code would fail to find a row indexed with `1`.
**Solution**: This PR uses `DataFrame.iterrows` to iterrate the rows of a pandas DataFrame instead.
> SNOW-1216530 Fix Local Testing's handling of `VARIANT` columns at `DataFrame.collect`

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
Fixes #SNOW-1105953
**Issue:** The previous implementation does not work with pandas dataframe's row indexing. On Line 224, `dict_data` could already have a row indexing that's not a consecutive integer sequence starting from 0, so `temp_table` is not initialized correctly.
**PR:** This PR implements `count_distinct` by merging all incoming columns into a column of tuples, then applying `pandas.DataFrame.nunique`.
> SNOW-1105953 Fix Local Testing implementation of count_distinct

- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/mock/_telemetry.py
- tests/mock/test_oob_telemetry.py
skip oob telemetry tests as stored proc does not support oob telemetry
> SNOW-1239792: disable oob telemetry in stored procedure

- tests/integ/scala/test_dataframe_reader_suite.py
PR similar to https://github.com/snowflakedb/snowpark-python/pull/1165.
in sproc + our current test setting, the timezone information is wanted:
```python
G=datetime.datetime(2024, 3, 1, 9, 10, 11, tzinfo=&lt;UTC&gt;)
```
> SNOW-1248609: fix newly introduced test failure related to timezone in sproc

- CHANGELOG.md
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
- tests/unit/test_session.py
Fixes #1259 
Instead of throwing an error message when attempting to close a session a warning is written informing that closing a session inside a stored procedure is a no-op.
Afterwards the functionality to close sessions is ignored by returning from the function directly after writing a warning.
> Alter closing sessions inside a stored procedure to write a warning instead of throwing an error

- docs/source/dataframe.rst
- src/snowflake/snowpark/dataframe_analytics_functions.py
DataFrame.analytics APIs were released in 1.12. But it was missing the API reference changes. 
The PR adds API reference docs for DataFrame.analytics functions. 
> SNOW-1267005: Add API reference docs for dataframe.analytics functions

- docs/source/conf.py
Fixes SNOW-993572
We no longer create release branches in the release process. This PR changes the path of source code links in the API reference docs to use release tags.
> SNOW-993572 Change source code links to use release tags

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_function.py
Fixes #SNOW-1075566
This PR adds some pattern matching to function expression handling that detects constant functions and fills the column with the returned value rather than null filling after the first value.
See here for more info: https://github.com/snowflakedb/snowpark-python/issues/1266
An alternative to this PR would be to introduce a new return type to local functions that tells the planner that the result is a constant that should populate a whole column. This would make it more explicit when this …
> SNOW-1075566: Refactor local testing to allow constant function returns

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/mock/_functions.py
- src/snowflake/snowpark/mock/_util.py
- tests/integ/scala/test_function_suite.py
- tests/integ/test_stored_procedure.py
Fixes #1063719
This change adds support for `date_trunc` to local testing. Most supported cases are handled by a call to pandas.floor, but several time units are not supported by pandas so equivalent logic is provided. I've also added related testing for date_trunc to validate correctness as well as type preservation.
> SNOW-1063719: [Local Testing] Add date_trunc support

- src/snowflake/snowpark/mock/_telemetry.py
- tests/conftest.py
- tests/mock/__init__.py
- tests/mock_unit/conftest.py
- tests/mock_unit/test_create_df_from_pandas.py
- tests/mock_unit/test_filter.py
- tests/mock_unit/test_functions.py
- tests/mock_unit/test_oob_telemetry.py
- tests/mock_unit/test_sort.py
- tests/mock_unit/test_union.py
- tox.ini
Fixes SNOW-1296430
- update oob telemetry endpoint to use old endpoint which works, the engineering team is working on getting the previous endpoint to work. after their work complete, both endpoint shall work so the change is safe.
- previously the mock unit test is not picked up because of tox.ini setting, now we update the config to run those unit tests
- some mock unit tests are failing in the dir tests/mock, those will be fixed in separate PRs, check SNOW-930299
> SNOW-1296430: fix telemetry endpoint

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/file_operation.py
- tests/unit/test_internal_utils.py
Fixes #1345
Adds support for `snow://` prefixed stage paths. Also fixes a bug where local file path is incorrectly extracted from single quoted paths: `'@path/file'` -> `file'` (note trailing quote)
> Add support for `snow://` stage paths

- CHANGELOG.md
- docs/source/index.rst
- docs/source/udaf.rst
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
Description
We are shooting for public preview at the end of April, so we want to remove the private preview decorator in the April client release.
Testing
N/A
Fixes SNOW-1284684
> SNOW-1284684 Remove private_preview tag for udaf

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/test_function.py
Fixes #SNOW-958582 
This PR changes the Local Testing implementation of `to_object`, `to_array`and `to_binary` to support (1) when the input is null and (2) when the input is a null json string stored in a VARIANT column.
> SNOW-958582 [Local Testing] Add better support for to_object, to_array, to_binary

- src/snowflake/snowpark/dataframe_writer.py
Fixes https://github.com/snowflakedb/snowpark-python/issues/1363
* [`src/snowflake/snowpark/dataframe_writer.py`](diffhunk://#diff-30e3ff47797748b9e4b3bf0e50aede5c2a609f6624f51ef83ac2c04802cf17e9L243-R243): The `copy_into_location` method was updated in three instances. The `copy_options` parameter was changed from `Optional[str]` to `Optional[Dict[str, Any]]`. This change allows for a wider range of types to be accepted as copy options, providing more flexibility when calling the method. …
> SNOW-1304211: Pylance throws errors when using copy_options with copy_into_location method

- .github/workflows/daily_precommit.yml
Fixes #NNNN
Add daily precommit tests. An example here https://github.com/snowflakedb/snowpark-python/actions/runs/8637285804
> SNOW-1296603: Add daily precommit test

- setup.py
- src/snowflake/snowpark/mock/_telemetry.py
- tests/mock_unit/test_oob_telemetry.py
Fixes SNOW-1324573
the local testing oob telemetry is flaky because the service takes longer to process or throttled.
do the following to improve:
- increate the default wait time, this barely add overhead to customer as we are doing batch sending underneath
- add retry in our test
- remove duplicate and unreliable exact record tuple assertion, checking caplog text should be enough
> SNOW-1324573: local testing fix flaky oob telemetry test

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- src/snowflake/snowpark/mock/_stored_procedure.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/stored_procedure.py
- tests/integ/scala/test_function_suite.py
- tests/integ/test_function.py
- tests/integ/test_stored_procedure.py
> SNOW-1183322: [Local Testing] Add support for registering sprocs

- CHANGELOG.md
- src/snowflake/snowpark/mock/_connection.py
- tests/integ/test_session.py
Fixes SNOW-1325264
Session.builder.getOrCreate should return a created mock session instead of trying to create a new one.
The bug is caused by not setting `expired` attr on the mock connection object.
also enabling a bunch of session related tests in local testing
> SNOW-1325264: Fix local testing Session.builder.getOrCreate to return created session

- CHANGELOG.md
- src/snowflake/snowpark/mock/_util.py
- tests/integ/scala/test_column_suite.py
- tests/utils.py
Fixes SNOW-1284674
in local testing, timestamp comparison beyond year 2262 will trigger pandas out of time bound error.
it's a know limitation from numpy https://numpy.org/doc/stable/reference/arrays.datetime.html#datetime-units:
`ns nanosecond +/- 292 years [ 1678 AD, 2262 AD]`
to handle the issue, we change to use `object` for now -- there is not obvious side effect as tests are passing. ideally we can use datetime64[us] (microsecond) to bypass the issue, however datetime64[us] don't work on Python 3.8 …
> SNOW-1284674: fix timestamp data comparison beyond datetime64[ns] range

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
Fixes https://github.com/snowflakedb/snowpark-python/issues/1388
type hint in internal module should not raise AttributeError, the `_hashlib` can be unreliable for type hint
> SNOW-1331246: type hint should not raise attribute error

- scripts/tox_install_cmd.sh
- tox.ini
Fixes #SNOW-1308662
We set env variable [snowflake_path](https://github.com/snowflakedb/jenkins_utils/blob/2babdc1b74a6058d271dd1fb7aff903dec4211e7/jobs/ci1/jobs/ci-dev-142/SnowparkPythonSnowflakePythonClientRegress.groovy#L104) in the jenkins job but we don't pass this path down to tox environment. This PR fixes the problem.
Testing:
Tested [jenkins job](https://ci-dev-142.int.snowflakecomputing.com/job/SnowparkPythonSnowflakePythonClientRegressRunner/579/console) with this branch and noted that the …
> Test don't install python connector from pypi

- src/snowflake/snowpark/_internal/udf_utils.py
- tests/unit/test_stored_procedure.py
- tests/unit/test_udaf.py
- tests/unit/test_udf.py
- tests/unit/test_udf_utils.py
- tests/unit/test_udtf.py
There is no open Github issue for this PR as it is initiated internally within Snowflake.
A bug was identified in PR #1397 whereby the first time the udf_utils module is loaded, the callback value is read and never updated. This is because of the semantics of `from ... import` in Python (vs `import <module>`). The bug was not detected by the existing tests because they incorrectly mocked the state. The tests have been updated now, and the behaviour was verified manually through an end-to-end example. I …
> Fixed import from context bug

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
- tests/unit/test_stored_procedure.py
> SNOW-1325652: release snowpark 1.15.0

- src/snowflake/snowpark/modin/pandas/__init__.py
- src/snowflake/snowpark/modin/plugin/__init__.py
- tests/unit/modin/test_python_version.py
Fixes #1324779
This PR modifies Snowpark pandas to error and prompt the user to install Modin if the incorrect pandas or Modin version is encountered. It also adds a warning informing users that the pandas feature is in PuPr.
These error messages were tested manually by manually installing the appropriate dependencies. If so desired, they can also be set up in CI as well, but might be more complicated to run since they require environmental changes.
> SNOW-1324779: Update warnings for Snowpark pandas

- .github/CODEOWNERS
- .github/workflows/precommit.yml
- setup.py
- tox.ini
Fixes #NNNN
This PR changes `setup.py` to ensure `pip install -e '.[modin-development]` installs all necessary dependencies so users don't have to do `pip install -e '.[modin-development, development, pandas]`.
> Ensure `pip install -e '.[modin-development]'` installs all necessary dependencies

- tests/integ/test_stored_procedure.py
`test_stored_proc_register_with_module` uses pandas, so we add a skip if the test is running in an environment where pandas is not available.
> Add skip if pandas is not available to `test_stored_proc_register_with_module`

- src/snowflake/snowpark/modin/plugin/_internal/ordered_dataframe.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_where.py
Fixes SNOW-1338078
This PR makes sure that deduplication of columns before a join does not fail if metadata columns are not renamed. It also adds a test for this, which uncovered a bug where the `where` API does not ensure the row position column before doing a positional join, which was also fixed.
> [SNOW-1338078]: Do not fail in deduplication if ordering columns not renamed

- .github/workflows/daily_modin_precommit.yml
- .github/workflows/daily_precommit.yml
- .github/workflows/precommit.yml
Fixes SNOW-1349055 CI change: use ubuntu-latest for small tasks
For small tasks, use `ubuntu-latest` instead of 64-core machines.
> SNOW-1349055 CI change: use ubuntu-latest for small tasks

- src/snowflake/snowpark/modin/pandas/base.py
- tests/integ/modin/frame/test_getitem.py
- tests/integ/modin/series/test_getitem.py
Fixes SNOW-1348621
(boolean) DataFrame keys in `__getitem__` were not correctly supported. I use `where()` to evaluate the result for `df[DataFrame key]`.
> SNOW-1348621 Fix bug and add support for DataFrame key in getitem

- scripts/jenkins_regress_snowpandas.sh
- scripts/tox_install_cmd.sh
- src/snowflake/snowpark/modin/config/envvars.py
- tox.ini
SNOW-1297195
There were a few issues which prevent the daily snowpark pandas API jenkins job to run successfully:
- tox.ini had `MODIN_PYTEST_NO_COV_CMD` missing
- the jenkins invocation script requires tox to be installed
- the tox_install_cmd.sh was using sh, but should be bash and variables were not defined.
this PR addresses these issues.
> [SNOW-1297195] Add tox to daily jenkins job, fix tox.ini.

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_replace.py
- tests/integ/modin/series/test_replace.py
Fixes SNOW-1355199
Fix incorrect regex used in DataFrame/Series.replace.
> SNOW-1355199: Fix incorrect regex used in DataFrame/Series.replace

- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/modin/plugin/__init__.py
- src/snowflake/snowpark/modin/plugin/_internal/ordered_dataframe.py
- tests/conftest.py
- tests/integ/modin/frame/test_transpose.py
- tests/integ/modin/strings/test_get_dummies_series.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_pandas_to_df.py
- tests/integ/test_udf.py
- tests/unit/scala/test_utils_suite.py
Fixes SNOW-1344848
Stop warning the user about our internal usage of private preview
dynamic pivot features. The user should have already been warned that
Snowpark pandas is in public or private preview. They very likely don't
know or care that we are using Snowpark DataFrame pivot() internally,
let alone that we are using private preview features of Snowpark
Python.
I'm not adding a changelog note because we haven't released a version of
Snowpark Python with this bug yet.
> SNOW-1344848: Suppress dynamic pivot warnings

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/ordered_dataframe.py
- tests/integ/modin/test_chained_operations.py
Fixes SNOW-1348886
Following steps result in AssertionError: row count column "__row_count__" not found in ['"__row_position__"', '"PRICE"']
df = pd.read_snowflake("LINEITEM")
print(df)
df["PRICE"].sort_values(ascending=True)
Root cause: in ordered_dataframe.sort method we are passing row_count column to new ordered dataframe but didn't include row_count column in projection.
> SNOW-1348886: Bugfix: AssertError in sort_values after indexing

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py
- tests/integ/modin/frame/test_loc.py
Fixes SNOW-1057861
Investigated deviating behavior in pandas `df.loc` and `__setitem__` when a scalar column key is used to assign a single value DataFrame item. This issue is present in pandas 2.x.x, pandas 1.5.x has the correct behavior. I modified the xfail'd test to correctly test Snowpark pandas behavior and included the pandas GitHub issue for the bug: https://github.com/pandas-dev/pandas/issues/58482
> SNOW-1057861 Bug - loc set with scalar column key and DataFrame item

- src/snowflake/snowpark/modin/pandas/series_utils.py
- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/series/test_dt_accessor_unsupported.py
- tests/unit/modin/test_series_dt.py
Fixes SNOW-1347387
Raise not implemented error for Series.dt.* methods instead of falling back to native pandas.
NOTE: I have kept the existing tests mostly unmodified even though there is redundancy. This can be useful when we implement these APIs.
NOTE: This also require updates in docs/*supported.rst files. These files are not yet ported from snowpandas. So will do a follow up PR to update the docs.
> SNOW-1347387 Raise not implemented error for Series.dt.* methods

- src/snowflake/snowpark/modin/plugin/docstrings/base.py
- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
Fixes SNOW-1257115
The docstrings for the `isnull` and `isna` methods of `DataFrame`/`Series` previously used the top-level `pd.isna`/`isnull` documentation instead. This PR changes them to use the correct docstring.
> SNOW-1257115: Fix docs for Snowpark pandas DataFrame/Series.isnull/isna

- tests/integ/modin/frame/test_shift.py
Fixes SNOW-1357700
pandas bug https://github.com/pandas-dev/pandas/issues/57301 was fixed in 2.2.1, so we should remove the workaround for it.
> SNOW-1357700: Remove workaround for native pandas groupby.shift(axis=1)

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- tests/integ/modin/frame/test_apply.py
Fixes SNOW-1357695
We convert numpy ints to ints explicitly in the UDTF for `groupby.apply` [here](https://github.com/snowflakedb/snowpark-python/blob/31aad1fc33c263e3b2c3403f3dab160712e00f22/src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py#L310) and [here](https://github.com/snowflakedb/snowpark-python/blob/31aad1fc33c263e3b2c3403f3dab160712e00f22/src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py#L546) but have so far managed to avoid doing so for apply(axis=1). With the new server …
> SNOW-1357695: Fix int64 not serializable errors on apply(axis=1)

- src/snowflake/snowpark/modin/pandas/base.py
- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/binary/test_binary_op.py
SNOW-1054699
This PR fixes single-row Series and DataFrame binary ops which previously returned `AttributeError: 'numpy.int8' object has no attribute 'index'`.
> SNOW-1054699: Fix single-row Series and DataFrame binary ops

- tests/integ/modin/binary/test_binary_op.py
This PR fixes the query count for `test_binary_op_between_dataframe_and_series_axis0`(related to this PR: https://github.com/snowflakedb/snowpark-python/pull/1505) and adds them back to the merge gate.
> Fix query count for `test_binary_op_between_dataframe_and_series_axis0` and add back to merge gate

- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_session_suite.py
Fixes SNOW-1318080
Move "use object_type object" handling parsing logic into session to avoid accidentally causing confusion to users that sql query is supported
> SNOW-1318080: local testing move use object logic into session.py for better sql query isolation

- tests/mock_unit/test_oob_telemetry.py
Fixes SNOW-1357844
pytest.approx only supports number, datetime is not supported, so previously implementation doesn't work at all.
change to use timestamp to the approx equal
> SNOW-1357844: fix flaky test caused by oob telemetry datetime comparsion

- tests/integ/test_column_names.py
Fixes SNOW-1063738
This PR rewrites the test `tests/integ/test_column_names.py::test_binary_expression` to get rid of comparison between incompatible data types (i.e. str and int), so it could run against Local Testing. The original test **relies on live connection behavior where getting schema name does not actually run the query**, where the generated query would fail to execute in a live connection. Local Testing needs to evaluate the transformation to obtain the schema name, so this PR essentially rewrites the test to generate executable query.
> SNOW-1063738 Rewrite `tests/integ/test_column_names.py::test_binary_expression` to apply to Local Testing

- tests/integ/modin/test_qcut.py
There have been access issues in Azure (ubuntu) and GCP (windows) to access data in `SNOWFLAKE_SAMPLE_DATA`. Enable running test, which will pass if privileges are granted.
> [CI] Remove skip, run qcut test with access to SNOWFLAKE_SAMPLE_DATA.

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_describe.py
- tests/integ/modin/frame/test_quantile.py
- tests/integ/modin/series/test_describe.py
- tests/integ/modin/series/test_quantile.py
- tests/integ/modin/test_qcut.py
Fixes SNOW-1370365
This PR avoids UNION ALL operations for computing quantiles over 1-column datasets. This optimization has significant implications for `pd.qcut`, which frequently computes a large number of quantiles and previously would had extremely high union counts in queries.
In particular, `test_qcut.py::test_qcut_two_columns` goes from 90 unions -> 0 unions, 34 joins -> 14 joins; and `series/test_quantile.py::test_quantile_large' goes from ~80 queries -> 6 queries.
> SNOW-1370365: Avoid UNION ALL for 1-column quantile operations

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- src/snowflake/snowpark/mock/_util.py
- tests/integ/test_function.py
Fixes SNOW-1235486
this PR does the following things:
1. added more types support to to_char mock function including DecimalType, BinaryType, ArrayType, MapType, TimestampType, DateType and TimeType.
2. added to_varchar support which is an alias of to_char
3. refactor convert_snowflake_datetime_format to use native python mechanism to handle AM/PM
4. fixed a bug in convert_snowflake_datetime_format to handle fractional second part
5. raise notimplementederror for unsupported cases
> SNOW-1235486: local testing add more type support for to_char

- tests/integ/scala/test_datatype_suite.py
This PR fixes two test failures in the daily precommit job.
- test_structured_dtypes_pandas was failing when pandas is not available. I've added a skip for when pandas is not installed since it is required for this test.
- test_structured_dtypes_select was failing because it relies on the sql simplifier to resolve type information for queries that extract nested data from structured types. I've added a skip so that the test does not run when the simplifier is enabled. It may be worthwhile show in that test that Variants are expected when the simplifier is disabled.
> Fix structured types related test failures.

- tox.ini
Fixes SNOW-1374343
CI  times for this PR:
- [GCP](https://github.com/snowflakedb/snowpark-python/actions/runs/9025175335/job/24800489292?pr=1553): 25 minutes
- [AWS](https://github.com/snowflakedb/snowpark-python/actions/runs/9025175335/job/24800489826?pr=1553): 20 minutes
- [Azure](https://github.com/snowflakedb/snowpark-python/actions/runs/9025175335/job/24800490421?pr=1553): 22 minutes
These are a bit better than the usual times, but it's hard to tell because CI time is so variable (probably dependent on how many different jobs are running at the same time-- see SNOW-1347210). …
> SNOW-1374343: Use 48 pytest processes.

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/test_qcut.py
Fixes SNOW-1375037
Rewrite parts of qcut implementation to avoid joins completely. This results in significant performance improvement of qcut.
With this change overall runtime of benchmark notebook reduced from 297 seconds to 66 seconds and number of sql queries reduced from 521 to 91.
> SNOW-1375037: Remove joins from qcut implementation

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/groupby/test_groupby_transform.py
Fixes SNOW-1361200
- The bug here is caused due to the implementation of `create_udtf_for_groupby_apply`. Groupby apply/transform use this method to create a UDTF. 
- When multiple groupby apply/transform operations are performed on the same DataFrame, this method is called multiple times. However, it uses a fixed name for the column labels used to create the OrderedDataFrame used with the UDTF. This is what causes the issue - "ambiguous column name 'ROW_POSITION_WITHIN_GROUP'".
- "'ROW_POSITION_WITHIN_GROUP'" is a column label created and used by `create_udtf_for_groupby_apply`.
- …
> SNOW-1361200 Fix ambiguous row label error

- src/snowflake/snowpark/_internal/analyzer/cte_utils.py
- tests/integ/test_cte.py
- tests/unit/test_cte.py
Fixes SNOW-1413958
Due to https://snowflakecomputing.atlassian.net/browse/SNOW-1375062, we need to skip optimizing dynamic pivot query plan using CTE. Specifically, any subquery under dynamic pivot plan will not be converted to a CTE.
> SNOW-1413958: Skip optimizing dynamic pivot query plan using CTE 

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/telemetry.py
- tests/integ/modin/test_telemetry.py
- tests/unit/modin/test_type_annotations.py
Fixes SNOW-1374293
Carry property method type hints through the `TelemetryMeta` class.
Prior this commit, we would lose the type hints [here](https://github.com/snowflakedb/snowpark-python/blob/cc3d2898d4170cc68ca8d59a7872e9c2b1ba7929/src/snowflake/snowpark/modin/plugin/_internal/telemetry.py#L486-L491) because the type hints come from `fget`,`fset`, and `fdel` rather than from `__get__`, `__set__`, or `__delete__` respectively.
Also, the annotations [here](https://github.com/snowflakedb/snowpark-python/blob/cc3d2898d4170cc68ca8d59a7872e9c2b1ba7929/src/snowflake/snowpark/modin/plugin/_ …
> SNOW-1374293: Fix property method typing.

- src/snowflake/snowpark/modin/pandas/base.py
SNOW-1372258 - Print warning when calling __array__()
3rd party libraries call __array__() frequently to get a numpy array for local processing. We do not warn users of this so certain types of pandas code (iterating through columns to print) may take a very long time. Here we make calls to __array__ print a single warning, and we point users at the to_pandas or to_numpy API calls.
> SNOW-1372258 - Print warning when calling __array__()

- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/modin/plugin/_internal/telemetry.py
- tests/integ/modin/test_telemetry.py
- tests/unit/modin/test_telemetry.py
Fixes SNOW-1375119
This PR enables tracking of error messages for NotImplementedError only in Snowpark pandas telemetry.
> SNOW-1375119: Track error messages for `NotImplementedError` in Snowpark pandas telemetry

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/test_column.py
snowflake implicitly support 0-based start expr in function substr/substring (it's not documented in the doc: https://docs.snowflake.com/en/sql-reference/functions/substr)
in this PR we add support to 0-based start expr to align the behavior
> SNOW-1428349: local testing align with snowflake behavior on substr 0-based start_expr

- src/snowflake/snowpark/modin/pandas/general.py
- src/snowflake/snowpark/modin/plugin/docstrings/base.py
- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
Fixes SNOW-1421247
Removes doctests that previously defaulted to pandas, but now fail.
These can be identified by their presence in the modin dependency PR in our old repo (https://github.com/snowflakedb/snowpandas/pull/995/files), or grepping for SNOW-1336091 and doctest: +SKIP.
I did not touch the docstrings for `apply` and `transform` even though they mostly fail. Most of these examples previously defaulted to pandas, so removing them would remove most of the docstring.
> SNOW-1421247: Remove skipped doctests that previously defaulted to pandas

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py
- src/snowflake/snowpark/modin/plugin/docstrings/base.py
- tests/integ/modin/frame/test_drop_duplicates.py
- tests/integ/modin/frame/test_duplicated.py
- tests/integ/modin/frame/test_getitem.py
- tests/integ/modin/frame/test_loc.py
Fixes SNOW-1041878
Throw `KeyError` when user passes in missing column labels to `__getitem__` and `loc`
> SNOW-1041878: Throw KeyError on missing columns in getitem

- src/snowflake/snowpark/modin/plugin/docstrings/groupby.py
Fixes SNOW-1421735
This PR cleans up docstrings for DataFrameGroupBy and SeriesGroupBy.
Two followup tickets:
- different behavior in groupby.groups https://snowflakecomputing.atlassian.net/browse/SNOW-1432458
- update groupby.shift signature https://snowflakecomputing.atlassian.net/browse/SNOW-1432455
> SNOW-1421735: Clean up groupby docstrings

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/test_df_analytics.py
Fixes SNOW-1370305
Local testing did not have a converter mapped for FloatType which led to this test failures. I've added FloatType to the double converter which matches the behavior in live mode.
> SNOW-1370305: [Local Testing] fix test_compute_lead test failure

- docs/source/conf.py
- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/groupby.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
Fixes SNOW-1435489
This PR adds rst link tags in GroupBy docstrings so they properly link. DataFrame and Series now automatically link to the correct class, so this PR also removes unnecessary "Snowpark pandas DataFrame" qualifications from return types for consistency, and adds links to native pandas docs for `to_pandas` methods that return a native pandas frame.
> SNOW-1435489 Add class links in groupby return annotations

- tests/integ/modin/groupby/test_groupby_apply.py
Fixes SNOW-1434962
[`sort_values`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html) by default is not stable since it uses `kind="quicksort"`. Use a stable `nlargest` call with the default of `keep="first"` so that when multiple rows have the same price, we get them in the order that they appear in the input dataframe.
Unfortunately I couldn't reproduce the flake locally by running the test repeatedly unless I manually changed the order of the input dataframe before the `sort_values` to simulate instability of `sort_values`. However, I think now we …
> SNOW-1434962: Make groupby.apply sort result deterministic.

- docs/source/_templates/autosummary/base.rst
- docs/source/_templates/autosummary/class.rst
- docs/source/conf.py
Fixes SNOW-1359009
Change classpaths for pandas general APIs to be `modin.pandas.<>` instead of `snowflake.snowpark.modin.pandas.[general].<>`.
> SNOW-1359009 Change classpaths in pandas general APIs to be `modin.pandas.<>`

- src/snowflake/snowpark/modin/plugin/_internal/resample_utils.py
- tests/integ/modin/resample/test_resample.py
- tests/integ/modin/resample/test_resample_negative.py
Fixes SNOW-1437846
Enforces all datetimes to be converted to TIMESTAMP_NTZ as timestamps with timezones are not supported in Snowpark pandas resample
> SNOW-1437846: Enforce to_timestamp_ntz in resample

- tests/integ/scala/test_function_suite.py
- tests/integ/test_df_to_pandas.py
- tests/integ/test_function.py
fix test failure caused by:
1). reg env variable optimization leading to pandas dtype diff
in reg env, there is a parameter turned on which optimized data type according to the value.
the parameter is not turned on in production.
sql team is investigating, we skip the test to run in sproc
2). reg env timestamp output format different, by default sp in reg env outputs time with tz info, fix the test by explicitly using timestsamp ntz
3). to_timestamp applied to integer with variant type depends on server timezone which we can't control. the reg server uses tz UTC
> SNOW-1411701: fix regression test failure

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
Fixes SNOW-1019448
Previously, the error message assumes that `table_name` is a tuple of length 3, with schema and database name specified, this is not true. `db_schema_table` could be length of 1 or 2 as well. This PR fixes this issue by using the default database and schema associated with the session when needed.
> SNOW-1019448 Fix bad error message when referencing missing table in Local Testing

- CHANGELOG.md
- src/snowflake/snowpark/modin/pandas/base.py
- src/snowflake/snowpark/modin/pandas/dataframe.py
- src/snowflake/snowpark/modin/pandas/groupby.py
- src/snowflake/snowpark/modin/pandas/series.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/docstrings/base.py
- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/groupby.py
- tests/integ/modin/frame/test_shift.py
- tests/integ/modin/groupby/test_groupby_negative.py
- tests/integ/modin/series/test_shift.py
Fixes SNOW-1432455
Changes the `periods` parameter to `int | Sequence[int]` rather than `int`, and adds the `suffix` parameter. If `periods` is a sequence or `suffix` is specified, we now raise NotImplementedError.
> SNOW-1432455: Update shift signature to match pandas 2.x

- tests/integ/scala/test_function_suite.py
Fixes SNOW-1374081
After messing around with some sql queries I think the issue with this test is that the order of the window partitions is ambiguous, but seemingly stable. With some of the parameters changed the groups will sometimes be in different orders so I don't think local testing has anything to match here. I've added an order_by to remove the ambiguous ordering.
> SNOW-1374081: [Local Testing] fix test_row_number

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_dataframe_join_suite.py
Fixes SNOW-978584
The current implementation of DataFrame.drop relies on query generation being eager (i.e. `plan.expr_to_alias` is always populated) and checks if the dropped columns are present in the child query results. However, Local Testing does not execute the plan until the dataframe is evaluated, meaning the child query has not been executed when DataFrame.drop is called, so expr_to_alias (the dictionary used to keep track of expression id to column name mappings, enables usage like df.select(ancestor["col1"])) is empty. As a result, DataFrame.drop will ignore ancestor …
> SNOW-978584 Populate expr_to_alias map in DataFrame.drop by executing the plan

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_df_analytics.py
Fixes SNOW-1370276 and [SNOW-1370165](https://snowflakecomputing.atlassian.net/browse/SNOW-1370165)
This PR tries to enable 3 tests:
- `test_df_stat_sampleBy` is enabled after refactoring the test to ignore order. There's no bug to fix.
-   `test_compute_lag` is enabled after fixing the minor issue in `date_part`'s implementation. 
-  `test_time_series_agg_invalid_inputs` had multiple issues, first being `date_part`, then it requires `Column.cast` to support casting to `Boolean`, I added all target types we support of now. However it is still blocked by an error from computing …
> SNOW-1370276 Fix minor bug in date_part implementation and add more target types support for Column.cast

- src/snowflake/snowpark/mock/_plan.py
- src/snowflake/snowpark/mock/_udf_utils.py
- tests/integ/scala/test_udf_suite.py
- tests/integ/test_udf.py
Fixes SNOW-1370035 and SNOW-1374027
This PR improves local testing udf experience in a few ways when it comes to variant data.
- Variant data can contain just about anything, but often when passed to a udf it is coerced to certain types. I've added a mechanism to the udf call logic that coerces various types to the expected types.
- Variant Nones are passed to udfs as SqlNullWrapper objects. These are not currently defined or used in our repo so I've added a coercion for them in this PR as well.
- I've merged the logic for calculating udf inputs with the logic that validates input …
> SNOW-1370035: [Local Testing] Improve consistency of udf input/output

- CHANGELOG.md
- src/snowflake/snowpark/mock/_connection.py
- tests/integ/test_dataframe.py
Previously, the expression `table.columns != target_table.columns` will raise a pandas exception when table and target_table has different schema, this PR rewrites this comparison to (1) not compare the column names but compare the length instead and (2) allow truncating a table when incoming data are only missing columns that are nullable.
> SNOW-1369973 Fix DataFrameWriter.save_as_table behavior when appending/truncating with mismatching columns

- src/snowflake/snowpark/modin/pandas/base.py
- src/snowflake/snowpark/modin/plugin/docstrings/base.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_overrides.py
- src/snowflake/snowpark/modin/plugin/extensions/series_overrides.py
Fixes SNOW-1264688
`infer_objects` and `nunique` were overridden as vestigial remnants of the SnowparkPandasDataFrame and SnowparkPandasSeries classes. Now that we can use the docs extension modules, there is no longer any reason to keep these overrides around.
After this PR, only 2 remaining DF/Series methods are overridden:
- `memory_usage` can also be removed pretty easily; since it has a separate ticket filed I'll remove it in a separate PR.
- `Series.isin` does some extra argument processing that I'd prefer not to touch in case something breaks.
> SNOW-1264688: Remove overrides of infer_object/nunique

- src/snowflake/snowpark/_internal/ast.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/table.py
- tests/thin-client/select_outputs.py
- tests/thin-client/steel-thread.py
- `Column`s are created with no reference to the parent `Dataframe` in the current Snowpark API
- Following this pattern when generating the AST (invoking `proto` IR entity constructors directly)
- `ast` parameter added to `Column` constructor to enable `Column` methods to create and push-down ASTs
- `ast` property added to `Column` class to enable backwards compatibility with `col._expression: Expression` using `SpColumnSqlExpr` as a backup
Current test case output AST
```
client_version {
major: 42
}
client_language {
python_language {
version {
major: 3
minor: 8
}
}
}
body {
assign {
uid: 1
var_id {
bitfield1: 1
}
expr {
sp_table {
table: "test_table"
}
}
}
}
body {
assign {
uid: 2
var_id {
bitfield1: 2
}
expr {
sp_dataframe_filter {
df {
sp_dataframe_ref {
id {
bitfield1: 1
}
}
} …
```
> Basic select API working

- docs/source/index.rst
DOC: fix maxdepth to 2
Fix the doc regression introduced in 1.17. Once the `maxdepth` is 2, then we can see the left bar with correct levels:
> DOC: fix maxdepth to 2

- tests/integ/modin/strings/test_strings.py
The OSS modin version of StringMethods provides some frontend validation that we skipped for the unimplemented `Series.str.index`/`rindex` methods. This PR changes the argument to the correct type.
> SNOW-1445536: Fix Jenkins failure in test_strings.py::test_index_raises_not_implemented_error

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/test_dataframe.py
there is a bug in mock to_date implementation that when the input is empty, the function will return a TableEmulator instead of a ColumnEmulator.
> SNOW-1455291: fix dataframe creation of empty data with DateType

- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- tests/integ/modin/io/test_read_snowflake.py
Fixes SNOW-1445337
Log warning when data is materialized during snowpark pandas dataframe creation
> SNOW-1445337: Log warning when data is materialized during dataframe creation

- src/snowflake/snowpark/modin/plugin/docstrings/base.py
- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/groupby.py
- src/snowflake/snowpark/modin/plugin/docstrings/resample.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
- src/snowflake/snowpark/modin/plugin/docstrings/series_utils.py
- src/snowflake/snowpark/modin/plugin/io/snow_io.py
- tox.ini
CI: ignore some not implemented methods code coverage
> CI: ignore some not implemented methods code coverage

- .github/labeler.yml
> Fix labeler to use the correct label for Local Testing

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/mock/test_functions.py
Fixes SNOW-1348700 
Previously the implementation of mock_to_char relies on the incoming column has index of [0,1,...,n-1], this is not always true and causes the code raise `IndexError`, this PR fixes that and adds a test for this specific scenario.
> SNOW-1348700 Fix to_char's implementation when incoming column has inconsecutive row index

- tests/integ/conftest.py
- tests/integ/modin/binary/test_binary_op.py
- tests/integ/modin/conftest.py
- tests/integ/modin/frame/test_iloc.py
- tests/integ/modin/frame/test_itertuples.py
- tests/integ/modin/frame/test_loc.py
- tests/integ/modin/frame/test_transpose.py
- tests/integ/modin/groupby/test_groupby_idxmax_idxmin.py
- tests/integ/modin/groupby/test_quantile.py
- tests/integ/modin/series/test_rename.py
- tests/integ/modin/strings/test_cat.py
- tests/integ/modin/strings/test_extract.py
- tests/integ/modin/strings/test_get_dummies.py
- tests/integ/modin/strings/test_strings.py
- tests/integ/modin/test_session.py
- tests/utils.py
Those running_on_* methods was in `tests/integ/conftest.py` which requires `tests.parameters` available. It blocks us to use them in sproc tests since there is no `tests.parameters` there.
> SNOW-1284606 Move running_on_* to tests/utils.py

- tests/integ/modin/strings/test_strings.py
Fixes SNOW-1467815
Fix Jenkins runner regression related to test_lstrip_rs trip in test_strings.
> SNOW-1467815: Fix Jenkins runner regression related to test_lstrip_rstrip in test_strings

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_describe.py
Fixes SNOW-1019479
This PR fixes a bug with `df.describe()` if `df` had columns with the same name but different dtypes. Since the method computes separate query compilers for the statistics on `object`, numeric, and `datetime` columns and concats them all together, if two columns shared a label but had different dtypes, it would try to concat them together and either error or produce an incorrect result. This PR works around this by relabeling the columns with ordinal values before performing any aggregations, and restoring the labels after concatenation.
> SNOW-1019479: Fix describe with duplicate column names

- src/snowflake/snowpark/_internal/ast.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/session.py
- tests/ast/run-unparser.sh
- tests/ast/test_ast_driver.py
As of this diff, we continue to pursue Phase 0 and Phase 1 client on top of the same codebase to minimize development overhead. `ServerConnection.phase1_enabled()` can be used to branch based on the phase.
Phase 0 is the default and Phase 1 is enabled via the env var `SNOWPARK_PHASE_1=1`.
This diff makes Phase 0 behave as it's going to appear in the actual design. Phase 1 is still a total hack which issues a parallel request just to test the TCM. We will need to make the Phase 1 code path more real soon as well – in order to enable a proper end-to-end test.
> [feature branch] Phase 0 client

- src/snowflake/snowpark/modin/conftest.py
- src/snowflake/snowpark/modin/plugin/__init__.py
- tests/unit/modin/test_docstrings.py
Fixes SNOW-1461192
SNOW-1445536 removed our copies of the `StringMethods` and `DatetimeProperties` classes in favor of their upstream modin versions. After this PR, doctests (run via `pytest src/snowflake/snowpark/modin/plugin/docstrings/series_utils.py`) still passed, but the `__doc__` attributes of these classes' methods were not correctly updated since we did not use `modin.config.DocModule` (only `snowflake.snowpark.modin.config.DocModule`).
This PR sets modin's `DocModule` attribute so the docstrings are appropriately overridden, and changes some module initialization order to …
> SNOW-1461192: Fix StringMethods and DatetimeProperties docs

- src/snowflake/snowpark/_internal/telemetry.py
- tests/integ/test_telemetry.py
Fixes SNOW-1457758
Short term fix to not trigger duplicate queries when using `session.sql()` to run describe, truncate, copy queries. When collecting telemetry for finding the number of duplicate plan subtrees within the query plan, we end up calling `SelectSQL.to_subqueryable` for the `SelectSQL` plan node generated by `session.sql`. During this step, we call `analyze_attributes` for the given query twice - once during initializing a new subqueryable and second when initializing column states. When these describe queries are run from within a stored sproc, they are being detected as …
> SNOW-1457758: Disable telemetry triggering extra describe queries

- setup.py
Modifies `setup.py` to use the latest HEAD of https://github.com/snowflakedb/snowflake-connector-python/tree/server-side-snowpark which includes connector changes (most notable adding the `_dataframe_ast` field for phase 0).
To update your local dev environment run
```
pip uninstall snowflake-connector-python -y
python -m pip install --no-cache -e ".[development,pandas]"
```
Running the pip command should show `git clone` in the logs.
> [ThinClient] Use connector with server-side-snowpark changes in setup.py

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
- tests/mock/test_column.py
Fixes SNOW-1348700 
This PR fixes the bugs in Local Testing's handling of CaseExpr, IsNull, IsNotNull and Like expressions where the previous implementation (1) ignores indexing of incoming column and (2) assume input always has an index starting at 0
> SNOW-1348700 Fix index issues in handling of CaseExpr, IsNull, IsNotNull and Like expressions

- .pre-commit-config.yaml
- setup.py
- src/snowflake/snowpark/mock/_pandas_util.py
- src/snowflake/snowpark/modin/plugin/_internal/type_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/unpivot_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
- src/snowflake/snowpark/modin/plugin/docstrings/series_utils.py
- tests/integ/modin/binary/test_binary_op.py
- tests/integ/modin/frame/test_melt.py
- tests/integ/modin/frame/test_merge.py
- tests/integ/modin/frame/test_replace.py
- tests/integ/modin/frame/test_skew.py
- tests/integ/modin/series/test_astype.py
- tests/integ/modin/series/test_dropna.py
- tests/integ/modin/series/test_replace.py
- tests/integ/modin/series/test_str_accessor.py
- tests/integ/modin/utils.py
- tests/integ/test_udf.py
Fixes SNOW-1487311
This PR fixes issues that are raised from the lint environment resolving numpy to 2.0.0. This does not mean Snowpark pandas supports numpy 2.0.0 (though Snowpark Python + local testing should); this PR just makes non-impactful code changes to pass lint and make code consistent.
Notably, numpy 2.0.0 removes `np.float_` in favor of `np.float64`, and `np.NaN` in favor of `np.nan`.
> SNOW-1487311: Fix test failures and lint issues with numpy 2

- .github/workflows/daily_modin_precommit.yml
- tests/integ/modin/frame/test_quantile.py
Fixes SNOW-1435354
Add CTE optimization tests to snowpark pandas daily precommit tests. A successful run: https://github.com/snowflakedb/snowpark-python/actions/runs/9406047620
> SNOW-1435354: Add CTE optimization tests to snowpark pandas daily precommit tests

- CHANGELOG.md
- src/snowflake/snowpark/_internal/server_connection.py
- tests/integ/modin/series/test_unique.py
> SNOW-1356685: Fix precision loss bug in `DataFrame/Series` with `dtype=np.uint64`

- tests/unit/test_generated_udf_lock.py
In this PR I've done a few things to improve `test_lock_function`.
- Removed the InvokedFlag class and replaced with similar functionality of the threading.Event object.
- Added a unique lock for incrementing load_model_called so that `lock_function_once` lock and the increment lock don't unintentionally block each other.
- Increased the sleep time. Windows is a little slower to create and manage threads so I think increasing the sleep time will better ensure that multiple invocations of the udf run concurrently.
> Fix test_lock_function failures on windows

- .pre-commit-config.yaml
Exclude protobuf file in precommit (flake8), as protobuf does not adhere to good coding standards and a protobuf update will consequently fail precommit.
> [SERVER-SIDE CI] Exclude protobuf file in flake8 precommit

- tests/integ/modin/frame/test_nlargest_nsmallest.py
- tests/integ/modin/series/test_nlargest_nsmallest.py
Fixes SNOW-1502286
native pandas output for nlargest when n > number of rows in df/series is not consistent. 
This test `test_nlargest_nsmallest_large_n` is failing in daily CI but passes locally. This PR disables the tests to unblock CI and other PRs.
> SNOW-1502286: Disable test test_nlargest_nsmallest_large_n

- tests/ast/update-unparser.sh
Fixes issue of bazel not producing a fat jar in `scala_binary` by calling both the bazel build and the sbt build. This is a temporary workaround till we fix in bazel the rules to emit a fat jar.
> [SERVER-SIDE CI] Temporary fix for unparser fat jar

- src/snowflake/snowpark/_internal/ast_utils.py
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/table.py
- tests/ast/test_ast_driver.py
- tests/ast/update-unparser.sh
- Adding src position information to Column AST building APIs
- Adding a flag in `ast_utils.py` to signal whether to fail loudly on missing AST fields
- Generate useful error message in Column APIs if any Snowpark API generates a column and does not log its AST
> Fill colum expr src positions, raise explicit errors on missing AST

- src/snowflake/snowpark/modin/plugin/_internal/transpose_utils.py
SNOW-1504601 Use any_value with filter to ensure determinism during transpose
SNOW-1504601 Use any_value with filter to ensure determinism during transpose
The transpose operation internally used any_value prior to a pivot, so the output would have a column based on these valuse, however, it later dropped them, however, because pivot internally executes a subquery it's possible any_value can return different results.  We found in some tests there was a flakiness attributed to this nondeterminism.  To address this the code will use a min so it is deterministic on a given data set.
> SNOW-1504601 Use any_value with filter to ensure determinism during transpose

- .github/workflows/daily_modin_precommit.yml
- src/snowflake/snowpark/modin/plugin/__init__.py
See failure: https://github.com/snowflakedb/snowpark-python/actions/runs/9676725704
The job that checks that importing Snowpark pandas on python 3.8 broke with https://github.com/snowflakedb/snowpark-python/commit/0e2ac6b2dd1bfaae7989835840cd87aece0f6dce because isort floated an `import modin` to the top of `plugin/__init__.py` before version checks occurred; the reference to the imported class has been moved to the bottom of the file after the checks.
The job checking our numpy version compatibility was failing because `parameters.py` was not decrypted.
> Fix Snowpark pandas daily tests

- setup.py
The `server-side-snowpark` branch no longer exists in `snowflakedb/snowflake-connector-python` after https://github.com/snowflakedb/snowflake-connector-python/pull/1964
Refer to `snowflakedb/snowflake-connector-python@main` instead.
Prerequisite for SNOW-1491327.
Since the Snowflake Python connector does not support the dataframe AST functionality in any released version yet, `setup.py` in `snowflakedb/snowpark-python@server-side-snowpark` refers to the dependency by git repository URL and commit.
Fix the pointer to refer to the `main` branch instead of the topic branch that no longer …
> Fix reference to snowflakedb/snowflake-connector-python@server-side-snowpark

- mypy.ini
This PR sets `ignore_missing_imports = True` for `modin` in mypy configuration, as we already do for `pandas` and `snowflake`. This is needed to suppress `error: Cannot find implementation or library stub for module named "modin.pandas.base"  [import]`.
This error isn't majorly affecting the codebase yet, but I'm making the change now as an independent PR to make sure snowpark-python-api-reviewers doesn't get pinged on the larger followup PRs that basically only touch Snowpark pandas code.
> Ignore modin import paths in mypy

- src/snowflake/snowpark/_internal/ast_utils.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe.py
Ensures all tests pass on main branch
> Only raise explicit errors for Snowpark non-internal API calls

- tests/integ/scala/test_datatype_suite.py
- tests/integ/test_stored_procedure.py
- tests/utils.py
Fixes SNOW-1437699
This PR refactors the way tests detect if structured types are enabled by using the actual account name rather than assuming all accounts in AWS are sfctest0. It also adds a test that shows that cast statements work with structured types.
> SNOW-1437699: Add support for explicit casts to Structured Types

- src/snowflake/snowpark/_internal/analyzer/cte_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/integ/test_cte.py
Fixes SNOW-1492846
Before this change, we call to_subqueryable() in search algorithm of CTE to convert non-select SQL to select SQL, and use it to encode ID. But it is unnecessary and we can always use original SQL here.
> SNOW-1492846: Get rid of converting non-select SQL to select SQL in `SelectSQL` when finding duplicate subtrees

- src/snowflake/snowpark/_internal/telemetry.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/integ/test_telemetry.py
Fixes SNOW-1474971
The telemetry for these two stats were previously disabled due to a bug in CTE search algorithm, now we can re-enable it after the fix.
> SNOW-1474971: Re-enable telemetry for collecting plan heights and number of duplicate nodes

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/series/test_value_counts.py
Fixes SNOW-1527038
`Series.value_counts` is a method that counts the occurrence of each value in the given Series. There are several parameters to it, the only one relevant here is `sort`.
When `sort=True`, the result is supposed to display the value counts in descending order. When two values have the same count, maintain the ordering from the original Series. For instance, in the example below 3 appears before 2 and therefore the result is ordered as such.
```py
>>> pd.Series([1, 3, 1, 1, 1, 3, 1, 1, 1, 2, 2, 2, 3]).value_counts()
1    7
3    3
2    3
Name: count, dtype: int64
``` …
> SNOW-1527038 Fix value_counts bug where the index is not sorted properly

- CHANGELOG.md
- src/snowflake/snowpark/_internal/error_message.py
Fixes SNOW-1300453
Improved error message for `write_pandas` when target table does not exist and the function is called with `auto_create_table=False`.
> SNOW-1300453: Improve error message for write_pandas auto_create_table=False

- src/snowflake/snowpark/mock/_telemetry.py
- tests/mock/test_oob_telemetry.py
Fixes SNOW-1518381
to coordinate the change coming from python connector https://github.com/snowflakedb/snowflake-connector-python/pull/1991, we overwrite the enable/disable methods to turn oob telemetry on for local testing
> SNOW-1518381: enabling oob telemetry for local testing

- src/snowflake/snowpark/modin/plugin/docstrings/series.py
- tests/integ/modin/series/test_value_counts.py
Fixes SNOW-1527038
This PR is here since there were some issues with running the `series/test_value_counts.py::test_series_value_counts` test. When run locally, the Snowpark pandas output matches native pandas. However, when run on Jenkins, the output differs.
Jenkins runs to refer to: prod runs 604, 605, and 606 (this run has clearer console output so that you can see the difference).
On closer inspection, the Snowpark pandas output is deterministic - native pandas' output is the one that differed on both platforms. 
There are two parameters to `Series.value_counts` that control the …
> SNOW-1527038 Fix Jenkins failure, explain `Series.value_counts` behavior 

- CHANGELOG.md
- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
- tests/unit/test_session.py
Fixes [SIT-1383](https://snowflakecomputing.atlassian.net/browse/SIT-1383)
Added a new optional parameter to the `Session.SessionBuilder.app_name` function that allows to set the app name in the `Session.query_tag` in JSON format.
[SIT-1383]: https://snowflakecomputing.atlassian.net/browse/SIT-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SIT-1383: Added support to set the app_name to the session query_tag in JSON format

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/perf/perf_runner.py
SNOW-1533733
With https://docs.google.com/document/d/1DKFgGOHSTuI8gvHOaU2Xj_wzfFvMSPuKKtLgDxfvNeA/edit?pli=1, we are separating queries used for final execution and queries for intermediate process, and the queries for final execution will have optimizations applied.
In this pr, we add a new property execution_queries for the SnowflakePlan, which is used to get the final query will be sent over to server for execution, the returned exuecution_queries will have optimization applied if the optimization is enabeld.
> [SNOW-1533733] Add execution_queries property for SnowflakePlan to get the final query will be sent over to server for execution

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/mock/_analyzer.py
- tests/integ/test_cte.py
Fixes SNOW-1545149
Theoretically, all snowflake plan should be associated with a source logical plan, however, the SnowflakePlan resolved for table/view create node doesn't have any source plan associated with it. Furthermore, the newly added compilation stage performs optimization on the logical plan level, missing source logical plan can miss some optimization opportunity.
In this pr, we ensures the original source plan is attached for the create table/view nodes.
> [SNOW-1545149] Ensure source plan is attached for Table and View create SnowflakePlan

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/expression.py
- tests/integ/test_simplifier_suite.py
Fixes SNOW-1539454
When the column is `df['*']`, `expressions` contains Attributes from all columns. When the column is `col('*')` or just '*' string, `expressions` is empty, but its dependent columns should be all columns too, so it won't be flattened in sql simplifier
> SNOW-1539454: Fix Star expression column dependency 

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/test_deepcopy.py
SNOW-1541087
The SnowflakePlan and Selectable has analyzer and session associated with it, which can not be copied today. In order to enable the deepcopy of those node, we overwrites the __deepcopy__ method to to copy the reference of the analyzer and session.
> [SNOW-1541087] Allow deep copy of SnowflakePlan and Selectable

- tests/integ/scala/test_snowflake_plan_suite.py
SNOW-1551115
test_execution_queries_and_queries is failing when sql simplifier is disabled because the cte optimization actually didn't kick in. update test to verify the result based on the sql simplifier configuration
> [SNOW-1551115] Fix test failure for test_execution_queries_and_queries when sql_simplifier is disabled

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_drop_duplicates.py
- tests/integ/modin/series/test_drop_duplicates.py
Fixes SNOW-1549173
Calling drop_duplicates on a Series or DataFrame where row_postion_column is not cached results in an error similar to following: `AssertionError: dataframe column="__row_position_gvdf__" not found in snowpark dataframe schema`. This happens due to incorrect reference to row_position_column from old frame. This PR fixes the issues by using the row position from updated frame.
> SNOW-1549173: Fix AssertionError in  Series/DataFrame drop_duplicates

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/test_deepcopy.py
The entity_name of SelectableEntity has been replaced with entity: SnowflakeTable. Update the test and deep copy to do the correct copy
> Fix test failure for test_deepcopy.py/test_selectentity 

- docs/source/_templates/autosummary/modin_accessor.rst
- docs/source/conf.py
- docs/source/modin/dataframe.rst
- docs/source/modin/series.rst
- src/snowflake/snowpark/modin/pandas/io.py
Fixes SNOW-1545615
This PR adds extra customization to allow sphinx documentation to use `modin.pandas` as the defined module rather than `snowflake.snowpark.modin.pandas`, in anticipation of the removal of the vendored copies of our DataFrame and Series classes.
Currently, our rst files only reference `modin.pandas` for the `StringMethods` and `DatetimeProperties` classes, which are taken from upstream modin. The other `currentmodule `directives referencing `snowflake.snowpark.modin.pandas` would indirectly trigger an import of `snowflake.snowpark.modin.plugin`, which implicitly …
> SNOW-1545615: Change snowflake.snowpark.modin.pandas to modin.pandas in DF/Series doc generation

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table.py
Fixes SNOW-0000000
Stylistic change - prefer direct logic instead of inverted logic.
Use `emit_ast` (default = `True`) everywhere instead of `suppress_ast` (default = `False`).
To get ASTs out of public APIs, do nothing. To prevent public APIs from emitting ASTs, provide `emit_ast = False`.
Name the argument `_emit_ast` on public APIs and `emit_ast` on internal APIs.
> (Readability) Replace all instances of suppress_ast with emit_ast to avoid negated logic

- src/snowflake/snowpark/modin/pandas/base.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-1552465
When a Snowpark pandas aggregation returns a Series, we often use `transpose_single_row` in the query compiler to force the result to conform to the expected dimensions. After this operation, the column name is the string "NULL", which we fix using an `isinstance(result, Series)` check that guards `result.name = None`. This check does not exist in modin, and for consistency with other methods that return a Series, the name setting operation should be performed within the query compiler.
This PR modifies the query compiler `agg` and `nunique` methods to set column …
> SNOW-1552465: Push `result.name = None` from frontend to QC

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_compare.py
- tests/integ/modin/index/test_equals.py
- tests/integ/modin/series/test_compare.py
Fixes SNOW-1478684
This bug is no longer reproducible. Possibly due to recent changes in Index.equals (https://snowflakecomputing.atlassian.net/browse/SNOW-1458148). This PR adds the new test as validation before closing the issue.
> SNOW-1478684: Remove index.equals workaround from compare

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_isin.py
- tests/integ/modin/series/test_isin.py
Fixes SNOW-864083
In Snowpark pandas series is always is represented as single column query compiler, we don't need to check if query compiler represent single row.
> SNOW-864083: Remove unnecessary count query from is_series_like

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes SNOW-1445227
Add INFER_SCHEMA_OPTIONS to DataFrameReader to allow passing additional options like `MAX_FILE_COUNT` and `MAX_RECORDS_PER_FILE` to [INFER_SCHEMA](https://docs.snowflake.com/en/sql-reference/functions/infer_schema) (invoked during semistructured data reading)
> Add INFER_SCHEMA_OPTIONS to DataFrameReader

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/extensions/index.py
- tests/integ/modin/index/test_index_methods.py
Fixes SNOW-1555397
Fix the result column name for `Index.to_frame` when `name` is not specified.
> SNOW-1555397 Fix index.to_frame()'s wrong result column name

- tests/integ/conftest.py
- tests/integ/scala/test_literal_suite.py
StringType no longer displays the length if the length is the max possible length.
See https://github.com/snowflakedb/snowpark-python/pull/1871
> Fix test_literal_suite

- CHANGELOG.md
- src/snowflake/snowpark/lineage.py
- tests/unit/test_lineage.py
Fixes SNOW-1552816 
Quoted Feature view names were not correctly split. This PR fixes that 
> SNOW-1552816 : Fix Session.lineage.trace API output for feature views

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/_internal/compiler/utils.py
- tests/unit/conftest.py
- tests/unit/test_replace_child.py
Fixes SNOW-1557229
This PR add method `repalce_child` to `LogicalPlan`, `SnowflakePlan` and `Selectable` classes to replace and old child node with a new one. This method is used when rewriting plan tree during optimization stages.
> SNOW-1557229: Add method to replace child for LogicalPlan and derivatives

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
This pr does the following small change that has no impact to users.
1) Update how TableUpdate, TableMerge and TableDelete  is handled in analyzer to use resolved children instead of the original one. This way it is consistent with how other nodes are handled in analyzer, and with the new compilation stage, the children may need to be re-resolved to get the final correct plan node.
2) update the _id to be a cached property, so that the id will not be updated once set.
> Update the analyzer to use a consistent way to get the resolved children

- CHANGELOG.md
- src/snowflake/snowpark/mock/_pandas_util.py
- tests/mock/test_pandas_util.py
Github Issue #1967 
Pandas prefers integer indexing with the `.iloc[]` accessor instead of implicitly assuming that an integer key is not a label but an index. It also issues a `FutureWarning` that in the future also integer keys will be treated as labels and not as integer index, which will most likely cause an error when this behavior is implemented.
The former code used either used `data[x]` instead of `data.iloc[x]` or (maybe unintentionally) `data.iloc[x][y]` instead of `data.iloc[x, y]` and caused this warning.
Not sure if an additional test is really …
> Fix Pandas FutureWarning about integer indexing

- tests/ast/test_ast_driver.py
Some of the column literal tests specify timestamps or datetime objects without a time zone. This is a good thing, as it's something client code can choose to do.
For these tests, the time zone defaults to the system time zone. This is a bad thing, as it renders the test sensitive to the current configured time zone.
Explicitly codify the time zone that is implicitly used in the existing expectation tests. Use any time zone *other* than `America/Los_Angeles` and `UTC`, to minimize the possibility that the test passes by chance.
Fixes SNOW-0000000
The `col_literals.test` creates …
> Always run tests in the America/New_York time zone

- tests/unit/test_generated_udf_lock.py
Even without the lock it's technically possible that all the thread line up such that load model is called once. I believe updating this condition will get rid of the flakiness of this test.
> Fix test_lock_function

- CHANGELOG.md
- src/snowflake/snowpark/column.py
- tests/integ/scala/test_column_suite.py
Fixes SNOW-1565789
Added a short-circuit to column.in_ so that it returns false when passed an empty set of items. I've also included more test cases that would have failed previously. I also changed the call order of parameters in the existing tests because check_answer expected actual then expected not the reverse. This was creating incorrect test failure messages.
> SNOW-1565789: Column.isin with empty list

- CHANGELOG.md
- src/snowflake/snowpark/modin/pandas/dataframe.py
- src/snowflake/snowpark/modin/plugin/_internal/frame.py
- src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/index.py
- tests/integ/modin/frame/test_axis.py
- tests/integ/modin/frame/test_getattr.py
- tests/integ/modin/frame/test_loc.py
- tests/integ/modin/frame/test_set_index.py
- tests/integ/modin/index/test_astype.py
- tests/integ/modin/index/test_equals.py
- tests/integ/modin/index/test_index_methods.py
- tests/integ/modin/test_from_pandas_to_pandas.py
- tests/integ/modin/utils.py
- tests/unit/modin/test_type_annotations.py
Fixes SNOW-1573193
- Snowpark pandas index is always lazy. 
- Removed `convert_to_lazy` from pd.Index constructor.
> SNOW-1573193: Remove local index from pd.Index

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
- tests/integ/scala/test_function_suite.py
Fixes SNOW-1569842
The typing for the fmt parameter of `to_date` is a little ambiguous in the [sql docs](https://docs.snowflake.com/en/sql-reference/functions/to_date#arguments). Spark and pandas both support string literals in their equivalent functions so I think it's worthwhile to add support for it here to.
> SNOW-1569842: Allow string literals in to_date fmt

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/test_cte.py
SNOW-1570952
Previously, we put an function for deduplication of queries to allow deduplication of same query text but different place_holder_id. However, when propagating those query, the same query comes from the same node, they will also have the same placeholder id, therefore, there is no need for this extra comparison function.
> [SNOW-1570952] Remove unnecessary workaround for query comparison

- src/snowflake/snowpark/_internal/compiler/query_generator.py
SNOW-1616087
In query generator https://github.com/snowflakedb/snowpark-python/blob/main/src/snowflake/snowpark/_internal/compiler/query_generator.py#L136, we made deep copy of the resolved child to avoid messing up with the original snowflake plan node, because there is an update of queries field, however, there is no need for a deep copy here, a shallow copy should be enough.
> [SNOW-1616087] Use copy instead of deepcopy during query generation

- CHANGELOG.md
- src/snowflake/snowpark/modin/pandas/base.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/datetime_index.py
- src/snowflake/snowpark/modin/plugin/extensions/index.py
- tests/integ/modin/index/test_datetime_index_methods.py
- tests/integ/modin/index/test_index_methods.py
Fixes SNOW-1618623
lazy index: 
- refactor qc as input for index constructor and make it consistent with other init methos like dataframe and series.
- raise ValueError for `pd.Index(df)`
> SNOW-1618623 lazy index: refactor qc as input for index constructor

- src/snowflake/snowpark/modin/pandas/base.py
- src/snowflake/snowpark/modin/plugin/_internal/aggregation_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-1615695
Snowpark pandas implements `df.any/all(axis=0)` via the BOOLAND_AGG and BOOLOR_AGG SQL functions. These functions return a single row of NULL if there are no elements, while pandas produces a vacuous True/False value. In the fixes for SNOW-1458141, these cases are handled in the frontend, but since the frontend changes don't make sense for other modin backends, they should be pushed down to the query compiler or lower.
This PR adds an IFNULL statement to wrap the result of BOOLAND_AGG/BOOLOR_AGG to handle the empty-row case without any additional queries. This …
> SNOW-1615695: Push empty all/any processing down to query compiler

- tests/integ/test_session.py
The current test is written in a way to test the default server parameter behavior, which might fail during server parameter update. 
Update the test with explicit parameter configuration, so that it could be more stable during feature value update
> Update test_eliminate_numeric_sql_value_cast_optimization_enabled_on_session to be invariant of the server parameter change

- tests/integ/test_udtf.py
Skip optional args test in sp precommit environment. The same test was is tested in merge gate and in pre-prod and it works correctly. Created SNOW-1618722 to track and fix sp issue.
> Skip optional args udtf test in sp

- CHANGELOG.md
- src/snowflake/snowpark/modin/pandas/general.py
- src/snowflake/snowpark/modin/pandas/series.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/docstrings/series_utils.py
- src/snowflake/snowpark/modin/plugin/extensions/index.py
- tests/integ/modin/frame/test_axis.py
- tests/integ/modin/frame/test_drop_duplicates.py
- tests/integ/modin/frame/test_duplicated.py
- tests/integ/modin/frame/test_getitem.py
- tests/integ/modin/frame/test_loc.py
- tests/integ/modin/frame/test_nlargest_nsmallest.py
- tests/integ/modin/frame/test_set_index.py
- tests/integ/modin/series/test_axis.py
- tests/integ/modin/series/test_getitem.py
- tests/integ/modin/series/test_loc.py
- tests/integ/modin/series/test_setitem.py
- tests/integ/modin/test_concat.py
- tests/integ/modin/test_telemetry.py
- tests/integ/modin/tools/test_date_range.py
- tests/integ/modin/tools/test_to_datetime.py
- tests/integ/modin/utils.py
Fixes SNOW-1486910
Return DatetimeIndex from pd.to_datetime and pd.date_range methods.
> SNOW-1486910: Return DatetimeIndex from to_datetime and date_range

- src/snowflake/snowpark/modin/plugin/docstrings/series_utils.py
We are preparing to rollout optimization for eliminating unnecessary cast for numeric values PYTHON_SNOWPARK_ELIMINATE_NUMERIC_SQL_VALUE_CAST_ENABLED.
After turning the flag on for our testing account, the following doctest start failing due to type difference
1. snowpark.modin.plugin.docstrings.series_utils.CombinedDatetimelikeProperties.dayofweek
2. snowpark.modin.plugin.docstrings.series_utils.CombinedDatetimelikeProperties.nanosecond
The difference is caused due to the remove of extra cast expression in binary operations, for example
before the change, the generated column expression for dayofweek contains an extra cast the integer 1
dayofweekiso("__reduced__") - 1::INT
After we remove the cast,  the query will have no extra cast, and completely rely on snowflake engine for type …
> Fix pandas doc test failure after removing unncessary cast

- tests/integ/scala/test_update_delete_merge_suite.py
- tests/mock/test_functions.py
Fixes SNOW-1623450
Fix flaky test due to the inherently unstable current time execution.
in this PR I decoupled the test:
1. add local testing current_timestamp/date/time test to use mock session only
2. update merge clause to be independent of current_timestamp/date/time
> SNOW-1623450: fix flaky test by mocking datetime now

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/groupby/test_groupby_head_tail.py
Fixes SNOW-1628228
This PR fixes a bug in `groupby.last` by using the correct columns for the Order By as part of the Window Expression.
> SNOW-1628228: Fix bug in `groupby.first/last` with ordering columns in window expression

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/unit/test_dataframe.py
Fixes SNOW-1558347
Previously if a user specified `PARSE_HEADER = True` in an externally defined file format it would not be able to be used with `session.read.csv` without throwing an exception. This exception was caused due to how we infer csv schemas in the client. The client separates out csv loading into a schema inference step and a query step. Parsing the header is valid in the inference step, but should be skipped in the query step.
This change modifies the logic to the read step so that a temporary file format is always created. The external file format is queried and merged …
> SNOW-1558347: Fix PARSE_HEADER bug in session.read.csv

- CHANGELOG.md
- src/snowflake/snowpark/mock/_connection.py
- tests/integ/scala/test_dataframe_writer_suite.py
Fixes SNOW-1552403
The implementation doesn't update index of the dataframe when writing table in truncate mode with fewer columns which leads to index error.
also the implementation only takes the order of column into account not the column names, which ended up updating wrong columns.
> SNOW-1552403: local testing save table in truncate mode with df of fewer column leads to indexerror

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/aggregation_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/concat_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/cumulative_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/cut_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/frame.py
- src/snowflake/snowpark/modin/plugin/_internal/generator_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/groupby_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/isin_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/join_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/pivot_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/resample_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/transpose_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/unpivot_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/utils/error_message.py
- tests/integ/modin/frame/test_reset_index.py
- tests/integ/modin/series/test_cache_result.py
- tests/integ/modin/series/test_copy.py
- tests/integ/modin/series/test_shift.py
- tests/integ/modin/series/test_sort_index.py
- tests/integ/modin/types/test_timedelta.py
- tests/unit/modin/conftest.py
- tests/unit/modin/test_internal_frame.py
- tests/unit/modin/test_snowflake_query_compiler.py
Fixes SNOW-1625377 Raise NotImplementedError for timedelta. This PR also supported SNOW-1620417 cache_result.
The main goal for this PR is to make sure we raise `NotImplementedError` from a SnowflakeQueryCompiler's public method when a dataframe or series contain Timedelta columns call it and it hasn't fully supported Timedelta type. Then in the coming weeks, we can remove those errors once we have implemented and tested those methods. The steps I did in this PR are:
1. Change `data_column_types` and …
> SNOW-1625377 Raise NotImplementedError for timedelta

- CHANGELOG.md
- src/snowflake/snowpark/session.py
- tests/integ/test_packaging.py
- tests/integ/test_session.py
- tests/integ/test_stored_procedure.py
Fixes SNOW-1573504
Previously registering stored proc will fail after switching database or schema because session.get_session_stage will return a different stage.
> SNOW-1573504: Fix session stage after switching database or schema

- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/session.py
- tests/integ/test_packaging.py
- tests/unit/test_session.py
Fixes SNOW-1418500
This PR refactors `Session._resolve_packages` to not have any side-effects. In the old implementation, we relied on this function to make updates to `Session._packages` variable. Now we return the final resulting state after resolving packages and update `Session._packages` only in `Session.add_packages` making `Session._resolve_packages` have no side-effect.
> SNOW-1418500: Refactor _resolve_packages to have no side-effects

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/binary_op_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/frame.py
- src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/join_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/snowpark_pandas_types.py
- src/snowflake/snowpark/modin/plugin/_internal/transpose_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/type_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/utils/warning_message.py
- tests/integ/modin/types/test_timedelta_indexing.py
- tests/unit/modin/test_snowpark_pandas_types.py
SNOW-1625468 Support indexing with Timedelta data columns
Support indexing with Timedelta data columns:
- Added sufficient tests cases for indexing including get and set values with the same timedelta type or different types.
- To achieve this, I updated several util methods related to transpose, join too.
- Also, I need to refactor `SnowparkPandasType` since there are some confusing on `type` object and class there.
This pull request includes several changes to enhance support for `Timedelta` and …
> SNOW-1625468 SNOW-1634393 Support indexing with Timedelta data columns

- tests/integ/modin/test_merge_asof.py
> FIX: Fix `merge_asof` test disabled sql simplifier

- tests/integ/scala/test_async_job_suite.py
- tests/integ/test_cte.py
Fixes SNOW-1638059
IMHO the two test cases are not be here, so removing them is the right approach here:
1. `test_async_place_holder`,  `show functions` causes flakiness because new functions can be created while the test is running, leading to chances of flakiness.
also we have a bunch of async tests, I don't think we need this place holder any more, deleting the test should not reduce test coverage
2. `test_sql `, sql `describe result last_query_id()` is not static, the result depends on the last executed query affected by the dataframe evaluation. 
see: …
> SNOW-1638059: fix daily precommit failure test

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/aggregation_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/binary_op_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/frame.py
- src/snowflake/snowpark/modin/plugin/_internal/indexing_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/join_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/resample_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/unpivot_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/where_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/index.py
- tests/integ/modin/frame/test_dtypes.py
- tests/unit/modin/conftest.py
- tests/unit/modin/test_series_dt.py
Fixes SNOW-1637932
The main purpose for this refactoring is to avoid calling schema when cached type is available, e.g., avoid calling schema when we know the type is Timedelta in binary ops.
This pull request includes several changes to the Snowflake Snowpark Modin plugin, focusing on refactoring the way Snowflake types are retrieved and used. The main changes involve replacing the `quoted_identifier_to_snowflake_type` method with a new `get_snowflake_type` method, which simplifies type retrieval by …
> SNOW-1637932 Refactor quoted_identifier_to_snowflake_type

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
- tests/integ/test_df_to_snowpark_pandas.py
- tox.ini
Fixes SNOW-1625830
Calling `to_snowpark_pandas` on a Snowpark Python DataFrame without first performing `import snowflake.snowpark.modin.plugin` currently raises an error (see attached JIRA for exact reproduction). This was not the case in previous releases, and this PR fixes internal imports such that performing this operation implicitly initializes Snowpark pandas.
After this PR, when `to_snowpark_pandas` is called without explicitly initializing Snowpark pandas, one of two things happens:
1. If modin is not installed, Snowpark pandas will surface the following error:
``` …
```
> SNOW-1625830: Fix circular import when calling `to_snowpark_pandas` without initializing Snowpark pandas

- tests/integ/test_df_to_snowpark_pandas.py
Updates the error message to check if we're on python 3.8 before checking the pandas version.
> Fix error message in python 3.8 to_snowpark_pandas daily test

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/compiler/query_generator.py
- src/snowflake/snowpark/_internal/compiler/utils.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/integ/test_cte.py
SNOW-1641324
The test Enable CTE Optimization merge gate is currently failing because
1) the _projection_in_str for select statement is reset properly after updating, which causes the expr_alias is updated properly during query generation
2) query parameter is not propogated properly during query generation which causes variable binding query fail
> Fix query_generator for new compilation stage after optimization applied

- CHANGELOG.md
- docs/source/modin/supported/general_supported.rst
- src/snowflake/snowpark/modin/pandas/general.py
- src/snowflake/snowpark/modin/plugin/_internal/timestamp_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/index.py
- src/snowflake/snowpark/modin/plugin/extensions/timedelta_index.py
- tests/integ/modin/tools/test_to_timedelta.py
- tests/integ/modin/utils.py
- tests/unit/modin/test_unsupported.py
Fixes SNOW-1638049
Added support for pd.to_timedelta
- Supports lazy snowpark pandas objects Series and Index.
- does not support `errors` parameter.
- does not support converting from strings (on lazy objects).
> SNOW-1638049: Add support for pd.to_timedelta

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/groupby_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/groupby/test_all_any.py
- tests/integ/modin/groupby/test_groupby_basic_agg.py
- tests/integ/modin/groupby/test_groupby_idxmax_idxmin.py
- tests/integ/modin/groupby/test_groupby_negative.py
- tests/integ/modin/groupby/test_groupby_nunique.py
- tests/integ/modin/groupby/test_groupby_size.py
- tests/integ/modin/groupby/test_min_max.py
- tests/integ/modin/types/test_timedelta.py
SNOW-1625380
This PR adds support for the following `GroupBy` aggregations with Timedelta columns: `min`, `max`, `mean`, `idxmax`, `idxmin`, `std`, `sum`, `median`, `count`, `any`, `all`, `size`, `nunique`
> SNOW-1625380: Add support for basic GroupBy aggregations with Timedelta

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/join_utils.py
- tests/integ/modin/binary/test_binary_op.py
- tests/integ/modin/test_concat.py
- tests/unit/modin/test_join_utils.py
Fixes SNOW-1636729
Concatenating series from the same dataframe requires joins today, but theoretically there is no join needed since they come from the same dataframe.
The reason those join are there is because concat calls join_on_index to join two series at a time, the join is only optimized today if the join is performed on the row position column, but join_on_index tries to creates a new column using coalesce even if the two columns to coalesce is the same column. Therefore, in the next join, the two columns to join on can not be recognized anymore.
In this pr, we tries to …
> [SNOW-1636729] Improve join/align performance by avoid unnecessary coalesce

- src/snowflake/snowpark/_internal/compiler/large_query_breakdown.py
- tests/integ/test_large_query_breakdown.py
Fixes SNOW-1546396
Remove `sortedcontainers` dependency. All old tests should pass.
> SNOW-1546396: Remove sortedcontainers dependency

- tests/integ/test_cte.py
SNOW-1556590
The test was failing when sql simplification is off, this is fixed with the new query compilation stage, re-enable the test
> [SNOW-1556590] Enable test_sql with new compilation stage

- src/snowflake/snowpark/udf.py
Forgot to add `ast_id` assignment in non-local mode which caused doctest failure, fixed in this PR.
> [SNOW-1514712] Fix udf registration for non-local mode

- src/snowflake/snowpark/modin/plugin/_internal/cut_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/frame.py
SNOW-1630273
Refactored following parts:
1) compute_bin_indices requires asoj join, which wasn't available before, refactor the code to use asof join with join_utils
2) refactor the whole implementation to operate at internal frame level.
> [SNOW-1630273] Refactor compute_bin_indices to reuse asof join

- tests/integ/test_temp_table_cleanup.py
Fixes SNOW-1651296
The entire test suite is flaky because the drop table sql query might not finish when checking its existence.
> SNOW-1651296: Skip temp table cleanup flaky test

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/aggregation_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/groupby_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/groupby/test_all_any.py
- tests/integ/modin/groupby/test_groupby_basic_agg.py
- tests/integ/modin/groupby/test_groupby_first_last.py
- tests/integ/modin/groupby/test_groupby_head_tail.py
- tests/integ/modin/groupby/test_groupby_idxmax_idxmin.py
- tests/integ/modin/groupby/test_groupby_nunique.py
- tests/integ/modin/groupby/test_groupby_size.py
- tests/integ/modin/groupby/test_min_max.py
- tests/integ/modin/io/test_to_csv.py
- tests/integ/modin/types/test_timedelta.py
SNOW-1652274, SNOW-1638408
This PR adds support for Timedelta data types for operations GroupBy `first`, `last`, `head`, `tail`, and `aggregate`. Additionally, a test for `to_csv` with TimedeltaIndex is added.
> SNOW-1652274, SNOW-1638408: Add support for Timedelta with GroupBy `first`, `last`, `head`, `tail`, `aggregate`

- src/snowflake/snowpark/modin/pandas/__init__.py
- src/snowflake/snowpark/modin/pandas/io.py
- src/snowflake/snowpark/modin/plugin/docstrings/base.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
- src/snowflake/snowpark/modin/plugin/extensions/pd_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/pd_overrides.py
- src/snowflake/snowpark/modin/plugin/io/snow_io.py
- tests/integ/modin/io/test_read_json.py
Fixes SNOW-1635365 (resolves #2139)
A few methods in documentation had an outdated import method for Snowpark pandas (`import snowflake.snowpark.modin.pandas as pd`). This PR updates docstrings to use the correct method (`import modin.pandas as pd; import snowflake.snowpark.modin.plugin`).
> SNOW-1635365: Update snowpark pandas imports in method documentation

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/datetime_index.py
- tests/integ/modin/index/test_datetime_index_methods.py
Fixes: SNOW-1616989
Allow creation of DatetimeIndex from other types of data. Internally use to_datetime for conversion.
> SNOW-1616989: Enable creation for DatetimeIndex with query_compiler numeric or str type

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/binary_op_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/frame.py
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/types/test_timedelta.py
Fixes SNOW-1628925
The main idea is to convert timedelta column to string before calling to_pandas, and then convert str back to timedelta to avoid precision loss.
> SNOW-1628925 Fix timedelta precision loss in to_pandas

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/server_connection.py
- tests/integ/test_large_query_breakdown.py
Fixes SNOW-1632701
Associate a `uuid` with each `SnowflakePlan` so that we can track all queries that originated from the same plan.
> SNOW-1632701: Add uuid to SnowflakePlan

- docs/source/modin/io.rst
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/modin/pandas/general.py
- src/snowflake/snowpark/modin/plugin/docstrings/base.py
- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/groupby.py
- src/snowflake/snowpark/modin/plugin/docstrings/resample.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
- src/snowflake/snowpark/modin/plugin/docstrings/series_utils.py
- src/snowflake/snowpark/modin/plugin/docstrings/shared_docs.py
- src/snowflake/snowpark/modin/plugin/docstrings/window.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/pd_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
- src/snowflake/snowpark/modin/plugin/io/snow_io.py
- src/snowflake/snowpark/modin/utils.py
- src/snowflake/snowpark/session.py
Fixes SNOW-1658008
This PR updates type annotation and documentation paths referencing Snowpark pandas objects. Notably, `snowflake.snowpark.modin.pandas.Series`/`DataFrame` are now referenced by `modin.pandas.Series`/`DataFrame`.
In Snowpark session + DataFrame objects: functions that reference Snowpark pandas objects now refer to `modin.pandas`, with the import guarded by the `TYPE_CHECKING` variable. This should not affect any Snowpark non-pandas users.
In Snowpark pandas, references to `snowflake.snowpark.modin.pandas.io.*` were not generating correctly; these have been edited to …
> SNOW-1658008: Clean up Snowpark pandas documentation references

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- tests/integ/modin/io/test_read_snowflake.py
1. Fill out the following pre-review checklist:
2. Please describe how your code solves the related issue.
read_snowflake will trigger table materialization under cases for hybrid table, iceberg table etc. include the reason inside the warning message to make the reason more clear to users
> Improve warning message for read_snowflake to include materialization reason

- src/snowflake/snowpark/modin/pandas/__init__.py
- src/snowflake/snowpark/modin/pandas/dataframe.py
- src/snowflake/snowpark/modin/plugin/_internal/telemetry.py
- src/snowflake/snowpark/modin/plugin/extensions/base_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/base_overrides.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_overrides.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/series_overrides.py
- tests/integ/modin/test_telemetry.py
Fixes SNOW-1659478
Previous code to de-duplicate telemetry entries was incorrect, and would not apply telemetry to methods defined on `dataframe.py` (currently still vendored) but inherited from upstream `base.py`, such as `DataFrame.copy`. This PR automatically applies telemetry annotations to Series + DataFrame inside `pandas/__init__.py` via the extensions module, meaning the `TelemetryMeta` class, and all annotations in extensions/overrides, should no longer be used.
> SNOW-1659478: Cherrypick telemetry fixes

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/binary_op_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-1641472
Try to improve readability of binary ops by reorganize it as a `BinaryOp` class.
This pull request focuses on improving the readability and maintainability of the binary operation utility code within the Snowflake query compiler. The changes primarily involve refactoring the binary operation functions into a new `BinaryOp` class and updating the relevant method calls throughout the codebase.
* [`src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py`](diffhunk://#diff …
> SNOW-1641472 Refactor binary ops utility to improve readability

- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/_internal/temp_table_auto_cleaner.py
- src/snowflake/snowpark/session.py
- tests/integ/test_telemetry.py
- tests/integ/test_temp_table_cleanup.py
- tests/unit/test_session.py
Fixes SNOW-1641644
see details in [discussion](https://snowflake.slack.com/archives/C04HF38JFAQ/p1725057972543059?thread_ts=1724782971.351959&cid=C04HF38JFAQ)
> SNOW-1641644: Drop temp table directly at garbage collection instead of using multi-threading 

- tests/integ/modin/frame/test_loc.py
SNOW-1320674: This bug is already fixed in main brach. Adding a explicit test case before closing it.
> SNOW-1320674: Add tests to verify loc raises KeyError for invalid labels

- src/snowflake/snowpark/_internal/analyzer/binary_expression.py
- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/grouping_set.py
- src/snowflake/snowpark/_internal/analyzer/sort_expression.py
- src/snowflake/snowpark/_internal/analyzer/unary_expression.py
- src/snowflake/snowpark/_internal/analyzer/window_expression.py
- tests/unit/test_expression_dependent_columns.py
Fixes SNOW-1632895
in order to handle nested select with column dependency (not handled by sql simplifier) complexity calculation, added a utility support for deriving all column depenencies with duplication, for example, col('a') + col('b') + 3*('a'), should return dependency ['a', 'b', 'a'] this provides both information about the columns it dependents on and also the number of times/
> [SNOW-1632895] Add derive_dependent_columns_with_duplication capability

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- tests/integ/modin/types/test_timedelta.py
> SNOW-1664064: Suppress SettingWithCopyWarning for Timedelta columns.

- src/snowflake/snowpark/session.py
Fixes SNOW-1418523
Minor refactor to handle thread-safe session. We remove `_tmpdir_handler` which is only used inside method `_upload_unsupported_packages`.
> SNOW-1418523: Remove session variable that can be local

- CHANGELOG.md
- docs/source/snowpark/functions.rst
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/window.py
- tests/integ/scala/test_window_frame_suite.py
- tests/integ/test_column_names.py
- tests/integ/test_dataframe.py
Fixes SNOW-1331876
Interval support in RANGE BTEWEEN is just GA last month.
> SNOW-1331876: Support interval in `Window.range_between`

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/series_overrides.py
- tests/integ/modin/series/test_sort_values.py
In native pandas, calling sort_values where column name overlaps with index name raises error `ValueError: 'col' is both an index level and a column label, which is ambiguous`. But this works for series. 
In Snowpark pandas we were raising errors both the scenarios Dataframe (this is expected) and Series (this was bug).
**Root cause**: In modin frontend we to implement Series.sort_values we convert this to Dataframe and call sort_values on it. So this failed the validation above.
**Fix:** Instead of converting Series to Dataframe directly call `query_compiler.sort_rows_by_column_values`.
> SNOW-1649780: Bug fix Series.sort_values fails when name overlaps with index name

- CHANGELOG.md
- src/snowflake/snowpark/modin/pandas/indexing.py
- src/snowflake/snowpark/modin/plugin/_internal/frame.py
- src/snowflake/snowpark/modin/plugin/_internal/type_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/datetime_index.py
- src/snowflake/snowpark/modin/plugin/extensions/index.py
- src/snowflake/snowpark/modin/plugin/extensions/series_overrides.py
- tests/integ/modin/frame/test_dtypes.py
- tests/integ/modin/index/test_index_methods.py
- tests/integ/modin/series/test_astype.py
- tests/integ/modin/series/test_dt_accessor.py
- tests/integ/modin/test_dtype_mapping.py
- tests/integ/modin/test_from_pandas_to_pandas.py
- tests/unit/modin/conftest.py
- tests/unit/modin/test_series_dt.py
Fixes SNOW-1657460
Previously we use "datetime64[ns]" as the dtype for datetime with timezone which is missing the tz info. This change will extract the timezone from timestamp_tz column and show the timezone offset when calling dtypes.
> SNOW-1657460 Improved  results for TIMESTAMP_TZ type to show correct timezone offset.

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Remove warning from sort_values when sort algorithm is 'quicksort'. We still raise warning if user passed a sort algorithm explicitly like `mergesort` for `quicksort` is default value so it doesn't make sense to raise this warning.
> SNOW-1320309: Remove unnecessary warning from sort_values

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- tests/integ/modin/io/test_read_snowflake.py
SNOW-1645085
Always use scoped temp table for internally created temp table during read_snowflake.
SCOPED temp object is feature introduced for snowpark internally created table, which is stored procedure scoped temp if the temp table is created within stored sproc, and session scoped if outside sored sproc.
Native app only allows usage of scoped object, similar as snowpark python, we always uses scoped object when enabled
> [SNOW-1645085] Always use SCOPED temp table for snowpark pandas generated api

- tests/integ/modin/frame/test_apply.py
- tests/integ/modin/frame/test_apply_axis_0.py
- tests/integ/modin/frame/test_applymap.py
- tests/integ/modin/groupby/test_groupby_apply.py
- tests/integ/modin/groupby/test_groupby_transform.py
- tests/integ/modin/series/test_apply.py
Fixes SNOW-1640167
Test two scenarios for apply-like methods `apply`, `applymap`, `groupby.transform`, and `groupby.apply`:
1) input dataframe has timedelta data columns or index columns
2) output includes timedelta values.
Situation 1) currently raises `NotImplementedError` and will continue to do so after this commit. Recognizing that we have timedelta instead of the underlying integer as input inside the UD(T)F requires adding extra metadata. Postpone this task till a user asks for it. In this commit, just check for the `NotImplementedError`.
Situation 2) currently puts string outputs instead of `Timedelta` in the result. That's a bug, but it does follow what Snowflake does in this case. Fixing the bug is possible, but requires adding some extra metadata to the UD(T)F output. For now …
> SNOW-1640167: Test Timedelta input and output in apply-like methods.

- tests/ast/data/DataFrame.count2.test
This test fails with a missing AST error.
The expectations were copied/pasted from the other `count()` test. This should be invoked with `--update-expectations`.
> Failing count() test case

- tests/integ/test_query_history.py
when sql simplifier is disabled, there is less describing query issued
> Fix query history test failure when sql simplifier disabled

- src/snowflake/snowpark/_internal/compiler/query_generator.py
- src/snowflake/snowpark/_internal/compiler/utils.py
- tests/integ/compiler/test_query_generator.py
1. Please describe how your code solves the related issue.
a) Fix alias query generation after transformation by propogating the alias map correctly to snowflake pln
b) fix a test that is actually doing wrong check
> Fix df alias test failure for new query generation when sql simplifier disabled

- src/snowflake/snowpark/_internal/analyzer/query_plan_analysis_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/compiler/utils.py
- tests/integ/test_deepcopy.py
- tests/integ/test_large_query_breakdown.py
- tests/integ/test_nested_select_plan_analysis.py
- tests/integ/test_query_plan_analysis.py
- tests/unit/test_query_plan_analysis.py
SNOW-1632898
1) adjust the projection complexity calculation, and cumulative complexity for selectStatement when _merge_projection_complexity_with_subquery set to True.
2) update the complexity calculation for snowflake plan to directly get the complexity from source plan, and update the reset to reset the cumulative complexity.
> [SNOW-1632898] Adjust SelectStatement projection complexity calculation

- src/snowflake/snowpark/modin/plugin/_internal/generator_utils.py
> SNOW-1646883: remove disable sql simplifier hack

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/window/test_expanding.py
- tests/integ/modin/window/test_rolling.py
- tests/integ/modin/window/utils.py
Fixes SNOW-1694806
Add support for rolling().count() and expanding().count() for both Series and DataFrames.
For other rolling and expanding methods, match pandas behavior, which is to raise some kind of error.
> SNOW-1694806: Add support for rolling and expanding count with timedelta.

- src/snowflake/snowpark/_internal/compiler/utils.py
1. Please describe how your code solves the related issue.
import graphviz seems also introduces a set of warning message like 
```
DEBUG    graphviz._tools:_tools.py:147 deprecate positional args: graphviz.graphs.BaseGraph.__init__(['comment', 'filename', 'directory', 'format', 'engine', 'encoding', 'graph_attr', 'node_attr', 'edge_attr', 'body', 'strict'])
DEBUG    graphviz._tools:_tools.py:147 deprecate positional args: graphviz.sources.Source.from_file(['directory', 'format', 'engine', 'encoding', 'renderer', 'formatter'])
DEBUG    graphviz._tools:_tools.py:147 deprecate positional args: graphviz.sources.Source.__init__(['filename', 'directory', 'format', 'engine', 'encoding'])
DEBUG    graphviz._tools:_tools.py:147 deprecate positional args: …
```
> Avoid unnecessary warning message when plotting is not enabled

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/resample/test_resample.py
- tests/integ/modin/resample/test_resample_asfreq.py
- tests/integ/modin/resample/test_resample_fillna.py
- tests/integ/modin/resample/test_resample_negative.py
Fixes SNOW-1694815
Test passing timedelta types through resampler methods.
It turns out that we are currently converting the timedelta types to integers, so fix that bug in most cases.
We support all resample "fill" methods, along with all aggregations except for `std`, which pandas does not support.
> SNOW-1694815: Propagate timedelta types through resampler methods.

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/pivot/test_pivot_table_negative.py
- tests/integ/modin/tools/test_to_datetime.py
- tests/integ/modin/tools/test_to_numeric.py
- Test that pivot() with timedelta inputs is not supported.
- pivot() is complicated so defer this feature until a user requests it.
- Test that timedelta is invalid input to to_datetime()
- Fix a bug where to_numeric() would leave timedelta values alone instead of converting them to integer.
Fixes SNOW-1625385
Fixes SNOW-1625384
> SNOW-1625385, SNOW-1625384: Test and/or fix timedelta in integ/modin/{pivot,tools}

- tests/integ/modin/test_sql_counter.py
Fixes SNOW-1704402 Fix sql counter failure on describe_count when sql simplifier disabled
Fix sql counter failure on describe_count when sql simplifier disabled
> SNOW-1704402 Fix sql counter test failure on describe_count when sql simplifier disabled

- src/snowflake/snowpark/modin/plugin/_internal/ordered_dataframe.py
- src/snowflake/snowpark/modin/plugin/_internal/pivot_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- tests/integ/test_cte.py
- tests/unit/modin/test_utils.py
SNOW-1678113]
In the reported case, the unstack calls pivot table underneath, and customer end with about 2000 columns after pivot. The pivot it's self took about 1~2 seconds to finish, but the after pivot it start looping over all columns and calling append_columns in each loop here [snowpark-python/src/snowflake/snowpark/modin/plugin/_internal/pivot_utils.py at 272e4e1ee5da84f8ac0abfefda95aab3b0bf4d7e · snowflakedb/snowpark-python](https://github.com/snowflakedb/snowpark-python/blob/272e4e1ee5da84f8ac0abfefda95aab3b0bf4d7e/src/snowflake/snowpark/modin/plugin/_internal/pivot_utils.py# …
> [SNOW-1678113] Improve pivot_table performance

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/_internal/compiler/query_generator.py
- src/snowflake/snowpark/dataframe_writer.py
- tests/integ/compiler/test_query_generator.py
- tests/integ/test_cte.py
- tests/integ/test_deepcopy.py
Fixes SNOW-1703599
We shouldn't call session._table_exists inside resolve, but we can call it before resolve.
> SNOW-1703599: Fix duplicate show query in save_as_table when new compilation stage is applied

- src/snowflake/snowpark/_internal/analyzer/query_plan_analysis_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/compiler/plan_compiler.py
- src/snowflake/snowpark/_internal/compiler/repeated_subquery_elimination.py
- src/snowflake/snowpark/_internal/compiler/telemetry_constants.py
- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/integ/test_telemetry.py
SNOW-1566363
1. add status for number of selectStatement with complexity merged
2.add status for number of cte created during repeated subquery elimination
> [SNOW-1566363] Add telemetry for new compilation stage

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- tests/integ/compiler/test_query_generator.py
1. Fill out the following pre-review checklist:
2. Please describe how your code solves the related issue.
1) fix a bug in test_query_generator that is was repeated test the query generation on the same plan node
2) use a copy for the alias_map to to use  during resolve to avoid unexpected update of the alias map
> Fix test_query_generator for query generation test on each snowflake plan node

- src/snowflake/snowpark/_internal/temp_table_auto_cleaner.py
- tests/integ/test_temp_table_cleanup.py
Fixes SNOW-1727163
It's possible that the session is already closed before garbage collection kicks in, where we should avoid sending drop table sql and eliminate the warning
> SNOW-1727163: Do not drop table in temp table cleaner if the session is already closed

- tests/integ/test_cte.py
- tests/integ/test_large_query_breakdown.py
- tests/integ/utils/sql_counter.py
Test fails because it cannot detect fixture `sql_simplifier_enabled`. Reading the value from session to workaround the issue.
example: https://ci-dev-133.int.snowflakecomputing.com/job/RT-PC-TestWorker/203222/testReport/junit/(root)/t_python_sp_integ_sp/snowpark_test_large_query_breakdown_sql/
> NO-SNOW: fix sp-precommit test for large_query_breakdown and cte

- src/snowflake/snowpark/table.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/unit/test_dataframe.py
Fixes SNOW-1727512
It should be the same as session.table(...).select_statement. Otherwise, we will cache metadata on wrong source_plan in the future.
> SNOW-1727512: session.table(...)._plan.source_plan should be SelectStatement instead of SnowflakeTable 

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- tests/integ/test_udf.py
Fixes SNOW-1728101
A `NoneType` check was missed when reading args for callable udfs. Moved the check to a common function.
> SNOW-1728101: Fix throwing bad optional args warning

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/test_apply_snowpark_python_functions.py
SNOW-1690717
This is the first PR to support Snowpark Python functions in pandas apply. It only introduce `sin` as the first example.
> SNOW-1690717 Applying Snowpark Python function (sin)

- CHANGELOG.md
Fixes SNOW-1728471
Fix changelog entry placement for DataFrameGroupBy.fillna and SeriesGroupBy.fillna.
> SNOW-1728471: Fix changelog entry placement for DataFrameGroupBy.fillna and SeriesGroupBy.fillna

- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/mock/_plan.py
- src/snowflake/snowpark/session.py
- tests/integ/test_reduce_describe_query.py
- tests/unit/compiler/test_replace_child_and_update_node.py
- tests/unit/test_dataframe.py
- tests/unit/test_query_plan_analysis.py
Fixes SNOW-1570734
This PR now actually only captures one part: cache attributes (metadata) when 1) the DataFrame operation doesn't change attributes (e.g., filter, sort) 2) SQL simplifier is disabled, or SQL simplifier is enabled but creating a SelectStatement directly from a non-SelectStatement (e.g., sesison.sql(...).schema can cache attributes, see more in tests). I will have another PR that will try to cache attributes on SelectStatement, which will address 2)
> SNOW-1570734: Reduce describe query when there is no schema change

- src/snowflake/snowpark/_internal/analyzer/cte_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/compiler/repeated_subquery_elimination.py
- tests/integ/test_cte.py
- tests/integ/test_deepcopy.py
- tests/unit/compiler/test_replace_child_and_update_node.py
- tests/unit/test_cte.py
SNOW-1731783
In the previous repeated subquery elimination, we updated the node comparison for SnowflakePlan for Selectable to 
```
def __eq__(self, other: "SnowflakePlan") -> bool:
if not isinstance(other, SnowflakePlan):
return False
if self._id is not None and other._id is not None:
return isinstance(other, SnowflakePlan) and self._id == other._id
else:
return super().__eq__(other)
def __hash__(self) -> int:
return hash(self._id) if self._id else super().__hash__()
```
where the id is generated based on the query and query parameter, this means two node are treated as the same if …
> [SNOW-1731783] Refactor node query comparison for Repeated subquery elimination

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/modin/frame/test_head_tail.py
- tests/integ/modin/series/test_head_tail.py
- tests/integ/test_simplifier_suite.py
SNOW-1731549
Today, sql simplification flattens df.limit(2).orderby(col1) into one SelectStatement, which always put order by clause in front of the limit clause during code generation. 
However, limit order by and order by limit can cause big performance difference, because limit can stop table scanning whenever the number of record is satisfied.
Therefore, this pr disallow sql simplification when the current SelectStatement has a limit clause to avoid moving order by in front of limit to respect what the user have coded.
> [SNOW-1731549] Disable sql simplification when sort is performed after limit

- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/test_reduce_describe_query.py
Fixes SNOW-1728988
When sql simplifier is on, it can resolve the scenarios where 1) select() is called because df._plan is not carried over, 2) sql simplifier can't flatten the query
> SNOW-1728988: Cache attributes on SelectStatement to reduce describe query 

- tests/integ/scala/test_datatype_suite.py
Test only change to drop iceberg table after test. Right now `session.sql()` is called without a `.collect()`
> Drop iceberg table after test

- src/snowflake/snowpark/_internal/analyzer/cte_utils.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_cte.py
SNOW-1739096
Repeated subquery elimination is only designed to eliminate subquery that is selectStatement. Since we do not distinguish query that is selectStatement and none selectStatement, we can incorrectly detect non selectstatement as candidate. for example, when we have 
```
df1 = session.sql("show tables")
df2 = session.sql("show tables")
df_result = df1.union(df2)
```
The show table query its-self can be incorrectly detected as a common query and produced wrong query like
```
with_cte_xxx (show tables) xxxx
```
In this pr, we exclude none-selectstatment from the candidate node …
> [SNOW-1739096] Disallow detecting none select statement as repeated subquery

- tests/integ/utils/sql_counter.py
Unused temp tables to be dropped to temp table cleaner may happen any time when garbage collection kicks in, so we should not count it
> Exclude drop table sql from temp table cleaner in sql_counter.py

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/io/test_to_csv.py
Fixes: SNOW-1730546
RCA: 
We have two different code paths depending on destination location.
When calling to_csv on the local path we use native pandas to_csv. This works because native pandas doesn’t differentiate between null and empty strings when writing to csv. Empty strings are treated as null values. As a side effect, calling to_csv and read_csv again will result in replacing all empty strings with NULL/NA.
When calling to_csv on the snowflake stage path we use snowflake’s copy command. Snowflake copy command is not able to handle empty strings out of box and requires users to pass FIELD_OPTIONALLY_ENCLOSED_BY (which is NONE by default).
Solution:
Always set EMPTY_FIELD_AS_NULL = False when to_csv on stage is called.
> SNOW-1730546: Bug fix for to_csv on stage with empty strings

- tests/integ/test_multithreading.py
Fixes SNOW-1659276
Make required tweaks to `integ/test_multithreading.py` to enable them to run in SP Precommit.
> SNOW-1659276 add multithreading tests to sp env

- tests/integ/modin/test_apply_snowpark_python_functions.py
- tests/integ/test_function.py
> SNOW-1758877 Fix flaky test test_snowflake_cortex_summarize

- src/snowflake/snowpark/_internal/ast_utils.py
- tests/ast/data/DataFrame.collect.test
- tests/ast/data/DataFrame.count.test
- tests/ast/data/DataFrame.count2.test
- tests/ast/data/DataFrame.stat.test
- tests/ast/data/DataFrame.to_local_iterator.test
- tests/ast/data/DataFrame.to_pandas.test
- tests/ast/data/DataFrame.to_pandas_batch.test
- tests/ast/data/DataFrame.write.test
- tests/ast/data/RelationalGroupedDataFrame.test
- tests/ast/data/Table.delete.test
- tests/ast/data/Table.merge.test
- tests/ast/data/Table.update.test
- tests/ast/data/col_udf.test
- tests/ast/data/df_random_split.test
- tests/ast/data/sproc.test
- tests/ast/data/udaf.test
- tests/ast/data/udtf.test
- tests/ast/test_ast_driver.py
Fix multi ast eval validation in decoding expectation test ast
> SNOW-1738538 Fix multi ast eval validation in decoding expectation test ast

- tests/integ/modin/io/test_read_snowflake_query_cte.py
Fixes SNOW-1760125
Disabling `test_read_snowflake_query_cte_with_python_anonymous_sproc` flaky test from Precommit run until there is a reliable fix
> SNOW-1760125: Disable test_read_snowflake_query_cte_with_python_anonymous_sproc test from precommit

- src/snowflake/snowpark/_internal/analyzer/query_plan_analysis_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/compiler/cte_utils.py
- src/snowflake/snowpark/_internal/compiler/repeated_subquery_elimination.py
- src/snowflake/snowpark/_internal/compiler/telemetry_constants.py
- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/integ/test_telemetry.py
- tests/unit/test_cte.py
SNOW-1758768
Add telemetry to record the distribution of repeated nodes complexity. Note, we are recording the number of repeated nodes, not just the cte nodes. For example, if n2 occured twice during the visit of the whole tree, it will be counted twice, instead of once.
The complexity bucket used today are :
```
1) low complexity
bin 0: <= 10,000; bin 1: > 10,000, <= 100,000; bin 2: > 100,000, <= 500,000
2) medium complexity
bin 3: > 500,000, <= 1,000,000;  bin 4: > 1,000,000, <= 5,000,000
4) large complexity
bin 5: > 5,000,000, <= 10,000,000;  bin 6: > 10,000,000
```
> [SNOW-1758768] Add repeated node complexity distribution telemetry

- .github/workflows/daily_modin_precommit.yml
- .github/workflows/daily_precommit.yml
- .github/workflows/precommit.yml
- tests/conftest.py
- tests/integ/modin/crosstab/test_crosstab.py
- tests/integ/modin/frame/test_assign.py
- tests/integ/modin/frame/test_cache_result.py
- tests/integ/modin/frame/test_describe.py
- tests/integ/modin/frame/test_loc.py
- tests/integ/modin/frame/test_name.py
- tests/integ/modin/frame/test_setitem.py
- tests/integ/modin/groupby/test_groupby_transform.py
- tests/integ/modin/pivot/test_pivot_table_dropna.py
- tests/integ/modin/pivot/test_pivot_table_fill_value.py
- tests/integ/modin/pivot/test_pivot_table_margins.py
- tests/integ/modin/series/test_cache_result.py
- tests/integ/modin/series/test_describe.py
- tests/integ/modin/series/test_fillna.py
- tests/integ/modin/series/test_loc.py
- tests/integ/modin/series/test_mask.py
- tests/integ/modin/series/test_setitem.py
- tests/integ/modin/series/test_where.py
- tests/integ/modin/types/test_timedelta_indexing.py
- tests/unit/test_open_telemetry.py
> SNOW-1733956: fix sql count of modin tests with cte enabled

- tests/integ/modin/io/test_read_snowflake_query_cte.py
Reverts snowflakedb/snowpark-python#2496
Disabling the test from the Snowfort Precommit test directly instead of from client.
> Revert "SNOW-1760125: Disable test_read_snowflake_query_cte_with_python_anonymous_sproc test from precommit"

- CHANGELOG.md
- src/snowflake/snowpark/_internal/type_utils.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/test_stored_procedure.py
This change fixes a bug where fields of structured data would have incorrect casing which causes issues when doing a structural comparison especially when copying data from one table to another with a CTAS statement. This should not be a BCR because the previous behavior would have work fine with all uppercase field names, but thrown an error with mixed case field names.
> SNOW-1754876: Fix inconsistent case in StructFields for structured types

- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/test_reduce_describe_query.py
- tests/unit/test_dataframe.py
Fixes SNOW-1615885
Quoted identifiers (column names) are actually already inferred in derive_column_states, we can just use it instead of calling snowflake_plan.attributes to retrieve metadata from server side
> SNOW-1615885: Don't use `snowflake_plan.attributes` in SQL simplifier and infer quoted identifiers 

- tests/integ/scala/test_session_suite.py
I suspect it's related to multiple transaction in one test, separating them may solve this problem
> Fix flaky test_create_temp_table_no_commit

- tests/integ/scala/test_datatype_suite.py
Fixes SNOW-1727257
This PR adds a test to ensure that large query breakdown preserves the final schema of table even when intermediate parts of the table are materialized.
> SNOW-1727257 test iceberg with large query breakdown

- src/snowflake/snowpark/_internal/compiler/utils.py
- tests/integ/test_cte.py
In replace_child, if the child of a parent has already been updated, the old child won't exist anymore, and an error could raise with the current code. However, if the child has already been updated with the new child, we should simply skip the update.
For this case, the original plan have 4 resolved snowflake plan node that is pointing to the same source plan, therefore updating the child of one parent automatically updates the other parents.
daily precommit test verification https://github.com/snowflakedb/snowpark-python/actions/runs/11545868356
> Skip child replace for new query compilation stage if the child has been updated already

- .github/workflows/precommit.yml
- tests/ast/README.md
- tests/ast/conftest.py
- tests/ast/test_ast_setup.py
- tox.ini
Before moving source code of IR to this repo, this PR add the test job in CI first which will run in merge gate. We will enforce this check before IR Phase 0 is complete.
> SNOW-1491199 add ast-encoding test in precommit

- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- tests/integ/test_reduce_describe_query.py
Fixes SNOW-1730742
When source_plan is a SnowflakeValues, metadata is already defined locally
> SNOW-1730742: Use SnowflakeValues.output as cached attributes 

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-1634498
Refactor df.corr implementation to call agg on OrderedD ataFrame.
> SNOW-1634498: Refactor df.corr implementation to call agg on OrderedD ataFrame

- tests/integ/test_cte.py
Fixes SNOW-1770289
We don't have such an test before. The generated query is like:
```
WITH SNOWPARK_TEMP_CTE_N7V3KVPKOM AS (with t as (select 1 as A) select * from t) SELECT count(1) AS "COUNT(LITERAL())" FROM ( SELECT  *  FROM ( SELECT  *  FROM ( SELECT "A" FROM (( SELECT  *  FROM (SNOWPARK_TEMP_CTE_N7V3KVPKOM)) UNION ( SELECT  *  FROM (SNOWPARK_TEMP_CTE_N7V3KVPKOM)))) WHERE True :: BOOLEAN) ORDER BY "A" ASC NULLS FIRST) LIMIT 1
```
> SNOW-1770289: Add test for CTE on `session.sql("with ...")` 

- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- tests/integ/test_reduce_describe_query.py
Fixes SNOW-1748403
We can use Aggregare.aggregate_expressions directly for quoted identifiers
> SNOW-1748403: Use Aggregate.aggregate_expressions to infer quoted identifiers

- tests/integ/modin/series/test_to_list.py
- tests/integ/modin/test_to_numpy.py
Fixes SNOW-1652384
`test_to_numpy` previously did not actually test `to_numpy`, and instead ran `Series.to_list`. This PR properly uses `Series.to_numpy`, and adds a new test for `Series.to_list`.
> SNOW-1652384: Add series/test_to_list and fix test_to_numpy

- .github/workflows/daily_precommit.yml
- .github/workflows/precommit.yml
- tests/conftest.py
- tests/utils.py
- tox.ini
This PR makes the following two changes:
i. Run with multithreaded mode enabled by default.  Move `--multithreading_mode` to `--disable_multithreading_mode` and run snowpark tests in multithreaded mode.
ii. Remove pytest marker `multithreaded_run` which was used to run a subset of snowpark pandas test with multithreaded-mode enabled. This is no longer needed as the snowpark-pandas tests will run with multithreaded mode enabled.
> NO-SNOW: Run tests with multithreading mode enabled by default

- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- tests/integ/test_reduce_describe_query.py
> SNOW-1764136: Infer quoted identifiers for Join

- src/snowflake/snowpark/mock/_nop_analyzer.py
- src/snowflake/snowpark/mock/_nop_connection.py
- src/snowflake/snowpark/mock/_nop_plan.py
- src/snowflake/snowpark/session.py
- tests/ast/conftest.py
- tests/ast/data/RelationalGroupedDataFrame.test
- tests/ast/data/Session.create_dataframe.test
- tests/ast/data/Session.table_function.test
- tests/ast/data/Table.merge.test
- tests/ast/test_ast_driver.py
This adds a NopConnection, NopAnalyzer, NopExecutionPlan which adds a new backend that does no execution, ie. nothing is executed or sent to the server.  This is useful for AST expectation testing to avoid blocking on local testing gaps and performance issues, in many cases the gaps blocked writing tests.  The biggest challenge is supporting a no execution mode is there is schema validation code scattered throughout the dataframe API that fails without attributes.  To mitigate this the NopAnalyzer makes a best effort to figure out the dataframe attributes, while it isn't guaranteed to always be correct in all cases, it effectively unblocks tests because majority of the time complete accuracy is not required on the client side.  Note there is no use case for AST serialization in local …
> SNOW-1738540 Add Nop / No-execution mode for running ast expectation tests

- CHANGELOG.md
- src/snowflake/snowpark/stored_procedure_profiler.py
- tests/integ/test_stored_procedure_profiler.py
Fixes SNOW-1762419
This PR is meant to fix the issue that error will be raised when call profiler.get_output if profiler is not enabled.
After fix, an empty string will be returned under that situation to make profiler not interrupt user code
> SNOW-1762419: Getting profiler output when profiler is disabled throws an exception

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/base_overrides.py
- tests/integ/modin/frame/test_dropna.py
Fixes SNOW-1787507
- Fix bugs where `DataFrame.dropna()` would:
- Treat an empty `subset` (e.g. `[]`) as if it specified all columns instead of no columns.
- Raise a `TypeError` for a scalar `subset` instead of filtering on just that column.
- Raise a `ValueError` for a `subset` of type `pandas.Index` instead of filtering on the columns in the index.
> SNOW-1787507: Fix DataFrame.dropna() with subset empty, scalar, or native_pd.Index.

- tests/integ/scala/test_session_suite.py
> NO-SNOW: Fix flaky no_commit test

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- src/snowflake/snowpark/session.py
- tests/integ/modin/io/test_read_snowflake.py
SNOW-1791241
scoped read only table doesn't work with dynamic pivot in notebook today, investigation needed. 
We added a flag to turns the scoped temp read only table off for snowpark padnas.
Follow up: https://snowflakecomputing.atlassian.net/browse/SNOW-1793002 enable the flag at server side for native app
> [SNOW-1791241] Add a session parameter to disable scoped read only temp table

- .github/scripts/install_protoc.sh
- .github/workflows/precommit.yml
- .pre-commit-config.yaml
- scripts/jenkins_regress.sh
- scripts/jenkins_regress_snowpandas.sh
- setup.py
- src/snowflake/snowpark/_internal/ast/batch.py
- src/snowflake/snowpark/_internal/ast/utils.py
- tox.ini
Fixes SNOW-1791994
This PR generates typed Python code from protobuf and make sure CI check types in precommit. 
Copilot summary:
This pull request includes several changes to improve type checking, streamline the build process, and enhance code quality. The most important changes include the addition of `mypy-protobuf` for generating typed Python code from protobuf, updates to the build and pre-commit configurations, and improvements to type annotations across various files.
* Added `mypy-protobuf` …
> SNOW-1791994 IR: Generate typed protobuf Python code

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_datatype_suite.py
- tests/unit/test_analyzer_util_suite.py
Fixes SNOW-1791051
This change allows iceberg configuration to be passed to `create_or_replace_dynamic_table` in the same way that it is passable to `save_as_table`.
> SNOW-1791051: Add support for iceberg to dynamic table create

- tests/ast/data/col_alias.test
Fixes SNOW-1804052
The test runs without failing – but this should fail if run like regular Snowpark code. The code tries to change the column name of a column that doesn’t exist. I slightly changed the test code.
> SNOW-1804052 Fix AST `col_alias.test`

- CHANGELOG.md
- docs/source/snowpark/dataframe.rst
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_datatype_suite.py
Fixes SNOW-1757892
This PR adds support to DataFrame.print_schema for nested data types. Before this change a nested schema would be printed like so:
```
root
|-- "MAP": MapType(StringType(), ArrayType(StructType([StructField('FIELD1', StringType(), nullable=True), StructField('FIELD2', LongType(), nullable=True)]))) (nullable = True)
```
After the change the nested schema will instead look like this:
```
root
|-- "MAP": MapType (nullable = True)
|   |-- key: StringType()
|   |-- value: ArrayType
|   |   |-- element: StructType
|   |   |   |-- "FIELD1": StringType() (nullable = True) …
```
> SNOW-1757892: Improve Dataframe.print_schema for structured types

- src/snowflake/snowpark/dataframe.py
Fixes SNOW-1755655
This pull request includes an update to the `cache_result` method in the `src/snowflake/snowpark/dataframe.py` file to provide additional documentation and clarity on the behavior of the method. The most important changes include adding a detailed note about the creation and lifecycle of the temporary table used to store the cached result.
Documentation improvements:
* [`src/snowflake/snowpark/dataframe.py`](diffhunk://#diff-9732895e18d0ffe66be3624d2aaefcba56260bcc238a6a0a598ef601512e03e8R4074-R4086): Added a note explaining that a temporary table is created to …
> SNOW-1755655: Add a note in cache_result about table name and temp table cleanup

- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- src/snowflake/snowpark/_internal/analyzer/schema_utils.py
- src/snowflake/snowpark/_internal/telemetry.py
- tests/integ/test_telemetry.py
Fixes SNOW-1637215
Add telemetry for describe query mentioned in https://docs.google.com/document/d/1DAN1I99BQd1CBBu_pLvWb9vLReTC7HIbfppxeVbXCSg/edit?tab=t.0#heading=h.r285g4qcslsz
> SNOW-1637215: Add describe query telemetry 

- tests/integ/test_session.py
sproc disallows new connection creation
> fix precommit test failure

- tests/integ/scala/test_datatype_suite.py
When the sql simplifier is disabled there is a set of braces in the query that don't get removed.
> SNOW-None: Fix structured type test when simplfier disabled

- tests/integ/test_multithreading.py
> NO-SNOW: Fix daily precommit test

- CHANGELOG.md
- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
- tests/unit/test_session.py
Fixes SNOW-1794381
This PR adds the following to `Session` class
- property `version` to get current snowpark client version.
- class method `get_active_session` and `getActiveSession` that return the current active session or `None` is there are no active sessions.
> SNOW-1794381: session api improvements

- src/snowflake/snowpark/_internal/ast_utils.py
- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/mock/_nop_plan.py
- src/snowflake/snowpark/mock/_udtf.py
- src/snowflake/snowpark/table_function.py
- src/snowflake/snowpark/udtf.py
- tests/ast/ast_test_utils.py
- tests/ast/data/DataFrame.to_pandas.test
- tests/ast/data/RelationalGroupedDataFrame.test
- tests/ast/data/udtf.test
- tests/ast/test_ast_driver.py
- tests/integ/scala/test_udtf_suite.py
- tests/integ/utils/sql_counter.py
Add Udtf registration that reuses the client registered UDTF.  Doesn't need all the previous parameters as they were only required for original creation of udtf.
Fix Full AST Validation to use same session for replay execution of unparser AST, thereby allowing reuse of client defined UDTFs.
> SNOW-1787415 Fix dataframe ast to register udtf for replay execution using client created udtf in same client session

- tests/integ/test_packaging.py
- tests/integ/test_stored_procedure.py
- tests/resources/test_requirements_unsupported.txt
snowflake 8.44 will have numpy 2.1.3 available in the package repo.
This breaks the test because previously numpy was uploaded to a stage and imported inside sproc or udf, however, after 8.44, the custom package logic will detect numpy 2.1.3 is available and use the version 2.1.3 which conflicts the numpy requirement by stored proc (numpy < 2.0a)
> SNOW-1818207: pin numpy to resolve package conflict in snowflake 8.44

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/ordered_dataframe.py
- tests/integ/modin/binary/test_binary_op.py
- tests/integ/modin/frame/test_align.py
- tests/integ/modin/series/test_align.py
- tests/integ/modin/test_ordered_dataframe.py
- tests/integ/test_cte.py
- tests/integ/utils/sql_counter.py
SNOW-1798141
The align operations is a very complicated operation when the alignment is not applied on the objects coming from the same dataframe, where extra steps are required to check whether columns are aligned etc. The extra checks requires generations of bunch of window function, which is inefficient.
However, when alignment is applied on the row positions columns, even if they are not coming from the same dataframe, we know they are unique, and some extra operations could be avoided.
> [SNOW-1798141] Improve align operation for align are performed on row position column by avoid unnecessary filter

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/test_dataframe.py
- tests/unit/compiler/test_large_query_breakdown.py
- tests/utils.py
Fixes SNOW-1815432
https://docs.snowflake.com/en/sql-reference/constructs/unpivot#parameters
> SNOW-1815432: Support `include_nulls` in unpivot

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/scala/test_dataframe_reader_suite.py
the previous implementation would convert bool("false") to True which is incorrect.
in snowflake, booleans are represented as "true" and "false" as per the doc: https://docs.snowflake.com/en/sql-reference/data-types-logical#boolean
> SNOW-1810534: fix boolean value parse in session.read.options

- tests/integ/modin/strings/test_strings.py
fallback_count has been deprecated for quite some time,  there is no such key called fallback_count in sql counter anymore.
> Remove non-existent sql counter fallback_count from test_string.py

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/ordered_dataframe.py
- src/snowflake/snowpark/modin/plugin/_internal/unpivot_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_transpose.py
Remove hack for transpose and melt which uses UNPIVOT_…NULL_REPLACE; now that UNPIVOT INCLUDE NULLS is implemented. Existing tests continue to pass.
Fixes SNOW-1032076
pre-review checklist:
> SNOW-1032076 - Remove hacks for Unpivot Null Handling

- tests/unit/test_types.py
This test: https://github.com/snowflakedb/snowpark-python/actions/runs/12020244963/job/33508548503
verified the fix is successful
> Fix daily precommit test when pandas not installed

- src/snowflake/snowpark/functions.py
- tests/ast/data/functions.test
Fixes SNOW-1831923
Added AST encoding for `size(<col or name>)` in functions.py. The test for this resides in `functions.test`.
> SNOW-1831923 Add AST encoding for `functions.size`

- src/snowflake/snowpark/mock/_nop_connection.py
- src/snowflake/snowpark/mock/_snowflake_data_type.py
fix the local testing change in https://github.com/snowflakedb/snowpark-python/commit/9f9398bcb4bb3435d20321d6d64d571eb2dde182
pandas is not a required dependency for snowpark python
in local testing we should avoid hard dependency on pandas which causes import error to users if pandas is not installed.
> SNOW-1842455: fix pandas import in local testing

- src/snowflake/snowpark/_internal/proto/update-from-devvm.sh
- src/snowflake/snowpark/session.py
Fixes SNOW-1842532
Removed an unnecessary comment, removed the example from the docstring of `auto_clean_up_temp_table_enabled` which was a merge artifact. See https://github.com/snowflakedb/snowpark-python/pull/2457/files.
> SNOW-1842532 Post-merge artifact removal

- .pre-commit-config.yaml
Fixes SNOW-1842673
decoder.py uses the match keyword that was introduced in Python 3.10. This keyword is not available in Python 3.9 and 
so there are many lint failures on that file. This PR adds the file to a "ignore" list. 
I have read the CLA Document and I hereby sign the CLA
> changes for avoiding linter errors

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-1843885.
Fixes AST error caused by `snowpark_round` where due to aliasing `session.ast_enabled` was not properly propagated.
> [SNOW-1843885] Fix error caused by snowpark_round

- CHANGELOG.md
- recipe/meta.yaml
- setup.py
relax cloudpickle constraint for python 311 so that we can have working noarch build for anaconda
there should be no impact to customer using python 311
> SNOW-1843819: relax snowpark python 3.11 cloudpickle dependency to unify anaconda no arch build

- tests/conftest.py
in stored proc it's unable to find pytest option "local_testing_mode".
giving a default value resolves the issue, however, it's still unknown why this doesn't happen before but happen after the IR PR merge.
probably because the fixture is referenced somewhere by the new tests. for now let's fix the issue to unblock release
successful running sproc precommit test job: 1490
> SNOW-1844280: fix stored proc pytest option issue

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-1846098: v1.26.0 release preparation 

- src/snowflake/snowpark/_internal/compiler/cte_utils.py
- tests/integ/test_cte.py
Fixes SNOW-1844465
The CTE optimization today will create a CTE out of a simple select * from TABLE, improve teh CTE by exclude such usage.
> [SNOW-1844465] Avoid creating a CTE out of simple select start on top of a select entity

- tests/ast/data/col_in_.test
- tests/ast/decoder.py
- tests/ast/test_ast_driver.py
Fixes SNOW-1830501, SNOW-1830503 (for try_cast)
Added decoder logic for Column APIs `in`, `between`, `try_cast`, `literal`, `__getitem__`.
`try_cast` is from ticket SNOW-1830503 (cast and alias are already implemented).
I had to modify the `col_in.test` to be logically correct (was taking in a list that was too long initially).
> SNOW-1830501 Column APIs implemented in decoder: `in`, `between`, `try_cast`, `literal`, `__getitem__`

- tests/ast/decoder.py
Fixes SNOW-1830505
Decoder logic for `equal_null`, `equal_nan`, `is_null`, `is_not_null`
> SNOW-1830505 Add column null/nan functions logic

- tests/ast/decoder.py
> Snow-1830500: Bit and unary operations on columns.

- tests/integ/test_cte.py
Fixes SNOW-1853194
Avoid disabling sql simplifier in integ/test_cte.py. 
In our daily test, we already run all test cases with sql simplifier disabled.
We also want to make all test cte cases consistent. Most of them do not explicitly disable sql simplifier.
> SNOW-1853194: Avoid disabling sql simplifier in integ/test_cte.py

- tests/integ/modin/io/test_read_snowflake_query_call.py
Fixes SNOW-1752915
Fix a flaky test involving system functions by using select (rather than call, which is incorrect and lead to flakiness).
Explanation for why the test is flaky/why this fix works: https://snowflakecomputing.atlassian.net/browse/SNOW-1752915?focusedCommentId=5988766
> [SNOW-1752915]: Fix flaky `read_snowflake` test

- src/snowflake/snowpark/modin/plugin/extensions/pd_extensions.py
Fixes SNOW-1852933
Makes documentation that we support stored procedures in `read_snowflake` more explicit.
> [SNOW-1852933]: Make stored proc support for `read_snowflake` more explicit

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/utils/numpy_to_pandas.py
- tests/integ/modin/frame/test_applymap.py
- tests/integ/modin/series/test_apply_and_map.py
Fixes SNOW-1801330
Map numpy functions to builtin snowpark function if exists. In POC this provided 5x speedup.
> SNOW-1801330: Map numpy functions in apply to builtin snowflake functions

- tests/integ/modin/test_apply_snowpark_python_functions.py
- tests/integ/test_function.py
Fixes SNOW-1859140
Skip Cortex function apply tests when run on Jenkins
> SNOW-1859140: Skip Cortex apply tests for Jenkins

- CHANGELOG.md
- tests/integ/test_lineage.py
Fixes SNOW-1854327
We have a new commit in snowflakedb (https://github.com/snowflakedb/snowflake/pull/230405) where we stop showing deleted nodes. This test relies on old behavior where we do show deleted nodes. The fix is to update the test to not expect deleted nodes.
> SNOW-1854327: fix test to exclude deleted nodes

- src/snowflake/snowpark/modin/plugin/docstrings/series_utils.py
Fixes SNOW-1859612
Enable skipped doctests for Series.str.center in the docs of Series.str.ljust/rjust.
> SNOW-1859612: Enable skipped doctests for Series.str.center in the docs of Series.str.ljust/rjust

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/utils/numpy_to_pandas.py
- tests/integ/modin/frame/test_apply.py
- tests/integ/modin/frame/test_apply_axis_0.py
Fixes SNOW-1801330
Map numpy universal functions (element-wise functions) and aggregate functions in df.apply to sql builtin functions.
> SNOW-1801330: Map numpy functions in df.apply to builtin functions

- tests/ast/decoder.py
Fixes SNOW-1830533
Added decoder logic for Dataframe NA functions, verified `df_col.test` also works (no logic needed to be explicitly added here).
> SNOW-1830533 Added decoder logic for Dataframe NA functions

- src/snowflake/snowpark/modin/plugin/docstrings/__init__.py
- src/snowflake/snowpark/modin/plugin/docstrings/datetime_index.py
- src/snowflake/snowpark/modin/plugin/extensions/datetime_index.py
Fixes SNOW-1865997
Use docstrings folder for DatetimeIndex methods and properties. Docstrings for TimedeltaIndex will be treated similarly in a follow-up PR
> SNOW-1865997: Use docstrings folder for DatetimeIndex methods and properties

- CHANGELOG.md
- docs/source/snowpark/dataframe.rst
- src/snowflake/snowpark/dataframe.py
Fixes SNOW-1794377
This PR adds an approximation of pysparks Dataframe.toJSON method. Notably Snowpark does not support RDDs so instead we return a Dataframe. Additionally Snowflake JSON methods don't support the `use_unicode` flag that pyspark provides so that is left out as well. We could add it as a dummy value for compatibility, but I think we should stick to what the Snowflake API can provide.
> SNOW-1794377: Add support for Dataframe.toJSON

- tests/ast/decoder.py
Fixes SNOW-1830534
Added decoder logic for the dataframe analytics functions. I "hardcoded" the col formatter lambda used since this is not necessary in the actual decoder but it helps pass the tests. It should not be hard to refactor out/remove.
> SNOW-1830534: Add decoder logic for the dataframe analytics functions

- src/snowflake/snowpark/session.py
- tests/ast/data/session_table_temp_table_cleanup.test
Fixes SNOW-981562
Expose `is_temp_table_for_cleanup` to `Session.table` API
> SNOW-981562: Expose is_temp_table_for_cleanup to Session.table

- src/snowflake/snowpark/_internal/compiler/utils.py
- tests/integ/test_large_query_breakdown.py
Fixes SNOW-1869362
Made the following improvements with this PR:
- Add threshold so only those plans which are above a threshold score are plotted.
- Note the name of with query block 
- Print the name of SnowflakeCreateTable
- Print the name of SelectableEntitity
- Shade with query blocks in gray.
> SNOW-1869362: Plan plotter improvements

- src/snowflake/snowpark/_internal/compiler/large_query_breakdown.py
- src/snowflake/snowpark/_internal/compiler/plan_compiler.py
- src/snowflake/snowpark/_internal/compiler/query_generator.py
- tests/integ/test_large_query_breakdown.py
Fixes SNOW-1865904
Update query generation for with query block where cte query is updated if the child plan is re-resolved during optimization process.
> SNOW-1865904 fix query gen when nested cte node is partitioned

- .github/workflows/enforce_localtest.yml
The nag comments for local testing add a lot of clutter to PRs. This change will instead fail the check with an error message.
> Fail local-testing check rather than add nag comment

- CHANGELOG.md
- src/snowflake/snowpark/types.py
- tests/unit/test_types.py
Fixes SNOW-1867961
This PR fixes a bug in `_parse_datatype_json_value` that failed to parse timestamp types that had timezone information. Previously the type strings for `timestamp_ntz`, `timestamp_ltz`, and `timestamp_tz` were not recognized as valid timezone types.
> SNOW-1867961: Fix from_json not working the TimestampType that contains tzinfo

- CHANGELOG.md
- docs/source/snowpark/dataframe.rst
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/test_dataframe.py
Fixes SNOW-1552377
This PR adds implementation for `Dataframe.flatmap` and refactors implementation of `Dataframe.map` to de-duplicate common code used in flatmap.
> SNOW-1552377: Add support for flatmap using udtf

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/groupby.py
- tests/integ/modin/frame/test_apply.py
- tests/integ/modin/frame/test_apply_axis_0.py
- tests/integ/modin/frame/test_applymap.py
- tests/integ/modin/frame/test_cache_result.py
- tests/integ/modin/groupby/test_all_any.py
- tests/integ/modin/groupby/test_groupby_apply.py
- tests/integ/modin/groupby/test_groupby_transform.py
- tests/integ/modin/series/test_apply_and_map.py
- tests/integ/modin/test_session.py
- tests/integ/modin/test_sql_counter.py
- tests/integ/modin/utils.py
> SNOW-1739034: Unskip tests requiring pandas 2.2.3 in anaconda.

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
- tests/integ/modin/frame/test_applymap.py
- tests/integ/modin/series/test_apply_and_map.py
- tests/unit/modin/test_apply_utils.py
SNOW-1852925 & SNOW-1852928
Add type inference for DataFrame.map, Series.apply and Series.map
> SNOW-1852925: Add type inference for Series.apply/map and Dataframe.map

- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
Fixes SNOW-1877144
Use only small dummy values here to avoid the risk of certain callables
taking a long time to execute (where execution time is a function of the input value).
As a downside this reduces diversity in input data so will reduce the effectiveness
type inference framework in some rare cases.
> SNOW-1877144: Use only small values in dummy input for type inference

- CHANGELOG.md
- docs/source/modin/supported/groupby_supported.rst
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/docstrings/groupby.py
- src/snowflake/snowpark/modin/plugin/extensions/groupby_overrides.py
- tests/integ/modin/groupby/test_groupby_apply.py
Support include_groups=False in groupby.apply.
When include_groups=False, we exclude grouping columns from the inputs to the user-supplied `func`.
This commit changes `func` in some groupby.apply tests where `func` assumes that the grouping columns are in the inputs.
Fixes SNOW-1847174
> SNOW-1847174: Support include_groups=False in groupby.apply.

- src/snowflake/snowpark/functions.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/test_function.py
- tests/utils.py
Fixes SNOW-1873566
With use of `filter` and `reduce` implement `_concat_ws_ignore_nulls` that accepts string columns and array of string columns as input and concatenates all the strings in given order by ignoring nulls.
> SNOW-1873566: Allow array type inputs to _concat_ws_ignore_nulls

- pyproject.toml
- setup.py
Fixes SNOW-1877354
As described in the linked JIRA, the `protoc-wheel-0` and `mypy-protobuf` dev dependencies must be installed _before_ `setup.py` is run, so a clean `pip install snowflake-snowpark-python[development]` will error if these packages were not installed beforehand. By adding `pyproject.toml` according to [these instructions](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/#how-to-handle-additional-build-time-dependencies), we're able to specify these dependencies before `setup.py` is invoked, thereby removing the need to explicitly `pip install` …
> SNOW-1877354: Add pyproject.toml and tox dev dependency

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
Fixes SNOW-1873676
Fixed a bug in `date_format` that allows date and timestamp columns. In old code, try_cast was applied on date or timestamp columns would throw
```
Function TRY_CAST cannot be used with arguments of types DATE and TIMESTAMP_NTZ()
```
In this fix, we are converting all input to string first and then, converting them into Timestamp type.
> SNOW-1873676: Fix date_format bug

- .github/workflows/precommit.yml
- src/conftest.py
Two of the doctests for snowflake.snowpark.Session require packages that are not available anymore for python 3.8 which causes a failure in our daily precommit tests. To fix this there are a few options:
1 Skip the doctests entirely.
2 Add some code in the doctest that skips it conditionally.
3 Intercept the doctest finder so that it does not include those tests when running in python 3.8.
I've opted for option 3 so that the tests can still be run on other python versions and there isn't code that might be confusing to readers in the examples.
> Disable python 3.8 incompatible doctest

- src/snowflake/snowpark/mock/_nop_connection.py
- src/snowflake/snowpark/mock/_nop_plan.py
- tests/ast/data/Dataframe.to_snowpark_pandas.test
Fixes SNOW-1882338
Add logic to the no-op AST testing code to create a temp read-only table for to_snowpark_pandas. This way `to_snowpark_pandas` works with both `nop` mode and `local_testing_mode`.
> SNOW-1882338 Fix AST `to_snowpark_pandas` test in nop testing mode

- src/snowflake/snowpark/mock/_nop_connection.py
- src/snowflake/snowpark/mock/_nop_plan.py
- tests/ast/data/Dataframe.to_snowpark_pandas.test
- tests/ast/decoder.py
Fixes SNOW-1830529
Added decoder logic for `to_local_iterator`, `to_pandas`, `to_snowpark_pandas`, and `to_pandas_batch`.
> SNOW-1830529 Add decoder logic for `to_local_iterator`, `to_pandas`, `to_snowpark_pandas`, and `to_pandas_batch`

- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/mock/_udtf.py
- tests/ast/data/functions1.test
> SNOW-1865910: fixing minor typos

- CHANGELOG.md
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
- tests/unit/test_types.py
Fixes SNOW-1871175
Support schema string
> SNOW-1871175: Add support for specifying a schema string for `DataFrame.create_dataframe`

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/types.py
- tests/integ/scala/test_datatype_suite.py
- tests/unit/test_types.py
Fixes SNOW-1853342
This PR adds support for the `contains_null` parameter to structured ArrayType objects. By default semi-structured and structured array columns allow null values. By setting contains_null in the ArrayType initilization we can specify that no elements of the array are null.
Note that Snowflake cannot create a table with a schema like `arr ARRAY(INT NOT NULL)` the column also has to be non-nullable like so `arr ARRAY(INT NOT NULL) NOT NULL`. Because of this and the fact that Snowpark uses select statements that are nullable by default, the nullability of a column and …
> SNOW-1853342: Add support for contains_null to ArrayType

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/types.py
- tests/integ/scala/test_datatype_suite.py
- tests/unit/test_types.py
Fixes SNOW-1847626
This PR adds support for value_contains_null to DictType objects. Structured map type columns never have nullable keys, but can have nullable values. This adds a parameter to the initializer that allows specifying.
> SNOW-1847626: Add support for value_contains_null to MapType

- src/snowflake/snowpark/_internal/ast/utils.py
- tests/ast/data/Session.create_dataframe.test
- tests/ast/decoder.py
Fixes SNOW-1830544, SNOW-1830604
Added decoder logic for Session.create_dataframe, Window/WindowSpec, and Session.range. Did not add logic for Session.create_dataframe_from_pandas since the test is disabled.
> SNOW-1830544, SNOW-1830604 Decoder logic for Session.create_dataframe, Window/WindowSpec, and Session.range 

- tests/integ/modin/frame/test_quantile.py
Fixes SNOW-1229442
A single `df.quantile` call with large data + many quantiles previously emitted 81 queries, many of which were duplicate temp table operations. After #2090, this number was reduced to 6, so we can remove the `pytest.skip` on the offending test.
> SNOW-1229442: Remove skipped large `df.quantile` test

- tests/integ/modin/test_telemetry.py
Please describe how your code solves the related issue.
test_telemetry_func_call_count is failing with error 
```
2025-01-23T06:42:31.0419150Z [31mFAILED[0m tests/integ/modin/test_telemetry.py::[1mtest_telemetry_func_call_count[0m - IndexError: list index out of range
```
It seems the Dataframe.__repr__ is occurred once in the result telemetry data. Turn this test off for now.
> Turn off test_telemetry_func_call_count for github failure

- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/conftest.py
- tests/integ/test_catalog.py
- tests/integ/test_df_to_pandas.py
- tests/integ/test_lineage.py
- tests/integ/test_pandas_to_df.py
- tests/unit/test_cte.py
- tox.ini
Fixes SNOW-1891120
This PR cleans up a few issues in our precommit jobs.
- Fixes several warnings
- `src/snowflake/snowpark/dataframe_reader.py` -> Change to non-deprecated logger method
- `tests/integ/test_df_to_pandas.py` -> Change to use iloc since positional access is deprecated.
- `tests/integ/test_pandas_to_df.py` -> Change a couple of calls that emit warnings that aren't tested.
- `tests/unit/test_cte.py` -> rename helper functions so pytest doesn't consider them test cases.
- `tox.ini` -> Add marks that are missing so that pytest doesn't emit missing mark warnings.
- Attempts …
> SNOW-1891120: Clean-up precommit

- tests/integ/modin/frame/test_apply.py
- tests/integ/modin/frame/test_apply_axis_0.py
- tests/integ/modin/frame/test_cache_result.py
- tests/integ/modin/groupby/test_groupby_apply.py
- tests/integ/modin/series/test_apply_and_map.py
- tests/integ/modin/series/test_items.py
- tests/integ/modin/window/test_rolling.py
Please describe how your code solves the related issue.
Turn off couple of time consuming tests of snowpark pandas. The test turned off in the github took over miniutes to finish
verified with jenkins run https://snowpark-python-001.jenkinsdev1.us-west-2.aws-dev.app.snowflake.com/job/SnowparkPythonSnowPandasDailyRegressRunner/197458/
> [SNOW-1894051]Turn off time consuming test from github actions

- .github/workflows/daily_precommit.yml
- .github/workflows/precommit.yml
Fixes NO-SNOW
This PR reduces the matrix for python 3.12 support in branch precommits in order to reduce strain on the testing warehouse. Additionally, it reduces the matrix for local testing to reduce strain on github runners.
> NO-SNOW: Limit Python 3.12 and local testing suites

- .github/workflows/precommit.yml
Fixes NO-SNOW
This PR spreads the ast test runs across CSPs to reduce load on AWS.
> NO-SNOW: Spread AST tests across CSPs

- src/snowflake/snowpark/_internal/ast/batch.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- src/snowflake/snowpark/types.py
- tests/ast/data/RelationalGroupedDataFrame.test
- tests/ast/data/udtf.test
- tests/ast/decoder.py
- tests/ast/test_ast_driver.py
Fixes SNOW-1830603
- Got UDTFs to work
- changed the UDTF test (will prob go through another change in the future and will make a change to this test in main then).
- got RelationalGroupedDataFrame to work
- added a way to reset the recorded callables and their IDs
> SNOW-1830603 UDTFs for the decoder

- tests/ast/data/Table.merge.test
- tests/ast/decoder.py
Fixes SNOW-1830580
Added decoder logic for tests starting with "Tables.*", fixed Table.merge test issues.
> SNOW-1830580 Decoder logic for tables

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/mock/_nop_analyzer.py
- src/snowflake/snowpark/mock/_plan.py
- src/snowflake/snowpark/mock/_select_statement.py
- tests/integ/compiler/test_query_generator.py
- tests/integ/test_multithreading.py
- tests/unit/compiler/test_large_query_breakdown.py
- tests/unit/compiler/test_replace_child_and_update_node.py
- tests/unit/test_cte.py
- tests/unit/test_deepcopy.py
- tests/unit/test_query_plan_analysis.py
Fixes SNOW-1878372
In this change, we make the following changes to `Selectable`:
- the analyzer object is accessed via a thread so that each selectable uses the analyzer created for the dedicated thread.
- the analyzer can be set to a different analyzer only during optimization stage when `_is_valid_for_replacement=True`.
We also update `Analyzer` to initialize `alias_maps_to_use` with an empty dict `{}` instead of `None`. In single threaded-case, `resolve` would initialize alias_maps_to_use to `{}` and then use it for `analyze` but in multithreaded-case, it is possible for one …
> SNOW-1878372: Fix analyzer access across threads

- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/types.py
- tests/ast/data/sproc.test
- tests/ast/decoder.py
> changes for fixing sp_struct_type decoding

- tests/integ/modin/frame/test_applymap.py
- tests/integ/modin/series/test_apply_and_map.py
test_args_and_kwargs is the only test that is flaky and failing now, turn this off to mitigate merge gate issue. Investigate tracked by ticket https://snowflakecomputing.atlassian.net/browse/SNOW-1896426
> [SNOW-1896426] Turn off test_args_and_kwargs to mitigate merge gate failure

- tests/integ/modin/groupby/conftest.py
- tests/integ/modin/groupby/test_groupby_default2pandas.py
- tests/integ/modin/groupby/test_groupby_ngroups.py
- tests/integ/modin/groupby/test_groupby_series.py
Fixes SNOW-890686
The test named in the PR was separated from the more general test because of a pandas bug with `groupby(sort=False)` that was fixed in 2.0.X. This PR removes this test and adds parametrization on the `sort` parameter to `test_groupby_sort_multiindex_series`.
This PR incidentally reduces some query counts by changing a test fixture from a Snowpark pandas Series to a native one to avoid some materializations.
> SNOW-890686: Remove test_groupby_sort_false_multiindex_series

- tests/integ/test_lineage.py
Fixes SNOW-1894152
The test example started failing due to a recent BCR that enabled secondary roles by default. The added statement should ensure that the test role is unable to see the data that is supposed to be masked in this test. For more information see here:
https://community.snowflake.com/s/article/default-secondary-roles-all-overview-and-additional-explanations
> SNOW-1894152: Fix test_lineage_trace failure

- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/types.py
- tests/ast/data/sproc.test
- tests/ast/decoder.py
Fixes SNOW-1794510
Added docstrings and rearranged the cases to be in alphabetical order.
> SNOW-1794510 refactor decoder

- tests/integ/conftest.py
Fixes NO-SNOW
This change reduces change the external access integrations to use static names. These integrations don't appear to have any test session specific requirements so they do not need to be recreated every session. This solves the issue of the integrations getting leaked causing a build-up of unused integrations. It would be better to understand how that leak was occurring.
> SNOW-1891120: Use static names for test integrations

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
- tests/unit/test_internal_utils.py
Fixes SNOW-1793953 (https://github.com/snowflakedb/snowpark-python/issues/2888)
This builds on the changes from #1346 to allow `/` as a remote path prefix so `file.get('/some/path')`will not try to prepend `@` to the path. This form of relative path is valid in some native application uses cases.
> accept stage paths starting with / for GET

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-1897441
When calling `describe` on a DataFrame with object columns, pandas will report a `top` column identifying the value that appears most frequently. If the top two values share the same frequency, [pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) indicates that it actually does not provide any stability guarantees:
> If multiple object values have the highest count, then the count and top results will be arbitrarily chosen from among those with the highest count.
Tests involving this behavior are currently failing on …
> SNOW-1897441: Fix missing row position sort in DataFrame.describe

- tests/ast/data/DataFrame.write.test
- tests/ast/decoder.py
Fixes SNOW-1901851
- UDTF AST does not need to be changed -- I figured out a way to distinguish between when a call like `udtf(<params>)` needs to be treated as a `TableFunctionCall` object vs when it actually needs to be executed. (In the AST both of these are recorded as `apply_expr`, which is not informative.) I tell the difference based on the "outer AST" or the function using the `apply_expr`. More details in the code.
- I modified the `Dataframe.write.test` code only for the decoder since one of the lines in the test has chained calls to `option(...)` that modify the same …
> SNOW-1901851 Fix UDTFs (TableFunctionCall vs function invocation) and a couple tests

- src/snowflake/snowpark/_internal/compiler/large_query_breakdown.py
- src/snowflake/snowpark/_internal/compiler/utils.py
- tests/integ/test_large_query_breakdown.py
Fixes SNOW-1734385
When large query breakdown partitions node such that the child node being partitioned is a `WithQueryBlock`, do not create a cte. Instead, use the underlying sql to materialize it as a table.
> SNOW-1734385: Do not create CTE when partitioning WithQueryBlocks

- tests/integ/test_scoped_temp_objects.py
it's related to a parameter change
reenable skipped test after parameter revert
> SNOW-XXXXXX: reenable skipped test after parameter revert

- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/test_data_source_api.py
Fixes SNOW-1887901
fix partition logic, now it would generate same results as spark do
> SNOW-1887901: fix partitioning logic

- src/snowflake/snowpark/session.py
- tests/integ/scala/test_datatype_suite.py
Fixes SNOW-1901507
This PR fixes an issue with `Session.create_dataframe` calls that would require a temp table creation. The issue caused incorrect schema_query generation when creating dataframes with non-nullable structured type columns. This was due to the temp table being created with a structured schema, but the schema query was expecting a string field instead.
This PR fixes the problem by deferring temp table creation until after the schema attributes have been modified to account for data serialization. I've added a test that provides a scenario that would have thrown a sql …
> SNOW-1901507: Fix non-nullable struct type schema expressions

- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
Fixes SNOW-1911279
Fix doctest python 3.12 issue for Series.to_dict. The doctest is skipped because python 3.12 behaves differently than earlier python versions, causing tests running in the python 3.12 environment to fail.
> SNOW-1911279: Fix doctest python 3.12 issue for to_dict

- src/snowflake/snowpark/_internal/proto/ast.proto
- tests/ast/ast_test_utils.py
Fixes SNOW-1914374
This is a test-only change.
When the AST unparser fails, it's frequently unclear why.
Capture the STDERR of the unparser on failure and add a new exception to the exception chain. Preserve the original `CallProcessError`, as well.
> SNOW-1914374 Capture the AST unparser STDERR on failure

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/session.py
- tests/integ/test_df_to_arrow.py
Fixes SNOW-1846317
This PR adds new methods `to_arrow` and `to_arrow_batches` to DataFrames. This methods converts the DataFrame to a local pyarrow Table. They work similarly to `to_pandas` and `to_pandas_batches` without having to pass through pandas.
Additionally this PR adds support for `session.write_arrow` which allows writing a pyarrow Table to a snowflake table with similar configuration options to that given by `sesison.write_pandas`. The bulk of this functionality should probably be pushed down into the connector, but that will cause some dependency issues.
> SNOW-1846317: Add support for reading/writing arrow data

- CHANGELOG.md
- docs/source/snowpark/functions.rst
- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Fixes SNOW-1916378
BCR: Remove Snowpark python functions snowflake_cortex_summarize and snowflake_cortex_sentiment since users can use functions from Cortex directly.
> SNOW-1916378: Remove Snowpark python functions snowflake_cortex_summarize and snowflake_cortex_sentiment

- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/metadata_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/test_reduce_describe_query.py
Fixes SNOW-1904798
When reduce describe query change is enabled, the snowpark client will update the underlying schema query for `SnowflakePlan` and `SelectStatement` so that future plans that are built on top of current will use a simpler schema query.
> SNOW-1904798: Update schema query when attributes are available

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/test_dataframe.py
Fixes SNOW-192360
Local testing had a bug where the type information for columns would be in correct if multiple columns were specified in the `on` parameter. The names of the columns were correctly reordered, but not the types. This change updates the types as well in order to avoid this issue.
> SNOW-192360: [Local Testing] Fix Join On column order

- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/dataframe.py
- tests/ast/data/Dataframe.show.test
Fixes NOSNOW
Dataframe.show was incorrectly recorded in the AST -- there was no logic transmitting the value of `n`/number of rows to retrieve for show. I added `n` to the corresponding AST and added a Dataframe.show test for it.
> NOSNOW - Add `n` to the recorded Dataframe.show AST, add Dataframe.show test

- tests/integ/modin/frame/test_iloc.py
- tests/integ/modin/frame/test_itertuples.py
- tests/integ/modin/frame/test_loc.py
- tests/integ/modin/series/test_items.py
Fixes SNOW-1934822
We removed set/unset query tag queries in a recent change
SNOW-1909920: Remove stacktrace from query-tag (#2981)
This reduced query count by 2 for all tests that materialize data as intermediate step. This PR fixes query count for some tests which we don't run in precommit but only in daily regress runner. 
Success Run with this PR: https://snowpark-python-001.jenkinsdev1.us-west-2.aws-dev.app.snowflake.com/job/SnowparkPythonSnowPandasDailyRegressRunner/197533
> SNOW-1934822: Fix query count mismatch in pandas tests

- recipe/meta.yaml
Fixes SNOW-1936459
Previously, when upgrading the version of the `modin` package required by Snowpark pandas, users in Snowflake environments (and our server-side test cases) ran into issues where the conda installation would pick a newer version of modin before Snowpark pandas released with support for it. This creates an annoying situation where we would need to attempt to synchronize the addition of a newer version of `modin` into the Snowflake Anaconda channel with the corresponding release of Snowpark Python that supports it.
As it turns out, conda recipes can define a …
> SNOW-1936459: Add modin as optional dependency to meta.yaml

- CHANGELOG.md
- src/snowflake/snowpark/catalog.py
- tests/integ/test_catalog.py
Fix a minor bug in catalog parsing where empty string was not treated the same as `None` when input argument is `database` or `schema`. This is creating issues for SAS
> NO-SNOW: Fix catalog parsing bug

- tests/integ/modin/series/test_hist.py
Fixes SNOW-1937038
Fix test_hist for the sproc environment. The tests in test_hist.py attempt to create a subdirectory directory in the current directory to output the image files corresponding to the charts generated by snowpack pandas and native pandas, and then compare them. For sprocs, creating a subdirectory in the current (root) directory is not allowed.
This PR skips those tests whenever the sproc environment is detected.
> SNOW-1937038: Fix test_hist for the sproc environment

- setup.py
- tests/integ/modin/test_apply_snowflake_cortex_functions.py
snowflake-ml-python, which provides snowflake.cortex, is not available on python 3.12. Skip the cortex Snowpark pandas tests on python versions >= 3.12.
Fixes SNOW-1934027
- daily tests run with python 3.9 and 3.10 using this branch: https://github.com/snowflakedb/snowpark-python/actions/runs/13405095565
- daily tests run with python 3.11 and 3.12 using this branch: https://github.com/snowflakedb/snowpark-python/actions/runs/13405093963
> SNOW-1934027: Skip cortex tests on python 3.12.

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
- tests/integ/modin/series/test_rename_axis.py
Fixes SNOW-1938767
Fix a `Series.rename_axis` bug, where the method `_set_axis_name` was only defined for `DataFrame` but not for `Series`. And hence an `AttributeError` was being raised whenever `Series.rename_axis` (which calls `_set_axis_name` internally) is called.
> SNOW-1938767: Fix Series.rename_axis AttributeError bug

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/groupby_overrides.py
- tests/integ/modin/groupby/test_groupby_transform.py
- tests/integ/utils/sql_counter.py
Fixes SNOW-1926346
This PR reimplements groupby.transform which does not use pivot. Output of transform maintains same row index as existing dataframe and column index omits by columns. We use this property of transform to correctly create output schema of UDTF and avoid expensive pivot step.
Note: We still generate VARIANT columns (same as existing implementation). In follow up PR use type inference framework to return correct types in output.
Note: It's possible that lambda passed in transform does not adhere to expected output schema. It should be rare but will improve this as well …
> SNOW-1926346: Implement groupby transform without pivot

- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udaf.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/conftest.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Fixes SNOW-1708509
This PR adds two new arguments to functions `udf`, `udtf`, `udaf`, and `sproc` calls as well as their corresponding registration functions. The arguments include:
- artifact_repository: Specifies an artifact repository integration to get packages from.
- artifact_repository_packages: Packages that should be added to the udxf or sproc from the artifact repository.
This feature feature has not been rolled out yet, but we do have access to it in our test account. Access to the arguments is being provided through kwargs on each affect function so that they don't show up …
> SNOW-1708509: Add support for artifact_repository to udxf

- tests/ast/data/functions2.test
[SNOW-1821290](https://snowflakecomputing.atlassian.net/browse/SNOW-1821290)
Remove `sp` prefixes from AST expectation tests for new fns added in previous commit.
[SNOW-1821290]: https://snowflakecomputing.atlassian.net/browse/SNOW-1821290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-1821290: Fix AST tests for recently added fns

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_window_frame_suite.py
Fixes SNOW-1923778
This PR adds support for literal values to the `range_between` window function. It also refactors `handle_range_frame_indexing` to remove repeated work from the for loops.
> SNOW-1923778: [Local Testing] Add support for literal values to range_between

- CHANGELOG.md
- src/snowflake/snowpark/_internal/compiler/cte_utils.py
- tests/integ/test_cte.py
Fixes SNOW-1906574
In this PR we update duplicate node detection logic where we invalidate any `WithQueryBlock` to contain a `SelectFromFileNode` as a child in its subtree. We do this by detecting `SelectFromFileNode` as a leaf and doing a bottom-up traversal, marking all parent as invalid in the deduplication logic.
> SNOW-1906574: Skip creating CTE on SelectFromFileNode

- tests/integ/test_multithreading.py
Example failure like [this](https://github.com/snowflakedb/snowpark-python/actions/runs/13510272232/job/37748997923?pr=3049) happens because a non-thread-safe session is running multi-threaded code. Update the test so that we only run one thread when multithreading is disabled.
> NO-SNOW: Fix flakiness giving RuntimeError

- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_reader.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
[SNOW-1918329](https://snowflakecomputing.atlassian.net/browse/SNOW-1918329)
This PR removes the following specialized `Expr` subtraits, and updates the Unparser to continue handling the roundtrip Expectation tests from the client repo.
- RelationalGroupedDataframeExpr
- DataframeReader
- DataframeWriter
- DataframeExpr
- FnRefExpr
- MatchedClause
- Regarding the removed TODO, I believe the extensions of this subtrait should be `Expr`s as they can be constructed independently and assigned. 
The above met all of the following criteria to be candidates for removal
- The trait doesn't …
> SNOW-1918329: Remove specialized Expr subtraits

- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Fixes SNOW-1950580
i. Fixed a bug in `_concat_ws_ignore_nulls` function which failed with `col.get_name()` returns None.
ii. Improved the implementation by using `array_to_string` which is already supported in snowflake instead of custom implementation of `concat_strings_with_sep` function using `reduce` and `substring`
> SNOW-1950580: Fix bug in snowpark concat ws ignore nulls

- tests/integ/test_stored_procedure.py
> NO-SNOW: skip tests in sproc that uses unavailable snowpark package

- src/snowflake/snowpark/_internal/ast/utils.py
- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_na_functions.py
- src/snowflake/snowpark/dataframe_stat_functions.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/table.py
- src/snowflake/snowpark/types.py
- tests/ast/data/DataFrame.count2.test
- tests/ast/data/DataFrame.stat.test
- tests/ast/data/DataFrame.write.test
- tests/ast/data/Dataframe.drop_duplicates_snow1874622.test
- tests/ast/data/Dataframe.to_snowpark_pandas.test
- tests/ast/data/DataframeNaFunctions.test
- tests/ast/data/RelationalGroupedDataFrame.test
- tests/ast/data/Session.call.test
- tests/ast/data/Session.create_dataframe.test
- tests/ast/data/Session.create_dataframe_from_pandas.test
- tests/ast/data/Session.table_function.test
- tests/ast/data/Table.merge.test
- tests/ast/data/col_cast.test
- tests/ast/data/col_cast_coll.test
- tests/ast/data/col_try_cast.test
- tests/ast/data/col_udf.test
- tests/ast/data/session.read.test
- tests/ast/data/sproc.test
- tests/ast/data/udaf.test
- tests/ast/data/udtf.test
[SNOW-1941023](https://snowflakecomputing.atlassian.net/browse/SNOW-1941023)
This PR contains the necessary changes to ensure correct AST generation after removing optionality from all `Option[List[T]]` and `Option[Map[T1, T2]]` type fields. We use an empty collection as an indicator of a missing value.
Slight modifications were made to make `StructType` AST building more concise.
It also removes the `eval` statement generation from `dataframe.stat.sample_by` which is not an eager API.
This PR is accompanied by [a server-side PR](https://github.com/snowflakedb/snowflake/pull/261101). …
> SNOW-1941023: Remove optionality for collections

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/get_dummies_utils.py
- tests/integ/modin/strings/test_get_dummies_dataframe.py
Fixes SNOW-1945131
Calling `pd.get_dummies` multiple times on the same DataFrame resulted in a 'Duplicated column name error'.
This happens when pivoted columns have at least one common value (including NULL). This PR fixed issue by renaming snowflake identifiers to avoid duplicated column names.
> SNOW-1945131: Bug Fix: Duplicate column error in get_dummies

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/strings/test_get_dummies_dataframe.py
SNOW-1954801
Fixes SNOW-1954801
`prefix` list generated in snowflake_query_compiler didn't account for columns list passed to get_dummies but always started with first column of dataframe. This resulted in incorrect column labels in output DataFrame. This PR fixes the issue by simply reusing columns list passed to populate prefix list.
Also added some validation to ensure columns list and prefix list have same lengths (same as native pandas)
> SNOW-1954801: Bug Fix: Passing list of columns in get_dummies generates incorrect column labels

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-1432556
Improve error message for to_snowflake table already exists.
> SNOW-1432556: Improve error message for to_snowflake table already exists

- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
Fixes SNOW-1960273
Add default statement params to UDxF creation jobs. Mainly snowpark_api = pandas which we use to identify pandas queries.
> SNOW-1960273: Set statement parameters for UDxF creation job from apply

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/get_dummies_utils.py
- src/snowflake/snowpark/modin/plugin/docstrings/general.py
- tests/integ/modin/strings/test_get_dummies_dataframe.py
Fixes SNOW-1952334
native pandas made get_dummies() return bools instead of ints in pandas 2: https://github.com/pandas-dev/pandas/issues/45848
This PR updates snowpark pandas to return bool columns instead of int columns in get_dummies().
> SNOW-1952334: get_dummies should return bool columns instead of int

- tests/integ/modin/test_modin_stored_procedures.py
Fixes SNOW-1758760
Some sproc tests were previously skipped while updating from modin 0.28.1 -> 0.30.1, and we neglected to restore them. Because Snowpark 1.29.0 now requires modin to be 0.30.1 if present, this started causing failures in the daily test where we were pinning the older version of modin (https://github.com/snowflakedb/snowpark-python/actions/runs/13720319594/job/38374328285).
> SNOW-1758760: Unpin modin/pandas versions in sproc tests

- src/snowflake/snowpark/dataframe_reader.py
- src/snowflake/snowpark/dataframe_writer.py
[SNOW-1961756](https://snowflakecomputing.atlassian.net/browse/SNOW-1961756)
Propagate `_emit_ast=False` across all internal calls to public APIs for new `dbapi` functionality.
Importantly, we will capture uses of `session.read.dbapi` as calls to `session.table` since we only support this functionality on the client side. Attempting to capture the call would mean creating an AST entity for `session.read.dbapi` specifically just to have it show up in query history, and this does not seem valuable from an AST or server-side execution perspective. 
[SNOW-1961756]: …
> SNOW-1961756: Enable AST capture from Session.read.dbapi

- src/snowflake/snowpark/_internal/ast/utils.py
- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_na_functions.py
- src/snowflake/snowpark/dataframe_stat_functions.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/modin/plugin/_internal/session.py
- tests/ast/data/DataFrame.count2.test
- tests/ast/data/DataFrame.create_or_replace.test
- tests/ast/data/DataFrame.flatten.test
- tests/ast/data/DataFrame.stat.test
- tests/ast/data/DataFrame.to_local_iterator.test
- tests/ast/data/DataframeNaFunctions.test
- tests/ast/data/Session.create_dataframe_from_pandas.test
- tests/ast/data/Session.flatten.test
- tests/ast/data/col_within_group.test
- tests/ast/data/functions1.test
- tests/ast/data/functions2.test
- tests/ast/data/session.read.test
- tests/ast/data/session_generator.test
- tests/ast/data/session_write_pandas.test
- tests/ast/data/shadowed_local_name.test
[SNOW-1918334](https://snowflakecomputing.atlassian.net/browse/SNOW-1918334)
Also fixes [SNOW-1952291](https://snowflakecomputing.atlassian.net/browse/SNOW-1952291)
The following changes are included in this PR
- After calls to `Dataframe.cache_result` there were `df.write` lines being generated - fixed with reference to use of `self.write` in `Dataframe.to_snowpark_pandas()`
- AST capture for several functions was fixed by using helper methods like `build_function_expr` and `build_builtin_fn_apply`
- `is_distinct` parameter was not being captured in calls to `array_agg`
- …
> SNOW-1918334: Various fixes to capture user code more accurately

- CHANGELOG.md
- docs/source/modin/supported/dataframe_supported.rst
- docs/source/modin/supported/series_supported.rst
- src/snowflake/snowpark/modin/plugin/_internal/cumulative_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/groupby_utils.py
- src/snowflake/snowpark/modin/plugin/_internal/resample_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_overrides.py
- src/snowflake/snowpark/modin/plugin/extensions/groupby_overrides.py
- tests/integ/modin/groupby/test_groupby_default2pandas.py
- tests/integ/modin/groupby/test_groupby_get_group.py
- tests/integ/modin/groupby/test_groupby_series.py
- tests/integ/modin/groupby/test_groupby_size.py
- tests/integ/modin/groupby/test_groupby_with_grouper.py
- tests/unit/modin/test_groupby_utils.py
Fixes SNOW-856100
Adds support for `pd.Grouper` objects in groupby operations. These objects allow specification of individual labels or index levels, and allow resampling via the `freq` argument if the specified column is a datetime/timestamp.
This changes the code paths for almost every query compiler groupby operation. If a column would be resampled by a Grouper object, its values are now replaced by the corresponding bin it belongs to before the grouping operation is performed. Most operations (including all that invoke `groupby_agg`) have been updated to follow this behavior; …
> SNOW-856100: pd.Grouper support

- tests/integ/scala/test_datatype_suite.py
- tests/integ/scala/test_result_attributes_suite.py
- tests/integ/scala/test_result_schema_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_packaging.py
- tests/integ/test_pandas_to_df.py
- tests/utils.py
Fixes SNOW-1938099
Several tests have been broken by a server side change in our test accounts. It appears that the default string size has been changed from 16mb to 128mb. I suspect this is caused by some parameter related to the LOB rollout. Confusingly though this only affects `select` statements and not table creation statements or statements that get various forms of metadata. I've updated all affected tests to either rely on the max string sized specified by the server or to explicitly use 16mb when appropriate.
> SNOW-1938099: Fix tests broken by default lob size change

- CHANGELOG.md
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/dataframe_na_functions.py
- tests/integ/test_dataframe.py
- tests/utils.py
Fixes SNOW-1952124
We found a problem where `int`s and `float`s should be able to fit into `Decimal` columns without problems. We have seen this discrepancy in `fillna` and `replace` functionalities.
In this PR I fix this behavior, but place it behind a flag argument and test these new/old behaviours.
> SNOW-1952124 decimal coercion

- CHANGELOG.md
Fixes SNOW-1992317
Fix changelog by moving missed updates from 1.28 to 1.30.
> SNOW-1992317: Fix changelog by moving missed updates to their correct versions: 1.28.0->1.29.0 and 1.29.0->1.30.0

- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_na_functions.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table.py
- src/snowflake/snowpark/table_function.py
- src/snowflake/snowpark/udaf.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- src/snowflake/snowpark/window.py
- tests/ast/conftest.py
- tests/ast/data/DataframeNaFunctions.test
- tests/ast/data/RelationalGroupedDataFrame.test
- tests/ast/data/col_udf.test
- tests/ast/data/df_map.test
- tests/ast/data/df_random_split.test
- tests/ast/data/functions.table_functions.test
- tests/ast/data/functions1.test
- tests/ast/data/functions2.test
- tests/ast/data/sproc.test
- tests/ast/data/udaf.test
- tests/ast/data/udtf.test
- tests/ast/test_ast_driver.py
- tests/unit/test_session.py
[SNOW-1916224](https://snowflakecomputing.atlassian.net/browse/SNOW-1916224)
Updates `dataframe.na.{replace,fill}` to add the new `include_decimal` parameter to the AST.
Adds the `@publicapi` decorator to APIs missing it
- `DataframeWriter.{partition_by, option, options}`
- `functions.fl_is_{video, document, compressed, image}`
- Overload of `Table.merge`
- `GroupingSets.__init__` in `relational_grouped_dataframe.py`
Fixes for issues in the following APIs and expectation tests for them:
- `map` in `dataframe.py`
- `Functions.`
- `system_reference`
- `mean`
- `var_samp`
- …
> SNOW-1916224: Ensure that all APIs have AST support

- src/snowflake/snowpark/modin/plugin/docstrings/__init__.py
- src/snowflake/snowpark/modin/plugin/docstrings/timedelta_index.py
- src/snowflake/snowpark/modin/plugin/extensions/timedelta_index.py
Fixes SNOW-1988858
Use docstrings folder for TimedeltaIndex methods and properties.
> SNOW-1988858: Use docstrings folder for TimedeltaIndex methods and properties

- src/snowflake/snowpark/_internal/proto/ast.proto
- src/snowflake/snowpark/dataframe.py
- tests/ast/data/DataFrame.create_or_replace.test
- tests/ast/data/DataframeNaFunctions.test
Fixes SNOW-1995618
To enable server-side execution, cache_result presents a duality as it effectively is a crossover of eval/assign. We resolve the existing TODO by treating cache_result as an expr together with an assign. Client-side optionally a temp table is created, and then stored within the expr. This will allow server-side to skip any nodes that formed lineage to the cache_result expr. Decoder changes done in monorepo/followup once decoder is refreshed to 1.29.
> SNOW-1995618 Store ref to temp table created in cache_result in AST

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/scala/test_function_suite.py
Fixes SNOW-1989053
When to_timestamp was called on a filtered column without a fmt defined the generated fmt would not have the correct index causing an indexing issue during conversion. This change applies the input columns index to the generated fmt in order to avoid this issue.
> SNOW-1989053: [Local Testing] Fix to_timestamp when called on filtered data

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
- tests/integ/modin/test_df_to_snowpark_pandas.py
- tests/integ/test_df_to_snowpark_pandas.py
Fixes SNOW-1974954
Support relaxed pandas in to_snowpark_pandas.
> SNOW-1974954: Support relaxed pandas in to_snowpark_pandas

- CHANGELOG.md
- src/snowflake/snowpark/_internal/data_source/datasource_partitioner.py
- src/snowflake/snowpark/_internal/data_source/datasource_reader.py
- src/snowflake/snowpark/_internal/data_source/utils.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/test_data_source_api.py
support multiple session init statements in dbapi
python dbapi only allows one statement to be executed in one statement, we take a list and execute them in sequence
> SNOW-1969300: support multiple session init statements in dbapi

- tests/integ/modin/io/test_read_snowflake_query_call.py
Fixes SNOW-2004982
Fix test_read_snowflake_call_sproc_relaxed_ordering_neg when sql simplifier is disabled.
> SNOW-2004982: Fix test_read_snowflake_call_sproc_relaxed_ordering_neg when sql simplifier is disabled

- src/snowflake/snowpark/functions.py
- tests/unit/test_telemetry.py
> SNOW-2004895: snowpark python 1.30.0 release preparation

- src/snowflake/snowpark/lineage.py
Remove preview warning for lineage.trace API since its GA. 
Fixes SNOW-2006135
> SNOW-2006135 : Remove preview warning for lineage.trace API

- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
1. Description:
With dbt project, we are planning on supporting multiple session insides procs. So we have added new API to _snowflake to create a pristine cloned version of the default server session. Using this, we will create a new new Snowpark session (a new object with new connection obj) and we will set the session_id of the connection (will be done in C API).  Currently we have a check in Snowpark lib which disallows creating multiple sessions inside sprocs. With this check we will that check the corresponding param is enabled (this param will only be enabled for dbt sprocs).
For more info on the multi-session project see this design doc: https://docs.google.com/document/d/1lwqyykHo549Vx3UWpFLWot1LIdYrwUjGKtGbQGaCnd8/edit?tab=t.0#heading=h.sil75ywnlm6n
An example of how this new …
> SNOW-1976643: Allow creating multi-session in sprocs if enabled

- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/session.py
- tests/ast/test_ast_mode.py
- tests/ast/test_ast_parameter.py
Fixes SNOW-1979918 snowpark python client ast mode and min ast version
[x] If adding any arguments to public Snowpark APIs or creating new public Snowpark APIs, I acknowledge that I have ensured my changes include AST support.
There is logic in snowpark session start up that checks for the client parameters and sets internal _ast_mode and ast_enabled states.
See: https://docs.google.com/document/d/1KwWYMxITaPxxKVU9Itsj1BuBeY04KftilcpwDdlC2Jg/edit?usp=sharing
> SNOW-1979918 snowpark python client ast mode and min ast version

- src/snowflake/snowpark/modin/plugin/_internal/frame.py
Fixes SNOW-2014497
Fix credit usage tracking for InternalFrame.has_unique_index().
> SNOW-2014497: Fix credit usage tracking for InternalFrame.has_unique_index()

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/docstrings/groupby.py
- tests/integ/modin/frame/test_apply_axis_0.py
- tests/integ/modin/groupby/test_all_any.py
- tests/integ/modin/groupby/test_groupby_apply.py
Fixes SNOW-1926348
This PR re-implements the `groupby-apply` method without the use of pivot. We infer the output schema and use that to create the UDTF with right number of columns. If we fail to infer to schema we fallback to old implementation.
**Performance improvement numbers:**
microbenchmark dataframe_groupby_apply_transform Before: 64.9 sec After: 21.4 sec
microbenchmark dataframe_groupby_apply_concat Before: 106.2 sec After: 40.7 sec
microbenchmark dataframe_groupby_apply_agg Before: 14.0 sec After: 13.4 sec
Customer support ticket …
> SNOW-1926348: Re-implement groupby-apply without pivot

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
- tests/integ/modin/frame/test_create_or_replace_dynamic_table.py
- tests/integ/modin/series/test_create_or_replace_dynamic_table.py
Fixes SNOW-2020943, SNOW-2020944
Support optional index retaining in DataFrame/Series.create_or_replace_dynamic_table.
> SNOW-2020943, SNOW-2020944: Support optional index retaining in DataFrame/Series.create_or_replace_dynamic_table

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
- tests/integ/modin/frame/test_create_or_replace_view.py
- tests/integ/modin/series/test_create_or_replace_view.py
Fixes SNOW-2020941, SNOW-2020942
Support optional index retaining in DataFrame/Series.create_or_replace_view.
> SNOW-2020941, SNOW-2020942: Support optional index retaining in DataFrame/Series.create_or_replace_view

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
Fixes SNOW-2020619
It is possible that pivot_col and aggregate_col references the same column, so we need to deduplicate
> SNOW-2020619: Fix pivot when aggregate column and pivot column are the same

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-2027156
Fix TypeError: create_udtf_for_groupby_apply() missing param after a bad merge.
> SNOW-2027156: Fix TypeError: create_udtf_for_groupby_apply() missing param after a bad merge

- src/snowflake/snowpark/dataframe_analytics_functions.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- tests/ast/data/functions1.test
- tests/ast/data/functions2.test
No JIRA ticket, but required for Phase 0 Client Closeout.
Due to widespread internal use of the `functions.builtin` method (an alias for `functions.function`), as well as `functions.call_builtin` (an alias for `functions.call_function`), we had set up the propagation of the AST directly through these methods down to the eventual call to the internal helper `_call_function`.
As a result, despite these being public APIs which are required to support Snowflake SQL functions not explicitly supported in Snowpark, we could not capture an AST to represent `call_function("foo", *args)` when …
> NOSNOW: Refactor functions.py for AST generation

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- tests/integ/modin/io/test_read_snowflake_iceberg.py
Fixes SNOW-2025063
Fix read_snowflake iceberg table bug when relaxed pandas is not enabled.
> SNOW-2025063: Fix read_snowflake iceberg table bug when relaxed pandas is not enabled

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- src/snowflake/snowpark/mock/_plan.py
- tests/mock/test_column.py
- tests/mock/test_functions.py
Fixes SNOW-2020993
Fixed an issue with `Column.getItem` and `snowpark.snowflake.functions.get` that caused an `IndexError` to be raised in local testing instead of returning None.
> SNOW-2020993: [Local Testing] Fix get and getItem indexing bug

- tests/integ/modin/frame/test_transpose.py
- tests/integ/modin/groupby/test_groupby_idxmax_idxmin.py
- tests/integ/modin/groupby/test_groupby_named_agg.py
- tests/integ/modin/groupby/test_quantile.py
- tests/integ/modin/series/test_rename.py
- tests/integ/modin/strings/test_cat.py
- tests/integ/modin/strings/test_extract.py
- tests/integ/modin/strings/test_get_dummies.py
- tests/integ/modin/strings/test_strings.py
- tests/integ/modin/test_sql_counter.py
- tests/integ/modin/test_telemetry.py
Fixes SNOW-1336091
When Snowpark pandas originally merged with the Snowpark repository, it would default to running native pandas in a stored procedure for certain operations that we did not directly provide distributed support for. This has since changed, and we no longer do any stored procedure fallback due to the prohibitive runtime cost of doing so. When we previously upgraded modin from 0.26.0 -> 0.28.1, the lag in time for the package becoming available in the conda channel meant we had to XFAIL many tests, but the `strict=True` modifier did not warn of us any changes in …
> SNOW-1336091: Update pandas tests that previously caused fallback to stored procedure

- tests/integ/test_stored_procedure.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Fixes SNOW-2041110
These tests are flaky so xfail until they I can figure out why.
> SNOW-2041110: Disable artifact repository for flakiness

- tests/integ/modin/io/test_read_snowflake_iceberg.py
Fixes SNOW-2044844
Fix preprod/qa6 iceberg failure, where the following error was being raised:
```
E       snowflake.snowpark.exceptions.SnowparkSQLException: (1304): 01bbadf1-0108-e88a-0001-122608a93082: 393921 (42601): External volume PYTHON_CONNECTOR_ICEBERG_EXVOL must have STORAGE_LOCATIONS defined.
```
> SNOW-2044844: Fix preprod/qa6 iceberg failure

- CHANGELOG.md
- src/snowflake/snowpark/dataframe_writer.py
- tests/integ/scala/test_dataframe_writer_suite.py
Fixes SNOW-1990241
When running in `overwrite` mode save_as_table has no issue writing reserved names to tables. This is due to the downstream query generation using the attribute names instead of the column names. This change modifies how column names are fetched for other save modes so that they also use the attribute names instead of schema names.
> SNOW-1990241: Fixed reserved name bug in append mode

- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/integ/test_function.py
- tests/resources/nested.xml
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_internal_utils.py
- tests/utils.py
Fixes SNOW-2014299
This PR does three things: 1) add a private property to DataFrame class to indicate whether all columns are variant 2) When calling select() on a dataframe, if this property is true, it means all columns are variants and we should support query nested fields using dot notation 3) Handling double quotes when querying nested fields using dot notation
> SNOW-2014299: Query XML dataframe with dot notation

- CHANGELOG.md
- src/snowflake/snowpark/mock/__init__.py
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/scala/test_function_suite.py
- tests/integ/scala/test_udf_suite.py
- tests/mock/test_functions.py
Fixes SNOW-2034834
This PR adds local testing support for array_construct.
Enabling those tests showed that local testing was not encoding null values contained in lists the same as Snowflake would. I've also patched the local testing json encoder to better cover that.
> SNOW-2034834: [Local Testing] Add support for array_construct function

- CHANGELOG.md
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_update_delete_merge_suite.py
Fixes SNOW-2042420
This PR fixes an issue raised in GH-3262. When merging data into an empty table the merge_condition would lose all column information due to calculating an empty DataFrame. This PR fixes this by explicitly setting columns on an empty dataframe to prevent the loss of context.
> SNOW-2042420: [Local Testing] Merge into empty table fix.

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/scala/test_snowflake_plan_suite.py
Fixes SNOW-1708651
We shouldn't create a new ProgrammingError.
> SNOW-1708651: Keep original exception for invalid identifier message

- tests/ast/test_ast_driver.py
- tests/integ/test_df_to_snowpark_pandas.py
Fixes SNOW-2046103
Fixes a failure in the daily test that occurs when pandas is not installed due to an incorrect expected error message.
Also skips `test_ast[df_copy.test]` in Python 3.12 environments ([slack discussion](https://snowflake.slack.com/archives/C06UKGN5HJP/p1745344602123719?thread_ts=1744840132.805579&cid=C06UKGN5HJP)).
Relevant daily tests passing: https://github.com/snowflakedb/snowpark-python/actions/runs/14601741926/job/40961489775 (failures are either unrelated or transient).
> SNOW-2046103: Fix no pandas and AST daily test failures

- src/snowflake/snowpark/_internal/xml_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/resources/books2.xml
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_xml_reader.py
- tests/utils.py
Fixes SNOW-2049277
For such an XML record:
```
<a>
<b .../>
</a>
```
The original implementation will fail because we look for the self-closing tag right away. This PR fixes this bug by looking for a ">" directly after the opening tag.
> SNOW-2049277: Fix XML reader when an XML record has nested self-closing tag

- src/snowflake/snowpark/_internal/ast/utils.py
- src/snowflake/snowpark/_internal/proto/ast.proto
- tests/ast/data/RelationalGroupedDataFrame.test
- tests/ast/data/Session.call.test
- tests/ast/data/Session.table_function.test
- tests/ast/data/col_udf.test
- tests/ast/data/df_map.test
- tests/ast/data/sproc.test
- tests/ast/data/udaf.test
- tests/ast/data/udtf.test
Fixes SNOW-2036949
This change updates the AST with new parameters for sprocs and udxfs to support artifact_repository parameters. Previously these parameters were being added via kwargs, but now they are named parameters. This results in quite a few expectation tests dropping them as parameters when unparsing. I've added examples with them included to maintain coverage.
> SNOW-2036949: Sync artifact repositry ast changes

- CHANGELOG.md
- src/snowflake/snowpark/session.py
- tests/integ/test_stored_procedure.py
Fixes SNOW-2012567
For `session.call` snowpark client runs a `describe procedure` query on the given procedure to determine if the return type is scalar or a table. However, running a describe on `SYSTEM$` procedures shows up as a failed query in query history. In this PR, we skip submitting a describe for `SYSTEM$` procedures since all system procedure's return type is scalar.
> SNOW-2012567: Skip describe for SYSTEM$ procedures

- CHANGELOG.md
- docs/source/modin/supported/series_str_supported.rst
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/series/test_str_accessor.py
Fixes SNOW-2053921
Add support for dict values in Series.str[].
> SNOW-2053921: Add support for dict values in Series.str[]

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/mock/test_functions.py
Fixes SNOW-2043855
This PR changes the mock implementation of rank to respect the order_by clause for each column in the window specification.
Previously pandas would recalculate the order of the input data and apply the rank to that ordering. This works correctly when the order_by clause on the window uses the default ordering, but is incorrect when one or more order_by columns are set to descending. 
With this change the rank function takes advantage of the fact that the data has already been ordered and manually calculates the order rather than use the pandas function.
This …
> SNOW-2043855: [Local Testing] Fix rank order bug

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
- tests/integ/modin/frame/test_to_iceberg.py
- tests/integ/modin/series/test_to_iceberg.py
Fixes SNOW-2070070
Make iceberg_config a required parameter for DataFrame/Series.to_iceberg. Before this change, when iceberg_config was not provided, a non-iceberg table would get created. By making it a required parameter, we guarantee that the method will only create iceberg tables.
> SNOW-2070070: Make iceberg_config a required parameter for DataFrame/Series.to_iceberg

- CHANGELOG.md
- docs/source/snowpark/types.rst
- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
- tests/utils.py
Fixes SNOW-1952256
Now we can create a dataframe with the stage url and file data type directly
> SNOW-1952256: Add support for `create_dataframe` with FILE data type

- setup.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-2094085
Error in Build Doc ci job
docs: install_deps> bash ./scripts/tox_install_cmd.sh sphinx './.[modin-development]'
error: resolution-too-deep
sphinx ./.[modin-development]
× Dependency resolution exceeded maximum depth
╰─> Pip cannot resolve the current dependencies as the dependency graph is too complex for pip to solve efficiently.
This PR fixes the issue by limiting the supported range for `snowflake-ml-python` in the `modin` dependency.
> SNOW-2094085: Limit supported range for snowpak-ml-python in modin dependency

- tests/integ/modin/io/test_read_snowflake_query_call.py
This PR changes the sproc for `test_read_snowflake_call_sproc` and `test_read_snowflake_call_sproc_enforce_ordering_neg` to use Python 3.9 instead of the deprecated Python 3.8 runtime version.
> CI: Fix Python version runtime sproc test

- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe_reader.py
> SNOW-2086682: Add telemetry for XML reader with row tag

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/io/snow_io.py
- tests/integ/modin/io/test_read_csv.py
Fixes SNOW-2090084
Add support for reading files from S3 buckets using pd.read_csv.
> SNOW-2090084: Add support for reading files from S3 buckets using pd.read_csv

- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes SNOW-2098847
register_from_file() doesn't work in stored procedure when calling the UDF, if the underlying stage (session stage) is scoped temporary.
> SNOW-2098847: Do not use "scoped temporary" stage for XML reader in stored procedure 

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
Fixes SNOW-2103487, SNOW-213488
Make index=False by default for DataFrame/Series.to_view/to_dynamic_table.
> SNOW-2103487, SNOW-213488: Make index=False by default for DataFrame/Series.to_view/to_dynamic_table

- tests/integ/modin/test_session_write_pandas.py
- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_file_operation_suite.py
- tests/integ/scala/test_permanent_udf_suite.py
- tests/integ/scala/test_window_frame_suite.py
- tests/integ/scala/test_window_spec_suite.py
- tests/integ/test_column.py
- tests/integ/test_dataframe.py
- tests/integ/test_df_analytics.py
- tests/integ/test_function.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Fixes SNOW-2084165
This PR is split up from https://github.com/snowflakedb/snowpark-python/pull/3339
str(ex_info) compresses the error using `...` and some of the expected string in string matching gets hidden into the `...`. We make these updates to find the expected string in the full error string.
example str(ex_info) output
```
<ExceptionInfo SnowparkSQLException('snowflake.snowpark.exceptions.SnowparkSQLException: (1304): 01bc4ee1-0a10-0849-000c-a909c7a27113...s/snowpark-python/tests/integ/test_function.py|787:9-787:52:  session.create_dataframe([4], schema=["a"])', None, None) …
```
> SNOW-2084165: Update str(ex_info) to str(ex_info.value) for better string checks

- tests/integ/modin/io/test_read_snowflake_query_cte.py
This PR ensures that all sproc use the Python 3.9 runtime, other sprocs were updated in this PR here: https://github.com/snowflakedb/snowpark-python/pull/3349
> TEST: Change all sproc to use Python 3.9 runtime

- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/exceptions.py
- tests/unit/scala/test_error_message.py
- tests/unit/test_error_message.py
Fixes SNOW-2084165
Add a new field `debug_context` to `SnowparkSQLException` to support additional debug into to be shown in the error message.
> SNOW-2084165: add debug info to error message

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/exceptions.py
- src/snowflake/snowpark/mock/_plan.py
- src/snowflake/snowpark/mock/_select_statement.py
- tests/integ/test_df_ast_id_map.py
- tests/unit/compiler/test_replace_child_and_update_node.py
- tests/unit/conftest.py
- tests/unit/scala/test_error_message.py
- tests/unit/test_error_message.py
- tests/unit/test_query_plan_analysis.py
Fixes SNOW-2096094
This change updates `SnowflakePlan` and `Selectable` to have their generating `Dataframe` object's `_ast_id` linked to them. We add `df_ast_id` field to `SnowflakePlan` and `df_ast_ids` to Selectable to keep maintain the list.
> SNOW-2096094: Add associated df ast id to SnowflakePlan and Selectable

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_snowflake_plan_suite.py
Fixes SNOW-2115026
Previously when calling dataframe.schema or other functions that run a describe query it was possible to get back an error message along the lines of this even though the dataframe had some columns:
```
There are existing quoted column identifiers: []
```
This is because the get_result_attributes function does not have a SnowflakePlan available to look up the identifiers in. This change moves the wrapper further up the call stack so that the context is available in more cases. SelectSQL plans will still lack the context, but they also will no longer show the …
> SNOW-2115026: Improve existing identifiers error message

- tests/integ/modin/strings/test_cat.py
Link to failing test: https://github.com/snowflakedb/snowpark-python/blob/main/tests/integ/modin/strings/test_cat.py#L70.
> NO-SNOW: Fix test count in `test_str_cat_incorrect_lengths`

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/xml_reader.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/test_xml_reader_row_tag.py
- tests/unit/test_xml_reader.py
> SNOW-2127344: Add `valueTag` option for xml reader

- CHANGELOG.md
- src/snowflake/snowpark/lineage.py
- tests/unit/test_lineage.py
Fixes SNOW-2123730
3. Fill out the following pre-review checklist:
i updated the unit tests to reflect the new dgql query, and have verified that the integration test continues to pass.
4. Please describe how your code solves the related issue.
The Lineage API now requires providing a `properties` key if we want to retrieve Edge properties, this PR adds the `properties` key to the query
> SNOW-2123730: lookup Edge properties when getting lineage

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/xml_reader.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/test_xml_reader_row_tag.py
- tests/resources/nested.xml
- tests/resources/null_value.xml
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_xml_reader.py
- tests/utils.py
Fixes SNOW-2129001
Also found a related bug that for value_tag, if there are attributes available, we should use value_tag as column name too.
> SNOW-2129001: Support `nullValue` option in XML reader

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/xml_reader.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/unit/test_xml_reader.py
Fixes [SNOW-2132902](https://snowflakecomputing.atlassian.net/browse/SNOW-2132902)
[SNOW-2132902]: https://snowflakecomputing.atlassian.net/browse/SNOW-2132902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-2132902: Support `charset` option in XML reader

- tests/conftest.py
- tests/integ/scala/test_dataframe_join_suite.py
- tests/integ/test_cte.py
test running:
diamond join test are passing
https://github.com/snowflakedb/snowpark-python/actions/runs/15423809004
> SNOW-2060042: fix failing diamond join daily precommit test

- tests/integ/scala/test_dataframe_reader_suite.py
> NO-SNOW: Skip xml tests in SP

- tests/integ/scala/test_async_job_suite.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes NO-SNOW
For `test_read_json_with_infer_schema` we could set a parameter on that Snowfort test suite that would fix the issue, but the test doesn't really need to be using StringType so I've replaced it with a different type.
For the `test_async_to_pandas_common` failure I'm not sure why stored proc wouldn't be able to call that show function, but it should be ok to skip this test here. The next test case under it has similar coverage.
> NO-SNOW: Fix Snowfort failures

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_analyzer_util_suite.py
Fixes SNOW-2128261
This PR fixes an issue that DataFrameReader can run into when inferring schema. Before this change the `_infer_schema_for_file_format` would generate a query that used all files in the stage location in order to infer the schema. This is brittle because a stage location could contain files of different types or structures.
We already provide support for specifying `PATTERN` when loading files with a predefined schema. This change ensures that the same `PATTERN` is used to filter out files that should not affect the inferred schema. It does this by running a `list …
> SNOW-2128261: Allow PATTERN when INFER_SCHEMA is enabled

- tests/mock/conftest.py
- tests/mock/test_stage_registry.py
Fixes SNOW-2111933
Added tests that leverages put/get/readfile APIs inside of a mocked sproc. Made it so that the conftest session fixture is registered as the default session.
> SNOW-2111933: Add local testing for sproc put and get 

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/mock/test_functions.py
Fixes SNOW-2116667
Dropping the index in concat_ws is not correct. This causes issues when the input df does not have a default index such as when some rows have been filtered out.
> SNOW-2116667: [Local Testing] Fix indexing issue in concat_ws

- CHANGELOG.md
- src/snowflake/snowpark/mock/_stage_registry.py
- tests/integ/scala/test_file_operation_suite.py
- tests/mock/test_file_operations.py
Fixes SNOW-1285387
Added tests to verify that snowurls work with session.file.get and .put in local testing. Removed unnecessary error check in stage_registry to allow for snowurls and make get and read_file consistent with put.
> SNOW-1285387: add local testing and support for snowurl get/put

- tests/integ/test_stored_procedure.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Fixes NO-SNOW
The stored proc env does not have permissions to run `show warehouses`. Depending on the deployment the error can be different so I've added both cases. The UDxF objects also need cloudpickle to run.
> NO-SNOW: Skip failing tests in stored procs

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/extensions/base_overrides.py
- tests/integ/modin/series/test_where.py
Fixes SNOW-2135829
Fix a bug in `Series.where` where a NaN value may be incorrectly generated when the `other` parameter is an unnamed `Series`.
> SNOW-2135829: Fix NaN bug in Series.where

- tests/integ/modin/hybrid/conftest.py
- tests/integ/modin/hybrid/test_df_creation_backend.py
- tests/integ/modin/hybrid/test_switch_operations.py
Fixes SNOW-2147180
This fixes 2 test issues detected in Jenkins and GH.
1. Jenkins failure from tests/integ/modin/hybrid/test_switch_operations.py::test_filtered_data: https://snowpark-python-001.jenkinsdev1.us-west-2.aws-dev.app.snowflake.com/job/SnowparkPythonSnowPandasDailyRegressRunner/197901/consoleFull
Based on the output, `pd.Timestamp().today()` reports a different value from SQL `current_date`. This PR changes the test to be deterministic and use a fixed date instead.
2. GH actions failure on Windows in tests/integ/modin/hybrid/test_df_creation_backend.py: …
> SNOW-2147180: Fix test_switch_operations.py::test_filtered_data on jenkins and test_df_creation.py::test_read_csv_local on windows

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/xml_reader.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/test_xml_reader_row_tag.py
- tests/resources/books.xsd
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_xml_reader.py
- tests/utils.py
> SNOW-2145168: Support `rowValidationXSDPath` option in XML reader

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/_nop_plan.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/test_df_ast_id_map.py
- tests/unit/compiler/test_replace_child_and_update_node.py
- tests/unit/conftest.py
- tests/unit/test_selectable_queries.py
Bug fixes associated with SNOW-2096094
Added code to maintain a list of ast ids for SnowflakePlan rather than a single int for cases when multiple dfs are responsible for a SnowflakePlan. This case mainly arises when we create a SnowflakePlan from a Selectable object, as we previously just took the last ast_id.
> SNOW-2096094: Maintaining list of ast_ids for SnowflakePlan

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- tests/unit/test_analyzer_util_suite.py
Fixes SNOW-2160042
According to Jamison's comment on the Jira ticket, we only need to remove the redundant validation
> SNOW-2160042: remove redundant validation in iceberg table

- CHANGELOG.md
- src/snowflake/snowpark/_internal/data_source/datasource_reader.py
- src/snowflake/snowpark/_internal/data_source/drivers/base_driver.py
- tests/unit/test_data_source.py
Fixes SNOW-2174093
Best effort to close cursor and connection in dbapi; failures are non-critical and can be ignored.
> SNOW-2174093: improve error handling when closing cursor and connection in dbapi

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/base_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/base_overrides.py
- tests/integ/modin/hybrid/test_df_creation_backend.py
- tests/integ/modin/hybrid/test_switch_operations.py
Fixes SNOW-2173644 and SNOW-2157873
SNOW-2157873 occurs because upstream modin does not implement `__array_function__`, instead converting to numpy ndarrays via `__array__` when a numpy function is called on it. The presence of the extension wrapper for `__array_function__` introduced by Snowpark pandas confuses numpy dispatch, causing unexpected AttributeErrors. This is fixed upstream with https://github.com/modin-project/modin/pull/7617, and will presumably become available in the next modin release. On the Snowpark side, this PR adds relevant tests, and adds a version-guarded flag …
> SNOW-2173644, SNOW-2157873: Fix __array_function__ hybrid switching and native Series constructor switching bugs

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
- tests/integ/test_dataframe.py
- tests/integ/test_simplifier_suite.py
Fixes SNOW-2113721
This PR improves upon https://github.com/snowflakedb/snowpark-python/pull/3421 by also supporting `Column` objects in select when the underlying column expression are `Attributes`/ `UnresolvedAttributes`.
> SNOW-2113721: Fix overlapping columns with table function

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/telemetry.py
- tests/integ/modin/test_telemetry.py
SNOW-1900052 - Add basic telemetry data to modin telemetry
We are currently receiving telemetry; but this will allow it to be typed correctly with less processing.
pre-review checklist:
> SNOW-1900052 - Add basic telemetry data to modin telemetry

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_dataframe.py
> SNOW-2128687: Fix all FractionalTypes being casted to FloatType

- tests/integ/scala/test_dataframe_reader_suite.py
> SNOW-2201113: skip checking string length for regression tests due to LOB issue

- tests/integ/test_query_line_intervals.py
Fixes NO-SNOW, fixes test in 1.34.0 release
3. Fill out the following pre-review checklist:
4. Please describe how your code solves the related issue.
We use pattern matching to verify the sql queries for join related tests rather than hard coding the join key values in order to fix flakiness.
> Using regex for join tests to fix flakiness

- tests/integ/modin/io/test_read_json.py
Running the test suite locally left `test_read_json_empty_file.json` behind as an artifact. This PR wraps the code in try/finally to properly remove the file.
> NO-SNOW: Fix file cleanup in test_read_json_empty_file

- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
Fixes SNOW-2206502
Fix a type error in the doctest for DataFrame.boxplot.
> SNOW-2206502: Fix a type error in the doctest for DataFrame.boxplot

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/io/snow_io.py
- tests/integ/modin/io/test_read_excel.py
Fixes SNOW-2221567
Fix pd.read_excel bug when reading files inside stage inner directory.
> SNOW-2221567: Fix pd.read_excel bug when reading files inside stage inner directory

- tests/integ/datasource/test_databricks.py
- tests/integ/datasource/test_mysql.py
- tests/integ/datasource/test_oracledb.py
- tests/integ/datasource/test_postgres.py
> NO SNOW: skip udtf test of data source in py313

- CHANGELOG.md
- src/snowflake/snowpark/files.py
- tests/unit/test_files.py
Fixes SNOW-2138082
Removes enforcement that the path passed to SnowflakeFile has to be an absolute path.
> [SNOW-2138082]: Add relative path support for SnowflakeFile

- src/snowflake/snowpark/dataframe.py
- tests/integ/test_trace_sql_errors_to_df.py
- tests/utils.py
Fixes NO-SNOW
Fixing small bug with eager schema validation enabled for tracing SQL error to DF, and adding line numbers to integration tests
> Trace SQL error to DF bug fixes

- tests/integ/test_trace_sql_errors_to_df.py
Example failure: https://github.com/snowflakedb/snowpark-python/actions/runs/16744274500/job/47399231532.
Current test expects start and end line number but 3.10 and older python only captures start line number. Update the test to reflect this change.
> NO-SNOW: Update line number check to handle python 3.10

- src/snowflake/snowpark/functions.py
ENABLE_STRUCTURED_TYPES_NATIVE_ARROW_FORMAT
ENABLE_STRUCTURED_TYPES_IN_CLIENT_RESPONSE
they should both set to true or both to false to get the function work
however, in our test deployment, it's improperly set that ENABLE_STRUCTURED_TYPES_NATIVE_ARROW_FORMAT is false and the other ENABLE_STRUCTURED_TYPES_IN_CLIENT_RESPONSE is true
I need to check why they are set differently, skipping the test first to reduce noise
> NO-SNOW: skip map_cat test due to improper structured type session parameter settings

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/compiler/utils.py
- tests/integ/test_cte.py
Fixes SNOW-2254287, #3641
I ran the following pipeline to reproduce the original reported issue above
```
data = [(x, x*2) for x in range(int(1e5))]
df = session.create_dataframe(data, schema=["id", "value"])
df = df.union(df)
df = df.cache_result()
```
I was successfully able to reproduce the memory spike due to deepcopy see the flamegraphs below
Heap: 170MB
RSS: 240MB
Heap: 436MB
RSS: 549MB
---
Heap: 170MB
RSS: 246 MB
> SNOW-2254287: Remove deepcopy of large data during optimization stage

- src/snowflake/snowpark/relational_grouped_dataframe.py
- tests/integ/test_df_aggregate.py
There is already a LIMIT 1 in aggregation expression if there is no grouping columns https://github.com/snowflakedb/snowpark-python/blob/b5178d3c314ee298bba5e43e3c19fc3732621ccc/src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py#L642
> Fix limit when there is no grouping expression in aggregation

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/extensions/index.py
- tests/integ/modin/hybrid/test_switch_operations.py
Fixes SNOW-2250267
`pd.to_datetime`/`pd.to_timedelta` have code paths to create `pd.Index` objects (defined as extensions in Snowpark pandas) when their arguments are non-pandas objects. Internally, the `pd.Index` constructor may create a modin DF/Series from this data, which then may incorrectly use a `NativeQueryCompiler` when a `SnowflakeQueryCompiler` one is expected instead. This PR forces the extension `pd.Index` constructor to always use the Snowflake backend, as any switching decisions should have been made before the constructor was called.
> SNOW-2250267: Prevent switching within extension Index constructor

- tox.ini
With this fix, Snowpark pandas daily Jenkins tests no longer fail due to failure to install pyarrow: https://snowpark-python-001.jenkinsdev1.us-west-2.aws-dev.app.snowflake.com/job/SnowparkPythonSnowPandasDailyRegressRunner/198110/console
Fixes SNOW-2266293
> SNOW-2266293: Cap pyarrow<21 in snowpark pandas jenkins tests.

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/telemetry.py
- src/snowflake/snowpark/modin/plugin/extensions/pd_extensions.py
- tests/integ/modin/hybrid/test_switch_operations.py
Fixes SNOW-2262562
`pd.explain_switch(simple=True)` would return `None` if no operations were performed, which looks weird in an interactive environment because nothing is printed.
The bug cited in the ticket occurs because the previous implementation of `explain_switch` tripped an uncommon code path in telemetry that checked if a function returned None and if its first argument was a Snowpark pandas DF/Series. This PR adds a defensive length check to telemetry to avoid the IndexError, and also changes `explain_switch(simple=True)` to always return an empty DF instead of None. When …
> SNOW-2262562: Return empty DF instead of None for pd.explain_switch(simple=True)

- CHANGELOG.md
- docs/source/modin/numpy.rst
- src/snowflake/snowpark/modin/plugin/utils/numpy_to_pandas.py
- tests/integ/modin/test_numpy.py
Map np.unique(df) to pd.unique with appropriate handling for DataFrames/Series. As with np.unique and pd.unique we return an ndarray, which is a materialized result set. We cannot avoid this because usages of this function often chain operations which expect an ndarray. This is specifically implemented to improve scikit-learn compatibility.
Fixes SNOW-2241331:
> SNOW-2241331: Unable to use numpy.unique through sklearn.metrics._scorer

- CHANGELOG.md
- src/snowflake/snowpark/_internal/data_source/utils.py
- tests/integ/test_data_source_api.py
Fixes SNOW-2276751
- improve dbapi thread based ingestion error handling, do not over send stop events in case there is error in one thread and immediately returns
- improve the test case to avoid flakiness
3. Fill out the following pre-review checklist:
4. Please describe how your code solves the related issue.
> SNOW-2276751: improve dbapi thread based ingestion error handling

- src/snowflake/snowpark/session.py
- tests/integ/test_packaging.py
- tests/resources/test_requirements.txt
Fixes SNOW-2282619
A recent change bumped or minimum modin version to 0.34 which requires pandas 2.2-2.3. This PR updates some doc tests that were failing due to package resolution caused by this change.
> SNOW-2282619: Daily precommit pandas fix

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/pd_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/series_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/utils.py
- tests/integ/modin/hybrid/test_data_movement.py
- tests/integ/modin/hybrid/test_extensions.py
Make sure that we support the function and method variants of `to_snowflake()`, `to_snowpark()`, `to_iceberg()`, `read_snowflake()`, and `to_pandas()` on the pandas and Ray backends. Prior to this commit, we only supported some of these functions and methods on the Pandas backend.
Fixes SNOW-2189056
> SNOW-2189056: Support some snowflake extensions on other backends.

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes SNOW-2282132
This PR fixes a bug in inference statement generation that would cause incorrect file prefixes to be included in the query.
The conditions for this issue are probably easiest to see via example. For the three cases below assume that two csv files have been uploaded to the stage, `good1.csv.gz` and `bad1.csv.gz`. The user has specified to use the pattern `.*good.*` to select files to load. Both of them have been uploaded to the `path` prefix.
Each scenario causes snowpark to execute a query similar to `list @<stage_name>/path/ pattern = '.*good.*'`. 
The matching …
> SNOW-2282132: Fix external stage prefix inferrence

- src/snowflake/snowpark/_internal/server_connection.py
- tests/unit/test_server_connection.py
Fixes [SNOW-2020306](https://snowflakecomputing.atlassian.net/browse/SNOW-2020306) and [SNOW-2227655](https://snowflakecomputing.atlassian.net/browse/SNOW-2227655)
Update application in server_connections to track queries are created from snowflake SPCS notebook runs. This will categorize usage attribution better for notebooks
Testing
- Added unit tests for _add_application_parameters
[SNOW-2020306]: https://snowflakecomputing.atlassian.net/browse/SNOW-2020306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNOW-2227655]: …
> [SNOW-2020306] Update application tracking for notebooks

- tests/integ/modin/hybrid/conftest.py
Fixes SNOW-2292908
Per @sfc-gh-mvashishtha 's investigation, Ray startup is extremely flaky in Windows environments when multiple pytest workers are running. As such, we should skip tests that rely on Ray.
> SNOW-2292908: Skip flaky modin hybrid tests on Windows

- CHANGELOG.md
- docs/source/snowpark/index.rst
- docs/source/snowpark/secrets.rst
- src/snowflake/snowpark/__init__.py
- src/snowflake/snowpark/secrets.py
- tests/integ/conftest.py
- tests/integ/test_secrets.py
- tests/unit/test_secrets.py
Fixes SNOW-2324796
- Migrate [secrets API](https://docs.snowflake.com/en/developer-guide/external-network-access/secret-api-reference#python-api-for-secret-access) from `_snowflake` to snowpark python.
- Current phase only supports execution on Snowflake server environment.
- Add to Snowfort test PR: https://github.com/snowflakedb/snowflake/pull/337192
- Triggered Snowfort tests on 2 custom branches, Secrets tests passed: [SnowCI report](https://snowci-prod.ci1.us-west-2.aws-dev.app.snowflake.com/reports …
> Snow 2324796 secrets api migration 1

- scripts/conda_build_verification/README.md
- scripts/conda_build_verification/conda_build_verification.sh
- scripts/conda_build_verification/docker_verify.sh
- scripts/conda_build_verification/smoke_test.py
Fixes SNOW-2336332
automate conda package validation
> SNOW-2336332: faster release automate fast path release package validation

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- src/snowflake/snowpark/context.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/test_stored_procedure.py
Fixes SNOW-2360274
The sql generation for describe queries has an edge case that can cause invalid sql to be generated when using nested structured types. The schema_expression function does it's best to respect nullability when generating schema queries. Snowflake does not support nullability inside of structured types so this should not be needed for structured types. This fix short circuits the sql generation by replacing the recursive call with NULLs. I have not found any cases in which this would break, but to be extra sure it's not a BCR I am gating it behind a context variable. …
> SNOW-2360274: Fix schema query sql generation for structured types

- src/snowflake/snowpark/_internal/compiler/cte_utils.py
- tests/integ/test_cte.py
- tests/unit/test_cte.py
Fixes SNOW-2261400
Now we consider the dataframe with the same query but different alias map as different, as they will have different join conditions in parent queries.
> SNOW-2261400: Fix incorrect join condition in repeated subquery elimination 

- CHANGELOG.md
- src/snowflake/snowpark/_internal/xml_reader.py
- tests/integ/test_xml_reader_row_tag.py
Fixes SNOW-2362488
Added malformed xml record string to the error message
> SNOW-2362488: Improve the error message of XSD validation when mode=failfast

- CHANGELOG.md
- src/snowflake/snowpark/modin/config/envvars.py
- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- src/snowflake/snowpark/modin/plugin/extensions/dataframe_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/pd_extensions.py
- src/snowflake/snowpark/modin/plugin/extensions/utils.py
- tests/integ/modin/frame/test_to_snowflake.py
To implement to_snowflake() for a Snowpark pandas dataframe on the pandas backend with large enough data, upload data via a parquet file instead of via a Snowpark dataframe. The Snowpark dataframe typically inserts values through parametrized SQL queries.
Benchmarking showed that a good threshold to switch to parquet was roughly 3 MB, so I've set that as the configurable default switching threshold. Performance of this approach seems to improve with dataset size. Exporting an 800 MB dataframe took about 55 seconds via parquet versus about 429 seconds via the old method, so we get over 7x speedup.
This work took me much longer than expected, so I am sending out this PR with just the changes for DataFrame.to_snowflake(). We can address Series.to_snowflake() separately.
We can take a similar …
> SNOW-2372686: Write large_pandas_backend_df.to_snowflake() via parquet.

- scripts/jenkins_regress.sh
- tests/unit/test_packaging_utils.py
- tox.ini
pandas 2.3.3 is not compatible with jenkins gcc complier
> Fix SnowparkPythonSnowflakePythonClientRegressRunner

- .github/workflows/precommit.yml
- CHANGELOG.md
- src/snowflake/snowpark/session.py
- tox.ini
Fixes SNOW-2389912
Hybrid execution was accidentally disabled by default in #3789 in certain cases, which wrote to the `AutoSwitchBackend` variable during [session initialization](https://github.com/snowflakedb/snowpark-python/blob/d02aa5ce540afa6e10e536107880659f7321f589/src/snowflake/snowpark/session.py#L759-L768) before the [https://github.com/snowflakedb/snowpark-python/blob/d02aa5ce540afa6e10e536107880659f7321f589/src/snowflake/snowpark/modin/plugin/__init__.py#L1[…]86](https://github.com/snowflakedb/snowpark-python/blob/d02aa5ce540afa6e10e536107880659f7321f589/src/snowflake/snowp …
> SNOW-2389912: Ensure hybrid execution is actually enabled by default

- CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/test_faster_pandas.py
Fixes SNOW-2397930
Add support for isna, isnull, notna, and notnull in faster pandas.
> SNOW-2397930: Add support for isna, isnull, notna, and notnull in faster pandas
