- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/file_operation.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/scala/test_udtf_suite.py
Description
Unified Stacktrace for exceptions
Testing
Fixes #NNNN
> SNOW-594516 Unified Stacktrace for exceptions

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-587511: release 0.7.0

- .github/workflows/python-publish.yml
> Python Publish Package

- CONTRIBUTING.md
- MANIFEST.in
- README.md
> SNOW-595309: Adjust README CONTRIBUTING and MANIFEST

- CONTRIBUTING.md
Fixes SNOW-596304
Just adding some description to external contributors
> SNOW-596304 Update CONTRIBUTING.md

- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- tests/integ/test_dataframe.py
- tests/unit/test_datatype_mapper.py
> SNOW-607466: Fix the limited length of string column in `create_dataframe`

- .github/CODEOWNERS
- .github/workflows/python-publish.yml
- .pre-commit-config.yaml
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/binary_expression.py
- src/snowflake/snowpark/_internal/analyzer/binary_plan_node.py
- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/grouping_set.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/_internal/analyzer/sort_expression.py
- src/snowflake/snowpark/_internal/analyzer/table_function.py
- src/snowflake/snowpark/_internal/analyzer/table_merge_expression.py
- src/snowflake/snowpark/_internal/analyzer/unary_expression.py
- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/_internal/analyzer/window_expression.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/query_history.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/table.py
- src/snowflake/snowpark/table_function.py
- src/snowflake/snowpark/udtf.py
- tests/integ/scala/test_udtf_suite.py
- tests/integ/test_udf.py
- tests/unit/test_generated_udf_lock.py
- tests/utils.py
- tox.ini
Fixes SNOW-589639
Now all `__init__` functions will need to have an explicit `-> None` attached to them.
> SNOW-589639 adding new flake8 plugin and fixing flake8 issues

- CONTRIBUTING.md
Updated instructions in contributing guide to be more clear and verbose for external contributors.
> Updated instructions in contributing guide

- src/snowflake/snowpark/functions.py
- tests/integ/scala/test_function_suite.py
Description
Updated trim definition
Testing
Updated testing to test trim without the optional argument
Fixes SNOW-614486
> SNOW-614486 Aligned definition of 'trim' with SQL function definition

- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/session.py
- tests/integ/test_stored_procedure.py
Fixes [SNOW-557128](https://snowflakecomputing.atlassian.net/browse/SNOW-557128)
> SNOW-557128 added Column support to stored procedure calls

- tests/integ/test_stored_procedure.py
> Fix test_stored_procedure_with_column_datatype

- src/snowflake/snowpark/_internal/server_connection.py
> SNOW-620212: Don't fetch the data when getting result query ID

- setup.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/ml/__init__.py
- src/snowflake/snowpark/ml/transformer.py
- src/snowflake/snowpark/ml/utils.py
- tests/integ/ml/__init__.py
- tests/integ/ml/test_transformer.py
> SNOW-607203: ml transformers(StandardScaler, MinmaxScaler, OnehotEncoder, OrdinalEncoder, Binarizer)

- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_reader_suite.py
Description
Preserve column order in INFER_SCEHMA related tests
Testing
Updated automated tests and removed tag to skip testing in stored procs
Fixes #NNNN
> SNOW-595068 Preserve column order in INFER_SCEHMA related tests

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_na_functions.py
- src/snowflake/snowpark/dataframe_reader.py
- src/snowflake/snowpark/dataframe_stat_functions.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table.py
- tests/integ/test_telemetry.py
Description
Added more usage telemetry to snowpark-python
Testing
> SNOW-582820 Finer-grained usage telemetry for Snowpark Python

- src/snowflake/snowpark/session.py
- tests/integ/test_udf.py
> SNOW-610869: Check if anaconda terms are acknowledged when adding missing packages

- src/snowflake/snowpark/ml/transformer.py
- src/snowflake/snowpark/ml/utils.py
- tests/integ/ml/test_transformer.py
> SNOW-621669 ml transformer: Normalizer and KBinsDiscretizer

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_update_delete_merge_suite.py
- tests/integ/test_dataframe.py
Description
table_type is expected to replace create_temp_table as it is
more flexible for supporting different kind of table types. We
begin with supporting transient and temp tables
Testing
integ test
Fixes #NNNN
> SNOW-623524 Support table_type in save_as_table

- src/snowflake/snowpark/functions.py
- tests/integ/test_stored_procedure.py
Description
Fixed this test when running in RT mode. Also updated the definition for date_from_parts to allow for integer inputs
Testing
Updated broken test and added more doctests
Fixes #NNNN
> SNOW-630966 Fix test_stored_procedure_with_column_datatype

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-629044: 0.8.0 Release Notes

- tests/integ/scala/test_dataframe_copy_into.py
To fix the test failure in SP reg test. It should be in (test-)0.8.0. 
> SNOW-632268: Mark `snowpark_scala_test_dataframe_copy_into` as a flaky test

- .github/workflows/jira_issue.yml
Fixes #NNNN
It looks like our Jira Area id has changed. `14586` refers to `Snowpark: Stored Procs & APIs`
> update Jira issue Area

- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/udtf.py
Description
As title
Testing
N/A
Fixes #NNNN
> SNOW-641436 Fix UDTF related doc

- docs/source/_themes/snowflake_rtd_theme/footer2.html
Fixes SNOW-642185
Not applicable
The link to get to the Community page has changed so I have updated it.
> SNOW-642185: In the api docs, update link to community page

- src/snowflake/snowpark/dataframe.py
Description
We apparantly support anti/cross/semi joins, so we might as
well add that to the doc
Testing
N/A
Fixes #NNNN
> SNOW-641391 Add more join types in doc

- tests/integ/test_dataframe.py
Fixes SNOW-629044
Skips a test that should not be run
> SNOW-629044: Skip test in stored proc for localfs since we need resources setup

- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_reader_suite.py
> SNOW-629044: Disable tests failing for stored procs

- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/exceptions.py
- src/snowflake/snowpark/file_operation.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_file_operation_suite.py
- tests/unit/scala/test_error_message.py
Fixes #SNOW-584202
SNOW-584202 is created to add upload and download stream in file API. This PR covers the upload part by using the python connector to handle the upload
> SNOW-584202: Support upload stream in file API

- tests/integ/scala/test_dataframe_copy_into.py
This is missed when we try to skip tests due to failures.
Fixes #NNNN
> Skip test_copy_non_csv_auto_transformation for stored proc

- docs/source/_templates/module.rst
- src/snowflake/snowpark/__init__.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_async_job_suite.py
> SNOW-629121: create async job api

- .github/pull_request_template.md
Fixes SNOW-646318
Adding a new question to our PR template to act as a reminder to add telemetry messages.
> SNOW-646318 Update pull_request_template.md

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-652526: update release notes for v0.9.0

- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/stored_procedure.py
- tests/integ/test_stored_procedure.py
- tests/unit/test_stored_procedure.py
Fixes SNOW-631792
In this PR I add `EXECUTE AS` clause to stored procedures.
> SNOW-631792 adding EXECUTE AS and tests for correctness

- src/snowflake/snowpark/_internal/utils.py
- tests/integ/test_udf.py
Fixes #NNNN
Split from #455
I randomized a UDF's name to prevent test collisions.
> randomize a UDF name to prevent test collision

- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
- tests/utils.py
Fixes SNOW-645479
using `show table like xxx in yyy` to check whether table exists in schema/database.
I'm following the spec https://docs.snowflake.com/en/sql-reference/name-resolution.html to implement object parsing.
> SNOW-645479: Support qualified table name in session._table_exists

- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/context.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_reader.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/integ/test_query_history.py
- tests/integ/test_scoped_temp_objects.py
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_analyzer_util_suite.py
- tests/unit/test_session.py
> SNOW-622058: Use job-scoped temp object in snowpark API

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/table.py
- tests/integ/test_simplifier_suite.py
Fixes SNOW-624886
Use SelectStatement for DataFrames created by df.unpivot and df.sample
> SNOW-624886: Flatten queries created by sample and unpivot

- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes SNOW-624869
Use SelectStatement for DataFrames created by DataFrameReader
> SNOW-624869: Flatten queries created by DataFrameReader

- src/snowflake/snowpark/session.py
- tests/integ/test_simplifier_suite.py
> SNOW-659753: Flatten session.range()

- docs/source/_templates/module.rst
- src/snowflake/snowpark/__init__.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_async_job_suite.py
SNOW-629121
Merge #416 to main branch. @experimental decorator will be created then.
> SNOW-629121: Support Async job

- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
- tests/integ/test_pandas_to_df.py
- tests/unit/scala/test_utils_suite.py
> SNOW-659918: Using logging.warning for deprecation and only warn once

- src/snowflake/snowpark/session.py
Description
We want to get rid of the specific function being called since it provides no analytical value
Fixes #NNNN
> SNOW-659901 Dedup Session.call and Session.table_function API calls

- src/snowflake/snowpark/udf.py
- tests/integ/test_udf.py
SNOW-654807
Hold off on #476 and deprecate it first.
> SNOW-654807: Deprecate the UDF invocation where arguments are wrapped by a list 

- tests/integ/test_udf.py
Fixes #NNNN
caplog somehow doesn't work yet.
> Skip test_deprecate_call_udf_with_list in SP regression test

- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_async_job_suite.py
- tests/unit/scala/test_utils_suite.py
> SNOW-658235: Create experimental decorator and mark Async-related features experimental

- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_async_job_suite.py
> SNOW-659431: Async support for to_pandas_batches

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/test_dataframe.py
Fixes [SNOW-641716](https://snowflakecomputing.atlassian.net/browse/SNOW-641716)
Implements offset as an optional parameter to `dataframe.limit()`
> SNOW-641716 support offset in dataframe

- tests/integ/scala/test_dataframe_suite.py
Fixes #NNNN
After query is flattened, somehow it becomes a large result query.
> Skip test_sample_on_union in SP regression test

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-658232: 0.10.0 release

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/session.py
- tests/integ/test_telemetry.py
Fixes SNOW-649741
Maintain the `api_calls` on `SelectStatement` and share it with the corresponding `SnowflakePlan`
> SNOW-649741: Fix telemetry when using sql simplifier

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- tests/integ/scala/test_update_delete_merge_suite.py
Fixes #470
Previously we just used the last query of source dataframe, which is not correct if a table needs to be created first. This PR fixes this issue and combine query plans from source dataframe.
> SNOW-656406: Combine query plans from source dataframe for methods in Table class

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/utils.py
- tests/integ/scala/test_sql_suite.py
- tests/unit/scala/test_utils_suite.py
Fixes SNOW-664434
Use regular expression to check whether a sql starts with `select` and `with`. Ignore case and allows preceding space and open parenthesis.
> SNOW-664434: Fix the logic that checks whether a SQL is a select statement

- ci/docker/snowpark_test_fips/Dockerfile
Fixes [SNOW-442275](https://snowflakecomputing.atlassian.net/browse/SNOW-442275)
Reduces docker image size by reducing the number of layers created by yum install commands and cleaning the cache afterwards.
> SNOW-442275: Reduce docker image size

- .github/workflows/precommit.yml
- tests/conftest.py
- tests/integ/conftest.py
- tests/integ/test_simplifier_suite.py
Fixes SNOW-667374
Use pytest addoptions
> SNOW-667374: Fix an issue that sql simplifier tests are not run

- src/snowflake/snowpark/dataframe.py
- tests/integ/test_simplifier_suite.py
Fixes #SNOW-666110
Use `select_statement.set_operator` to ensure that we do not add multiple nesting levels as we have more `union_by_name` calls stacked
> SNOW-666110: optimize flatten union_by_name

- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/file_operation.py
- tests/integ/scala/test_file_operation_suite.py
Fixes #SNOW-641129
Expose the streaming version of download for users to complete the file stream API.
> SNOW-641129 support download stream in snowpark api

- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe_reader.py
- src/snowflake/snowpark/functions.py
- tests/integ/test_column.py
Fixes #SNOW-668030
No-op change. just fixing some typos.
> SNOW-668030 fixing typos

- src/snowflake/snowpark/dataframe.py
- tests/integ/test_simplifier_suite.py
Fixes SNOW-668696
Use SelectStatement for natural join
> SNOW-668696: Flatten natural join

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/table.py
Fixes #505 
Now you can get autocomplete after to_pandas()! Also, using @overload can improve the API doc readability:
> SNOW-665404: Improve async job related APIs' annotations

- src/snowflake/snowpark/functions.py
- tests/integ/scala/test_function_suite.py
> SNOW-623555: Allow ntile to accept int value

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- tests/unit/test_function.py
> SNOW-667839: Replace functions.builtin with functions.function 

- tests/integ/scala/test_async_job_suite.py
> SNOW-669535: Bump the threshold to 20s for test_async_is_running_and_cancel

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
Description
As title
Testing
N/A
Fixes #NNNN
> SNOW-667837 Add release note for 0.11.0

- tests/integ/test_udf.py
Address #SNOW-656800
Add more integration tests to cover the data types of input and output supported by vectorized UDF's, as documented [here](https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-batch.html#type-support).
> [SNOW-656800] Add tests on data types for vectorized UDF's

- src/snowflake/snowpark/dataframe.py
- tests/integ/test_dataframe.py
Fixes #NNNN
To align with [pyspark](https://spark.apache.org/docs/3.1.2/api/python/reference/api/pyspark.sql.DataFrame.join.html) and [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html).
> SNOW-664571: Add "on" as an alias for "using_columns" and "how" as an alias for "join_type" in DataFrame.join

- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
> SNOW-664555: Session.use_secondary_roles

- tests/integ/test_session.py
> Skip test_use_secondary_roles in SP

- tests/integ/scala/test_dataframe_copy_into.py
> Fix an error message in test_copy_json_negative_test_with_column_names

- recipe/meta.yaml
N/A
Port https://github.com/AnacondaRecipes/snowpark-python-feedstock/commit/d1de488961c46e91ed22af3a66758176add9b346
> Remove pandas constraints on local recipe

- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/functions.py
Fixes #SNOW-650290
Remove `Column` type from the signature. ([Relevant slack discussion](https://snowflake.slack.com/archives/C02KH7E6SHX/p1664996589510559))
> SNOW-650290 Change type hints for column.in_ and functions.in_

- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- tests/unit/test_analyzer_util_suite.py
Fixes #SNOW-654057
escape single quotes in the middle of a string before adding single quotes to both sides of it.
> SNOW-654057: Escape single quote when converting a string value to SQL option

- src/snowflake/snowpark/session.py
Fixes #SNOW-660004
Add text in the API doc to tell users to double quote the table name if it has special chars.
> SNOW-660004: Add notes to session.table() about table name.

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_dataframe_suite.py
Fixes #SNOW-654710
Instead of purging the cached table automatically, we added an API and context manager to drop the table manually.
> SNOW-654710: Add drop_table() to class Table

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_copy_into.py
> SNOW-619385: Pass options set in session.read.options to df.copy_into_table

- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/session.py
- tests/integ/test_telemetry.py
Fixes #SNOW-675138
Instrument 1) when the sql simplifier is enabled 2) when a df action is invoked
> SNOW-675138: Add telemetry to queries that use sql simplifier

- src/snowflake/snowpark/_internal/telemetry.py
- tests/integ/test_telemetry.py
> SNOW-675138: Add sql simplifier telemetry type

- .pre-commit-config.yaml
- src/snowflake/snowpark/files.py
- tests/unit/test_files.py
SNOW-640230
We create a SnowflakeFile interface for user to use during development of Python UDF locally.
I have read the CLA Document and I hereby sign the CLA
> SNOW-640230-add SnowflakeFile interface and tests

- src/snowflake/snowpark/dataframe.py
> SNOW-646407 Add documentation about referencing overlapping columns in join when no suffix is provided

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> Add Release notes to 0.12.0 release notes

- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_async_job_suite.py
Fixes #SNOW-676250
Remove experimental tags and related warnings and docstring.
> SNOW-676250 remove experimental tags

- snowpark_style_guide.md
Fixes #SNOW-628244
create a style guide like: https://github.com/palantir/pyspark-style-guide
> SNOW-628244: Create a style guide for snowpark python api

- src/snowflake/snowpark/_internal/utils.py
- tests/unit/scala/test_utils_suite.py
> SNOW-662338: Handle `None` returned by connector's cursor

- tests/perf/long_runner.py
Fixes #SNOW-526816
Use the python scripts with command line to repeatedly run DataFrame operations for long time (hours, or days)
For instance, run the test with sql simplifier and 50 columns for 3 days (259200 seconds) and output CPU and Memory usage every 60 seconds.
```cmd
python long_runner.py --duration 259200 --res_interval 60 --log_folder "results/simplifier" --columns 50 --simplify
```
> SNOW-526816: Add long running test script

- src/snowflake/snowpark/dataframe_reader.py
Fixes #SNOW-588656
Update documentation to let people know breaking select behavior without using quoted columns when loading dataframe from parquet, orc or avro.
> SNOW-588656 add note to quote columns

- tests/unit/__init__.py
- tests/unit/test_pandas_to_df.py
Description
as title
Testing
unit test
Improve test coverage for `_internal/error_message.py` and `session.py`
> SNOW-683056 Add unit test to cover DF_PANDAS_GENERAL_EXCEPTION

- tests/integ/scala/test_dataframe_copy_into.py
These tests are flaky because we didn't sort the results
> Deflake test_dataframe_copy_into.py

- src/snowflake/snowpark/_internal/telemetry.py
Description
These three decorators are not used in the codebase.
Testing
existing tests
These three decorators are not used in the code base.
> SNOW-683056 Remove unused decorator in telemetry.py

- src/snowflake/snowpark/_internal/type_utils.py
- tests/integ/test_dataframe.py
- tests/unit/test_types.py
Description
Added/Modified tests to increase test coverage. Also removed some unused code path.
Testing
unit/integ tests
Added/Modified tests to increase test coverage. Also removed some unused code path.
> SNOW-683056 Increase test coverage for type_utils.py

- tests/integ/test_udtf.py
- tests/unit/conftest.py
- tests/unit/test_udf_utils.py
Description
Covers the remaining lines
Testing
unit/integ test
Covers the remaining lines in udf_utils.py
> SNOW-683056 Increase code coverage for udf_utils.py

- src/snowflake/snowpark/_internal/server_connection.py
Description
These code paths are tested in internal regression tests
Testing
N/A
Skip is_in_stored_procedure() branch for code coverage given they are tested in internal regression tests
> SNOW-683056 Skip is_in_stored_procedure() branch for code coverage

- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
- tests/integ/test_telemetry.py
> SNOW-681372: Use session parameter PYTHON_SNOWPARK_USE_SQL_SIMPLIFIER

- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Description
As title
Testing
integ test
Fixes SNOW-585098 
Support secure UDF and UDTF.
> SNOW-585098 Support secure UDF/UDTF

- src/snowflake/snowpark/_internal/code_generation.py
- tests/unit/test_code_generation.py
Fixes #NNNN
Also found two bugs where the code is not covered by tests
> SNOW-683054: Improve the code coverage of code_generation.py

- src/snowflake/snowpark/files.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- src/snowflake/snowpark/row.py
- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
- tests/unit/test_files.py
- tests/unit/test_function.py
- tests/unit/test_row.py
> SNOW-683057: Improve code coverage of row, files, session, functions

- src/snowflake/snowpark/table.py
- src/snowflake/snowpark/types.py
- src/snowflake/snowpark/window.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_update_delete_merge_suite.py
- tests/integ/test_table_function.py
- tests/integ/test_udtf.py
- tests/unit/test_stored_procedure.py
- tests/unit/test_types.py
- tests/unit/test_udf.py
- tests/unit/test_udtf.py
> SNOW-683060 add test coverage for code-coverage batch-5

- src/snowflake/snowpark/functions.py
- tests/integ/scala/test_function_suite.py
> SNOW-683060 add test coverage function.py

- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/functions.py
Fixes #SNOW-685611
Only updating type hints
> SNOW-685611 remove redundat union type hints

- .github/workflows/precommit.yml
> Change coverage path of Test SQL Simplifier macos-3.8-aws

- src/snowflake/snowpark/session.py
> Use cursor instead of _run_query to avoid unnecessary error logs

- src/snowflake/snowpark/exceptions.py
> SNOW-679009: Include query id when printing SnowparkSQLException

- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/table.py
- src/snowflake/snowpark/udf.py
> SNOW-583979: Improve UDF and table merge docstring

- CHANGELOG.md
- recipe/meta.yaml
- setup.py
- src/snowflake/snowpark/version.py
> SNOW-682115: Get ready to release 1.0.0

- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/unary_expression.py
- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_simplifier_suite.py
- tests/unit/test_analyzer_util_suite.py
- tests/unit/test_expressions.py
> SNOW-683054: Analyzer-related test coverage improvement

- ci/test_fips.sh
> SNOW-688841: Fix failing FIPS tests

- src/snowflake/snowpark/session.py
- tests/integ/scala/test_dataframe_suite.py
- tests/unit/test_session.py
Fixes #SNOW-683057
Use mock to add tests to the not-covered session.py
> SNOW-683057: Improve session.py code coverage

- tests/integ/scala/test_function_suite.py
Fixes #NNNN
Ensuring that the test runs successfully irrespective of timezone in the test env.
> SNOW-683060 fix timezone test

- src/snowflake/snowpark/table.py
> SNOW-645093: Add example to merge method with & operator

- tests/integ/scala/test_dataframe_copy_into.py
> SNOW-691384: Fix flaky test test_copy_csv_copy_transformation_with_column_names

- src/snowflake/snowpark/dataframe.py
> SNOW-710021: Add multi-aggregation sample code to DataFrame.agg

- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Fixes #640 
- [ X] I am adding a new automated test(s) to verify correctness of my new code
It just adds the missing overloads
> Adding overloads

- src/snowflake/snowpark/files.py
Description
Add a seek method to SnowflakeFile API. The server side is already set up.
> SNOW-706985 add seek method to SnowflakeFile API

- docs/source/column.rst
- docs/source/functions.rst
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/functions.py
- tests/unit/test_column.py
- tests/unit/test_function.py
SNOW-698080
The second part will come with `flatten` related functions.
> SNOW-698080: Add functions for user code migration (part 1)

- .github/workflows/precommit.yml
- src/snowflake/snowpark/session.py
- tests/conftest.py
- tests/integ/test_session.py
- tests/integ/test_simplifier_suite.py
> SNOW-721895: Set Session.sql_simplifier_enabled True by default

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
Fixes #SNOW-726471
Update Changelog and bump version number.
> SNOW-726471 Release Snowpark 1.1.0

- CHANGELOG.md
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/exceptions.py
- src/snowflake/snowpark/session.py
- tests/integ/test_pandas_to_df.py
- tests/integ/test_udf.py
- tests/unit/test_udf_utils.py
> Revert behavior changes 

- setup.py
> Accommodate Python connector major version bump

- CHANGELOG.md
> Update 1.1.0 Release date

- .github/workflows/semgrep.yml
SNOW-667402 : Security Update
This PR creates/updates the Semgrep static analysis workflow. Local semgrep rules have been deleted. 
If your repo had a semgrep stage in the Jenkinsfile, we attempted to delete it.  Please review changes and merge them as soon as possible
[Announcement](https://snowflake.slack.com/archives/C02BTC3HY/p1661797484408489)
> SNOW-667402:Semgrep workflow update

- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
> SNOW-703365: add functions.reverse

- src/snowflake/snowpark/_internal/udf_utils.py
Description
This is a no-op today, but will be useful when we support multiple python minor versions.
Testing
existing tests
Fixes SNOW-742345
This is a no-op today, but will be useful when we support multiple python minor versions.
> SNOW-742345 Use current runtime version for UDF/SP creation

- .github/workflows/precommit.yml
Description
Follow-up to add no-simplifier py39 test. We did not add FIPS test because connector today also only tests on one python version.
Testing
merge gate
Fixes SNOW-742340
Add no-simplifier py39 test.
> SNOW-742340 Add no-simplifier py39 test

- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/session.py
Fixes #SNOW-741323
Unset `snowflake.connector.paramstyle` in import path, set it by adding an optional connection parameter.
> SNOW-741323  Remove side effect of import statements

- recipe/meta.yaml
Description
The internal recipe should enable runtime test mode to build packages for different python versions
Testing
precommit job
Fixes #NNNN
> SNOW-742344 Add SNOWFLAKE_IS_PYTHON_RUNTIME_TEST to recipe

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-751624 Release Snowpark Python 1.2.0

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/version.py
- tests/integ/test_dataframe.py
- tests/unit/test_analyzer_util_suite.py
- tests/unit/test_dataframe.py
> Revert SNOW-719900 Remove random alias for subqeury in joins (#669)

- tests/integ/conftest.py
Fixes #SNOW-753533
Read `role` from `parameters.py` when running integ tests.
> read role from parameters.py if present for integ tests

- src/snowflake/snowpark/functions.py
Fixes #SNOW-749408
Add doctest examples.
> SNOW-749408  Add function example - batch 3

- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/row.py
- tests/integ/test_dataframe.py
- tests/unit/test_row.py
Fixes #618 
`_internal/utils.py` and `row.py` are the two files where the interesting changes are present. Rest of the files are just propagating parameters and tests.
> SNOW-693539: Allow case insensitive access to fields on Row

- src/snowflake/snowpark/mock/mock_analyzer.py
- src/snowflake/snowpark/mock/mock_plan.py
- src/snowflake/snowpark/mock/mock_select_statement.py
- src/snowflake/snowpark/mock/snowflake_data_type.py
- src/snowflake/snowpark/mock/util.py
- tests/mock/test_filter.py
- tests/mock/test_sort.py
> SNOW-749342: Impelment sorting and filtering

- tests/integ/test_dataframe.py
> SNOW-758000 skip async job tests inside SP

- tests/integ/test_session.py
> SNOW-758381 skip test_runtime_config if run in SP

- src/snowflake/snowpark/functions.py
Fixes #SNOW-749407
Adding examples for functions in `snowflake.snowpark.functions` file.
> add example to functions batch 2

- src/snowflake/snowpark/functions.py
> SNOW-749412: snowpark python functions sample code batch 6

- .github/workflows/changelog.yml
Fixes #725 
Add a Github Workflow to grep for `CHANGELOG.md` in the list of changed files in a PR's `git diff`. Skip this check by specifying the label "NO-CHANGELOG-UPDATES".
> SNOW-756525 Add changelog check in CI

- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/error_message.py
- tests/unit/scala/test_error_message.py
Fixes #SNOW-701257
Update all instances where `ProgrammingError` was caught and query information was dropped.
> SNOW-701257 extract query from all programming errors

- src/snowflake/snowpark/mock/mock_analyzer.py
- src/snowflake/snowpark/mock/mock_functions.py
- src/snowflake/snowpark/mock/mock_plan.py
- tests/mock/test_agg.py
- tests/mock/test_sort.py
> SNOW-757921: implement aggregation functions

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/row.py
- tests/unit/test_row.py
Fixes #SNOW-693539
Based on discussion with @sfc-gh-yixie we have decided to make row builder interface internal and only expose it via `dataframe.collect`.
> SNOW-693539: make row builder private

- tests/integ/conftest.py
> Fix test connection parameter 

- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
> SNOW-749411: add example for functions

- CHANGELOG.md
- src/snowflake/snowpark/version.py
> SNOW-769625: 1.3.0 release preparation

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/table_function.py
- tests/integ/test_dataframe.py
> SNOW-704112 explode related methods

- src/snowflake/snowpark/functions.py
- tox.ini
Fixes SNOW-749414
Just adding some code examples to doc-strings
> SNOW-749414 adding code examples

- src/snowflake/snowpark/functions.py
Fixes #SNOW-704112
Adding tests to track usage of `functions.explode`.
> SNOW-704112 Add telemetry to explode

- src/snowflake/snowpark/functions.py
Fixes #SNOW-749406
Add sample code with doctest
> SNOW-749406: Add sample code to functions - batch 1

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
- tests/integ/test_function.py
- tests/integ/test_session.py
Fixes #732, #730, #710, SNOW-754768
- [ X ] I am adding a new automated test(s) to verify correctness of my new code
if adds implementations in functions.py and session.py for:
function.array_distinct
functions.regexp_extract
functions.struct
functions.format_number
function.daydiff
functions.date_add
functions.date_sub
session.getOrCreate and session.appName
> Snowpark_extensions_for_functions

- src/snowflake/snowpark/mock/mock_plan.py
- src/snowflake/snowpark/mock/mock_select_statement.py
- tests/mock/test_union.py
> SNOW-757922: local testing dataframe union

- CHANGELOG.md
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/session.py
- tests/integ/test_udf.py
- tests/unit/scala/test_utils_suite.py
SNOW-787955
The original PR for SnowML here. https://github.com/snowflakedb/snowml/pull/589/files
> SNOW-787955: resolve namespace collision for udf/stored proc imports 

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/exceptions.py
- tests/integ/test_dataframe.py
- tests/unit/scala/test_error_message.py
- tests/unit/test_analyzer_util_suite.py
- tests/unit/test_dataframe.py
- tests/utils.py
Fixes #[SNOW-535070](https://snowflakecomputing.atlassian.net/browse/SNOW-535070)
Adds support for creating Snowflake Dynamic Tables from a DataFrame.
[SNOW-535070]: https://snowflakecomputing.atlassian.net/browse/SNOW-535070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-535070 Adds support for DTs

- tests/integ/test_session.py
> Fix regression test failures

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_writer_suite.py
- tests/integ/test_session.py
- tests/unit/test_session.py
> SNOW-781049: support dot in table name

- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_writer_suite.py
- tests/integ/test_session.py
Fixes SNOW-781049, the tests previous PR are incompatible with stored proc because it can not create randomly generated temp table name.
pre-commit test: https://buwa.ci1.us-west-2.aws-dev.app.snowflake.com/builds/precommit/ci-dev-133.int.snowflakecomputing.com/9897
> SNOW-781049: update test to be compatible with stored proc

- src/snowflake/snowpark/table.py
Fixes SNOW-797214
Fix flaky test
> SNOW-797214 Fix flaky test for table.py

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/session.py
- tests/integ/test_bind_variable.py
Description
- Add params to session.sql
- Plumb params to python connector
- Make sure params are processed correctly in plan nodes
Testing
integ test
Fixes SNOW-754127 
- Add params to session.sql
- Plumb params to python connector
- Make sure params are processed correctly in plan nodes
> SNOW-754127 Support binding variable in session.sql

- src/snowflake/snowpark/async_job.py
> SNOW-754092: Fix flaky async job tests

- src/snowflake/snowpark/async_job.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/session.py
> Remove experimental decorator for Async job

- .github/workflows/precommit.yml
> SNOW-731800: Enable manually run precommit

- tests/integ/test_udf.py
Fixes #NNNN
Marks `register_from_file_with_skip_upload` as flaky.
> SNOW-799761: add xfail to flaky test on gcp

- src/snowflake/snowpark/session.py
- tests/unit/test_session.py
Fixes #763
Instead of forcing users to set database explicitly, query built-in snowflake DB. That way user can specify packages and FQNs when registering UDF/Sproc without any issues
> #763: Fix querying conda packages list

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
Fixes #SNOW-799501
Add alias `functions.element_at` for `functions.get` and improve examples to show the full range of the function.
> SNOW-799501 added alias and added more examples

- tests/integ/scala/test_result_attributes_suite.py
- tests/integ/scala/test_result_schema_suite.py
- tests/integ/test_pandas_to_df.py
Helps with SNOW-802306
In this PR I should have made some tests more resilient against name collision and provide more information when they fail.
> SNOW-802306 improve tests

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes #SNOW-774303
We missing adding correct `pre_actions` and `post_actions` in `SelectTableFunction` in its initial implementation. This change is to add that.
> SNOW-774303: Add pre and post actions in SelectTableFunction

- docs/source/functions.rst
Fixes the missing function names in functions.rst
> SNOW-799496 update functions.rst

- .github/workflows/precommit.yml
Description
Today we only do no-simplifier tests for macos/py38 combination, the rest is actually testing the simplifier path, which is not desired
Testing
N/A
Fixes #NNNN
> Fix no-simplifier merge gate tests

- src/snowflake/snowpark/mock/mock_plan.py
- src/snowflake/snowpark/mock/util.py
- tests/mock/test_functions.py
> SNOW-786728: Local test implement first/take

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/functions.py
- tests/integ/scala/test_function_suite.py
- tests/integ/test_function.py
- tests/unit/test_function.py
Implementing feature request in SNOW-804340
The main addition made in this PR is a new Snowflake function called  `array_unique_agg` which serves a similar purpose to `spark.sql.functions.collect_set` in pyspark.
> SNOW-804340 add array_unique_agg function

- src/snowflake/snowpark/dataframe_writer.py
Fixes #NNNN
Follow up https://github.com/snowflakedb/snowpark-python/pull/755. For credit usage when queries are executed via writer APIs.
> SNOW-788527: Add dataframe statement params to query executions in dataframe writer

- tests/integ/test_stored_procedure.py
Fixes #NNNN
Fix breaking regtests that are caused due to temp stored procedure name collision.
> Fix Table Sproc regression tests.

- src/snowflake/snowpark/dataframe.py
Fixes #NNNN
Add statement params to the dataframe created from `_with_plan`.
> SNOW-788527: Add statement params to returned new dataframe

- .github/workflows/precommit.yml
- tests/conftest.py
- tests/integ/conftest.py
- tox.ini
Fixes #NNNN
-    Test local testing changes by marking a test function `localtest` and `tox -e py{ver}-local` 
-    Add local testing jobs in CI
> Add testing utils for local testing

- .github/workflows/precommit.yml
Fixes #NNNN
Please see https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency.
> Only run precommit for HEAD and cancel in-progress jobs

- tests/integ/test_dataframe.py
Fixes SNOW-812442
Updated the dynamic table integration test to avoid a newly added server error.
> SNOW-812442 update dynamic table test to avoid new error

- src/snowflake/snowpark/mock/__init__.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/mock_functions.py
- src/snowflake/snowpark/mock/mock_plan.py
- src/snowflake/snowpark/mock/snowflake_data_type.py
- tests/mock/test_agg.py
> SNOW-808886: local testing implement user defined mock function feature

- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_datatype_suite.py
Fixes #NNNN
Results from describe result query are inconsistent which is causing this test to fail in reg env. Quarantining this test until bug is fixed from sql side.
> Mark xfail for some string type checks

- tests/integ/test_udf.py
> Remove a test line that is not consistently reproducible

- tests/integ/scala/test_datatype_suite.py
- tests/integ/test_dataframe.py
> Mark xfail for known string type bug

- .github/CODEOWNERS
- CHANGELOG.md
> set default reviewer

- CHANGELOG.md
- src/snowflake/snowpark/column.py
- tests/integ/test_column.py
Fixes #SNOW-805802
Add an alias to `functions.contains` in `Column` to ease lift and shift effort by snow-convert team.
> SNOW-805802 Add Column.contains

- CHANGELOG.md
- src/snowflake/snowpark/types.py
- tests/unit/test_types.py
Fixes #SCT-2035
Add a way to append more fields to `StructType` using `add`.
> Add StructType.add

- CHANGELOG.md
- src/snowflake/snowpark/relational_grouped_dataframe.py
- src/snowflake/snowpark/session.py
- tests/integ/test_dataframe.py
- tests/integ/test_df_aggregate.py
Fixes #SNOW-767766
Another attempt at addressing the issue described in #758. Test change is taken from original PR.
> SNOW-767766:  Remove _strip_invalid_sf_identifier_chars

- src/snowflake/snowpark/session.py
> SNOW-738585: Update docstring of session.telemetry_enabled

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/mock_analyzer.py
- src/snowflake/snowpark/mock/mock_plan.py
- src/snowflake/snowpark/mock/mock_select_statement.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
- tests/integ/test_df_aggregate.py
- tests/mock/test_union.py
- tests/utils.py
Duplication change of PR: https://github.com/snowflakedb/snowpark-python/pull/853
because rebasing requires too much work, so start a new PR
> SNOW-820061: Add tests for aggregate

- src/snowflake/snowpark/mock/mock_plan.py
- tests/integ/scala/test_dataframe_set_operations_suite.py
> SNOW-823356: Local testing add tests to union functions

- CHANGELOG.md
- docs/source/io.rst
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
Fixes #SNOW-619443
Added support for querying metadata columns from stage when creating DFs using `DataFrameReader`. More about metadata columns can be found here: https://docs.snowflake.com/en/user-guide/querying-metadata
> SNOW-619443 Add ability to query metadata columns from stage

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- src/snowflake/snowpark/session.py
- tests/integ/conftest.py
- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/scala/test_dataframe_writer_suite.py
- tests/integ/test_session.py
- tests/unit/test_session.py
- tests/utils.py
Fixes SNOW-831868
when users input a string as table name, it can be a unquoted identifier or double quoted identifier.
we need to tell whether a `.` (dot) in the string is part of the name of whether it splits the schema and table name.
This PR follows the guidance from snowflake to resolve the identifier.
> SNOW-831868: Fix table name exist check

- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/test_session.py
> SNOW-830758: Fix tests in stored proc

- src/snowflake/snowpark/types.py
- tests/unit/test_types.py
> Fix hash value for correct comparison

- src/snowflake/snowpark/mock/mock_connection.py
- src/snowflake/snowpark/table.py
- tests/conftest.py
- tests/integ/scala/test_table_suite.py
> [Local testing] Support `Table.drop_table`

- CHANGELOG.md
- docs/README.md
- docs/source/functions.rst
- docs/source/types.rst
- recipe/meta.yaml
- setup.py
- src/snowflake/snowpark/_internal/analyzer/datatype_mapper.py
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/types.py
- src/snowflake/snowpark/version.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/scala/test_function_suite.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/scala/test_table_suite.py
- tests/integ/scala/test_udf_suite.py
- tests/integ/test_udf.py
- tests/unit/test_datatype_mapper.py
- tests/unit/test_types.py
- tests/utils.py
- tox.ini
> SNOW-844520 - Release 1.5.1

- CHANGELOG.md
- setup.py
https://snowflakecomputing.atlassian.net/browse/SNOW-845800
> SNOW-845800: Remove redundant typing-extensions dependency

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_stat_functions.py
- tests/integ/scala/test_dataframe_suite.py
> Add sort to fix test results

- tests/integ/scala/test_permanent_udf_suite.py
- tests/integ/test_df_to_pandas.py
https://snowflakecomputing.atlassian.net/browse/SNOW-845769
> SNOW-845769: Unskip test_mix_temporary_and_permanent_udf

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_bind_variable.py
- tests/integ/test_dataframe.py
- tests/integ/test_telemetry.py
- tests/unit/test_dataframe.py
https://snowflakecomputing.atlassian.net/browse/SNOW-845927
- [] I am adding new logging messages
> SNOW-845927: Change implementation of rename() to use RENAME SQL clause

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Fixes #SNOW-821760
Add support for `functions.array_sort`
> SNOW-821760: Add support for array_sort

- tests/integ/conftest.py
Description
We hit 10k row limit for SHOW TABLES in our Jenkins tests. Using temp schema can help resolve this issue.
Testing
Jenkins test
Fixes SNOW-849062
> SNOW-849062 Use temp schema for Jenkins initiated tests

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/snowflake_data_type.py
- src/snowflake/snowpark/session.py
- tests/mock/readme.md
> SNOW-844977: bug bash part 2 update tests and readme

- src/snowflake/snowpark/session.py
> Fix failing doc test for Session.write_pandas

- src/snowflake/snowpark/dataframe_na_functions.py
- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/connection.py
- src/snowflake/snowpark/mock/select_statement.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table.py
- tests/conftest.py
- tests/integ/scala/test_session_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_function.py
- tests/integ/test_query_history.py
- tests/integ/test_session.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_telemetry.py
- tests/integ/test_udtf.py
- tests/utils.py
> SNOW-841487  [Local Testing] Raise good error messages for unsupported API

- .github/workflows/precommit.yml
- tests/integ/scala/test_query_tag_suite.py
- tox.ini
> Run tests in parallel

- .github/workflows/cla_bot.yml
- CONTRIBUTING.md
Fixes #NNNN
CLA document is moved to a new repo, we need to update the link. This should be automated in the future.
> Update CLA link

- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_udtf_suite.py
- tests/integ/scala/test_update_delete_merge_suite.py
- tests/integ/test_dataframe.py
> SNOW-817445 fix pre-commit tests

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/table_function.py
Fixes #SNOW-855964
We added in this PR: https://github.com/snowflakedb/snowpark-python/pull/762, but `explode_outer` was not covered. Add support for it in this PR.
> SNOW-855964: Add explode_outer

- tests/integ/test_udf.py
> Package auto-upload: Fix native dependency tests

- tests/integ/test_packaging.py
- tox.ini
>  SNOW-848839: Fix unpinned packages

- ci/test_fips.sh
- recipe/meta.yaml
> Add pytest timeout package to FIPS environment

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/udaf.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_udaf.py
- tests/resources/test_udaf_dir/test_udaf_file.py
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_udaf.py
- tests/utils.py
Description
Add UDAF API support
Testing
Unit + Integ
Fixes SNOW-747608 
Add UDAF API support
> SNOW-747608 Support UDAF API

- src/snowflake/snowpark/session.py
- tests/utils.py
Fixes #NNNN
85 warnings down to 4, which could be further silenced if desired.
> SNOW-851550 Clean up pytest warnings

- src/snowflake/snowpark/_internal/udf_utils.py
- tests/integ/test_udtf.py
Fixes #NNNN
Precommit run: https://ci-dev-142.int.snowflakecomputing.com/job/PythonStoredProcBuildPrecommitTest/476/
> Fix PythonStoredProcBuildPrecommitTest

- src/snowflake/snowpark/_internal/packaging_utils.py
- tests/integ/test_packaging.py
- tests/unit/test_packaging_utils.py
> SNOW-871306: Fix test failures on Windows for tests in test_packaging.py

- tox.ini
> Increase pytest timeout to 1200 seconds

- src/snowflake/snowpark/session.py
> Revert PR 930

- src/snowflake/snowpark/_internal/udf_utils.py
- tests/integ/scala/test_udtf_suite.py
- tests/integ/test_udtf.py
- tests/resources/test_udtf_dir/test_udtf_file.py
Fixes #NNNN
Fix the `ValueError`s in https://ci-dev-151.int.snowflakecomputing.com/job/TestSnowMLSnowpark/70/console by (1) allowing `process` to have a type hint of None and (2) favoring `end_parition`'s return type hint over that of `process`.
> Fix ML precommit

- src/snowflake/snowpark/async_job.py
> SNOW-833259: Skip async doc test

- src/snowflake/snowpark/session.py
> SNOW-875849: Add docstring for sql_simplifier_enabled

- tests/integ/test_dataframe.py
> Skip test_dataframe_result_cache_changing_schema in stored proc

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-878562 - Release 1.6.0

- .github/workflows/precommit.yml
- tox.ini
> Add no pandas merge gate

- .github/workflows/precommit.yml
- src/snowflake/snowpark/_internal/udf_utils.py
- tests/integ/scala/test_async_job_suite.py
- tests/integ/test_bind_variable.py
- tests/integ/test_dataframe.py
- tests/integ/test_df_to_pandas.py
- tests/integ/test_pandas_to_df.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_telemetry.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
- tests/unit/test_code_generation.py
- tests/unit/test_pandas_to_df.py
- tests/unit/test_session.py
- tests/unit/test_types.py
- tox.ini
> Fix tests with no pandas installed

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-884263 - Release 1.6.1

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Fixes #SNOW-821772
Add `array_flatten` to `snowflake.snowpark.functions`
> SNOW-821772: Add support for functions.flatten

- tests/integ/test_function.py
Fixes #SNOW-821772
I introduced bad linted file in my last merge. This is the fix.
> SNOW-821772: Fix lint

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/conftest.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
> SNOW-867520: external access integration

- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
- tests/utils.py
Fixes SNOW-867520, fixing test failures in jenkins running due to missing resources
> SNOW-867520: fix test failure in jenkins

- CHANGELOG.md
- src/snowflake/snowpark/_internal/type_utils.py
- tests/unit/test_types.py
Fixes #994
Earlier the result of `merge_type(a, b)` was not same as `merge_type(b, a)`. This change fixes the issue.
> SNOW-888898: Fix merge_type logic

- src/snowflake/snowpark/async_job.py
Fixes [SNOW-754092](https://snowflakecomputing.atlassian.net/browse/SNOW-754092)
Actually it doesn't make sense to test if an async query is faster than non-async query, and we have enough coverage for it, so we can just remove it for now. 
[SNOW-754092]: https://snowflakecomputing.atlassian.net/browse/SNOW-754092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-754092: Remove the flaky async test

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/column.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_na_functions.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/table_function.py
- src/snowflake/snowpark/types.py
- tests/integ/scala/test_session_suite.py
- tests/integ/scala/test_udtf_suite.py
- tests/integ/scala/test_view_suite.py
- tests/integ/test_column_names.py
- tests/unit/scala/test_datatype_suite.py
- tests/unit/test_types.py
- tests/utils.py
> SNOW-823361 Enquote normalized names in constructor of ColumnIdentifier

- local-testing-docs/README.md
- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/util.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/mock/test_datatypes.py
Fixes #SNOW-849605
- fix nullable
- fix time type, timestamp type
> SNOW-849605: fix datatype misalignment

- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/select_statement.py
- tests/integ/scala/test_dataframe_copy_into.py
- tests/integ/test_dataframe.py
[SNOW-844493](https://snowflakecomputing.atlassian.net/browse/SNOW-844493)
and
[SNOW-849373](https://snowflakecomputing.atlassian.net/browse/SNOW-849373)
[SNOW-844493]: https://snowflakecomputing.atlassian.net/browse/SNOW-844493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNOW-849373]: https://snowflakecomputing.atlassian.net/browse/SNOW-849373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> [Local Testing] Fix aggregation with empty dataframe and support limit offset

- tests/integ/test_packaging.py
> Test fixes

- src/snowflake/snowpark/_internal/server_connection.py
- src/snowflake/snowpark/session.py
- tests/unit/test_session.py
This PR add the simple change needed to enable async child job creation in Python stored procs. We need this change along with Stored-Proc-Python-Connector changes (https://github.com/snowflakedb/Stored-Proc-Python-Connector/pull/123) for the main [PR #117080](https://github.com/snowflakedb/snowflake/pull/117080).
Precommit run with https://github.com/snowflakedb/Stored-Proc-Python-Connector/pull/123 and BPTP-stable: …
> SNOW-867508: Snowpark changes for Python stored proc async child jobs

- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/scala/test_literal_suite.py
- tests/integ/test_dataframe.py
- tests/utils.py
> SNOW-815559: Remove xfail from string type tests

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/functions.py
Fixes #SNOW-859947
Added `function.flatten` to have quick access for `flatten` table function with examples on some helpful ways to use it.
> SNOW-859947 Add function for flatten

- tests/integ/test_udf.py
Fixes SNOW-896225
The failures are caused by precision differences between the datetime objects. This PR modifies the test to accept a bigger set of precisions.
> SNOW-896225  Fix test failures in QA

- src/snowflake/snowpark/functions.py
Fixes #1013 
Fix documentation to match with implementation
> SNOW-898383: Fix documentation to match implementation

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan_node.py
- src/snowflake/snowpark/dataframe_writer.py
- tests/integ/test_dataframe.py
Fixes #SNOW-819811
Add a way to add clustering keys when creating a new table.
> SNOW-819811: Support clustering keys in table creation

- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
> SNOW-844750: Add examples to array related functions

- tests/integ/test_dataframe.py
CP the change in https://github.com/snowflakedb/snowpark-python/pull/1033/files
> SNOW-903873: fix flaky test dynamic table creation

- CHANGELOG.md
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/dataframe_na_functions.py
- tests/integ/test_stored_procedure.py
- tests/resources/test_sp_dir/test_table_sp_file.py
- tests/unit/scala/test_utils_suite.py
- tests/unit/test_types.py
- tests/utils.py
Fixes #1019 
Fix type hint detection when registering table sprocs using `register_from_file`.
> SNOW-900112 fix table sproc register from file

- local-testing-docs/README.md
- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
- tests/integ/scala/test_dataframe_join_suite.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_column.py
- tests/integ/test_df_aggregate.py
- tox.ini
> SNOW-899722 [Local Testing] Update supported API list and enable more tests.

- CHANGELOG.md
- src/snowflake/snowpark/_internal/packaging_utils.py
- src/snowflake/snowpark/session.py
- tests/integ/test_packaging.py
- tests/unit/test_packaging_utils.py
> SNOW-903907: Custom package upload bug fix

- .github/workflows/precommit.yml
- src/snowflake/snowpark/_internal/code_generation.py
- src/snowflake/snowpark/types.py
- tests/integ/test_dataframe.py
- tests/integ/test_packaging.py
- tox.ini
> SNOW-900365: Add Python 3.11 merge gate

- src/snowflake/snowpark/session.py
The original import won't work in stored procedure, so we need to import it inside the create function
> Fix default config reading import

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/connection.py
- tests/integ/scala/test_dataframe_suite.py
Fixes [SNOW-904169](https://snowflakecomputing.atlassian.net/browse/SNOW-904169)
[SNOW-904169]: https://snowflakecomputing.atlassian.net/browse/SNOW-904169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Local Testing] SNOW-904169 Add support for DataFrame.cache_result

- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/udtf.py
Fixes #NNNN
Adds the missing `PandasDataFrameType` in type hints annotation.
> Fix type hints for registering vectorized UDTF

- src/snowflake/snowpark/session.py
Fixes #NNNN
Precommit passes with this fix.
> SNOW-910685: Fix importing config manager

- setup.py
Fixes SNOW-900365, we also need to update cloudpickle to support py 3.11
> SNOW-900365: update cloudpickle dep for python 3.11 support

- recipe/meta.yaml
> SNOW-900365: update conda build recipe for py311

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-915736 - Release 1.8.0

- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
> SNOW-754087: Remove xfail from if_not_exists tests

- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_function_suite.py
- tests/integ/test_column.py
> [Local Testing] SNOW-904992 Support CaseWhen expressions

- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/functions.py
- tests/integ/scala/test_function_suite.py
- tests/integ/test_column.py
> [Local Testing] SNOW-904988 Support Functions.substr and Column.substr

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/connection.py
- tests/integ/scala/test_large_dataframe_suite.py
> [Local Testing] SNOW-904865 Support DataFrame.toLocalIterator

- src/snowflake/snowpark/mock/functions.py
- tests/integ/scala/test_function_suite.py
- tests/integ/test_function.py
> [Local Testing] SNOW-923345  Support functions.coalesce

- src/snowflake/snowpark/mock/functions.py
- tests/integ/test_column.py
> [Local Testing] SNOW-904987 Support Column.startswith and Column.endswith

- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/mock/plan.py
- tests/integ/scala/test_dataframe_set_operations_suite.py
> [Local Testing] SNOW-904261 Support DataFrame.except_

- local-testing-docs/README.md
- src/snowflake/snowpark/session.py
- tests/integ/conftest.py
> [Local Testing] SNOW-857481 Use session builder pattern for local testing

- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/mock/plan.py
- tests/integ/scala/test_complex_dataframe_suite.py
- tests/integ/scala/test_dataframe_set_operations_suite.py
> [Local Testing] SNOW-904267 Support DataFrame.intersect

- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_dataframe_suite.py
> [Local Testing] SNOW-930302 Support DataFrame.sample and Table.sample

- tests/integ/scala/test_complex_dataframe_suite.py
> SNOW-934379: Sort test result

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-939540 - Release 1.9.0

- .github/workflows/precommit.yml
- tests/integ/test_packaging.py
Fixes SNOW-938998
GCP deployment now has the packages ready
> SNOW-938998: reenable gcp tests after packages are ready

- tests/integ/scala/test_complex_dataframe_suite.py
Fixes SNOW-941914, azure preprod4 failed due to old rpm package, to silence the failure, we cp the test fix
dup change: https://github.com/snowflakedb/snowpark-python/pull/1081/files
> SNOW-941914: fix v1.4.0 test failure

- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/connection.py
- src/snowflake/snowpark/mock/plan.py
- tests/integ/test_column_names.py
- tests/mock/test_column_names.py
Fixes SNOW-913939
handling double quotes in column name
> SNOW-913939: Align column name in local testing with live connection

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
- tests/unit/test_function.py
> SNOW-897931: fix date_format implementation

- src/snowflake/snowpark/async_job.py
- tests/integ/scala/test_async_job_suite.py
Fixes #NNNN
Using the XP's new end-point for canceling async child jobs from stored proc (based the [python's connector new API for canceling queries](https://github.com/snowflakedb/Stored-Proc-Python-Connector/pull/133)).
NOTE: I'll add regression tests in a separate PR.
Precommit with Snowflake bptp-stable and https://github.com/snowflakedb/Stored-Proc-Python-Connector/pull/133:
https://ci-dev-142.int.snowflakecomputing.com/job/PythonStoredProcBuildPrecommitTest/664/
> Smirzaei snow 932731 snowpark sp cancel query

- tests/integ/test_packaging.py
Fixes #NNNN
Marking flaky test as mark.xfail so other snowpark PRs pass merge gate.
> SNOW-948834 Mark flaky test as xfail

- tests/integ/scala/test_async_job_suite.py
Fixes #NNNN
I mistakenly merged a change (PR #1084) enabling a test before having the server-side changes merged. This is causing precommit failures. I'll enable it back once the server-side changes are in. 
Example of a precommit failure: https://ci-dev-133.int.snowflakecomputing.com/job/RT-PC-TestWorker/188666/testReport/junit/(root)/t_python_sp_integ_scala/snowpark_scala_test_async_job_suite_sql/
> Disable the test only PR131074 is merged

- tests/integ/scala/test_dataframe_join_suite.py
- tests/integ/scala/test_dataframe_set_operations_suite.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/scala/test_function_suite.py
- tests/integ/scala/test_permanent_udf_suite.py
- tests/integ/scala/test_session_suite.py
- tests/integ/test_column.py
- tests/integ/test_dataframe.py
- tests/integ/test_df_aggregate.py
- tests/integ/test_function.py
- tests/integ/test_stored_procedure.py
Enables a bunch more tests to run in local testing mode.
> [Local Testing] SNOW-849368 Enable more tests

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
- tests/integ/test_dataframe.py
Fixes #926
Adds case_sensitive keyword arg and passes through to `self._session._conn.execute`.
> SNOW-853533: Support case sensitivity in to_local_iterator

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/functions.py
- tests/integ/test_dataframe.py
- tests/integ/test_simplifier_suite.py
> SNOW-810566: Fix sql flattening logic for windowing and data generator

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/test_simplifier_suite.py
> SNOW-951722: Fix offset impacting previous limit

- src/snowflake/snowpark/functions.py
Fixes #1112 
Minor documentation update to match the functionality.
> Fix daydiff documentation

- src/snowflake/snowpark/window.py
> Add sort in doc test to fix flakiness

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/analyzer.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/snowflake_data_type.py
- src/snowflake/snowpark/mock/util.py
- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_datatype_suite.py
- tests/integ/test_column.py
- tests/integ/test_column_names.py
- tests/integ/test_function.py
- tests/mock/test_datatypes.py
> [Local Testing] SNOW-875801 Support Column.cast

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> Bump up Snowpark Python to 1.10.0

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_na_functions.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- tests/integ/scala/test_dataframe_suite.py
- tests/integ/test_dataframe.py
> [Local Testing] SNOW-904260 support dataframe na functions

- .github/workflows/snyk-issue.yml
- .github/workflows/snyk-pr.yml
> PRODSEC-3611 fix GHA parsing

- tests/integ/test_df_to_pandas.py
Description
Starting from pyarrow 13, pyarrow no longer coerces datetime to nanosecond if pandas version is >= 2.0. So we need to adapt our test.
Testing
integ test
Fixes SNOW-971549
Starting from pyarrow 13, pyarrow no longer coerces datetime to nanosecond if pandas version is >= 2.0. So we need to adapt our test.
> SNOW-971549 Fix test_to_pandas_cast_integer for new pyarrow/pandas

- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/snowflake_data_type.py
- tests/integ/scala/test_column_suite.py
> [Local Testing] SNOW-904990 Support Column.in/Column.isin

- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/connection.py
- src/snowflake/snowpark/mock/functions.py
- tests/integ/test_df_to_pandas.py
- tests/integ/test_pandas_to_df.py
- tests/mock/test_to_pandas.py
> SNOW-786887: implement df.to_pandas

- src/snowflake/snowpark/mock/connection.py
- tests/integ/test_dataframe.py
N/A
This PR includes the changes to support `DataFrame.collect(case_sensitive=False)` in Local Testing and enables the test `tests/integ/test_dataframe.py::test_case_insensitive_collect` for local testing merge gates.
>  [Local Testing] SNOW-850263 Support Dataframe case insensitive collect

- src/snowflake/snowpark/mock/functions.py
- src/snowflake/snowpark/mock/plan.py
- src/snowflake/snowpark/mock/window_utils.py
Fixes #NNNN
This PR includes 2 changes: (1) refactor the FunctionExpression handling code to reduce duplicate code and (2) add a full list of rank related functions.
> [Local Testing] Reduce duplicate code in FunctionExpression handling

- src/snowflake/snowpark/session.py
> SNOW-870432: make use_logical_type backwards compatible

- src/snowflake/snowpark/mock/_analyzer.py
- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_update_delete_merge_suite.py
Fixes #SNOW-929078
CP the table change https://github.com/snowflakedb/snowpark-python/commit/bff4206cefc19d8b45ceb8dc6fcb8d600a91a751.
It is not CPed in the previous merge back to main PR because at that time the work is not finished
> SNOW-929078: Local Testing Support Table.update/delete/merge

- src/snowflake/snowpark/mock/__init__.py
- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/mock/_functions.py
- src/snowflake/snowpark/mock/_plan.py
N/A
- Exposed CUSTOM_JSON_ENCODER and CUSTOM_JSON_DECODER as public APIs. 
- Removed `snowflake.connector.paramstyle = "qmark"`.
> [Local Testing] Expose CUSTOM_JSON_ENCODER and CUSTOM_JSON_DECODER as public APIs

- tests/integ/test_pandas_to_df.py
Fixes #NNNN
update the test to use similar framework as other write_pandas test in the file instead of using a temp table to write the result.
> Do not use temp table to fix sproc test

- CHANGELOG.md
> Bump version to 1.11.0

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/mock/_util.py
- src/snowflake/snowpark/version.py
- tests/integ/test_udf.py
- tox.ini
> SNOW-986112: Fix numpy dependency issue

- tests/integ/scala/test_udf_suite.py
> Fix test_udf_suite

- tests/integ/test_stored_procedure.py
Fixes #NNNN
Removing upload to stage statement which is redundant [see](https://github.com/snowflakedb/snowpark-python/blob/01ee9e8b60d2d132579b4e0b2265f23a4b13f676/tests/integ/test_udf.py#L639-L663) for alternate test in udf file. This fixes our failing test.
> Fix tests/integ/test_stored_procedure.py

- mypy.ini
- src/snowflake/snowpark/_internal/analyzer/expression.py
- src/snowflake/snowpark/_internal/code_generation.py
- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/_internal/type_utils.py
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/row.py
- tox.ini
Fixes #NNNN
This PR cleans up mypy errors in the following files:
```
src/snowflake/snowpark/_internal/telemetry.py 
src/snowflake/snowpark/_internal/type_utils.py 
src/snowflake/snowpark/_internal/udf_utils.py 
src/snowflake/snowpark/_internal/utils.py
```
> Cleaning mypy errors in utils, type_utils, udf_utils, and telemetry.

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/udaf.py
- tests/integ/conftest.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
Fixes SNOW-886368
- add external access integration to UDAF
- refactor test to dynamically create resource each time
> SNOW-886368: UDAF External Access Integration support

- CHANGELOG.md
- src/snowflake/snowpark/stored_procedure.py
- tests/integ/test_stored_procedure.py
N/A (JIRA: SNOW-993761)
Exposes statement_params for telemetry in `StoredProcedure.__call__` for use with snowpark-ml.
> SNOW-993761: Add statement params to anonymous sproc

- src/snowflake/snowpark/session.py
Fixes #NNNN
Created a follow-up JIRA: https://snowflakecomputing.atlassian.net/browse/SNOW-999471
> Fix doctest session.replicate_local_environment

- src/snowflake/snowpark/dataframe_na_functions.py
> fix for DataFrameNaFunctions return type hints

- CHANGELOG.md
- src/snowflake/snowpark/session.py
- tests/integ/test_session.py
Fixes SNOW-933894
Adds new functions to Session that allows a user to append  or update a value on the current session query tag.
> SNOW-933894: Add support for appending to query tag

- src/snowflake/snowpark/files.py
Fixes SNOW-967378
Removing PrPr marking on SnowflakeFile.open.
> SNOW-967378: Remove PrPr warning on SnowparkFile.open

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/_select_statement.py
- tests/integ/test_bind_variable.py
- tests/integ/test_dataframe.py
> SNOW-983006: Copy column states, schema query and query params when copying a DataFrame

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/test_simplifier_suite.py
> SNOW-1011472: Don't flatten the filter df.sort().limit().filter()

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- tests/integ/test_simplifier_suite.py
> Don't flatten if data generator is called after limit.

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
Description
As title
Testing
doc test
Fixes SNOW-967727
Add functions sign/signum
> SNOW-967727 Add functions sign/signum

- src/snowflake/snowpark/session.py
Fixing a minor typo before API goes public. Fixing later would be a API breaking change.
> SNOW-933894: Fix typo

- CHANGELOG.md
- src/snowflake/snowpark/table.py
- tests/integ/scala/test_update_delete_merge_suite.py
> Correct UpdateResult for ERROR_ON_NONDETERMINISTIC_UPDATE=True

- tests/integ/scala/test_update_delete_merge_suite.py
- tests/integ/test_stored_procedure.py
> SNOW-1023749: fix test failure related to stored proc execution

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
Fixes #NNNN
Ensure part argument to last_day is optional so column name is not changed by default.
> FIX: Ensure part argument to last_day is optional so column name is not changed by default

- src/snowflake/snowpark/session.py
> SNOW-1032347: update comment of session.sql for lazy evaluation

- .github/CODEOWNERS
> Update codeowners to reviewers

- src/snowflake/snowpark/functions.py
- tests/integ/test_function.py
Fixes #NNNN
This PR updates doc strings to remove mention of BCR dependence for array related functions.
> SNOW-849384: remove bcr prompts from documentation

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/test_function.py
Fixes #1016694
This change adds local testing support for the following functions:
- current_timestamp
- current_date
- current_time
It also refactors the related test to verify that the various components of those times are approximately equal when called.
For some reason pylint also updated a bunch of unrelated lines.
> SNOW-1016694: Add support for current_timestamp to local testing

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
Bump the version number to release v1.13.0.
> Prepare v1.13.0 release

- docs/source/functions.rst
- docs/source/session.rst
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
> SNOW-1060285: Add missing user and account related funcs

- .github/ISSUE_TEMPLATE/LOCAL_TESTING_BUG_REPORT.md
- CHANGELOG.md
- snowpark_style_guide.md
- src/snowflake/snowpark/_internal/error_message.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/session.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/types.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/scala/test_async_job_suite.py
- tests/integ/test_bind_variable.py
- tests/integ/test_df_to_pandas.py
- tests/integ/test_pandas_to_df.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udf.py
- tests/unit/scala/test_error_message.py
- tests/unit/test_pandas_to_df.py
- tests/unit/test_server_connection.py
Fixes SNOW-1161403 Replaced all pandas text to lowercase
Make it consistent with pandas where itself and related projects all use lowercase for `pandas`, e.g., "[pandas API on spark](https://spark.apache.org/docs/latest/api/python/getting_started/quickstart_ps.html)" and "[cuDF pandas accelerator mode](https://docs.rapids.ai/api/cudf/stable/cudf_pandas/)"
> SNOW-1161403 Replaced all pandas text to lowercase

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_udtf.py
- tests/resources/test_udtf_dir/test_vectorized_udtf.py
> SNOW-1002053: Support vectorized UDTF process method

- CHANGELOG.md
- src/snowflake/snowpark/functions.py
Fixes [SCT-10614](https://snowflakecomputing.atlassian.net/browse/SCT-10614)
Adding a new example for the split function, specifying a string separator by using lit()
[SCT-10614]: https://snowflakecomputing.atlassian.net/browse/SCT-10614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added example using lit() for the split function

- tests/integ/test_column_names.py
Fixes #NNNN
Windowed range between is not currently a fully supported feature. This change swaps out it out for rows_between to avoid conflicts with a feature that is under active development.
> Window function merge gate fix

- CHANGELOG.md
- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/mock/_constants.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_session_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_session.py
- tests/mock/test_session.py
> SNOW-1063732: Implement get_current_warehouse/account/role, and set methods on session

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/binary_plan_node.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/mock/_plan.py
- tests/integ/scala/test_dataframe_join_suite.py
- tests/unit/scala/test_expression_and_plan_node_suite.py
- tests/unit/test_analyzer_util_suite.py
Fixes #SNOW-1018248
Add ASOF join support in snowpark python.
> SNOW-1018248: Add support for asof join in snowpark

- CHANGELOG.md
- src/snowflake/snowpark/dataframe.py
Fixes #SNOW-1032732
Doc change only with additional examples.
> SNOW-1032732: Add join examples

- .github/workflows/precommit.yml
- tests/conftest.py
- tests/integ/conftest.py
Fixes SNOW-1227550
Add a dedicated merge gate for CTE optimization. Note that these merge gates have sql simplifier enabled.
> SNOW-1227550: Add CTE optimization merge gate

- tests/integ/test_cte.py
Fixes #NNNN
It seems the result of explain query in preprod and prod is different, so this PR changes the string for assertion, which exists in both envs.
> Fix CTE explain test

- CHANGELOG.md
- src/snowflake/snowpark/mock/_connection.py
- tests/integ/test_df_to_pandas.py
Fixes SNOW-1065294/ #1264
This PR ports the fix from #1232
> SNOW-1065294 Fix Local Testing's handling of null values in integer columns

- CHANGELOG.md
- docs/source/functions.rst
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/scala/test_function_suite.py
Fixes #NNNN
This function exists on the sql side and local testing already has a mock for it, but I did not see it as a dataframe function.
> Add support for to_double

- CHANGELOG.md
- src/snowflake/snowpark/dataframe_reader.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/unit/test_dataframe.py
> SNOW-1010144:When trying to do an ingest from an stage with infer schema, we will get an exception if no files are present

- CHANGELOG.md
- src/snowflake/snowpark/mock/_functions.py
- tests/integ/scala/test_function_suite.py
Fixes #1043115
This PR adds support to local testing for convert_timezone.
> SNOW-1043115: Add support for CONVERT_TIMEZONE to local testing.

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-1233279: release snowpark v1.14.0

- .github/repo_meta.yaml
> SNOW-1254531: Update repo_meta.yaml

- src/snowflake/snowpark/dataframe.py
Fixes #NNNN
Documentation of asof join is currently merged with a note [doc](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/latest/api/snowflake.snowpark.DataFrame.join) This PR fixes the issue.
> SNOW-1032732: Fix join documentation

- src/snowflake/snowpark/_internal/analyzer/cte_utils.py
- src/snowflake/snowpark/_internal/analyzer/select_statement.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/dataframe_reader.py
- src/snowflake/snowpark/session.py
- tests/integ/scala/test_dataframe_reader_suite.py
- tests/integ/test_cte.py
- tests/unit/test_cte.py
- tests/unit/test_dataframe.py
Fixes SNOW-1060071
This PR adds the support for CTE optimization with SQL simplifier. The dedicated merge gate for CTE will be in a following PR.
> SNOW-1060071: Support CTE optimization with SQL simplifier

- .github/workflows/precommit.yml
- .pre-commit-config.yaml
- tox.ini
Fixes SNOW-1225162
This PR updates tox and pre-commit to use Python 3.9 instead of 3.8, in anticipation of the latter's EOL this October. CI tests and support for Python 3.8 remain unchanged.
> SNOW-1225162: Update dev environments to Python 3.9

- .pre-commit-config.yaml
- src/snowflake/snowpark/dataframe.py
Fixes SNOW-1272098
If we run flake8 with flake8-print and we accidentally add a print statement in a PR, lint will fail and prevent us from merging the PR.
> SNOW-1272098: Catch accidental print statements with flake8.

- tests/integ/test_dataframe.py
> SNOW-1293113: fix test_create_dataframe_large_without_batch_insert

- ci/test_fips.sh
> Fix FIPS failure because of lack of opentelemetry in env

- tests/integ/conftest.py
Fixes #SNOW-1226680
Making the function to create temp_schema scoped at function level i.e. for each function, a new schema will be created and destroyed after the test run instead of being using the same schema for the module.
> SNOW-1226680: Make temp_schema scoped at function level

- setup.py
- src/snowflake/snowpark/__init__.py
- src/snowflake/snowpark/_internal/open_telemetry.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/dataframe_writer.py
- tox.ini
Fixes #NNNN
This PR upgrades pre-commit >= 3.5.0 in tox.ini, and force it run on all files on the merge gate (precommit test / Check linting). Also fixed the changes that don't pass pre-commit hook
> SNOW-1285811: Upgrade and force pre-commit on merge gate

- tests/integ/test_pandas_to_df.py
- tests/unit/test_internal_utils.py
> Fix write pandas test

- .github/workflows/precommit.yml
Fixes #NNNN
This PR add `py-` prefix to all existing test jobs to indicate the test is used for Python APIs.
> SNOW-1300479 add py prefix for all python tests

- src/snowflake/snowpark/_internal/analyzer/select_statement.py
Fixes #NNNN
This property/function is called many times in CTE optimization functions and makes CTE optimization slow on the client side. Make it being lazily evaluated fixes this issue.
> SNOW-1300360: Lazily evaluate `sql_query` of SetStatement

- src/snowflake/snowpark/_internal/open_telemetry.py
- tests/unit/test_open_telemetry.py
> SNOW-1306434:Change tracer scope name to reflect class

- tests/perf/perf_runner.py
> SNOW-1254469: Add CTE optimization to tests/perf/perf_runner

- CHANGELOG.md
- src/snowflake/snowpark/_internal/analyzer/analyzer.py
- src/snowflake/snowpark/_internal/analyzer/analyzer_utils.py
- src/snowflake/snowpark/_internal/analyzer/snowflake_plan.py
- src/snowflake/snowpark/_internal/analyzer/unary_plan_node.py
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/dataframe.py
- src/snowflake/snowpark/relational_grouped_dataframe.py
- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
- tests/unit/scala/test_df_suite.py
SNOW-1271612 Merge dynamic pivot into snowpark python
> SNOW-1271612 Merge dynamic pivot into snowpark python

- .github/workflows/precommit.yml
Fixes #NNNN
For precommit test, we will only have 4 required gates:
precommit test / Test py-macos-latest-3.9-aws (doctest)
precommit test / Test py-windows-latest-64-cores-3.11-gcp
precommit test / Test py-ubuntu-latest-64-cores-3.9-aws 
precommit test / Test py-ubuntu-latest-64-cores-3.10-azure 
we will also have local testing gates, and one cte merge gates. No pandas and disable sql simplifier test have been moved to daily github actions.
> SNOW-1296607: Reduce merge gates to a minimum set

- ci/test_fips.sh
- tox.ini
Fixes #NNNN
This should be a no op change for now but it make it clear that all existing jobs won't run anything under future modin paths.
> SNOW-1331835 Ignore modin path for current test jobs

- .github/workflows/precommit.yml
Fixes #NNNN
We don't run doctest on CTE merge gate anymore, which will run in daily precommit tests
> Change to use ubuntu-latest-64-cores for CTE merge gate

- .github/workflows/checkprs.yml
- scripts/longprs.py
Fixes #1314326
Porting over this script. It should check whether a PR is too long, has too many comments, and if it has been open for too long.
> SNOW-1314326 Add GitHub workflow/script to check PRs

- src/snowflake/snowpark/mock/_udf.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udaf.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
SNOW-1305596
Add field `._packages` to `UserDefinedFunction`, `UserDefinedTableFunction`, `UserDefinedAggregationFunction`, `StoredProcedure` classes to keep track of which packages a function object requires. This allows e.g. to define a new udf based on the code of another and carry over the package dependency.
> [SNOW-1305596] Add field to function objects to track packages

- CHANGELOG.md
- src/snowflake/snowpark/_internal/udf_utils.py
- src/snowflake/snowpark/functions.py
- src/snowflake/snowpark/mock/_stored_procedure.py
- src/snowflake/snowpark/mock/_udf.py
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udaf.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
> SNOW-1161498: Support adding COMMENT when registering sprocs/udxfs

- CHANGELOG.md
- src/snowflake/snowpark/stored_procedure.py
- src/snowflake/snowpark/udaf.py
- src/snowflake/snowpark/udf.py
- src/snowflake/snowpark/udtf.py
- tests/integ/test_stored_procedure.py
- tests/integ/test_udaf.py
- tests/integ/test_udf.py
- tests/integ/test_udtf.py
- tests/utils.py
Fixes #SNOW-1316591
Pass statement params when registering sp/udf.
> SNOW-1316591: Pass statement params when creating udf/sp

- .github/workflows/daily_precommit.yml
- tox.ini
> Change the parallelism of merge gates and daily tests 

- src/snowflake/snowpark/dataframe_writer.py
> SNOW-1227759: Fix the type annotation of `save_as_table`

- CHANGELOG.md
- src/snowflake/snowpark/_internal/telemetry.py
- src/snowflake/snowpark/session.py
- tests/integ/test_cte.py
> SNOW-1060150: Add `session.cte_optimization_enabled` parameter

- src/snowflake/snowpark/mock/_plan.py
- src/snowflake/snowpark/mock/_stored_procedure.py
- src/snowflake/snowpark/mock/_udf.py
- src/snowflake/snowpark/mock/_udf_utils.py
- src/snowflake/snowpark/session.py
- tests/integ/test_stored_procedure.py
- tests/resources/test_sp_dir/test_sp_file.py
- tests/resources/test_sp_dir/test_sp_mod3_file.py
Fixes #NNNN
This PR is essentially adding https://github.com/snowflakedb/snowpark-python/pull/1329 for `MockStoredProcedure`. The code is placed in different places because a UDF expression is executed in `calculate_expression` but a stored procedure is executed on its own by invoking the `__call__` method of `MockStoredProcedure`. This could be refactored better.
> [Local Testing] SNOW-1184278 Support file imports in stored procedures

- src/snowflake/snowpark/_internal/analyzer/cte_utils.py
Fixes #NNNN
This is avoid hitting Python's maximum recursion depth limit
> SNOW-1324410: Rewrite search algorithm for CTE with an iterative approach

- CHANGELOG.md
- tests/integ/conftest.py
- tests/integ/scala/test_column_suite.py
- tests/integ/scala/test_dataframe_aggregate_suite.py
- tests/integ/scala/test_snowflake_plan_suite.py
- tests/utils.py
> SNOW-1325652: fix stored proc test failure and prepare release

- src/snowflake/snowpark/mock/_connection.py
- src/snowflake/snowpark/mock/_plan.py
- src/snowflake/snowpark/mock/_stored_procedure.py
- src/snowflake/snowpark/mock/_udf.py
- src/snowflake/snowpark/mock/_util.py
- tests/mock/test_udf.py
Fixes SNOW-1342947
The previous implementation does not respect the database and schema specified in the UDF/SProc names, this PR fixes that.
> SNOW-1342947 Fix bug in Local Testing's implementation of UDF and Sproc to use fully qualified name

- src/snowflake/snowpark/async_job.py
> SNOW1333607: Preparation for async GA

- .github/workflows/precommit.yml
- setup.py
- tests/integ/modin/test_modin_extra_without_pandas_extra.py
- tox.ini
Fixes SNOW-1345421
Include pandas requirements in modin extra requirements.
> SNOW-1345421: Include pandas requirements in modin extra requirements.

- src/snowflake/snowpark/modin/plugin/__init__.py
Fixes #1324779
Updates pandas import warning to show PrPr instead of PuPr, since we will continue to have PrPr releases before PuPr.
> SNOW-1324779: Update warning for pandas PrPr

- src/snowflake/snowpark/mock/_functions.py
- tests/integ/test_function.py
Fixes #SNOW-1235476
This PR improves the implementation of `to_decimal` to support more input types.
> SNOW-1235476 Improve Local Testing's implementation of to_decimal

- .github/CODEOWNERS
> Add docs/* to CODEOWNERS for Snowpark pandas team

- .github/pull_request_template.md
Fixes SNOW-1348403
Use a JIRA template that will make GitHub hyperlink to a SNOW- issue if developers fill in the issue number.
> SNOW-1348403: Fix the SNOW issue template in pull request template.

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/series/test_str_accessor.py
Fixes SNOW-1347796
Fix incorrect regex used in Series.str.contains.
> SNOW-1347796: Fix incorrect regex used in Series.str.contains

- .github/workflows/daily_modin_precommit.yml
- .github/workflows/daily_precommit.yml
Fixes SNOW-1349082 CI: remove concurrency restriction on daily jobs
Make sure all daily job can run if we want to run. It's okay to run them concurrently.
> SNOW-1349082 CI: remove concurrency restriction on daily jobs

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
Fixes SNOW-1348621
Forgot to update the changelog in the PR with the fix, therefore updating pandas changelog in this PR. Previous PR fixed using DataFrame keys with `__getitem__`.
> SNOW-1348621 Update pandas changelog

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/groupby/test_groupby_default2pandas.py
SNOW-1347393
This PR removes fallback and raises NotImplementedError for GroupBy APIs.
> SNOW-1347393: Remove fallback and raise NotImplementedError for GroupBy APIs

- .github/workflows/precommit.yml
This PR removes Codecov/Combine Coverage from merge gate for PRs. Codecov/Combine Coverage will still be present in the daily precommit job.
> Remove Combine Coverage from PR merge gate

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/version.py
> SNOW-1358736: Release snowpark 1.16.0

- src/snowflake/snowpark/lineage.py
- tests/unit/test_lineage.py
Fixes the workaround logic
WOrkaround: There is a bug in DGQL output that will get deployed in 8.18. I have made a workaround that will work with and without the fix in 8.18.
But I realized I needed to add one more check. Fixed it in this PR
> SNOW-1305528 : Fix the workaround

- docs/README.md
- docs/source/snowpark/functions.rst
- docs/source/snowpark/types.rst
- src/snowflake/snowpark/functions.py
> SNOW-1359379:Add VectorType to snowpark python API doc

- docs/README.md
> SNOW-1359379: update doc generate readme

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
Fixes SNOW-1349069
Link to SNOW-1345395 and explain that we need to keep the `cache_result` calls.
> SNOW-1349069: Update cache_result comments in apply methods

- tests/integ/modin/strings/test_strings.py
Fixes SNOW-1347401
Missed changing a test in the previous PR, this one fixes the test.
> SNOW-1347401 Fix test that raises wrong error

- scripts/parameters_qa.py.gpg
Fixes SNOW-1359299 Add QA parameters
Added parameters for QA and tested https://ci-dev-142.int.snowflakecomputing.com/job/SnowparkPythonSnowPandasDailyRegressRunner/368/
> SNOW-1359299 Add QA parameters

- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
> SNOW-1347394: Close parentheses in SnowflakeQueryCompiler.default_to_pandas message

- .github/workflows/daily_precommit.yml
Fixes SNOW-1320543
need to do `python -m pip install ".[modin-development]"`
> Fix Daily test - Update daily job to have correct environment

- .github/pull_request_template.md
- .pre-commit-config.yaml
Fixes SNOW-1349033
Currently the template says "What GitHub issue is this PR addressing", but we only want Jira numbers.
We should always add a Snowflake JIRA number, even if a GitHub issue exists.
If a user creates a GitHub issue and wants to reference it in a PR, a bot will
create a SNOW-jira ticket for them, as in #1400.
> SNOW-1349033: Clarify need for Jira issue in PR request template.

- docs/source/snowpark/functions.rst
- docs/source/snowpark/session.rst
Description
Make sure UDAF doc can be referenced in the right locations
Testing
Checked build/html
Fixes SNOW-1284684
> SNOW-1284684 Add udaf to session.rst and function.rst

- recipe/meta.yaml
- src/snowflake/snowpark/_internal/utils.py
- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/version.py
Fixes SNOW-1345607
Last alpha release v1.15.0a1! Updated the version numbers and fixed some grammar in the pandas changelog.
> SNOW-1345607 Release 1.15.0a1

- src/snowflake/snowpark/lineage.py
- tests/integ/test_lineage.py
- tests/unit/test_lineage.py
The PR adds support for handling case sensitive name of the objects. 
1. Constructs case sensitive names and versions 
2. Queries DGQL by Id for distance >= 2. This also helps in going beyond deleted objects.  
3. Fill out the following pre-review checklist:
4. Please describe how your code solves the related issue.
> SNOW-1305528 : Supporting case sensitive objects in session.lineage.trace

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
Move Snowpark pandas modin import changelog to 1.15
> Move Snowpark pandas modin import changelog to 1.15

- docs/README.md
- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
Fixes SNOW-1345607
Fix README/md pip install command.
> SNOW-1345607 Fix docs README.md pip install command

- src/snowflake/snowpark/modin/plugin/_internal/utils.py
- tests/integ/modin/io/test_read_snowflake_query_cte.py
- tests/integ/modin/io/test_read_snowflake_query_order_by.py
- tests/integ/modin/io/test_read_snowflake_select_query.py
Fixes SNOW-1357748
This PR updates read_snowflake to use string matching for the order by warning.
> [SNOW-1357748]: Update read_snowflake to use string matching

- src/snowflake/snowpark/modin/plugin/__init__.py
This PR adds double quotes to the pip install message users see when installing Modin to accomodate for zsh.
> Add quotes to pip install message with target

- tests/integ/modin/frame/test_add_prefix.py
- tests/integ/modin/frame/test_add_suffix.py
- tests/integ/modin/frame/test_apply.py
- tests/integ/modin/frame/test_dtypes.py
- tests/integ/modin/groupby/test_groupby_apply.py
- tests/integ/modin/series/test_add_prefix.py
- tests/integ/modin/series/test_add_suffix.py
- tests/integ/modin/series/test_apply.py
- tests/integ/modin/series/test_astype.py
- tests/integ/modin/test_from_pandas_to_pandas.py
- tests/integ/modin/tools/test_to_numeric.py
Fixes SNOW-1357611 Fix all quarantined pandas tests for 8.18
remove all skipped tests from SNOW-1358681
> SNOW-1357611 Fix all quarantined pandas tests for 8.18

- tests/integ/modin/binary/test_binary_op.py
- tests/integ/modin/test_concat.py
- tests/integ/modin/test_from_pandas_to_pandas.py
Fixes SNOW-1348919
This bug has been fixed in https://github.com/snowflakedb/snowpark-python/pull/1533
> SNOW-1348919 Add tests to confirm the pandas sub bug has been fixed already

- tests/integ/scala/test_function_suite.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/scala/test_literal_suite.py
- tests/integ/scala/test_permanent_udf_suite.py
- tests/integ/scala/test_session_suite.py
- tests/integ/scala/test_table_suite.py
- tests/integ/scala/test_udf_suite.py
- tests/integ/scala/test_window_frame_suite.py
- tests/integ/scala/test_window_spec_suite.py
- tests/integ/test_column_names.py
- tests/integ/test_pandas_to_df.py
- tests/integ/test_telemetry.py
- tests/utils.py
This PR is part of a series to enable local testing by default in all relevant tests.
It covers the following test files:
- tests/integ/scala/test_function_suite.py
- tests/integ/scala/test_large_dataframe_suite.py
- tests/integ/scala/test_literal_suite.py
- tests/integ/scala/test_permanent_udf_suite.py
- tests/integ/scala/test_session_suite.py
- tests/integ/scala/test_udf_suite.py
- tests/integ/scala/test_window_frame_suite.py
- tests/integ/scala/test_window_spec_suite.py
- …
> [Local Testing] Test Enablement Part 2

- src/snowflake/snowpark/modin/plugin/__init__.py
Fixes SNOW-1347052 Update pandas API PuPr warning messages
- change the words from "private preview" to "public preview"
> SNOW-1347052 Update pandas API PuPr warning messages

- src/snowflake/snowpark/modin/plugin/docstrings/base.py
Fixes SNOW-1374306
This PR adds a docstring for resample.
> SNOW-1374306: Add docstring for resample

- src/snowflake/snowpark/dataframe.py
Fixes SNOW-1326280
Update the links in the documentation for `to_snowpark_pandas` from the LIMITED-ACCESS version to public! These links will not work until all of the Snowpark pandas documentation is public.
> SNOW-1326280 Update the doc links in `to_snowpark_pandas`

- tests/integ/scala/test_dataframe_reader_suite.py
- tests/integ/test_udf.py
> fix merge gate

- docs/source/snowpark/dataframe.rst
Fixes SNOW-1421125
I generated documentation and checked that the new page shows up.
> SNOW-1421125: Add to_snowpark_pandas to documentation.

- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
Fixes SNOW-1374305
Added docstring to Dataframe.merge method
> SNOW-1374305: Add docstring to Dataframe.merge method

- tests/integ/modin/frame/test_apply.py
- tests/integ/modin/series/test_apply.py
Fixes SNOW-1428607 quarantined tests for 8.20 due to sql query count mismatch
> SNOW-1428607 quarantined tests for 8.20 due to sql query count mismatch

- src/snowflake/snowpark/table.py
> SNOW-1324418: Add an example for WhenMatchedClause docstring

- tests/integ/modin/strings/test_strings.py
This PR fixes the query counts for `test_slice`, original PR adding support is here: https://github.com/snowflakedb/snowpark-python/pull/1579
> TEST: Fix query count for `test_slice`

- tox.ini
temporarily omit the test coverage for mock.
we will bring it back after removing unused code in the mocking module
> SNOW-1356862: omit mock module test coverage temporarily

- docs/source/modin/supported/groupby_supported.rst
- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/_internal/apply_utils.py
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/groupby/test_groupby_apply.py
> SNOW-1429855 Explicit raise NotImplementedError for groupby.apply with include_groups = False

- .github/CODEOWNERS
This PR updates CODEOWNERS to use the https://github.com/orgs/snowflakedb/teams/snowpark-pandas-api/ team
> Update CODEOWNERS to replace snowpandas with snowpark-pandas-api team

- src/snowflake/snowpark/modin/pandas/series_utils.py
- tests/conftest.py
Fixes SNOW-1430675
- Enabled doctests for Series utils.
- Removed tests that were raising NotImplementedError.
- Skipped tests in `Series.str.strip()` since they were producing incorrect outputs - here is the ticket for it. https://snowflakecomputing.atlassian.net/browse/SNOW-1432420
> SNOW-1430675 Enable doctests for Series utils

- src/snowflake/snowpark/modin/plugin/docstrings/dataframe.py
- src/snowflake/snowpark/modin/plugin/docstrings/series.py
Fixes SNOW-1432344
This PR fixes our docstrings for `df.apply` and `df.transform` such that the doctests actually succeed.
> SNOW-1432344: Clean up apply + transform doctests

- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/modin/plugin/compiler/snowflake_query_compiler.py
- tests/integ/modin/frame/test_replace.py
- tests/integ/modin/series/test_replace.py
Fixes SNOW-1433131
Enable regex in DataFrame/Series.replace to include '|' (and other regex special characters).
> SNOW-1433131: Enable regex in DataFrame/Series.replace to include '|' (and other regex special characters)

- tests/integ/modin/groupby/test_groupby_apply.py
Fixes SNOW-1434962
Unblock CI and will investigate it soon.
> xfail SNOW-1434962 groupby.apply order is not deterministic

- tests/utils.py
Fixes SNOW-1423583
The stored proc test env does not have structured type support rolled out yet.
> SNOW-1423583: Structured types not yet supported in SP test env

- tests/integ/test_lineage.py
- tests/integ/test_stored_procedure.py
Fixes SNOW-1434844
Fixing broken tests in SP precommit
> SNOW-1434844: Fix SP integ test and xfail lineage trace test

- tests/integ/scala/test_dataframe_aggregate_suite.py
- tests/integ/test_dataframe.py
- tests/integ/test_pandas_to_df.py
> SNOW-1434844: Skip caplog checks in SP

- .github/pull_request_template.md
- .github/workflows/enforce_localtest.yml
Fixes SNOW-1063738
The changes include
-  an item in the pull request template checklist to ask for Local Testing feature parity
- a Github action that checks if a pull request contain the word `"local_testing_mode"` and posts a comment asking the user to requests review from @snowflakedb/local-testing. Unfortunately the job cannot directly request review since Github token does not grant access to organizations/team scope actions.
> SNOW-1063738 Add template and Github Action changes to enforce local testing parity 

- CHANGELOG.md
- recipe/meta.yaml
- src/snowflake/snowpark/modin/plugin/PANDAS_CHANGELOG.md
- src/snowflake/snowpark/version.py
Release 1.17.0 (Initial public preview release of pandas API)
> Release 1.17.0 (Initial public preview release of pandas API)

- tests/conftest.py
SNOW-1440016 Make sure all modin doctests are covered in CI
> SNOW-1440016 Make sure all modin doctests are covered in CI

- .github/workflows/precommit.yml
Fixes SNOW-1438057
This PR adds a combine coverage job to CI ensuring 95% of code in the PR compared to main is covered. This CI job/test is not a part of merge gate yet so it is non-blocking, but should be part of the merge gate in future.
> SNOW-1438057: Add code coverage to precommit

- .github/workflows/enforce_localtest.yml
The action introduced in https://github.com/snowflakedb/snowpark-python/pull/1639 would fail for pull requests that did not contain the keyword "local_testing_mode", which is confusing. This PR adds a negative case so the command does not exit with a non-zero code when `grep "^+" | grep "local_testing_mode"` does not return anything.
> Fix Github Action to not fail if the pull request did not contain Local Testing changes

- .github/CODEOWNERS
> Ensure both teams do not get assigned as reviewers only due to CHANGELOG modifications

- tests/integ/test_df_to_pandas.py
- tests/integ/test_lineage.py
- tests/utils.py
> SNOW-1411701: CP regression test fix

- .github/workflows/precommit.yml
This PR fixes CI to require all other tests (excluding docs and linting) to run to completion before executing the combine coverage test.
> TEST: Fix combine coverage job
